[General]
SyntaxVersion=2
BeginHotkey=121
BeginHotkeyMod=0
PauseHotkey=19
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=7fd8487c-1fab-4130-9531-d4b7eb0ae524
Description=舰娘
Enable=1
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=1
QUI=Form
[Relative]
SetupOCXFile=
[Comment]

[UIPackage]
UEsDBBQAAgAIAD4baUalG23SvW8AAAjABgAJABEAVUlQYWNrYWdlVVQNAAe7Ev1UuxL9VLsS/VTsXQl8VNXVP28Iq4gsgoAo4Ia7mSULii2TZBICk0xMJmFRHAaIEgkJJoECbtR9QVzqXjfcty6CoAiKVT9ErZRapZTvaz+s31fb2vZz+T7sVyv0nPfe5L0kE5nz3plcBnL9HZMM78155757z/3/z7333B5glG2/GLRr1fMjP4J25TvQA/bs7Qu9bJ/1RtESfwwE8OCPQSh79u7dm/h4ORgXLacL8YLldFEPgL3dZb8s36Bk4Ss6xXy/PVHonfdB6YfSF+UQlENR+qMMMF49HIYyzHz/g1GGoByOMhRlOMoRKCNQRqGMRDkS5SiU0ShHo4xBOQZlLMqxKMejHIdyAsqJKONQTkI5FeVklNNQYijZKKejnIHiRfGj+FACKLkoOSh5KONR8lHORJmAchbK2SgT9bYN8F2UIEohSgFKEUoxSgilBKUUZRLKZJQylCkoYZRylAhKBUoVyjkolShRlBqUapSpKNNRpqHMQDkP5VyUmSizUM5HiaP8AGUOymyUuSgXoNSiXIhyEco8lDqU+SgLUOpRGlAWojSiXIzSjNKE0oKyGGURyvdQlqIsQVmGcinKJSiXoVyBcjnK91Gu1p+9Ef9rwfcRwu9uwe9aCpwyDFtMoi1p+7j2tb9OCr83fZvWg/4Y5dE/q8aazgbnpQ9oWkL/1z2SX7PrnWJdb0K//d8K8c2FXTxBP5v+nvDt+hM/7f8WxfpeiG+9HFvEAv3t88pg8Oj6qT/utfnhfZUs8yf5bhUy2vQBY00/cKzZ/483fcA40w+cZPb/U0xfcJqt/2ebPsBn+oGA2f9zTR+Qb/qBM83+P8H0AYn+P9H0AQWmHygy+3+xwnrpailubFrgovuB2/s1cFfc3q+6fPbZZyLfMwvd6QoHleHU71j+z9MG26X6zhL+h0adOI6A9Q6fYQD6P8InvRn+z2PTX4MjbDOK0ycYiPr7g4VvU7mnh01/JWqN4+gfwXqoZ469Cf/fCwyslqr+LJv+KOpfoqMHx+9f475/O18oRPRRj9Lk8EkOd6C/p81+S38Bvoc5OtZi6tffZ19G/fdq9/7nuKx/wuZ9GPp7g4HhqczAlteE7a9WR5GO+h+7//ex2R/GuufXelv7B5jfl6r+vjb9xai/wV39s+2nvjrB/D2Ira8OEX+D7oUbnLR/tv5DbParLruTP7M+kpVVjamKNzSPqaptqrsgTfqj8dmFjQ0tTY31ju+PFTY2OR5AVeMfg/94XbR/TaPxlHD7kE6uSTf/ORp4429/sw9SUYF/Ev6aigT+oTjLcIb/GwCy+Gcks/4PA1n8Q3GnQQz7B4Io/oH9Af8cy7B/EOw//t8t/yFnQjHMOeiEVmrO7ner301xO/71gawP1n34Vdaa3Ru+ylq9/qW/Z2359K09Wc/vWvN21vrH1jyZteXD7a9mvf3H7W8kv18C/1LMdzSj/Q0GWfybiC2nqn8IqMW/h4Ms/h1l1mmq+oeCWvxL8wYJ/FuKumtxBG52qL8/2k/fN5ZhP81NnGz+XoXa6802WKtH4XllsAP7h4N9/KHRP9H3rN6YahmJ9pM9xzHsH2HT73YccOu/peJfqspgl/evoP5YEC2PhSMlhcFoLFIRKi+OhItClRQl6B0OFoTCAS+9pSGFBbFgNBosnFJeWjIpWkz/o2FiEH5eGaoIllbGZkyKlJdURCgeMQY/raquqAhPj02dFCqPhaZVhIpKo6WR8lhBqDhSGfIYX2+0v2bHLXCUg/Y/0tbuqrDfLXWMfvX+z9Z/ZIf+16yPAnUmA4+j1Ol+cd9ljAP9o5Lon4S6KQ4wj+mLhznQfxS0jX8ZNtfhT/KAPI98NPqfMWDM4aSqn/jaMf0S+ol/+hz3H/v824mdXJPgnZ99nr75txyG/TS/nOB/KvgnzWsn8A+6F19uz1ZX4/fS7wNKC2IF1aXholhVNBQKW//sy8myvFJ2zzZeKYZepSxIHoYqeKDllaaVBiOGUzrMuph803TN0uujL+tbUhmpriiITMu3OT+/pdIXsH73++mOQ8l1Go8aLCqiT4ZaOsKlZaXRWGGkujxKIc9e+n3jSekIvKhwUrC8JFQerDE9pPGYNvt8NsX6QxhfkK+1NVu/uShYEaHP+2LNGZ6cLBhdmPhLv2pqsLK0vKQqWBOqKC2MVleGLCtzsun3Ye2+1fTn9MUDrPokXT1a7/TqfWdUO3dvfksbV092+HqYD1kUqomFa6w3G9Df7GD9d3vVeJN/7Ev+sT/5x4HkH3eiMteq9xwvvbhjkrytwki5OZz5smP+bLplZJLLzBpM/LNtFKRr/DG8tCBMc76J2jQssGqzcFKocEqkNAzmx2bFJj62WrBPr6l+ZtXiP9nqNmC1nrzebb+oqLSqKhKuCSVG8mB1NGIZYWuB2fYrLDug9ZtzLSsCeXTjgEhr6ytFTNGr9UryVXAI9Rx6VLPfmHfqlT/2Wys8G6vcMiige6HWCgt42vzpa/unv+2fXqtlenXFrQ7Arz+iWZnBsrJIT7MPkPXFwcJopHJ6T/MSo/sbjblP2Pyb/hhoOYfKUFmkJmTzc/k9rbZnvorS8qLQtN5tu2GwOBqqNDsevYAjktQM9UerPvxWk/DmtbFJr4teYd0m25OMt9X+eLpheLtm1lrzWqsSn5a8QftsDXp0238uw4aGP0M1aDBdGkjhGn8K1/hsnSfQxl4vPeThrS8IKzEUjOreWPfcrf+QeL1mHeRbdem11aXuLA6zmnRRqKC6pJddn17btndnPmmYHlVr2+vKghWtHyepxoCtGoe288nGMNHZIGK0FHqQ/mbjbTeC+gNtR00dxqMB5UWaOUCaXn5qqNRw86322YfpHL0Kzf5g3NHD9onx3bbay2/zZnJsI7re/AabD9vuHZnKdMUDEv7C6kr9W1+h6e4GWH6zKlIZpfY+tLSz4XiA0fnsr8IGGozBx26T8cUeux0Baxj05dseOI9+H46aq0LRKA65Mb2WY5Fq/Kss1NuqlvG9E27CbFWF4VDQxrx8ebZvzU5AI+ul68Ng24+8HT/yd/wo0PGj3I4f5eybnRfOq50zv6BxiVP8SDVeuzBe1xQrjy9eGmNPBGX6+p3tG7Y+t+13a3e+v+GVR9b9quv1u41/kBt/EeURlPcc3C8x/0Tr8U5m8B9aWys4/8TmP5NBdv6JhsDTGPZPAfn1NwGG/jAYc4B6/xeaf/Iz9JeB7PobWi96KkN/OcjOP9A61FMY+iOgdv6hwmb/my79l+r5L1D8/KpLOD67tt7N/QLzTwQaxjHa/zmgdv6J9mtMaPU/83QPMN/R7I+x/oHWop/EsL8KOvr/SkfRX2frv6KgNv5ebdOvYv1bDdjHH4o/+120P00jX057fsZ3ck0i7pzO+HMho/3Rsyb2qqiIP9O+qAT+kMCftJfjLIb900F2/dNEMPaNpKp/BsjiT9rf8h2G/nNt+vXxI1YWXxiuXexkIMl0/rd2x3sbH31ZnX63/O8MMMYz6lNxB/erWP9P+yET+4ql+EcRo/3PBFn+QXvNzmboPx9k+QftYZvA0B8DtfxjFsiuf6L9e/kM++OgFn/OBrXr/+fY7J/l0n9lOv9TXQTit8FFLY3Blpb4HCe9KIr9Po7trhlRaBx/57bB4Q7a31yw4/9FqK8ReUgdLHOGf9n6a6E9/g+46P/W+pPSTq7pCvxfw/B/1JdUrj+h/AaHmr9L4H+Kp01h2D8P1Maf60AW/1eBEdNMVf9FNv2Zjt9p3fumZ9bvUKXfLX6ntZAUu6YcHQUO7o+4fH4p/F/NaH/zbf5HCv9HGfrrQRb/03q+Mob+BSCL/ymeGmbobwC1+L8RZPE/8d9JDPsXglr8T3l7JOPPNJ8zmWF/E8j5/+75G3elsHHB7EaX+F/H/sV1F85rqWxc1MBrRSrmH5pB7fxDC6idf1gE7flHjgv/o2mUr4j614xOrkk3/6gF3v5fylOmkn9QfrTEXnUJ/jELjJhmqvqXgOz8Q5xZ/0vhwMH/bgsjZVrScrXpzzaiXO/g/nqXz++2/iX4J80nxRjtfxnIr3+ay9CvOv/QJSDLP2ju53yG/ZeCLP+gePZMhv7LQC3/uBxk+QfF06cz7L8C1PKP5WDxj4Mlz6FTedthHf3a4X3/3cXvxC1/Q/yZrXk1n+bXAlqOlqvlafnaeOiyIjF/ovOn2NR5tQ2xaXXxxopGxv2Zjp8E8i+w/Q/lHh5m/q4i/8KV0J5/5brwv9b8T10n13TF/M9ixvhzFajlX4SZh5q/S/Av6q/zGfZfA2rnf64F2fkf6rsNDPuvA3n8vYih/3qw8q9J4e8Whv4bQBZ/03zmAob+G0EWf1M8uZ6h/yaw8Pe2VZs3r95As2igpLidPzsRvelq/LkEf25ycP9il8+f6fFzFfxrBcjyL3ryeYz2fzOo5V8rQXb+h+azLmLYfwuo3X9wK6iN/98GauP/t0N7/Jnnov1pGqHXtWDE1ZKVb8OfGT9/5p7/hZYsrJ1b11LX2KDvgQ7EQg3x2fUpNshM539S/OM6hv+hc29U8o87wFh3Q0WCfywHI6aaqv47QS3/uAtk+QfxuSsY9t8N8vzjWob+e0B+/dE1DP33giz/IOd3OUP/fTb9a3e++6aazAdGkdj/8iAYnH6dg/vLXT5/puN/Cf5J8bTLGO3vh6B2/ud+kOUfFE9byrD/AVDLP6i/SPIPiudewrD/IVDLPx4GtfxjFajlH4+A3PoP1UVs/ZzDPbCZjv8N/pnvwv9Y8x83dXJNuuc/7gLe+qdHQS3/eAysvNES/IPiGTdD6v73cZBdf3Y7s/6fAFn+QfHEWxn2Pwny/ONOyJz1R0+B3PkfbtfP0bol2sNC9ecEf8x0+fyq8XtvsK+eyNrwt3U/ga4sEvyT5tNuYbT/p0F2/oviSSsZ+p8BtfzjWZDlHxTPupFh/3Ogln/8CETP/2Dr/zFY679VrD/5CbSP/ztfMEX4i+bTaUy9r5Nr0o2/Hgfe+P9TUIu/ngdr/ZEE/noYjJhCqvpXgyz+WsWs/zX29ifHn+qam+saG5gcqnv/gTv89DMw8BOtG3WCnyTwN8XzHmK0/xdAHn8/BpmDv9eCbPyf5jMeZNi/DmTxF8WTHmDofxHU4q+XQBZ/UTzhXob960Et/qJ0Zwn8FQd3RTV/6mnjT6CgCIyftvUH5hhKQ6i+FmHf5yK5rX8V+HsDGGfwUlGBvzdCe/zthWzH9lvxz6c7uSbd+PsF4OG/V0At/n4VjPNCqUjgb+JTz0Lq/ncTyOLvnzLr/zWQjX9SPOPHDPt/BgfO/I9b/Ex9gfJnHKqBo/df4vL5VY+fUvh7DWQO/n4dZPE3zSf8iGH/GyCLvyme8RxD/5ugFn//G8jib4qnPMWwfzOoxd9vgdr45xaA1rNNx0HH3Zseb7bH6/V4fR6v3+MNeLw5Hm+ux5vn8eZ7vOM9vmyPz+vx+Tw+v8cX8PhyPL5cjy/P48v3+MZ7/Nkev9fj93n8fo8/4PHnePy5Hn+ex5/v8adhX2h68fe+88JnevxKBf5+Bzrib6/D5yf8TetJaQHjS51ck278/Qbw8N+7oBZ//xxk8Tfh+ZcZ/vc9kMXfm5j1vxVk8TfFc15h2P8LkI9/vg6Zg7+2gSz+onjmRob9vwRZ/PUaGDGNVPW/D2rx169g/1n/Qf2G8nER/1rh4P6FLp9fNf9Sjb8k8DfFE15ktP8PQC3+/hDU4u/tYOFvFfhrh2D/Ty/+3nde9u75Y3f+N4G/fQ7vt8e/3+rkmnTj7/eBh/9+A2rx906Qxd+Ep9+G1P3vv4Ms/t7KrP//AFn8TfGMnzPs/y3I4+9fQubg79+BLP6meN67DPv/E2TxN/Gpdxj6d4Fa/P0RyMY/iU9tZtj/e5t+wt8Pg4G/1zrQ3wzuysGOv90Wt/kPVODvj0Et/v4vUIu//wAd459+x/Zr2pumTds7uaYr8s99zPA/n4Ba/PVHkM3/QHhmB8P+P4Ha/A9/tre/DvlPfAdV/pO1O9ftyfT8B5TDgPIfOMkRIIG/d4HBKVJtf5+CPP7+PUP/X0A+/8dHDP1/BVn8TfG0nQz9fwNZ/E184jcM/f8DavH3ZyCLv4nPfMiw/3NQG//8Aiz8FXbpv7rPD1Jb9PO7Xdwvkf+D4im/ZrT/L0Ft/o//BbX5P/4P1Ob/2A0d+UfAsf1W/PeTTq7pCv7xOaP9UarbnubvKvjH38E6/1yCfxCe+BPD/v+3vX/df/gcm5/x+H/9jk1PPfqyOv1u8f/dug8z4nizHdwvEf8nPPklo/39A2Tj/8Tn/8LQ/zXI8w9O//+nrf9L8Y8vGPZ/A7L8g/aefsrQvwdk+QfxiT8z9O8FtfyDnJ4k/yAP8geG/ZpNf/cZPwe3zAV3JdP5n+rilr/p9/ud368i/uDRrPiDCv7TQ7OP/0047jUgBlqIP5vYzzDcgf4szc7/FqG+RsRwdbDMGf9h6++pdeR/TjdPE/+j9Zt0/kZnR4h0Bf+jMS1V+3tpavlfb02W/xGeI06Xqv4+mtz6P9X8bcsn67/e+kz2o8998MX2DS98sXbn+xte2v3qb9d+HOwa/W75G63bojNoLtaMORxuaXT5/BL8j/B8D0b/66vJ8j+Kp/yT0f77aWr53yGaNf8sxf88jPrvr8nyP4pnfs2o/0M1Wf5HSv/B0D9AU8v/DhPmf+SEdzPsH6jJ7f/vxu8C+D3g/H63708F/h+kGP8PVoz/hyjG/4cnwf9OT0C1z//07qQxtuL+ESVpw/+DGOPfUMX4f5gw/qfxtC/D/iM02fX/NJ4OYegfLoz/iM/0Z+gfoRj/jdTk1x8NZth/pLb/5P/ZsnXr56VF6mbg3PI3yrtM82+0/9jJ/Ntkl8/v9v1J4H+KJx3CaH+jhPE/4el+DP1HKcb/Rwvjf8LzvRj2j9bUrj8boxj/jVWM/45RjP+Otenv5m8C/M1F5lHV62cS+N/pCbSE/2k+4zjNwJVJSwL3pxH/j2X4v+MU4//jhfE/jWcjGPafIIz/aTw7lqF/nDD+Jz4xiqH/RMX4/6Q04P9jGPafLDj/cyDgd8rfTfh9tYP7L3b5/KrjrxL4n+IpRzLa3ynC+J/w7EiG/lMV4//ThPE/4elhDPtPV4z/z1CM/7MV43+vYvzvE/T/qosIfs91fv+Bcf6n1/EJoPb4/ziF+N/L8H9+xfg/IIz/aTw5iWF/jjD+p/HEz9CfK4z/Cc+fytCfpxj/56cB//sY9o+32X8g4Hc6e3yj+Tu3NLl8/kxfPyGB/ymecQqj/Z0pjP8JT57M0H+WYvw/QRj/E549gWH/2Yrx/3cU4//vKsb/ExXj/+B+hP/d5q+i8ycXtTRaOWyY92c6fv9g3YdfbXpm/Q7H9Wfif6epyQj/03qiGs3AVUlLF+D/Iob/K9DU5p8qRP2DzN8l8D/58/EM+4s0tfmnQsL4n/zZBIb9xWnA/4UM/SVpwP8FDP2TBP2/W/xO6+BPRZlD/dLB/ae7fP6DPX+NBP6neMJZjPZXKoz/Cc+dydA/WTH+nyKM/wlP5jLsDyvG/2U2/C+Rf4j4RD7D/nJNbf6hiKY2/1DFgYX/2+Wv9B9k+Su3fOMmf+U32GauxJ9XgbH/8DqUa1GuByOedgPKTSg3g3E+y0qUW1FuQbkN5Q6U21HuBCMHNeWjuQuFziS/D4xzsel8eDqf/H4wzgmns+JXgZF3ms4Op7PbaQ7+cRQ6S/EJMM7zo3NN6UxdOtuVzlekMw7pnFM6b5XOfKVzD+ncSZq3pzNw6QwSymFN5wHRWWAU1KSzmehsHsqPQzFCOqvqNTDOgKVzS+jsLjo7iXLo0vkFlMuc8snTfjLKKU77Mym3OeW4pxzzlGuf8o1TvnfKu01nD1D+RXoBlAOQ8qBRHl4iZJSTkfIiUm5MypFGeWIpV+IuMHKgU85IyptLuSspfy/lz6JcKpTLg3LaUE4TyutEuVUoxxPluKFcO4S4KOcJ5byivDuU+4VymtEeMNqLR/uwaT8e7YukfcG0N5Ji9LRPk/YKk5Og/YK0Z1pF/OWcDvtPfCLnL09SyD+rGeNPpWL+WaXJ5j+m8XQyw/6oYv5ZLcw/6X2WMeyvSQP/jDL0T00D/6xi6J8mvP+Y+HyYoX+6MP8gPDWFoX+GYv5x7n7E/yl/NeU/IOyx0sH9ZS6f/2Dn/xL8k8bzEkb7P08x/5wpzD+Jz5Uy7D9fMf+MKeafszS1+W/jSfCnm/OHKZ59oWaMK0lLF+DPCxjtb7Zt/FddBPh/Ze3CeF1TrCi+0EEynEzn/y98uXnzlk/f2uP0fhX8Y45GuMUoEvyD/Nm5jPY/VzH/qBXmH1Sf5zPsvyAN/KOWof/CNPCPuQz984T5B/GpmQz9dcL8g8az8xj6L7LxD7dFAv9PAyOW2ODg/tdcPv/Bjv9V8M/5wvNfhGemMdp/vWL+sUCYfxCensGwv0Ex/2hUzD8WKuYfFyfhHxLnL1/kgH+oLhLr/1pa4nPmx6bOq22IzZjX2HBhBYMHZDr+375t8+bVG9bs3vCVs/ul+Of3GP6nSfH8RzPtlzR/l+Af5E/qGfa3KOYfi4T5B9nTyLB/cRr4x2KGfmqr/RL+Q4h/LGLoXyLMP4jPNDD0L92P4v80j07z95S/Y5OD+xe5fP6DHf9L8E/y5wsY7W+Z4vmvS4T5B40ndQz7L1XMPy4T5h+EZ+cz7L9cMf+4QjH/WK6Yf3y/+/yfbjEFFBdh/lcUr+BNAh0I8z9u+F8i/uD0CCGKP1A+g42aMa4mLV0w/3k9Y/y5UjH/vIryJZu/S/BP8ueXMey/WjH/vEaYf9L3LWfYf20a+Od1DP3XpYF/XsvQf/1+xP+WgcH/aK21E/7X4vL5u/d/uY8/UDzhCkb7u0F4/pP86eUM/Tcq5p83CfNP8ufLGPavUMw/bxbmnzSeX8qwf6Vi/nmLYv5564G1/8tc/zWtLt5YwV4Blun4f9sqd+u/VMQfbksy/+n0CCT7/OeKffCPgRPTxz/uZfif2xXzjx/Yxj8J/kH2rGTYf4di/nGnMP+4SzPadKr670oD/7iHof/uNKy/u5uh/x7h+S/Cc7cy9N8rjD+pPd/C0H+fYvz5w/2I/9E+V1r/R/sHnaz/e93l83fv/3HPP8if3sRo//cr5h8PCPMPGk9vZtj/oGL+8ZBi/vGw4vmvVUnwp5vzzyme8axmtKukbWRi+vHnM4z298gBuf+HvfRPxH/uD+v/Mm3/z6PC+e/o+x5itP/HFPOPx4X5x5Oa0adT1f9EGvjH0wz9T6aBfzzF0P8v9q4DPIqqa29BlM+CgKIiIKIiAkpCR0QQEAlSRQVrDBIgCkkooYlS7CLYCxYkWWkhlJBCCqElJCFASDYhQKSJBRRFEQQEo/97mQ2OD8vvnpmzHJbs/Z7XbwXnnD2zZ+68721nPrP+UHw6muB/AbP+UPk0m+A/9jza/6POFlL8X51vY4T/rzH5/f37f869/lzIPP+h+rPPCPkfJ6w/FjHrD/U+m0WIf7Gw/lgirD+WCuuPeDf6g6P++mID+kO6sa3/6hU2ZOjoruof57T/lL6ZauVXXrwjLnNVYn7yiozjztQtGZTrufRnOqH/WSY8/5HAvP4q0ar1KZ76TxTWH0nM+iPFqt1TT/0ne0F/pBH8L7eqftvVfzDpj1SC/xRm/aH4zDKC/9TzaPxfzfuq8+vVmZs9DHSmYSa/v3//j3n9qZ7neEL+pQnPf6Uz6w/VnywixL9CWH9kMOsP9T5ZQoh/pbD+WCWsP1YL648159H6L5b6nYHGr/d1/q94f8bx9GOJ+XllRqr4levP1obz32pV6xl2WLXnym0fcQ7mv9YT+p+1wvU/M5nrf66zas+0p/6zmOt/ZsPeBoL/dcz6Q/WnWQT/2cL1P3N0599x6Y88Qvy559n5v2oP/0sWrfYAta0z+f19nf+bbRz6U/HJTEL+rWee/1LP01qC/zxh/bGBWX+o53klIf6Nwvpjk3D9z3zh+p+bhet/FjD2/yz8vY1FrEnz95wDuctzN6tR+6KC+G3O2OLthdHFhxxxqc70E3mpRZnqbzafTMuKz83YnHiY3385/zf6E+jnnzYL8v/thP6vUJj/O5n5/xarFpOn/ouY+X8J7H1F8F/MzP9VRhUT/G8R5v/qft1x+vnj4f+lhPi3Ms8/qPd5EcH/Nmb+p+JxEvxvF+Z/pcz8T93PfEL8X+n8m9Vvqjaamr/5yVUDitqyLeZaRddvZpsE/98hzP93CvP/XcL8f7eb9Udm6r9vdD3/uwX53w+E/m+PMP/7Gv4vdn3m4H/fWTWbnvrfq3//sMy/NLNINXn9lppYGO0sXBWbfUTVYXXEZaYXFah/S8pS/74s3Rmr/gtv+Tf7/ubg/9/jRzhAyL9vmPm/ep6/Jfj/Vpj/q+e1oeszF///kRD/98z8X71PvyH438fM/5W9vQT/+4X5/w/M/F/Fs4sQ/486/6oOrDq/t7FVOxeU2mqZ7ID9/N1cM7t+WoL/HxDm/z8J8/+fhfn/wTP4f3OW+tu/CPL/Pwn93y/C689/hf+qrs8c/P932DtEiP+Q/vc/fX5uv6jISDr/uhD2T+QsdcTlrCrJXpaacjyp1JmueHvD7CNFmeoPnMUrlhZGlxSU/8VtvP451k+rMTh1/kSpgesl9h/8xsz//4C9I4T8P+wF/n+S4F9913LFzMX/TxD8/87M/9X77DDB/1Fm/n/MquWUp/6PCfP/48z8X9k7SIj/D53/6ys4fz+vNkMaaL7I/08w7z9Q/cmvhPw/Kbz/4E/h/QdlwvsP/nKjP8zUXz+C/69sxz9sZ8mRc6A/Lrd5nn9/C+sPdZ8uL/8t/DVQKjSU/osaHaHE37DxBvLP1/WfknirYlO3Sfk3q//U+G0TYCLQycD1HOMPldGf2Aj9n9Umu//dZuPVn/+DvYsI8dtt/PrzMoL/Sjb+87cuJfi/yMarP0/xCYL/yjZe/XmJTftNPfV/sU1Wf16ii7+2X//5dDOr/zjGH6rYNE7raf5VscnuP1H9Naf+VM+zlfD8X2qT1Z+X2WT15+U2Wf15he1M/dnMcPz/zH9VE9SfdQn5V9Umqz+vtP1T/4yDf14DezUI8VcT5p/Vmfnn9bBXkxB/Ddu/5v807WewAIuv67+k0g2n1ulJ+Ter/5T2mwdMtRirn8elP+oQ8u8qL+iP2gT/VzPrD9WfXk3wX5NZf1xn0+6pp/6vEdYf19p4579q2bR3iqf+rxPmn7WY+ae6n9UJ8V+vi7+DX//5dDOr/yT0R21h/VFHWH/UdaM/zNTfVnomAKgvqD+aEvqfG4T1Rz1m/dEQ9m4mxH+jsP6o747/GxTAvs//k//ydf6vzkBV/H+Kges59GcT5NOthPy/yQvzH3cQ/N/sBf1xO8H/Lcz6Q/VnDQj+GzDrj0Y2LSZP/d8qrD8aMuuPxjatT/fU/23C+qORTn+09/N/n26m6ycw6E+VzzcR8r+x8PxHE2H9cbuw/rjDjf7gqL/dXFB/dCTkX1Nh/RHArD/awl5LQvyB7vi/QQHq+/w/t8zX+f9rFo3/zzZwvYT+bMY8/9Ue9toQ8r+5F/RHB4L/Fl7QH3cT/Ldk1h+qP2lN8N+KWX+0s2k2PfXfWlh/tGHWH3fZtGfKU/9tdf7v9vN/n26+uP/nTub5L2WvBSH/2wnrj7uE9Ud7Yf1xtxv9Yab+uppPeBroIqg/+hLyr4Ow/uio0x+n+b/BDVi+z/+1bf1S/jn4f3eLxv8HGrieQ392Rz51JeT/PcLzX52Y9Ucv2AsixN/ZC/qjD8F/Fy/oj94E//cy6w/1e3Yj+O/KrD96wN59BP/3CeuPbrr47/Lzf59u58P+j542rU/zNP+ChOe/ujPrj/ttWp/mqf/7hfVHD2H90VNYf/Ryoz846q8/JKg/BhLyr7ew/lBcpbbrMwf/fAz2+hPi7yvMPx9g5p/BsPcoIf5+7uZ/gvsPDQ0vPwuuU+jgiJEe3Y4L4/w3dQqAjH+O89/UV1+inkUDN5NLf4QQ8u9B/fgDk/54iuD/IWb9oZ6nRwj+H2bWH0/A3gCC//7C+mMA8/zHkzYtpzz1/4gw/3yUmX8+btNyylP/j+niH+bXfz7dfHH/x+PC+uMJYf3xpBv9Yab+tuKTo4HB/6E/6g3xnv4YReh/goX1h+IK9VyfOfTHMNgbSog/RFh/DDw7/793XGTooLDRYRHhBA1gpkn3v8XJW3ye/1e3avz/ZgM3k0N/RiKfniXk/9NemP8YSfA/yAv6YwTBfyiz/lDxPEPwP5hZf4TDXhjB/xBh/TGUWX9E2LTf1FP/YcL64xmd/gj3cf7v6+NPZltQeGTUaOH9H8Nt2jPtaf49Kzz/MUxYfwwX1h/hbvQHR/3vsWfRH+W6w5v6Ywoh/yKE9YfiS1e4PnPoj+dhbzwh/hG63z+oU3DnoSHhQ0J7hYwxsgasove/nh65fbamOu4E4ASQa+D6ESZvIEf9xxeQT1MJ+TeSef5rHOxNJPgfZZOt//iX7r/j0h8vEuIfzaw/omDvOYL/KGb9MQn2JhD8jxHWH2OZ9cdkmxaTp/7H6fz76y+aazz1k1sYvt7s7yehP8fbZOs/TtDlfx/0eqPwv7Gn+kC6AjJSf/E5nf+elijcgdG4Bz2AcPI72Ej8E93wfzP139V67nXAq4L8/x1C/6f4smT9d8WXOOu/T4e91wnxT+Kdf7DOgL33CP4nM/O/12DvTYL/KcL8T3HlKqefPx7+9y4h/hd18ftr4BjDZtuFce+k9Xdg2rrEuPx0R5qQf7Pzb+2B5cBYYJ2B60cKj79z6L+X8SxMI/Q/LzHrv7dg7w2C/5eF9d8rzPrvbZtm01P/rwrPP70mzP9ft8nWf3/DJlv/fZrOf0XX76bPT9Pq5/0zhk68Xnr8XNN/LSwBBq/Xz/98JKj/viT0f28Kz/8ovVbN9ZlD/30OezMJ8c/QPf9luMaOX+QiVUMNqKxqkwIXA1WAS63avoLLgCuAy4GqQDVVQ9uqrT26GqgBXAXUBK4FrgGus2r1pWtZtTpjdYE6wA3AjUA9oL5VW7d0E3ALcCvQAGgINAJuAxoDTYEmwO1AABCiaqgDgUBzoCXQAmgFtAFaA22BdsCdVm2fqzrrRp13qc68vwfoCHQC7gU6A12ArkA34D4gCLgf6A70AHoBPYHeQF+gD/AA8CDQD3gIGAA8DPQHHgEeAx4FHgeeBJ4AgoGBwFPA08AHQCgwCBgMDAWGAGHAs8AzVm2dtlqrMRyIsGq8MdKqzf+MAqKA0cAYYBwwFhgPPAdMACYCLwDPA5OAqcAUq8z6w7eY9X807H1GyP+3vaD/HQT/73hh/30Mwf+7uvjNtvg9CesvhPqpsRZj9VNH+fj6KQ799wHy6VNC/r3HrP++gL1PCP7fF9Z/HzDrv9mw9yEh/g+F9d9HzPufZsHex4T4PxZefzZTeP3ZJ4z9v6+v3+GZv20u9v3N3n+J8ZdPz5h/bGExePzYKf2p+vMkYL6g/lxG6H8+E55//Jx5/nEx7MUS4p/FPP+4BPYSCf6/YNYfC2BvEcH/bOH5R6WX2lh4WlCXvLKVm/JylhZmxCTGbfijuDQpy5mQV7b1WH5s3uL89Lwyh+tPCwryyvJjU46qP4t2cPV/Zvm/KnukxhhUTfo2BjrT0RcM/zenPxMI+R/DvP5wLuzFEfw7mPXHUthbSPD/pbD+mMOsP+Jhbx4h/rnC+mOe8PzTfOH5pwWM/F+68fD3lmLfX1o/Scw/xrrh/wbLD/5r/ilFkP+vJfR/C4X5fxwz/18Je2mE+Bcx8/9VsJdF8L+Ymf+nwl4Gwf8SYf6v+Motrs/xubn7kkpbOhOSspJKm29wJsY54oK6rNxUkJiwvmUzx/ytMYGOBV7sfzj4ewfX/GFfA51pVAU//4iL/2cS8j+emf8nw94Kgv9lzPx/NeylE/wnCPP/RGb+vwb2lhPiTxLm/8nC/H+5MP9POY/4Pw9/byX2/aX5e1GJ9gYPDNBe4YEB2jtcjckFBrT9zxe4BP9PdcP/jc6gKP6vxjO+A3IF+b+T0P+lCfP/dGb+nw97eYT4VzDzf7UXo5jgP4OZ/6+HvU0E/yuF+b/SSw1OP388/K+IEP9qZv6XDXsbCf7XMPO/AtjbQPC/Vpj/ZTK+/zn02wDXGs6hBl6mYyq4fjPbOPh/IfIph5D/WcL8f50w/88W5v85wvtPct3wP47649sE+d9eQv6vF+Z/eTr+Z7r/YNFvrS1STVq/KXmWppZGJBYFrIrNW+GYHxAdExgd0yw6pnl0TIvomJbRMa2iY1pHx7SJjmnrWKBWUziLy3Xeit9z5wQm5RaVGj2+gYX/70I+lRLyfwMz/98Ne98S/G9k5v/bYW8nwf8mYf6v9Fo312cu/v8NIf4CZv5fAns7CP4Lmfn/Htj7iuDfKcz/i84z/q/2M9XEd5psoDMe6+f/phoH//8av91WQv4XC/P/LcL8v0SY/28V5v/b3PB/M/W/1e/5O7BfkP//Rsj/7cL8v/S84//GVyP7+vmzuftSTzpjNx4sSEzek3I0qIsjrihz4vKSlCOO+Wpip+XEwICJzdp6bwkGB/8/iHz6kZD/XzHz/19g7wjB/w5m/v8D7P1M8L9TmP8rvdbQ9ZmL/x8mxL+bmf9/D3s/EfzvYeb/v8LeAYL/r4X5/15d/Bz8vYbrDIj6BjrTcX7+Lto4+P8h5NM+Qv5/I8z/vxXm/98J8//vhfn/Pjf8n6P+9nFB/n+R3fP83y98/pDiK9eW33+G86+0mtGnLHWOCNfKx3l6/YVRP9oRl78rryjbsXqTWnDl3OuIU7x+WfqaDRl7t+xNOZo6N2uHIy7nQP6v2UeKMh3RfHze7Pubg///hXw6Qej/fxSuf3iAmf/b8OyXEeL/yQv8vxKh//lZt/+Xi//bCf4PMvP/o7D3J+H+/8LM/y2I/STB/6/C/P+QLn41767OYpvuOleN2sb760f7dOPg/1bk/zFC/v8mzP8PM58/9Dfs/UGI/4jw+UO/C58/dFS4/t0xN/rDTP1tdZ71c3gGqtjd/zfe1h9Xud69nsZ/XH/+YMTwgREs/L9rxMjhIRTqz9J/VvT6cers1N4WbQ2tkf5LQn+qvrKG6zOH/qiK/L+UwD9PMM8/XEl8/k4y64//wf8VhPj/9IL+qEHw7436d5T7X8asPy5G7JdT4mfWH9Xg+zKC/7+F9YfSS5z7T6vD3iWE+K12Wf6pxgvK+WcQfIeiBx5l0L8R/qW0+vW6Z9GPiosXhAmUWf1+kaVS0pytOyulJBYXVVpbUpBfaeNO/CNpTtrX5+T7s6x/aRZg+HqzP18/9D7DXO+g0HNU/7CS/Uz9xVF//Nr/0F8BM7w3/1Of8P5Rc0WS678q23n3/9aFvVqE+C+28/LvG2DvZoL/S+y8/Ps62KtD8F/FLrv+R+mFykz9h9m25XBBvljxN4v5+bOyUzmknT8UYuD6ScI/AJf+uomQ/5faefVXTdirTfB/mZ1Xf9VTfJrgX2lFSf11BbP+uhH2riHEX1VYf11pl13/U80uu/6nut1f/+10/2d+/Uu/qMjIYeO19S+9w4ad2+9v/vz/c7/+q4Yb/m+m/vjVsNcKaHgW/l/O+73J/1sS+j81XyO5/kvdr+quzxz8/w7Ya0SIv6Zddv3PNcz8vxns3U6I/1ov8P8WBP9Kr9Ri6n/UOrfc+KJNaZuSljgXOOKKf1uWXpy85RjfCf//fzPL39X6l5PAfotW25DaJvvP/z+Vf80J+VeLmf83gL0mBP/XM/P/ANhrTPBfW5j/12Hm/4Gwdysh/rrC/P8GO+/6n6awdxsh/np22fU/N+r8V/T1F8zr38n8X/r+S6z/qm+XXf910xn6oyVL/eu2gvqjK6H/uVlYf9zCrD86wF47QvwNhPXHrcz6ozPs3U2Iv6Gd7/yX8v0v7nSA+jtv6wAO/r/Poq2jO2rg+ik+zv+59Oe9hPxTXKm+6zOX/uhC8N+IWX+0hr32BP+NmfXHPYrPEvw3EdYftzPrj06w14YQ/x3C+qMps/7oCHt3EuIPsPvr/5a3+0ZGREWa4P/l1xutXyvN/yX0Z6Bddv9JM2H90dyN/jBT/1jx6RCgu4z+IMffQlh/qLmaKq7PHPqjD+z1IPS/rZjXP/Ul7j9ozaw/7oe93oT42wivf1I6PeD082eaf5Lz705e/mntBnu9CPe/HeP7P2X3iuT1+0syHfO1Ew9ylyfPV6ce/HPiQcGulKysuNzNhdGbD/KfY2ZW/6l5sJnqmTR4/uhUH9d/HPrjAeRTT0L+3SWsP9oz649+sBdEiP9uYf3R4V/6Q+MfHPVX+/sI/+gozD/uYeYfT8DeI4T866TLPy79YzR/fH3+ydfffxz880ki/+zMzD8HwN7jhPzvIsw/7xXmn12Z+edDsPcY4f7fxzz+GQx7jxL8dxPmH0HM/OMp2HuYEH93nX/Ff7er59hmrP7Wiz7Of7nef82F4jd7vQT/vN8N/zRT//NB2AsHBvkI/+whzD97MvPPZ2BvMKH/6cU8/vUskX/0ZuYfobAXRoi/jzD/6KvjH2bbhTD+UwocQq8QbKAzfcnH989L8M8HmPnnQNgbSnj++jHzz2GwN4Tg/0Fh/vkQM/8cDntPE+J/WHj8q78b/sFRf3KEj/CPATr+wcV/jd4///iPuWb2/SfBPx9h5p9jYW8Uof95lJl/jiPyz8eY+edI2BtDiP9xYf75hPD415PM/CMC9qII9z+YmX+Mh73RBP9P6fhHHWAGoN5KQQY605d9nP/ynN8UKBa/2dsvwT9DmPnnBNiLJOT/QGH++bQb/mmm/qEaT88AXhDcf/Ia4f4PEj7/KpT5/KuXYG8yIf7BzPzjZdh7g+B/CDP/mAR7LxL8DxXmH2qsru7p549n/8HrhPifYd5/MBH2phL8P8u4/qtc9RSsU6onJfPflW4sXm9m9c8Ei8ZF70Gv2NHA9a/4139ZX0E+TSHk3zDh8a/hzPzjVdh7nhB/uDD/iBA+/ypS+PyrEXbZ+ncj3az/56h/N8MA//P1xrB//4HQyJCwkcH9Q8P6RJCv9/XxSy7+/ymh/xslPP+txkqquj5z8P/3Ye9tQvxRwvvPxzDz/49h7z1C/GO9wP8/Ifgf54X9xzMJ/scz8/83Ye9dgv8JOv+n6s8XrlxUVLClrLg090DOX0lZavd+wa6UxPyY7OykLO/2Pxz7951AI6t2hhe1vVbB69dx8P8PkU/vEPLvOWH+P5GZ/38Ee9MJ8T8vzP9fYN5//gHsvUWIf5Lw+VeThfcfTxHefzxV599fA6Viw+frl7LM3zUT+/7S9798/MFM/ctp6E/igC/+Y/yhY5L35p8WEN4/LwrPP73EPP80B/aiCfG/zDz/NBf2FhL8v8KsP2fD3pcE/68Kzz+puVLu+uuxhPhf18W/Nca515FWkq70XlKpMz0jJrlIacLUxMJopQP//TeaIsyISYzj6n/M6r9g4ACQil7lDwPXv+7j61fMNo7xh8+RTw5C/r3BvP5pHuzFEPxPE9afbzLrz/mwN4sQ/3Rh/TlDeP7pLeH5p7eF55/eYZz/N93/mJ+/6Tw0JHxIaK+QMeOD+w8NDXfN53h4va/P36gRW1P338X/OeovLjkL/y/n/d7k/ysI/d+7wvNPaq7kOtdnDv6fBHvxhPjfF55/+oCZ/6fCXiIh/g+9wP/TCf4/cjv/Y47/pxH8f8zY/5vl7+2Ap4BpwAgD10+v4PM3Zr8/B/9fhHxKIOTfTGb+vxz2lhH8fyLM/z9l5v8psLeYEP9nwvz/c+b5p2TYW0qIf5bw/NMXwvNPsy9s/t85InxQ2OiwiPDggOD/rKzu6/w/27F6U9pPaxKMXi+hv6PdrH80U/9R9We7gNWC+mMTof+JEdYfaqzuRtdnDv2RDXtrCfF/Kaw/5jDrjzzYW0eIf64X9MdGgv95uvzj0h8bCP7nM69/Wwl7WQT/C5j5Zy7sZRL8xwrzz4Xnmf6bCKgX2HQD18/w6z9TjUN/rEc+rSLkf5yw/ljErD9yYG8NIf7FwvpjibD+WCq8/i3+DP7ZiqX+X6Eg//yKkH/LdOtfpBvP+q0Whq/3df2Xl1qU6SzevFatycg4XlCQ8md6OuV6Cf2RwLz+aSvsFRHyP5F5/dM22NtJ8J/ErD+csFdC8J8svP5Jjdde5frMpT92EOJPYdYfm2FvC8F/KrP+2A57xQT/aTr9YbaZ5f/q5JxZwAZgsYHr367g/N9sk9Cf6czzH6WwV0DI/xXC+iNDeP3TSuH1T6uE1z+tdsP/zdTfy4e9A8DXMvyfHP8a3fif2cZ1fqjR8698nb+vil0eI+lfgv+vZT7/cx/sfUPo/zOZ+f9+4vmfWcz8fy/sfU+If50w/8/mXf9Ezr8c5vM/d8Ped4T7n8vM/3+AvW8J/tfr+L9Z/t7UosYQLZar0ZGWGLj+PR/n7zzjV63E4pfg/3nM/P9H2NtDyP8Nwvx/4xnnf7Ziqb940AD/LMN1qoaTOsdX1bJQ59mpPVGvWrWzMd4A3gSmWbW1lm9ZtTk3pbvfBd6xas/wh8D7wEdALjAT+Bj4BPgM+BT4HJgNzAK+AKIBBxADfAnMBeYA84AFwHwgFogDFgKLgCXAYmApsAyIBxKAJCARSLZqe8GWAylAGrACSAcygFXASmA1sBZYA2QC64AsIBtYD+QAecD/tXceAFFdTRtekGbvsUaNvStiT2xgD3ZjV0RFISoQBUuKSUwxvSemGQt2SRQFFQF7QVRsiL23WGPX2PK/h13MzZf1j3PvLMPi3uSNm8Q74yyzZ5+Zc+4596Ct0BZom5N5n+RkaDu0E9oN7YJS1PgH7YH2QvuhfdAB6BB0EDoMHYWOQMegE9Bx6CR0GjoFnYHOQWfVfibQeegidAG6BP0BXYauQNeczOeWXIduQjegW9Ad6LZ6Hg66D92FHkC1nDFeQA/xWj347ezMN/9wh/D52yb8/G0yc//5BuxdIcS/nZk/b8LeXYL/HRr/0vVP6r7l0dHJSQ8iVsj4N8o/PlAw9JbJvI6Ben0jzD8c9ccfyKfrhPzbKVx/qPmSHI9+fjzzD38S4t/NPP9wEfauEfynMNcft2DvKsH/HuH1T6nM/Hkb9i4R4t8rzJ/7NPxp7/MXRq92waHhYQb6l+28/VoGjFHPnAb4h/mEhAcTf5TS/UuJ+Yf9wvMPB4TnHw5amX8wcv6pYvs/ANQPBdcfebg8+fh3SHj9u1qrUcDymoP/XdQPkxD/EWb+d4Wx7AT/R5n7z3/BXjaC/2PC/Kfm6Zweff54+C8HIf4TzPx3H/acCf5PMq7/5jpHVu/1hCE/9poIqf7tfGiCjvu/dZz/4OSGZHIi5N8pYf4/zcz/7jD2gMD/Z4T5/6zw+pPfNfF3xqg3Gn+NTRsD6Svw9fDXOY3/DuC/EYg6CJkQhPgDMiD+81b4j+P82TyPGdT/P/5zNtn3xTP/1kD3/Y7zH8z8U5Qw/l8Q7v9fZO7/F0Ls+QjxX2Lm/8IwVpzg/zIz/+eFsYIE/38I87+aq3GzvObi/2KE+K8y838uGCtA8H9Ne/5D/JrtUnMvaT8Lg/MvraHJ0Eholo77v3Oc/2CY/59BMuUn5N91Yf6/wcz/RWAsNyH+m8L8f0uY/28L93/vCPd//7TC/0bO/80JY9WgUo/h/86HzNyf/qspE11M8y+dgnQWAfbO754GG3Bc/F+ZMP7dFe7/39PM/3Pwf3nEXoYQ/31m/q8AY1UI/h8w839pGCtH8P9QmP/VfEV634OL/6sS4lfBc/J/SRgrS/Dv5OI4/8chs4x+/xg1EQp9a9EcHfdPtvP6Tbr/ylH/VcRg8hxh/FFzlZL1XzYX3vqvEow9S4jfxUW2/lPrBSTrPzcX2fkfdxfZ+R8Pl3/Xfxznf9cUqP945l8a6r7f3uu3mIW75kn2X7nqv4aE8U+tVZKc/1FrdTjnf+rCXm1C/DldeOu/ejDWmOA/lwtv/VcLxrwI/nO7yNZ/ap6ce/6nESH+vMz1X3UYq0Pwn0/jn2P+ZanJPP+i56jw7x3794heHPxfH8nkSci//ML8X4CZ/xvAWA1C/AWF+b+QMP8XdpGd/3nGRXb+p4gV/jdy/m4JGOsLNdXB/1z815aQ/2qtkGT/X63VyGl5zcF/LWGvOSH+4sz81wrG2hH8l9D4Z5p/azFyZIiu+5/2+Tejl9H+Kwf/N0My+RDyr6Qw/6teHff8T3tC/KWY+f8FGPMm+C/twvv8b2sYa0HwX0aY/55j5r82MNaEEH9ZYf4rp+E/Nf8SbTLPv2zU4f8Hx/yL6GW0/yrB/+WF+/8VhPv/Fa3wP8f5ux0F+b8XYfyrJNz/rczc/+0Oe50J8Vdh5v+XYKwPwX9V7fdf2vyL3tPX7J/fl6cuXm/P69+Xmczr34+Y9K1/5+D/TkimboT8qybM/9Vt0P/vTYi/BjP/+8JYV4L/msz83wPGuhD81xLm/9rM/N8TxjoQ4vcU5v86Gv7/0TH/Inox9d+6hQXoKwMk+N9LuP9fV7j/X88K/xs5//ZFGBsODRDk/0DC+FdfuP+v5utyWV5z8P8Q2BtIiL8hM/8HwFgQwX8jF779Px39d2P998Mmc+/N2Unf+uefDP4AOPjfD8k0mJB/jYX5/3kb9P9fJsT/AjP/94OxQQT/TZj5fyiM+RP8NxXm/2bM/D8MxvoT4m8uzP8tNPzv6L8bu1jWP3vp/xKzx/0/vYX7/z7C/f+W/+L/BiznDwcL8v84wvjXSrj/35q5/x8Ge6GE+Nsw8384jL1K8N/WJfPs/792jWT3naf/rtY/q/67nvXPP2eB/f9DkEyjCfnXTpj/27uwnj+W5n88If4Xmfl/BIyNIvj3Zeb/MTD2CsF/B2H+78jM/2NhbCQh/k7C/N/ZxbH//6OxiKf/7jtG5/1P4/7/XYT7/12F+//drPC/kfOHVT8rFpogyP8fEMa/7sL9f7VehvP82Xdh7y1C/D2Y+f89GPuQ4L8n8/Ofb8LYOwT/vYT5r7cN+r8fEeLvw8x/r8PYRIL/vi58+/9nhfkXtf5Zzb/oWf88xbH/v9P7SKa3CfnXT5j/+zPz/yQYe4MQ/wBh/vcTfv5zoHD/11+4/zvICv9xnP/7mQ7+s/f5F5/AgMHDDdRvPt5+LcLDQlr7Dw4LGUXHH8f+/xb++Ykw/g0W5n+1XieP5TUH/38De18Q4g/g5X9y/EOZ+f97GPuaEP8wG/D/jwT/gZr84+L/Hwj+g5j5/xMY+4rg/2WN/9iZS+asmh+7T2r8MTr/UhyqbjKfveyt4/5fHPv/G+b/75BMXxLyb7gw/49g5v/JMPYpIf6RwvwfrOF/H1NgWgYMxz+H6PCv+k/fwt7nhPhDrIz/XdOqkMAMqT9CNf67weN43d/+ir/p/l/5R/854+uvUZlo/t/o1WZUSHioAf5Pv1/v/pv2zv/p9aeR84c/RjLNg6bKzD+Q83+0cP0Rxjz/MAv2phPG33Dm+YfZFt9P6n8Mc/0xDcZmEuIfKzz/MI53/Qk5/8Zr/CfMTbkoOf4Y5X9PJ/UdbjIVcTaZUnXcP9XO+d/o+mOG+tNpCpIpgvD5e5V5/dEcGJtB8P+acP3xOnP9MRfGfiHE/4Zw/THhH/WHmT84zr+N/A/+GJitrc3WPywlvP9vCq9/fkuz/tlxBsrTLfPzJ56688/e65/Ufcujo5OTHkitQjfKP63wBgbj14lO5h4o+X6G+mMxxpPfCOPf28z1xxIYW07wP5G5/vgVxqII/t8Rrj/UerX08++45j+WEeJ/j3n+Yz6MLSL4f5+ZP6NhbCHB/yRh/vxAE/80x/4vohfD+nPv8KARQ/y6BoQG+If5hIQHk5KZo/6IQTItIOT/h8L1x0fC658+Fl7//onw+vdPrax/MnL+8c8wth+Kf0z9l1732bL+20jI/8+E+89qrq6Q5TUH/62FvZWE+L9g5r91MLaJ4P9LZv5LgLE1BP9fCfOfWquT/iGw9/pNePm54fXn7+INVP3bSPw6Qcf90w3+ALj4P5GQ/98w8/8KGFtN8P8tM/+vh7FVBP/fCfP/ZOb+8wYYiyPE/70w//0gzH8/Cq9//4lx/Ydj/x+O/X/q6L7f6M9P4vmHn63wP8f5t1sF+T+VMP5NEZ7/+YV5/5tdsJdMiH8qM//vhrF9BP/TmPl/G4ztJPifLsz/MzT7n0vze2L8mu32vP9+Wyfz/vshTvr2358h3H/l4v+9hPyPYOb/JBjbQfA/k5n/U2BsO8H/LGH+n83M/3tgbAsh/jnC/D9XmP/nCfd/52v8O+ZfmOZfOgXpKgPk9//J+P7/Aiv8b+T8280wdg46JMj/ZwjjX6Rw//9X5v3vT8DeEUL8vzHz/0kYO0vwv5CZ/w/D2HGC/0XC/B/lwtd38bLz/V9GOZn335+sc//9CDtfP8HF/78T8n8xM/8fgLFjBP9LmPn/FIwdJfiPFub/GGb+Pw1jBwnxLxXm/2XC/L9cuP8fq/Hv6L+r/ruX7vvtff5cov+/wgr/c5x/e1GQ/28Rxr844f5/PHP//xrsXSbEn8DM/9dh7A7B/0pm/r8EY1cJ/lcJ8/9qTf8/ZuGuefbef1f776v+u57992c+5eufufj/NiH/1zDz/3kYu0Lwv5aZ/2/A2B8E/+uE+X89M//fhLELhPg3CPP/RmH+3yTc/09k3P/X6MXWf28xcmSIjvvtnd+N9t8k+v+brfC/kfNv1fP8YQDq+4L87+b65ONfknD/X83V5ra85uB/Z8T+kDD+b2Xm/2zw7054/7cx8/8DtZ6e4D9ZmP+322D/ew9C/DuY+e+uMkbwv5OZ/1yUb0L+7xLmv92M3/8c8y9q//3JOvffn2Xn9Zt0/5WD/12R//cI+Z8izP97hPk/Vbj/v1d4//t9/+K/hiznn+Zytf57MoL/niF8/+wX7v8e0PR/DY8fLPMvdXXfb+/12/LUxesl+68c/F8AyZyHkP8Hmfm/IHwXJfg/xMz/ueE7P8H/YWH+P6Lp/3PxfxFC/EeZ+T8HfOcj+D/GzP+F4Dsvwf9xYf4/oYnf6PxLrOX5h2M6n3+Y7dh/RvTi4P/CyP2chPw/Kcz/p4T5/7Rw//+M8P4vZ63wv5HzT7Mj96pAJQX5vyIh/38X7v+e05x/xDb/0i0sQE8h8LTPvxi9jPbfOPi/LHK/FCH/zzPzfzn4rkTwf4GZ/5+F7+cI/i8K8/8lG/T/KxPiv8zM/8XhuwzB/x/M/F8evksT/F8R5v+rmviPWp5/cHHW9/zDHEf/XfQy3H9j4P8KyP0ShPy/Jsz/14X5/4Zw//+mcP//lhX+5zj/trog/9cn5P9t4f7/HU3/39x/r6fbv73z+9o1kt13nv6bWv98TOf6Zw7+r4NkrknI/z+Z+d8LvhsS/N9l5v8a8O1J8H9PmP/v854/lea/ASH+B8z8XxW+axP8P2Tm/7rwXYvg/y9h/ldfPunxS58/oupm1T/IzGektMef78VM/mfUq7mO+RfRi63/6jtG1/0c9V89fDaqEcY/J1fZ+k+tV5as/7K5ys7/uLjKzv+4uv67/jNy/mwx2Oulfqb/Uf+FVrVd/deakP/qWQHJ+R+1Vj6n5TUH/3vDXlNC/B6uvPzvA3ttCP6zu/LyfxPYa0Hwn8NVlv/VXH163/MB7lG932yQK+QOuUEeUA4oO5QTyg3lgvJA+aC8UH6oIFQAKgQ9AxV2Np/FWhwqChWDSkAloWeh0lApqAxUDnoOKguVhypCFaBKUBWoMlQVqg5Vg2pAtaGakCc0GPKC6kB1ofpQPagB1BhqCDWCnoeaQC9ATaHmUDOoBeQDeUMtodZQK6gN1A5qC7WHfKEXoQ5QZ6gj1AnqAnWDukLdoR7QS1BPqDfUC+oD9YP6Qv0hP2gANBAaAvlDg6AA6HtoGDQUCoRehoKg4dBIaAQUDL0ChUCh0CgoDBoNhUNjoTHQOOhVaDz0GvQG9Do0AZoIvQm97eyYfzV6GZ1/PWp5/kF9BvU8/zAvk5z/0JYw/uVy5a3/G8Nec4L/3K689X9L2GtG8K/WykrW/3ldeZ//bgV7zxPizyfM//mF+b+Aq+z8T0FXx/kPXJdv0Ggj5bvJ19uvZcAY/f7t8fyHQlbqP47zv30fU/+l1322qv96Wsa+J41frZdNn3+TqP/Us0rp6/856r+usNeRMP4XYa7/uhHf/6LM9V8H2OtCiL+YDeq/HpT5D83vk+Z3o5dR/q5leRPW4ZfmOt6M+Y79X8n9h+LM/K/mZzoT8r8EM/93h71OBP8lhfn/WWb+f8kyP/ak/ksJ839pDf+3g+8AfAOP1uk/lw7/aq3qVMvrbvA+wpKDARnE/+U0738uU07P2tUbpf3tVTtnndrV66gX6jX+e73a1T3V3zk9LS/wf3Orf9bzhNR/yIXfXt/8Pz1r5zbfrv4PhN9ouUX9klf9m/m+NOVMt4e/c1nM10mzaP4Xr7S7nmT8N/QF4B0eFhYSbOD+sGAF8H4thgzRdb90/y2dv42cv9wO+TQU6ivD3+T8L6/hXwn+rsA8/+IPe/0J429FXv4mx1+Jmb8Hwd5AQvyVhedfqriyPn9Nfv+ruvLt/7P1UvzumAST2GV0/eR+yyBaGCqmYzBdkGX4Xzd/O/VGPvkRPn/VmPl7MOwNIPivzsvfTgGw14/gvwYzfw+BvT4E/zWF+buWhr8747tnXBoD6yNwPfVPbSv9R47zZ4PshH88Nd8/Ri8ufu4aMDJkjA4Asff5610blzyQ9C/Bv+p5gfTnzzn4NwT2hhPGPy9h/q3LzL+hsBdMiL+eMP/Wd2V9/oD8/jfg7T86DYO9kYT3vyEz/7wCeyMI/htp+IeDnytY+LmpjsE08ilff84wf5y2/lvv/Rz8Oxr59DIh/xoz8+8o2Ask+H9emH9fEObfJlb418j5q2o8WQiNFZp/n0ic/20qPP/eTLP+m4N/3oC98YT8b864/udpnz/2dDK/CRuc9M0f/yr8/cex/mIC8fPXgpl/x8He64T897YB/76tc/2FxPy7D/P8ezjsvUaIvyUz/74Je68S/LcSnn9vzcw/b8HeGEL8bYT5p63w/Luar4yyvJaYf/e1wl8c51++r4O/jNY/uUw5vSwLBvB3bjX172We8veqnadOA/N/hzwt/+qpfkMDtbLgn783d920X6rXN99ZN232/9G/epn/p/n3PPpX9T/xn/Kq/6ys1IMaqP9d7+/fXQ9u66W5tzj6nz9/Zlg/YDnAStcKAqPf/xL95w7C8+9qrSrn+UefwN4HhPG3k3D/sTMj/xu97H3++KCF/9Uzj3rmj38T5n8O/v4U+fQxIf+7CPefuwqvv+jG3H9+F/Y+Irz/3Zn5+zPY+5Dg/yXm+fcvYG8SwX8PZv7+HPbeI/jvKczfvTT8Ld3/5uMnfTPIT/v8sUT/ubeV+sfI+Z/vqPXU0Dd2sv6ijzD/9tWMvxz8+yPsfUcY//oJ829/5v7jT7D3AyH+AcL84yc8/z6QmX++gr3vCe+/PzP//Ax7kwn+BzHzzy+w9y3B/2DG9b8c9VMFS/2kZ/3Awqd9/UAm2P97CvLpa0L+DRHm3wDh+feh/+KfRiznX84Qmn9XviMJP3+1Xkpy/+tAzfw/B//Mhb2ZhPiDmJ9/nwd7vxH8v6ytf9P2/9a7+tn+66dV85fNiF2QlBCxIjF+zfbqMQt3zauuzuSsvnZNhvg3+v2pnl//HaqCN/K2jvs5+DcC+TSHkH/DhflXrZUsYXnNNf/+KyH+kczz79NgbzbBfzAz/86HvVkE/yHC8++hzP2/BbA3nRD/K8L8M0rDP4sc+z+LXjznZzfQfb/E/mejhfc/DhPe/zjcCv8bOf/yS9jbDi0W5P94wvg3Rpj/xzLz/3LYiybEP46Z/2NhbyXB//gstP43YW7KRTO/y/g3yu9q/bDi9zd18nuUwR8AB/8vQT4tI+Tfq8L8r9aq5rC85uL/BEL8rzPz/yLYW0rw/wYz/6+AvRiC/wnC/P8mM//HqfWkhPjfEub/tzX8n9nPp5mXRc/dySxy1G/GLp76raHu+43+/CTqv4nC9d87wvXfu1bqP47zT9cK1n9bCd9/7wnXf+8z13+JsLeeEP8k5vpvM+wlE/x/kInWf29ZEHd7zY6oS6uurT+QeDgiMjUqYXdS7O51qqZLerDysK39G67foDZ4Ey/g15d0vJmLs8D673XIp02E/PtQuP5Ta6XLWF5z1X/bCPF/zFz/rYa9jQT/nzDXf0mwt4Hg/1Ph+u8z5vpvC+ytIcT/uXD990UmWv8tffHweyOxP7898v+Xwvz/lTD/f22F/42cf7kK9o5CuwT5/xBh/PtGmP+/Zeb/fbCXQoj/O2b+3w97Rwj+JzOvf98Ne3sJ/r8X5j+1Vr/Qo88fD/8dJsT/IzP/7YC9VIL/nxjXf2/bGH9r3arEPYnJyVeTolTlNj3ClIGX0fpNPXOv1tAdgprquH+Jna+f4eD/A8inPYT8+1mY/6cw8/9B2NtJiP8XYf6fKnz+4TRh/psuzH8zrPAfx/l3J3Twn71fLPVbXblDhKV/GFz8f5Ew/kUI8/9MZv7/HfZOEeKfxcz/52DvMsH/bGb+Pwl7Zwn+5wjzv3pep73lNRf/XyLEP5+Z/4/B3hmC/wUa//F3dh/Ym7J0YezMJXNiZ68/tDhuScTudRGR61ZFJydsiFqZum/H2pQtO3YkRUVExh1P+537ovZEREYdWnci+Xr0rGUz0u+WGb+M8n9xaBQG4XzOJtNbOgbjaAf/O51HPp0m5F+kMP//ysz/F2DvOCH+34T5f6Ew/y8S5v8oYf5fbIX/jZy/9yeMXXEzma79B/+/1SXr8X+bUSHhoQY20E+/X+8TNPa+fl5i/5slmv3PJfhfPauR3fKag//vwN4Nwvgfw8z/fxL3317KzP/XYe82If5lwvyvntcpbnktsf9NLPP+N1dg7xbh/V+h8R8TtStl+9q90Vsjl83YfFdR/vL7cXEJM6IjM2b8McrvNdM+w+b9Y37ScX+MnfN7u+DQcCMHyHDw/13k001C/sUJ8388M//fg72rhPgThPl/pYb/0/mT4/zDvx7Dn+ncaY0/ufqP2d2e/P1fJcwfq5nPv3NF7E6E+Ndo8q+dt59PoH/wsICO/mPG61iE4jg/xtj5MWrg3gXdhc7quH+ZwTeQgz/dkHs5CPm3lpk/1WaaLgT/64T50xbnv+QkxL+euf/8APayEfxvYF5/7A7fzgT/G4X5YxMzf3gg9ocE/khkfP7DsX6YYf65jpfu+43+/CT4c7Nw/zlJk/+dMeqNxl9j08bAjDn/Z4vGfwdTON6BMLwHvlAw+TtYT/xbrfSfjZz/eB/2SmIMyvuYQ8Uzgv+LEcb/bcLrD5KZ1x8URuz5CfFvZ+4/PgPfJQj+dzDzXz74LkTwv1OY/3Zp+s9c/FecEP/uTPT8p9eKDdGRyXFS2/cY7j82gVKhsdApHfcvF+4/cvB/buReQUL+pTDzfxH4LkDwv0eY/1OZ+b8oYs9DiH+vcP9xnzD/7Rdef3BAeP3BQY3/p71+Mzp/8o/+qY5FHNL903T+5zh/tLQg/1chjH+HhPv/h5n7/xUQ+3OE+I8w839F+K5K8H+Umf/LwHd5gv9jWbD/W40Q/3HG5/+MXhzzJ1dN5vkTNx2DYexTvv81B/8/i9wrR8i/E8z8Xwm+yxL8nxTm/1PM/F8ZsZcixH9amP/PCPP/WeH+7+/C/d9zmWj855k/qaf7fntfv1DPYP8snf+NnL+ZC2OPL1RLkP8bEca/88L9/wvM/f96iN2TEP9FZv6vD9/PE/xfYub/2vBdl+D/sjD//2GD/n9jQvxXMtH5j6p/ftNk7p9n0zGYrnCcX2Po4uD/Gsg9L0L+XWXm/wbwXYfg/5ow/19n5v+GiL0mIf4bwvx/U5j/bwn3/28L9//vMI7/rP1zHZtgO9YfG+ufmfnf01Rb5wm0eTT9/2aC/N+OMP79Kdz/v8vc/2+F2FsQ4r/HzP+t4bs9wf99Zv5vDt8tCf4fZMH+/4uE+B8yr/9uAt8+BP9/MfNfG/j2JvhXzwtI8p96VoeT/9rCXlNC/M4a/44zcJ5uqXPnFiMPSjqbTJt05F+co/4WvYz2zyXqP/WskGT95+ImO//j6iY7/+Pm9r/r/xX/6zuBVvH/C7DXD+okyP+9Cd9/6nkxyf6/el6Ls///Eux1IcSfXcsfaftfeuqO397r7zp2vv68Jd7Apfh1An5dr+N+jvqvB/KpLyH/crjx1n+dYa87wX9ON9n6T82Xcs//9CHEn9uNt/7rAHvdCP7zuPHWfz1hryvBf17h+i8fc/3XC/Y6EuLPr/Ef7+B30Yu1f65jE3EJ/i8gzP8F3WTnfwq5yc7/FLbK//pOINX2//0E+T+IMP6p51Ul+//qeTXO/n8A7PkT4i/qxvf859M+f6b6Z2r/HtU/07N/T4Lw9y8H/w9FPr1MyL9izPw/EPaGEPwXd8t68z/DCfGXYOb//rA3mOC/JDP/D4O9QQT/zwrzfylm/g+EvQGE+Eu7ya7/KSPMf88J93/LCvd/y7k5nv9Nv3jOD6qj+/7M8fyv4n99e1Ap/q+OfPoVChHk//GE8a+8cP+/AnP/Pxz2XiHEX9GNd/3PGNh7jeC/EjP/hcJeGMF/ZWH+q2KD/u+rhPiruvGt/6ybBeZP1P49av5Ez/49K+28f8rB/yORT6MJ+VeNmf/Hwt4ogv/qwvxfg5n/x8FeMCH+msL8X0uY/2sL9389hfu/ddwyz/O/Ri/W+RMdm+Dbe//0b/7XdwKttv//piD/f0gY/7yE+/91mfv/78He24T46zHz//uw9xHBf31m/n8L9t4l+G+QBfu/HxPib8g4/nPMn6j9e9T8iZ79e1Y51i8Yujj4/w3k0zuE/GvEzP+TYG8iwX9jYf5/npn/P4C9CYT4XxDm/ybC/N9UuP/fTLj/35xx/Ofpn8udfyDN3/WF+2d/87++PZQU/7+OfPoZ+lyQ/38gjH8thPv/3sz9/29h70tC/D7M/P8d7P1E8N+Smf+/gL1vCP5bCfN/axv0/38kxN9GE/8D3PMO2Ps96F3ofegDaBL0IfQx9BH0CfQZ9Cn0OfQl9AX0FfQN9DX0LfQD9B00GfoR2gL9rM7mhKZAU6FfoGnQDGg6FAHNgmZCs6G50BxoHrQAmg9FQr9Bv0ILocXQIigKWgLFQNHQUmg5tAyKheKgFVA8tBJKgFZBa6DV0FpoPbQO2qCegYQ2QonQVmgzlARtgx5C26FkaAe0C9oJ7Yb2QClQKrQP2gvthw5CB6BD0BHoMHQUOgEdg45DJ6HT0CnoDPS7WksGnYMuQOehi9Bl6BL0B3QVugJdg25A16Gb0G3oFnQHugf9Cd2F7kN/QQ8gp2wmUx0oWzYe/v8U+fQ1If/aMvP/ZNj7iuC/nTD/t2fm/+9h7zNC/C9q/HPMn6n9u9T8mZ79u1Y76nfRS6L+8xWu/zoIz/90FJ7/6WR1/b++E4C1/f+pgvwfSRj/Ogv3/9WzukUsrzn4fxbsTSfE31X78w8MGDzcwPyZj3b+zK9nYECwX0v/ziFPfL+91+/R1zdulPRv9Pubof4j53835vpvHuzNJOR/dxvUfwsI/l+yuv7eWP03n+C/B/P6/ymwF0Hw35OZ/+fA3gyC/17C/N+bmf/nwt4vhPj7aPzHQv5Qdgyket6BNU85v9v7828S/N9Xw/8+psC0EWA4/jlEh3/Vf5wNe9MI+d/PyvjfNa0KCcyQ+qO/xn83eByvm/7U/vt0/wP+UX9kfP3lZ7X+0HcCsao/PoG97dCi/6g/vhhnu/ojgZB/A4XrD/WscPH095+f//sEhgQPe9ISwN75P3WHffM/R/25FPm0mJD/g3jnn8j5P5i5/lgBezGE+IfYoP6IJ/gPsEH9EUfwP5S5/vgN9qIJ/ocx1x/LYW8JwX+gcP0RpIm/gZOZ/yfp5P+1Dv6364uj/oxFPi0k5P/LwuvPhjPXH8tgL4oQ/wjh+mOkcP0RLFx/hFitP/SdgKyd/1jzmPojve6wZf2RTMi/UE39YQP+7xXkH/LEMwD2zv87pts3/0vUn+pZ9WKW1xz1xybYW0fI/1HC9cdo5vpjC+xtJMQfZoP6YxvBf7gN6o+tBP9jmOuPVbC3geB/LHP9sRn21hP8j9PUHzEYQAfhV1dn5KUO/+sc/G/Xl0T9OZ55/isJ9lYT8v9V4frjNeb6IxH21hLif124/nhDuP6YIFx/vGm1/tB3ArOqP1bC3jFol2D9cZSQf28Jz3+oZ6XLWl5z8Oc+2EshxD9RmD/fcZz/5JBFNqj/fUKChwSFBYUE+9Wp7ef1H8dK2nv9vzFi9bYliWuWSPk3Wv9z1J+HMJ7sJYx/79qg/jxC8P+etv/FVH8eJvh/n7n+3AF7qQT/k5jrzwOwt4fg/wPh+a8PmeuPg7C3kxD/R8L1x8ea+kOt/3sN8sRA+okO/+sd9b9dXxz1537k025C/n8iXH9+Klx/fiZcf35upf70ZDj/+6Rg/XmJkH9fCD///yXz8//nYO80If6v/vf8PwPjh3n/jrq677d3/o+J2rRIbPMOU6Z4/sfpPPLpD0L+fc08/3UK9n4n+P9GeP8HtV9H+lDJVX9cJsT/HXP9cRz2zhL8T2auPy7A3hmC/++F648fmOuPi7B3ghD/j9r9P9QYBpXXeX7oRsfz+6KXPZ7//ZPw8/8/Cz//P0X4+f9frPK//vO/1XrGUADtdUH+f0AY/6YK8/80Zv7/E/ZuEuKf/q/zv+vpjt/B78Yuo/yuvr/3mMzf33rOr+Dg/7sq9wj5N4OZ/2/A3h2C/whh/p9pA/5/SIh/FjP/X4W92wT/s5n5/x7s3SL4nyPM/3OZ+f8+7F0jxD9P43+Tg99FL57+W33d90vw/3xh/l8gzP+Rwvz/q1X+N37+dzZ3678nI/g/t/uTj3+/CfP/Qmb+zw5jroT4F2Wh87+zAr/fMJn5Xc/+mYkGfwAc/J8DuZeXkH9RzPzvAt8eBP+Lhfl/iQ34Pw8h/mhm/neCb3eC/xhm/s8J324E/0uF+X8ZM//nQuzOhPiXM47/Dn7n4PcGuu83+vOT4P9YYf5fIcz/ccL8H2+V//Wf/61gtgxUUJD/nyWMfwnC/L+Smf+LwVhhQvyrmM//KA7fpQn+VzPzXyH4Lkrwv0aY/9bagP9KEeJfx/j9b/Sy9/qtjLN5/UQbZ33rJzYL9185+D8/cq8IIf/WM/N/Cfh+huB/gzD/b2Tm/5KIvQAh/k3Czx8kCvPfZmH+SxLmvy0a/476jaN+a6j7fun+69/8b/z873KC/F+DMP5tFeb/bcz8XwXGKhDiT2bm/6rwXYvgfzsz/5eH78oE/zuE+X+nDfi/JiH+XYznv2YFflfrpxS/61k/lWTn6yc4+P855F4lQv7tZub/avBdkeA/RZj/9zDzf3XEXpYQf6ow/+8V5v99wvy/X5j/DzCO/9IXD7830n2/va+f+Jv/9Z//nQ9jT2fI6z/4f9pU2/F/E8L4d1CY/w8x838jGKtHiP8wM/83hu9mBP9HmPm/Lnw3JPg/Ksz/x2zA/00J8R/XxJ8V+F2tn1L8rmf91JanfP0zB/97IvcaEPLvBDP/Pw/f9Qn+Twrz/ylm/n8BsdchxH9amP/PCPP/WWH+/12Y/89lIv5n4XftFoTEx1jtnd9rG7z/b/43fv63z2P4P537bcn/HQjj33lh/lf7VRSwvObg/3aIvRUh/ovM/N8evjsR/F9i5v+W8N2W4P+yMP+rvXKcHn3+ePi/IyH+K4zjv1F+L403YqnJvP/gWh33b3U8v2jo4uD/Fsi9NoT8u8rM/y/Cd2uC/2vC/H+dmf99Ebs3If4bwvx/U5j/bwnz/21h/r/DOP6z8ztxGfrTzu9Gr7/5X//5280x9gyEugnyf3/C+PenMP/fZeb/3oj9JUL895j5vw98+xH832fm/+7w3Yvg/4Ew/z+0Af8PIMT/F/Pzn13guyfBv5r84uS/vrDXg+BfPa8qyX/O7rz81w/2uhLiz+buOP/FIbM46vdUk7l+P6Hj/m2O+l30kqj/1H4NkvWfq7ts/efmLlv/ubtbe/7X+PnXgwX5fyTh+0/tFSLJ/2q/Hk7+D4K9AEL8OdyZ9//X1u/EZWSO+t3YlRn2/38Z+RRCyL+c7rz13xDYCyT4z+UuW/+pvcq4679gQvx53HnrP3/YG0bwn5e5/hsOe0MJ/vMJ13/5meu/EbA3iBB/AY1/xe83TWZ+d9IxmCY7+F30ssf9/wsK838hYf4vLMz/z1jlf/3nT9eGvT+g0YL8/wZh/CsizP9Fmfl/POyFE+Iv9r/8r+V34jawDn43dhnl92bO5vUzXZz1rZ/h4P9XkU9vEvKvODP/h8HeOIL/EsL8X9IG/D+BEP+zzPz/CuyNJfgvxcz/r8HeGIL/0sL8X4aZ/1+HvVGE+J/T+N/u4HfRi73/RtzGRYL/ywrzfzlh/i8vzP8VrPB/HYbzf98R5P9PCeNfRWH+r8TM/x/C3nuE+Cu7Z539/7MCv6v5c8XveubPd2SC/f8/Qj59Tsi/Ksz8/y7sfUDwX1WY/6vZgP8/I8RfnZn/34a9SQT/NZj5/2PYe5/gv6Yw/9di5v9PYG8iIf7a7o79/7kudn4nPoZpj/v/ewrzfx1h/vcS5v+6Vvlf//m/b8HeNOhrQf6fQhj/6gnzf31m/v8B9r4lxN/AnXf9/4+wN5XgvyEz/30De98T/DcS5r/GNuC/XwjxP++eefb/zwr1m1o/oeo3PesndmaB/f+/RD5NJuTfC8z8/xPsfUfw30SY/5sy8//PsPcVIf5m7rLP/zYX5r8WwvznLcx/Pu6O/f8fvReBAYOHe4eM032/t1+LsDD/wcP9WgwNCxjl1zUg1D+IMJRklv3/6zCc/xshyP+LCOOf2i/Gw/Jagv/VXj3PpL9m4P95sDeLEH9rXv4nx9+Gmf9/hb25hPjb2oD/FxL8q/2amj/6/PHw/28E/+3d+fZ/SDiedGfF9YjINTPioxMvbHoYf3HxiYi5i+N2xS2du2t+bPTm7RGRuxbHHU85sPHUlntJUSuuqd+RdGjLlb3RWyMj5hn1b5Tf1XS52jf0IlRIx2C6y7H/v2k68mkOIf9eZOb/BbA3m+DfV5j/OzDzfyTszSDE31GY/ztp+N/HFJiWAcPxzyE6/Kv+03zYm0mIv7OV8b9rWhUSmCH1RxeN/27wOF73t7/JlEuH/66M4790/8jo1S44NDzMAP+38/brFhAWFhQ8zK910LDAML9O4WHdg0Y+8Y9Tmv8l6u9uVucf9J8//AXs7YSiBeuPlYTxp7tw/aH2Cipqec1Rf6yAvaWE+Hswzz/Ewd4qgv+ezPVHDOzFEvz3Ep5/UPtFOTONn57CDfwn3XLocdeHkBp55qd9FuhXSpbhf2P152pC/vdhXn+0GPaWE/z3Za4/4mFvGcF/P+H6oz9z/ZEAe0sI8Q8Qrj/8hOcfBmri74ysH42/xqZ9BugVkJ7+v7/GP9f3gNTFsv6qnqfu++19/XQHUzg+AWH4DPhCwWQG05P/g6zyv/Hzh9cL8n8yYfwbLLz+SO2Xwnn+WBKMbSTEH8DM/1tgbwfB/1Bm/t8Ae5sJ/ocJ83+gpv5blpq6OyJySWTsg5RrS2YkpSyLidu3fvnygxk1/hjt3y+H1JZTbfGp9tZx/x7H+V8s/L+dkP9BzPy/FvYSCf5fZub/rbC3ieB/uDD/j2Dm/22wt44Q/0hh/g8W5v8Q4fVHoZmo/8/Qf/cNGTbYP0zoz2/v8x8S689escr/+s8fXgN7x6GU/+D/RRttx/9HCOPfKOH+v9qnKbvlNQf/H4C9VEL8Ycz8fxD2jhL8hzPz/x7Y20/wP0aY/x9qfh8X/x0jxD+Wmf92wd4+gv9xzPx3CPb2EvyPF+a/VzXxG50/KQ5Vh85hVJ2o48sw1bH/jGj8HPx/GPm0m5D/rwnz/+vC/P+GcP9/gsa/RP/3Tav8Z/z82VOP4b907rMR/5HjV8/LulleS/Df25rvH8cZKE+3vMPDwkKC9X9/eIcFWwpwP58RAf5kiLH3+nvT6VV7YqI2LdqekrRy/YHEwxnt32j//AFywDkbxmPIDXKF3KHskAeUA8oN5YRyQXmgfFBeKD9UECoAFYKegQpDRaBiUFGoOFQSKgE9C5WGSkFloHLQc1BZqDxUEaoAVYKqQJWhqlB1qBpUA6oF1YRqQ16QJ1Q3m3kcq49f60ENoEZQQ6gx1AR6HnoBago1h5pBLSAfyBtqCbWGWkFtoHZQW6g95Au9CHWAOkEdoc5QV6gL1A3qAXWHXoJ6Qr2hXlAfqB/UF+pv+XMOsPyaGS6O+v88vk/OEPhvovDzR+8w1/8XYO8cIf53hev/9zTf/wz1P/n9f5+3/nc6AXu/E97/Scz1/0XYO0vw/wFv/e90GfZOE/x/qIn/Cr5AB0MDnPXV73uf8vqdkZ86hQYEtw4ZMSSAkgmZof6/hHw6Sci/j4Tr/4819X9nfPeMw6dvBL6FdH7+yP4/sVr/6j5/2RQFe9U9TKZrdlL/fipc/6q9EgtbXnPwzx3Yu0HI/8+F+eeLTLT/T/S1VfMT96SuTF4f/zB+R8b7N1o/qe/PopbvzwY63sx9wt+fHPz7J/LpNiH/vxTmX7VXTh7Lawn+/ZqZf6/A3i3C+/8NM//ehb2bBP/fMvPvfdi7TvD/HfP6p3uwd5Xgf7Iw/3yv4R9pfu4UGhYUEqx/AVCn9PU/fi0DBoUPy/DxU/r7M+Z2UoqR+yX49wer/Gv8/OFHi2r+57Ix/6b5z+3x5J//HzXrbyT4V+2Xl9fymoN/3RC7MyH+n4X5dwpz/y8HYnclxP+LDfgnF8H/VKv8YWz9T06C/2nM638eKnsE/9OZ+ccDvrMR/M8QXv8Twbj+12j95IS6Sf3M6+LXd3Tcf/Ap7z9mhv5fdpX7BP6dKcy/s5j3H3JH/E6Ez/9s4f2H5gjvPzT3H/ufZvz6q3lW+VP/+bcPYK8Efv75ZfiTHP98zfpz6avNqJDwUAPPf6Tf31Dn/fZe/6l1J6p/uvrYjm167peoPxYwP39QBMlckDD+RjI/f1DU4vtJ/f/KXH8UgP9nCPH/Jtx/VXul5rK8lui/LmLuv+bFe1+Y8P5HMdcfxeC7EMH/Yk39YfTimD+pYTLPn3yu4/5Dds7/fP3PdsFDQ+j3S9SfS5j778WR+/kI+R8tXH/E/KP+MPOnF8P5q6UE+5/VCO//UuH+5zLN/B8Hf5RH7GUI8S8X7n/GZqHzX6PO742X9M/R/1L7Dqr+V38d9x82+APg4M/KyP1yhPxfYQP+rErwH2eD/ncVgv945v53SfguS/CfwMyfFeH7OYL/lcL971XM/FEJsT9LiH+1MH+s0fCHNP8+7ftvMJw/ZOH/noEBwT39RwUFD+vmPyagc9DgsPBR/00UHP3vCsj90oT8Xyvc/14n3P9eL9z/3mCl/+1l4PzXPPjZh0K1BOuPFwj5t1F4/xW1V1hpy2uO+qMegvEkxJ+Yhfh/ya3oS0lRURHRZxL2bROoBDj6XzPwax/wf5SO+48Y/AFI1J+bmfvfjZD7dQn5n2SD+uN5gv8tvOuP0/w3Jvjfylx/1IBvL4L/bcz1RwP4rkPwnyxcf2xnrj8aIvaahPh3MI7/9r7+RfriOH80PCyEeuzoo0ui/tzJvP6mPnK/NiH/dwnXH7uF648U4fpjj9X6w/j5s80F648OhPxLFa4/1F51uS2vOeqP1gjGmxD/PuH5j/3M/NkesbcixH/ABvzpS/B/UJN/9l7/qTNnV82P3Sfl32j9l75/4usmffvXTzH45+eqP14k5N8h5vqjKXy3JPg/zFx/tIVvH4L/I8L1x1Hm+qMdYm9GiP+Y8PzHcWb+bIPYWxDiPyHMnycd9V+muRjqv27hoaEjxvt1Cxml42MkUX+cEq4/TlutP/SfP9sEn30/qItg/TGAMP6cEa4/zjKvv+qJYLoR4v9duP44x1x/9EXsPQjxn89C8z+7N2xPXBy7/E7K0j23l+5OPhcxNzFq97akqKTY3esi5tnev1H+V6feVcebGAw10/FmTjL4A+CqP/sT8k/tl1jK8pqr/uhH8H+Ruf7oBN8vEfxfYq4/esN3d4L/y8L1xx/M9UcfxN6ZEP8V4frjKnP90QuxdyXEf83B/5nm4pj/CQvzHzzcr2XQ6NEhI8YQIUai/rwuPP9xQ7j+uGm1/jB+/u0gwfojhDD+3BKuP9RedQUsrznqj0AEM4QQ/x3h+uPPLLX+K+72pkURkfEXF5+ISYiOXHs3IjLl2qZFibMSTmw9bXv/HPzf28n8RoboeDOPZoLnP0Yg94cR8v+uDea/ggn+79mg/hhJ8H+fuf4YCN9DCf4fMNcfL8N3AMH/Q+H64y/m+mM4YvcnxK++/CTrD7VXTXr94TgDx75l9HLUf7IXX/3nGzQyKMzPJyQ8mDKacPQfgjCeDCaMf84esvOf2Txk608XD9n609XDWv2p+/xlU0fY+xIaLVh/vkXIP7VfqWT9qfaL4zx/YDzshRPi9/DIOvXf9iOpG9dE7riTcCfudnRy0oOM9m+0/isL9YJ+gIbpuP+YHT7/k92Dd/7zDdgbR8j/HB789eebBP9qr1zG87fS/E8g+M/lwVt/vgJ7Ywn+c3vw1p+vwd4Ygv88HrL1Z14P3vrzddgbRYg/n4dj/iezXO2CQ8PDDPB/O4P8L9F/yO/BO//5KuyFEfK/gHD9UVC4/igkXH8Utlp/GD//+93/qD9WX7Jd/fEZIf+eEa4/ijDXHx/B3vuE+It68O6/+jHsfU7wX4yZP9+DvQ8J/ot7yO6/qvaqTv8Q2Hv9V1vY/5O2/B93qed3ekInoZE67j9u8AfAVX98Qcj/ksz1x0TY+4Dg/1nm+uMT2JtE8F9KuP4ozVx/fAp77xDiLyM8//Wchj8l+KesJv7OyPrR+Gts2meATsB69v8vl4XqP+nL139QwAij96eXcO2ChwQQK0GjP78OpnB8AsLwGfCFgskMpif/y1vlf93nHzu9DXtR0DeP4f907rcl//9CGP/UfnmultcS/K/26+Rc//Yj7H1HiL8SM///BHvTCP4rM/P/t7D3A8F/FWH+r8rI/0YvaX43On/j62Tm99H4Vc933EnhHwAX/08l5H81Zv7/Cva+J/ivzsz/P8PeZIL/GsL8X5OZ/6fA3teE+GsJ839tYf73/Mf4Pwp5H4zvwFD8Oor8Zyiqw38djX8HvzPwu2cj3fdL999agP/D8Bnshk/Bqxl0/pyXVf43fv7zTEH+/40w/tUV5n+1X7C75TUH/8+HvdmE+Osz8/8C2FtE8N+Amf9nwd48gv+GwvzfyIPv/K+YqE2L9h5ST+Go1VcRK0wZfBnl90smM7931cnvJ+z8/DEu/l9IyP/GzPw/A/bmEvw/z8z/kbA3h+D/BWH+b8LM/7/CXgQh/qbC/N9MmP+bC/N/Cw++89+lLxZ+r6e/C2Xv8+cS/O9tlf91n79tmg57a6BoQf5fSRj/fIT5vyUz/6+AvaWE+Fsx838c7K0m+G/NzP8xsBdL8N9GmP/VfqUVLa8T7iRe2JOwdFlSVPypxLOx95ZExj5QT9AvmZGUErcvJmH98uUHbUn1Rvm9HKRWDro7qbGEfu22c343enHx/ypC/rdj5v/FsLec4L89M//Hw94ygv8Xhfnfl5n/E2BvCSH+DsL831GY/zsJ839nRv43Ov6x8HsDuT+/NL+vWxWdrLpvey8vPbZifRL5CDEJ/u9ihf/rGjz/fCdsrhfk/2TC+NdVmP/VXrlultcc/J8EexsJ8Xdn5v8tsLeD4P8lZv7fAHubCf57CPN/Txs8f7qdEH8vZv5bC3uJBP+9mflvK+xtIvjvI8x/fRm//43WbxUgtfP6e1BzHfefesrrN6MXB/9vQz6tI+R/P2H+7y/M/wOE+d/vH89/Zjz/DbTKf7rPn37kP0WQ/44Q8t9fmP8GafgvU9Rv+pdPZYn9S/dGb43M+JUT5ouD/w8gn1IJ+T+Ymf8Pwt4xgv8hzPy/B/b2E/wHCPO/2is0h+U1F/8fJcQ/jJn/d8HePoL/QGb+PwR7ewn+g4T5/2VN/Eb5XbXeVNNpNLRSx/2nHfwuGj8H/x9GPu0m5P9wYf4fIcz/I4X5P1iY/0OY1x9R/XNf9uz//wBQSwECFwsUAAIACAA+G2lGpRtt0r1vAAAIwAYACQAJAAAAAAAAAAAAAIAAAAAAVUlQYWNrYWdlVVQFAAe7Ev1UUEsFBgAAAAABAAEAQAAAAPVvAAAAAA==


[Script]
/**********************************************************初始化变量**********************************************************/
Dim X,Y
X = -1 
Y = -1 
Dim ColorX, ColorY
X = -1 
Y = -1

Dim Ken_LeftClickOnXY_Delay
Ken_LeftClickOnXY_Delay = 100

//资源文件夹路径
Dim ResourceFolder

DimEnv ChangeNavyArray1Index,ChangeNavyArray2Index,ChangeNavyArray3Index,ChangeNavyArray4Index,ChangeNavyArray5Index,ChangeNavyArray6Index
ChangeNavyArray1Index = 0
ChangeNavyArray2Index = 0
ChangeNavyArray3Index = 0
ChangeNavyArray4Index = 0
ChangeNavyArray5Index = 0
ChangeNavyArray6Index = 0

Dim DebugLogPath, WarningLogPath

Dim LogcatFileStr
Dim LogLine
LogLine = 0























































/*****************************设置常量*****************************/
//远征舰队坐标
Const ExpeditionNavyPosition = "356|120"
Const ExpeditionNavyPositionOffset = 30
//远征地图坐标
Const ExpeditionMapPosition = "135|450"
Const ExpeditionMapPositionOffset = 55
//远征关卡坐标
Const ExpeditionMissionPosition = "160|170"
Const ExpeditionMissionPositionOffset = 30

//补给全选框坐标
Const SupplyCheckBoxAllPosition = "120|120"
//补给舰队坐标
Const SupplyNavyPosition = "150|120"
Const SupplyNavyPositionOffset = 30
//补给舰队确定
Const SupplyNavyConfirmPosition = "700|450"

//入渠空位坐标
Const RepairEmptyPosition = "250|170"
Const RepairEmptyPositionOffset = 80
//列表类型坐标
Const TypePosition = "780|110"
//入渠舰队坐标
Const RepairNavyPosition = "480|141"
Const RepairNavyPositionOffset = 30

//出击地图坐标
Const AttackMapPosition = "160|450"
Const AttackMapPositionOffset = 75
//出击任务坐标
Const AttackMissionPosition = "280|200"
Const AttackMissionPositionOffsetX = 350
Const AttackMissionPositionOffsetY = 150
//出击的BOSS地图坐标
Const AttackMissionPositionOfBossMap = "710|260"
//出击的BOSS地图任务2坐标
Const AttackMissionPositionOfBossMission1 = "710|260"
//出击的BOSS地图任务3坐标
Const AttackMissionPositionOfBossMission2 = "710|300"

//出击的活动地图坐标
Const AttackMissionPositionOfSpecialMap = "720|450"
//出击的活动地图任务1坐标
Const AttackMissionPositionOfSpecialMission = "720|200"
Const AttackMissionPositionOfSpecialMissionOffset = 100

//攻击阵形坐标数组
AttackFormationPositionArray = Array("450|185","480|185","710|185","510|345","640|345")//数组无法声明成const


//换船接触除了旗舰以外的船坐标
Const ChangeNavyWithOutFlagPosition = "420|120"
Const ChangeNavyPagePosition = "520|450"
Const ChangeNavyPagePositionOffset = 30
Const ChangeNavyListPosition = "470|170"
Const ChangeNavyListPositionOffset = 29
Const ChangeNavyBackToFirstPagePosition = "440|450"
Const ChangeNavyJumpPageToNext5Position = "680|450"
Const ChangeNavyListNavyPosition = "130|120"
Const ChangeNavyChangeInitBtnPosition = "420|220"
Const ChangeNavyChangeInitBtnPositionOffsetX = 350
Const ChangeNavyChangeInitBtnPositionOffsetY = 114

//工厂坐标
Const OilPosition = "490|140"
Const SteelPosition = "720|140"
Const AmmoPosition = "490|270"
Const LvPosition = "720|270"
FactoryPositionArray = Array(OilPosition, SteelPosition, AmmoPosition, LvPosition)

//工厂解体
Const FactoryDissolveType = "590|110"
Const FactoryDissolveFirstShipPosition = "300|140"

//编成HP位置
Const ChangeNavyHPPosition = "210|170"
Const ChangeNavyHPPositionRect = "65|7"
Const ChangeNavyHPPositionX = 343
Const ChangeNavyHPPositionY = 114
//编成维修位置
Const ChangeNavyRepairPosition = "419|157"
Const ChangeNavyStatePosition = "448|167"
//编程颜色
Const RGB_Ship_HP_DaPo = &HF333FF3
Const RGB_Ship_HP_ZhongPo = &HF017BFF
Const RGB_Ship_HP_XiaoPo = &H00E8FF
Const RGB_Ship_HP_Wusun = &H00FF00
Const RGB_Ship_Repair = &HC8C72C
Const RGB_Ship_State_HongLian = &H3C3CCF
Const RGB_Ship_State_HuangLian = &H205CC3

























































/**********************************************************窗体函数**********************************************************/
//开关
Dimenv AutoSupply,AutoRepair,AutoExpedition,AutoAttack,AutoChangeNavy,AutoFactory

Dimenv SupplyNavyArray
Dimenv ExpeditionNavyArray 
Dimenv AutoAttackNavyArray

//远征舰队
Dimenv Expedition_Navy2_Enable, Expedition_Navy3_Enable, Expedition_Navy4_Enable
//远征舰队对应任务ID
DimEnv ExpeditionMissionID_Navy2, ExpeditionMissionID_Navy3, ExpeditionMissionID_Navy4

//出击状态
DimEnv AttackNightFight,AttackFightRound

//换船
Dimenv ChangeNavyPageCount, ChangeNavyLineNumber

//窗体载入时
Event Form.LoadOver
    LB_Dev_Setting = Plugin.File.ReadINI("Factory", "DevList", ".\Config.ini")
    LB_Dev_SettingArray = Split(LB_Dev_Setting, "|")
    If (UBound(LB_Dev_SettingArray) = -1) Then 
        Form.LB_Dev.AddItem "10,10,10,10"
    End If
    For i = 0 To UBound(LB_Dev_SettingArray)
        Item = LB_Dev_SettingArray(i) 
        Form.LB_Dev.AddItem Item
    Next
    LB_Build_Setting = Plugin.File.ReadINI("Factory", "BuildList", ".\Config.ini")
    LB_Build_SettingArray = Split(LB_Build_Setting, "|")
    If (UBound(LB_Build_SettingArray) = -1) Then 
        Form.LB_Build.AddItem "30,30,30,30"
    End If
    For i = 0 To UBound(LB_Build_SettingArray)
        Item = LB_Build_SettingArray(i)
        Form.LB_Build.AddItem Item
    Next
    Form.IB_Dev_RepeatCount.Text = 0
    Form.IB_Build_RepeatCount.Text = 0
    Form.CB_AutoFactory.Value = 0
End Event
//脚本启动时
Sub OnScriptLoad()
End Sub
//脚本退出时
Sub OnScriptExit()
    BGCP2_02.UnTransformWindow(HwndGame)
    Call Ken_Logcat_W("肯的舰队脚本，停止")
End Sub

//自动补给开关
Event Form.CB_AutoSupply.Click
    If (Form.CB_AutoSupply.Value = 1) Then 
        Form.CB_Supply_When_Attack_Before.Value = 1
        Form.CB_Supply_When_Expedition_Before.Value = 1
        Form.CB_Supply_Sort.Value = 1
    End If
End Event
//自动入渠开关
Event Form.CB_AutoRepair.Click
    If (Form.CB_AutoRepair.Value = 1) Then 
        Form.CB_Repair_Dapo.Value = 1
        Form.CB_Repair_ZhongPo.Value = 1
        Form.CB_Repair_XiaoPo.Value = 0
        Form.CB_Repair_Navy_1.Value = 0
        Form.CB_Repair_WeiPo.Value = 0
    End If
End Event
//自动远征开关
Event Form.CB_AutoExpedition.Click
    If (Form.CB_AutoExpedition.Value = 1) Then 
        Form.CB_Supply_CheckOil.Value = 1
    End If
End Event
//自动攻击开关
Event Form.CB_AutoAttack.Click
    If (Form.CB_AutoAttack.Value = 1) Then 
        Form.CB_Attack_When_DaPo.Value = 1
        Form.CB_Attack_When_ZhongPo.Value = 1
        Form.CB_Attack_When_XiaoPo.Value = 0
        Form.CB_Attack_Suppy.Value = 1
        Form.CB_Attack_CheckOil.Value = 1
        Form.CB_Attack_After_Repair.Value = 0
        Form.CB_Attack_CheckCondition.Value = 0
        Form.CB_Attack_Limit_Count.Value = 0
        Form.CB_AttackNightFight.Value = 0
    End If
End Event
//自动换船开关
Event Form.CB_AutoChangeNavy.Click
    If (Form.CB_AutoChangeNavy.Value = 1) Then 
        Form.CB_ChangeNavy_When_Repair.Value = 1
        Form.CB_ChangeNavy_When_DaPo.Value = 1
        Form.CB_ChangeNavy_When_ZhongPo.Value = 1
        Form.Label_ChangeNavy_1.Caption = 0
        Form.Label_ChangeNavy_2.Caption = 0
        Form.Label_ChangeNavy_3.Caption = 0
        Form.Label_ChangeNavy_4.Caption = 0
        Form.Label_ChangeNavy_5.Caption = 0
        Form.Label_ChangeNavy_6.Caption = 0
    End If
End Event
//自动工厂开关
Event Form.CB_AutoFactory.Click
End Event


//大破出击开关
Event Form.CB_Attack_When_DaPo.Click
    If (Form.CB_Attack_When_DaPo.Value = 0) Then 
        MessageBox "警告，这极有可能导致舰船沉没！请确认了解该情况会导致的后果！"
    End If
End Event

//是否进击回合次数
Event Form.CB_AttackNightFight.Click
    AttackNightFight = Form.CB_AttackNightFight.Value
End Event
//是否夜战
Event Form.CB_AttackFightRound.SelectChange
    AttackFightRound = Form.CB_AttackFightRound.ListIndex
End Event

//设置第几舰队远征
Event Form.CB_Expedition_Navy2_Enable.Click
    Expedition_Navy2_Enable = Form.CB_Expedition_Navy2_Enable.Value
    Form.CB_Supply2.Value = Form.CB_Expedition_Navy2_Enable.Value
    Form.CB_AutoSupply.Value =1
End Event
Event Form.CB_Expedition_Navy3_Enable.Click
    Expedition_Navy3_Enable = Form.CB_Expedition_Navy3_Enable.Value
    Form.CB_Supply3.Value = Form.CB_Expedition_Navy3_Enable.Value
    Form.CB_AutoSupply.Value = 1
End Event
Event Form.CB_Expedition_Navy4_Enable.Click
    Expedition_Navy4_Enable = Form.CB_Expedition_Navy4_Enable.Value
    Form.CB_Supply4.Value = Form.CB_Expedition_Navy4_Enable.Value
    Form.CB_AutoSupply.Value = 1
End Event
//设置远征地图
Event Form.CB_Expedition_Missionevel_Navy2.SelectChange
    ExpeditionMissionID_Navy2 = Form.CB_Expedition_Missionevel_Navy2.ListIndex
End Event
Event Form.CB_Expedition_Missionevel_Navy3.SelectChange
    ExpeditionMissionID_Navy3 = Form.CB_Expedition_Missionevel_Navy3.ListIndex
End Event
Event Form.CB_Expedition_Missionevel_Navy4.SelectChange
    ExpeditionMissionID_Navy4 = Form.CB_Expedition_Missionevel_Navy4.ListIndex
End Event

//出击后强制补给
Event Form.CB_Attack_Suppy.Click
    Form.CB_Supply1.Value = Form.CB_Attack_Suppy.Value
    Form.CB_AutoSupply.Value = 1
End Event

//工厂开发公式列表
Event Form.LB_Dev.DblClick
    Dim SelectOfArray,ItemArray
    SelectOfArray = split(Form.LB_Dev.List, "|")
    ItemArray = split(SelectOfArray(Form.LB_Dev.ListIndex), ",")
    Form.IB_Dev_Oil.Text = ItemArray(0)
    Form.IB_Dev_Ammo.Text = ItemArray(1)
    Form.IB_Dev_Steel.Text = ItemArray(2)
    Form.IB_Dev_Lv.Text = ItemArray(3)
End Event
Event Form.Btn_Dev_Add.Click 
    Form.LB_Dev.AddItem (Form.IB_Dev_Oil.Text & "," & Form.IB_Dev_Ammo.Text & "," & Form.IB_Dev_Steel.Text & "," & Form.IB_Dev_Lv.Text)
    Call Plugin.File.WriteINI("Factory", "DevList", Form.LB_Dev.List, ".\Config.ini")
End Event
Event Form.Btn_Dev_Remove.Click
    Form.LB_Dev.RemoveItem (Form.LB_Dev.ListIndex)
    Call Plugin.File.WriteINI("Factory", "DevList", Form.LB_Dev.List, ".\Config.ini")
End Event
//工厂建造公式列表
Event Form.LB_Build.DblClick
    Dim SelectOfArray,ItemArray
    SelectOfArray = split(Form.LB_Build.List, "|")
    ItemArray = split(SelectOfArray(Form.LB_Build.ListIndex), ",")
    Form.IB_Build_Oil.Text = ItemArray(0)
    Form.IB_Build_Ammo.Text = ItemArray(1)
    Form.IB_Build_Steel.Text = ItemArray(2)
    Form.IB_Build_Lv.Text = ItemArray(3)
End Event
//开发公式保存
Event Form.Btn_Build_Add.Click 
    Form.LB_Build.AddItem (Form.IB_Build_Oil.Text & "," & Form.IB_Build_Ammo.Text & "," & Form.IB_Build_Steel.Text & "," & Form.IB_Build_Lv.Text)
    Call Plugin.File.WriteINI("Factory", "BuildList", Form.LB_Build.List, ".\Config.ini")
End Event
//建造公式保存
Event Form.Btn_Build_Remove.Click
    Form.LB_Build.RemoveItem (Form.LB_Build.ListIndex)
    Call Plugin.File.WriteINI("Factory", "BuildList", Form.LB_Build.List, ".\Config.ini")
End Event

//日志功能
Event Form.Btn_Logcat_Clear.Click
    Call Ken_LogInputBoxClear()
End Event
Event Form.Btn_Logcat_OpenFolder.Click
    Runapp ResourceFolder & "\日志\"
End Event

Event Form.IB_Setting_Fight_OutTime.Change
    Dim a
    a = lib.算法.提取字串符中所有数字(Form.IB_Setting_Fight_OutTime.Text)
    Form.IB_Setting_Fight_OutTime.Text = right(a, 2)
End Event





























































//**********************************************************逻辑**********************************************************/
Do
/****************************初始化****************************/
    Call GetHwndForGame()
    Call InitEnvironment()
        
    //    Call ChangeNavyByColor()
    Call TD_Attack()
    
    Call FactoryNavy()
    Call TD_CheckTiDu()
    Delay 5000
Loop While(1=1)

























































/**********************************************************提督很忙**********************************************************/
/*****************************远征*****************************/
Function TD_Expedition()
    Call SetHwndByGame()
    Call GoToMuGang()
    If (Form.CB_Supply_When_Expedition_Before.Value = 1) Then 
        Call SupplyNavy()
    End If
    Call ExpeditionNavy()
End Function

/****************************出击****************************/
Function TD_Attack()
    Call SetHwndByGame()
    Call GoToMuGang()
    If (Form.CB_Supply_When_Attack_Before.Value = 1) Then 
        Call SupplyNavy()
    End If
    If (ChangeNavy()) Then 
        Call Ken_Logcat_I("舰船状态检测完毕，准备出击")
        Call AttackNavy()
    Else 
        Call Ken_Logcat_W("舰船当前状态，无法出击")
    End If
    Call GoToMuGang()
    If (Form.CB_Attack_After_Repair.Value = 1) Then 
        Call RepairNavy()
    End If
End Function


/****************************检查远征是否就绪****************************/
Function TD_CheckTiDu()
    Do
        Call SetHwndByTidu()
        
        Rem 远征判断
        If (Form.CB_AutoExpedition.Value = 1) Then 
            If (Form.CB_Expedition_Navy2_Enable.Value = 1 and Ken_FindPic("提督_综合_远征_第二舰队_准备就绪1")) Then 
                Call TD_Expedition()
                Exit Function
            End If
            If (Form.CB_Expedition_Navy2_Enable.Value = 1 and Ken_FindPic("提督_综合_远征_第二舰队_准备就绪2")) Then 
                Call TD_Expedition()
                Exit Function
            End If
            If (Form.CB_Expedition_Navy3_Enable.Value = 1 and Ken_FindPic("提督_综合_远征_第三舰队_准备就绪1")) Then 
                Call TD_Expedition()
                Exit Function
            End If
            If (Form.CB_Expedition_Navy3_Enable.Value = 1 and Ken_FindPic("提督_综合_远征_第三舰队_准备就绪2")) Then 
                Call TD_Expedition()
                Exit Function
            End If
            If (Form.CB_Expedition_Navy4_Enable.Value = 1 and Ken_FindPic("提督_综合_远征_第四舰队_准备就绪1")) Then 
                Call TD_Expedition()
                Exit Function
            End If
            If (Form.CB_Expedition_Navy4_Enable.Value = 1 and Ken_FindPic("提督_综合_远征_第四舰队_准备就绪2")) Then 
                Call TD_Expedition()
                Exit Function
            End If
        Else 
            Call Ken_Logcat_I("远征没有开启")
        End If
        Rem 远征结束
        
        Rem 入渠开始判断	
        If (Form.CB_Repair_Dapo.Value = 1) Then 
            Call Ken_Logcat_I("按照入渠设置，检测是否大破")
            If (Ken_FindPic("提督_综合_舰队列表_HP_大破")) Then 
                Call Ken_Logcat_I("大破了吗？是")
                Call RepairNavy()
                Call ChangeNavy()
                Goto 入渠结束判断
            Else 
                Call Ken_Logcat_I("大破了吗？否")
            End If
        Else 
            Call Ken_Logcat_I("按照入渠设置，不检测是否大破")
        End If
        If (Form.CB_Repair_ZhongPo.Value = 1) Then 
            Call Ken_Logcat_I("按照入渠设置，检测是否中破")
            If (Ken_FindPic("提督_综合_舰队列表_HP_中破")) Then 
                Call Ken_Logcat_I("中破了吗？是")
                Call RepairNavy()
                Call ChangeNavy()
                Goto 入渠结束判断
            Else 
                Call Ken_Logcat_I("中破了吗？否")
            End If
        Else 
            Call Ken_Logcat_I("按照入渠设置，不检测是否中破")
        End If
            
        If (Form.CB_Repair_XiaoPo.Value = 1) Then 
            Call Ken_Logcat_I("按照入渠设置，检测是否小破")
            If (Ken_FindPic("提督_综合_舰队列表_HP_小破")) Then 
                Call Ken_Logcat_I("小破了吗？是！")
                Call RepairNavy()
                Call ChangeNavy()
                Goto 入渠结束判断
            Else 
                Call Ken_Logcat_I("小破了吗？否")
            End If
        Else
            Call Ken_Logcat_I("按照入渠设置，不检测是否小破")
        End If
        Rem 入渠结束判断
        
        Call Ken_Logcat_I("进击结束")
        Delay 5000
    loop While (True)
End Function

Function TD_RefreshGame()
    Call SetHwndByTidu()
    Call Ken_PointGetAndClick("30|840")
    Call Ken_PointGetAndClick("130|590")
    Call Ken_PointGetAndClick("770|590")
    Call Ken_FindPicAndClick("提督_设置")
    Call SetHwndByGame()
End Function


























































/**********************************************************函数**********************************************************/
Function GoToMuGang()
    Dim WayFromExpeditionFinish
    Call SetHwndByGame()
    //回到母港
    If (Ken_FindPic("母港_出击") = False)
        If (Ken_FindPicAndClick("左侧UI_母港")) Then 
            Call Ken_DeleyForNet()
        Else 
            Call Ken_Logcat_E("无法回到母港")
        End If
    End If
    
    Do While(Ken_FindPicAndClick("远征_结束_开始"))
        Call Ken_Logcat_I("发现远征结束舰队")
        Call Ken_DeleyForNet()
        Delay 8000
        If (Ken_FindPicUntilFoundThenClick("远征_结束_评价") = False) Then 
            Call Ken_Logcat_E("接收远征舰队失败——无法找到评价。尝试直接接收")
            Call Ken_FindPicUntilFoundThenClick("远征_结束_评价_继续")
        End If
        Delay 2000
        Call Ken_FindPicUntilFoundThenClick("远征_结束_评价_继续")
        Delay 2000
        Call Ken_DeleyForNet()
        WayFromExpeditionFinish = True
    Loop
    If (WayFromExpeditionFinish) Then 
        WayFromExpeditionFinish = False
        Call SupplyNavy()
    End If
End Function
Function GoToScene(SceneName)
    Call SetHwndByGame()
    If (Ken_FindPicAndClick("左侧UI_" & SceneName)) Then 
    Else 
        Call GoToMuGang()
        If (Ken_FindPicUntilFoundThenClick("母港_" & SceneName)) Then 
            Call Ken_Logcat_E("进入" & SceneName & "界面失败")
        End If
    End If
    Call Ken_Logcat_W("进入" & SceneName & "界面")
    Call Ken_DeleyForNet()
End Function

/*远征主逻辑*/
Function ExpeditionNavy()
    Call Ken_Logcat_I("远征模块是否打开:" & Form.CB_AutoExpedition.Value)
    Call SetHwndByGame()
    If (Form.CB_AutoExpedition.Value = 0) Then 
        Exit Function
    End If
    
    Call GoToMuGang()
    If (Ken_FindPicUntilFoundThenClick("母港_出击") = False) Then
        Call Ken_Logcat_E("远征失败，没有找到出击按钮，返回母港")
        Call GoToMuGang()
        Exit Function
    End If
    Call Ken_DeleyForNet()
    Call Ken_FindPicUntilFoundThenClick("出击_主界面_远征")
    Call Ken_DeleyForNet()
    
    If (Expedition_Navy2_Enable = 1) Then 
        Call ExpeditionSelectMapByMissionID(ExpeditionMissionID_Navy2,1)	
    End If
    If (Expedition_Navy3_Enable = 1) Then 
        Call ExpeditionSelectMapByMissionID(ExpeditionMissionID_Navy3,2)	
    End If
    If (Expedition_Navy4_Enable = 1) Then 
        Call ExpeditionSelectMapByMissionID(ExpeditionMissionID_Navy4,3)	
    End If

    Call Ken_DeleyForNet()
End Function

/*选择远征地图*/
Function ExpeditionSelectMapByMissionID(ExpeditionMissionID,NavyNumber)
    //远征地图下标
    ExpeditionMapIndex = Int(ExpeditionMissionID / 8)
    Call Ken_Logcat_D("ExpeditionMapIndex:" & ExpeditionMapIndex)
    //远征任务下标
    ExpeditionMissionIndex = Int(ExpeditionMissionID mod 8)
    Call Ken_Logcat_D("ExpeditionMissionIndex:" & ExpeditionMissionIndex)
    
    /*选择远征地图*/
    Call Ken_PointAddAndClick(ExpeditionMapPosition,ExpeditionMapIndex * ExpeditionMapPositionOffset,0)
	/*选择远征关卡*/
    Call Ken_PointAddAndClick(ExpeditionMissionPosition,0,ExpeditionMissionIndex * ExpeditionMissionPositionOffset)

    If (Ken_FindPic("出击_远征_远征中止")) Then //如果远征正在执行，则退出
        Call Ken_Logcat_I("第" & NavyNumber + 1 & "舰队已经在执行远征任务")
        Exit Function
    End If
    Delay 1000
    Call Ken_FindPicUntilFoundThenClick("出击_确定任务")
    Delay 1000
    Call Ken_PointAddAndClick(ExpeditionNavyPosition, NavyNumber * ExpeditionNavyPositionOffset, 0)
    
    If (Form.CB_Attack_CheckOil.Value = 1) Then 
        If (CheckOilAndAmmoIsFull() = false) Then 
            Call Ken_Logcat_I(NavyNumber & "舰队在执行任务" & ExpeditionMissionID + 1  & "时缺油或弹药")
            Call SupplyNavy()
            Exit Function
        End If
    End If
    Call Ken_FindPicUntilFoundThenClick("出击_远征_远征开始")
    Call Ken_DeleyForNet()
    Delay 5000
End Function

Function CheckOilAndAmmoIsFull()
    If (Ken_FindPic("远征_结束_舰队_缺油")) Then 
        CheckOilAndAmmoIsFull = False
        Exit Function
    End If
    
    If (Ken_FindPic("远征_结束_舰队_极度缺油")) Then 
        CheckOilAndAmmoIsFull = False
        Exit Function
    End If
    
    If (Ken_FindPic("远征_结束_舰队_缺弹药")) Then 
        CheckOilAndAmmoIsFull = False
        Exit Function
    End If
    CheckOilAndAmmoIsFull = True
End Function

/*补给主逻辑*/
Function SupplyNavy()
    Call Ken_Logcat_I("补给模块是否打开:" & Form.CB_AutoSupply.Value)
    Call SetHwndByGame()
    If (Form.CB_AutoSupply.Value = 0) Then 
        Exit Function
    End If
    Call GoToMuGang()
    Call GoToScene("补给")
    Call Ken_DeleyForNet()
    ForForm = 0
    ForTo = 3
    ForStep = 1
    If (Form.CB_Supply_Sort.Value = 1) Then 
        ForForm = 3
        ForTo = 0
        ForStep = -1
    End If
    For index = ForForm To ForTo Step ForStep
        If (index = 0) Then 
            If (Form.CB_Supply1.Value = 0) Then 
                Goto 下一个补给舰队
            End If
        End If
        If (index = 1) Then 
            If (Form.CB_Supply2.Value = 0) Then 
                Goto 下一个补给舰队
            End If
        End If
        If (index = 2) Then 
            If (Form.CB_Supply3.Value = 0) Then 
                Goto 下一个补给舰队
            End If
        End If
        If (index = 3) Then 
            If (Form.CB_Supply4.Value = 0) Then 
                Goto 下一个补给舰队
            End If
        End If
        Call Ken_PointAddAndClick(SupplyNavyPosition, index * SupplyNavyPositionOffset, 0)
        Delay 200//防卡
        If (Ken_FindPic("补给_补给列表_全选框")) Then 
            Call Ken_Logcat_I("补给第" & index+1 &"舰队")
            Call Ken_PointGetAndClick(SupplyCheckBoxAllPosition)
            If (Ken_FindPicAndClick("补给_补给列表_确定补给")) Then 
                Call Ken_DeleyForNet()
            Else
                Call Ken_Logcat_I("第" & index + 1 & "舰队不需要补给")
            End If
        End If
        Rem 下一个补给舰队
    Next
    Call GoToMuGang()
End Function

/*入渠主逻辑*/
Function RepairNavy()
    Call Ken_Logcat_I("入渠模块是否打开:" & Form.CB_AutoRepair.Value)
    Call SetHwndByGame()
    If (Form.CB_AutoRepair.Value = 0) Then 
        Exit Function
    End If
    Call GoToScene("入渠")
    Call Ken_DeleyForNet()
    
    Dim FlagShipIsRepayed //旗舰是否修复
    FlagShipIsRepayed = 0
    Dim RepairedX, RepairedY //扫描这行的起始坐标
    RepairedX = 360
    RepairedY = 125
    Dim HaveSomeoneOnRapired //整个扫描的页里面是否有一艘被修复的
    HaveSomeoneOnRapired = False
    Dim TheLineIsRepaired //这行是否被修复
    TheLineIsRepaired = 0
    
    For index = 0 To 3
        If (Ken_FindPicAndClick("入渠_维修列表_空位")) Then 
            Call Ken_Logcat_I("找到空位，准备入渠")
        End If
        Delay 1000//右边弹出 防卡
        //确定船只
        For index = 0 To 9
            Call Ken_Logcat_I("正在判断第" & index+1 &"艘舰")
                
            TheLineIsRepaired = RepairFindShip(RepairedX, RepairedY)
            Delay 200//防卡
            
            If (TheLineIsRepaired = False) Then 
                If (Ken_FindPicAndClick("入渠_维修列表_入渠开始")) Then 
                    Delay 500
                    Call Ken_FindPicAndClick("入渠_维修列表_维修开始_确定维修")
                    Call Ken_DeleyForNet()
                    Call Ken_FindPicAndClick("入渠_维修列表_空位_详情返回")
                    Delay 500
                    Call Ken_FindPicAndClick("入渠_维修列表_空位_列表返回")
                    Delay 500
                End If
            End If
            RepairedY = RepairedY + 30//查找下一行
        Next
    Next
    //    Call GoToMuGang()
End Function
Function RepairFindShip(mRepairedX, mRepairedY)
    Dim IsFirstNavy//这艘舰，这是第一舰队的

    RepairedYEnd = mRepairedY + 30
    
    If (Form.CB_Repair_Navy_1.Value = 1) Then 
        If (Ken_FindPicByRect("入渠_维修列表_第一舰队", mRepairedX, mRepairedY, 800, RepairedYEnd)) Then 
            Call Ken_Logcat_I("找到第一舰队 x:" & X & " Y:" &Y)
            IsFirstNavy = True
        Else 
            Call Ken_Logcat_I("没有找到第一舰队，如果没有找到当页最后，尝试继续查找")
            IsFirstNavy = False
            //RepairFindShip = False//当成已修复处理，跳过该舰入渠
            Exit Function
        End If
    End If
    
    
    If (Ken_FindPicByRect("入渠_战斗状态_修复", mRepairedX, mRepairedY, 800, RepairedYEnd)) Then 
        RepairFindShip = True//用作判断本行
        HaveSomeoneOnRapired = True//用来判断全部
        Exit Function
    End If
    If (Form.CB_Repair_XiaoPo.Value = 1) Then 
        Call Ken_Logcat_I("小破入渠被选中 检查中")
        Call Ken_FindPicByRectAndClick("入渠_战斗状态_小破", mRepairedX, mRepairedY, 800, RepairedYEnd)
        //        Call Ken_LeftClickOnXY()
    End If
    If (Form.CB_Repair_ZhongPo.Value = 1) Then 
        Call Ken_Logcat_I("中破入渠被选中 检查中")
        Call Ken_FindPicByRectAndClick("入渠_战斗状态_中破", mRepairedX, mRepairedY, 800, RepairedYEnd)
        //        Call Ken_LeftClickOnXY()
    End If
    If (Form.CB_Repair_DaPo.Value = 1) Then 
        Call Ken_Logcat_I("大破入渠被选中 检查中")
        Call Ken_FindPicByRectAndClick("入渠_战斗状态_大破", mRepairedX, mRepairedY, 800, RepairedYEnd)
        //        Call Ken_LeftClickOnXY()
    End If
    //    If (Form.CB_Repair_WeiPo.Value = 1 and HaveSomeoneOnRapired = True) Then 
    //        Call Ken_Logcat_I("微破入渠被选中，并且已经有其他正在入渠的舰只 检查中")
    //        If (Ken_FindPicByRect("入渠_战斗状态_满血", mRepairedX, mRepairedY, 800, RepairedYEnd) = False) Then 
    //            X = mRepairedX + 150
    //            Y = mRepairedY + 20
    //            Call Ken_LeftClickOnXY()
    //        End If
    //    End If
    
End Function

/**战斗**/
Function AttackNavy()
    Call SetHwndByGame()
    Call Ken_Logcat_I("出击模块是否打开:" & Form.CB_AutoAttack.Value)
    If (Form.CB_AutoAttack.Value = 0) Then 
        Exit Function
    End If
    If (Int(Form.CB_Attack_Limit_Count.Value) = 1 and Int(Form.Label_Attack_Index.Caption) > Int(Form.IB_Attack_Limit_Count.Text)) Then 
        Call Ken_Logcat_I("当前出击次数超过用户设置的最大次数，停止出击" & Form.Label_Attack_Index.Caption &" "& Int(Form.IB_Attack_Limit_Count.Text))
        Exit Function
    End If
    Form.Label_Attack_Index.Caption = Int(Form.Label_Attack_Index.Caption) + 1
        
    Call GoToMuGang()
    If (Ken_FindPicUntilFoundThenClick("母港_出击") = False) Then
        Call Ken_Logcat_E("出击失败，没有找到出击按钮，返回母港")
        Call GoToMuGang()
        Exit Function
    End If
    Call Ken_FindPicUntilFoundThenClick("出击_主界面_出击")
    Call Ken_DeleyForNet()
    
    //出击地图
    AttackMapIndex = Form.CB_Attack_MapLevel.ListIndex
    //出击关卡
    AttackMissionXIndex = Form.CB_Attack_MissionLevel.ListIndex mod 2
    AttackMissionYIndex = Int(Form.CB_Attack_MissionLevel.ListIndex / 2)
	
	/*选择出击地图*/
    If (AttackMapIndex < 6) Then //正常地图
        Call Ken_PointAddAndClick(AttackMapPosition, AttackMapIndex * AttackMapPositionOffset, 0)
		/*选择出击关卡*/
        If (Form.CB_Attack_MissionLevel.ListIndex < 4) Then //如果是正常地图，就用正常关卡
            Call Ken_PointAddAndClick(AttackMissionPosition,AttackMissionXIndex * AttackMissionPositionOffsetX,AttackMissionYIndex * AttackMissionPositionOffsetY)
        Else// If(AttackMapIndex = 5)//如果是BOSS地图，就是第五地图
            Call Ken_PointGetAndClick(AttackMissionPositionOfBossMap)
            Delay 2000
            Call Ken_PointGetAndClick(AttackMissionPositionOfBossMission1)//只实现了X-5，没有实现X-6
        End If
    Else// If(AttackMapIndex = 6)//活动地图
        Call Ken_PointGetAndClick(AttackMissionPositionOfSpecialMap)
        Call Ken_PointAddAndClick(AttackMissionPositionOfSpecialMission, 0, Form.CB_Attack_MissionLevel.ListIndex * AttackMissionPositionOfSpecialMissionOffset)
        Call Ken_PointAddAndClick(AttackMissionPositionOfSpecialMission, 0, Form.CB_Attack_MissionLevel.ListIndex * AttackMissionPositionOfSpecialMissionOffset)
        Call Ken_PointAddAndClick(AttackMissionPositionOfSpecialMission, 0, Form.CB_Attack_MissionLevel.ListIndex * AttackMissionPositionOfSpecialMissionOffset)
    End If
	
    Delay 1000//防卡
    If (Form.CB_Attack_Dissolve.Value = 1) Then 
        If (Ken_FindPic("出击_确定任务_舰船到达上限")) Then 
            Call FacotryDissolve()
        End If
    End If
	
    
    Call Ken_FindPicUntilFoundThenClick("出击_确定任务")
    Delay 500//防卡
    
    If (Form.CB_Supply_CheckOil.Value = 1) Then 
        If (CheckOilAndAmmoIsFull() = false) Then 
            Call Ken_Logcat_I(NavyNumber & "舰队在执行任务" & ExpeditionMissionID + 1  & "时缺油或弹药")
            Call SupplyNavy()
            Exit Function
        End If
    End If
    
    If (Ken_FindPic("出击_出击_出击开始_disable") = False) Then 
        Call Ken_FindPicUntilFoundThenClick("出击_出击_出击开始")
        Call Fighting()
        Call Ken_DeleyForNet()
    End If
End Function
//战斗中
Function Fighting()
    FightingRound = 0
    Timeout = 0
    Do
        Call Ken_FindPicAndClick("战斗_战斗中_指南针")
        
        Call Ken_PointGetAndClick(AttackFormationPositionArray(Form.CB_Attack_Formation.ListIndex))
        
        If (AttackNightFight = 1) Then 
            Call Ken_FindPicAndClick("战斗_战斗中_脱离判定_夜战")
        Else 
            Call Ken_FindPicAndClick("战斗_战斗中_脱离判定_追击")
        End If
        If (FightingRound < AttackFightRound) Then 
            If (Ken_FindPicAndClick("战斗_战斗中_回合结束_进击")) Then 
                FightingRound = FightingRound + 1
                Call Ken_Logcat_I("当前战斗回合数：" & FightingRound & " 总攻击回合数：" & AttackFightRound)
                Delay 1000
            End If
        Else 
            Call Ken_FindPicAndClick("战斗_战斗中_回合结束_撤退")
        End If
        If (Ken_FindPicAndClick("战斗_结束_评价_战果报告")) Then 
            Call Ken_Logcat_I("战斗结束，判断舰船是否大破")
            If (Ken_FindPicByRect("战斗_战斗中_战斗状态_大破", 0, 0, 400, 480)) Then 
                Call Ken_Logcat_I("检测到舰船大破，不再继续进击")
                ShipWasDestroyed = 1
                FightingRound = 999//不在继续战斗
            End If
        End If
        Call Ken_FindPicAndClick("进击_结束_评价_继续")
        Call Ken_FindPicAndClick("出击_结束_评价_返回")
        Delay 1000
        Timeout = Timeout + 1000
        
        FightOutTime = Int(Form.IB_Setting_Fight_OutTime.Text)
        If (FightOutTime <= 0) Then 
            FightOutTime = 10
        End If
        
        If (Timeout >= FightOutTime * 60 * 1000) Then 
            Exit Function
        End If
    Loop While (Ken_FindPic("母港_出击") = False)
    //Call Ken_FindPicUntilFoundThenClick("出击_结束_评价_继续")
End Function

//换船
Function ChangeNavy()
    Dim ChangeNavyNeedChangePortIndex, ChangeNavyDontNeedChangeNumber
    ChangeNavyDontNeedChangeNumber = 0
    
    Call Ken_Logcat_I("编成模块是否打开" & Form.CB_AutoChangeNavy.Value)
    If (Form.CB_AutoChangeNavy.Value = 0) Then 
        Exit Function
    End If
    Call GoToScene("编成")
    
    Call Ken_Logcat_I("通过条件判断哪艘船需要被替换")
    
    For ChangeNavyNeedChangePortIndex = 0 To 5
        Call Ken_Logcat_I("开始检测第" & ChangeNavyNeedChangePortIndex+1 & "船位的舰船状态")
        MultNumX = Int(ChangeNavyNeedChangePortIndex / 2)
        MultNumY = ChangeNavyNeedChangePortIndex mod 2
        If (ChangeNavyGetStateByColorRect(MultNumX, MultNumY)) Then //舰船当前状态是否需要更换其他舰船
            If (ChangeNavyChangeInit()) Then 
                Call Ken_Logcat_I("第" & ChangeNavyNeedChangePortIndex+1 & "船位更换成功")
                ChangeNavy = True
            Else
                Call Ken_Logcat_W("按照用户设置，现在需要更换舰船，但是更换失败")
                ChangeNavy = False
                Exit Function
            End If
        Else 
        Call Ken_Logcat_I("第" & ChangeNavyNeedChangePortIndex + 1 & "船位不需要更换")
        ChangeNavyDontNeedChangeNumber = ChangeNavyDontNeedChangeNumber + 1
        	If(ChangeNavyDontNeedChangeNumber>//要获得当前舰队的舰船数量)
        End If
    Next
    
    Call Ken_DeleyForNet()
End Function
//获取是否需要更换这个坐标区域的舰船
Function ChangeNavyGetStateByColorRect(MultXNum,MultYNum)
    Dim mStartX, mStartY, mEndX, mEndY
    mStartX = 210 + ChangeNavyHPPositionX * (MultXNum)
    mStartY = 170 + ChangeNavyHPPositionY * (MultYNum)
    mEndX = mStartX + 65
    mEndY = mStartY + 7
	
    If (Form.CB_ChangeNavy_When_Repair.Value = 1) Then 
        If (Ken_CmpColor(RGB_Ship_Repair, mStartX + 210, mStartY - 14)) Then 
            ChangeNavyGetStateByColorRect = True
            Exit Function
        End If
    End If
    If (Form.CB_ChangeNavy_When_Condition_0_20.Value = 1) Then 
        If (Ken_CmpColor(RGB_Ship_State_HongLian, mStartX + 239, mStartY)) Then 
            ChangeNavyGetStateByColorRect = True
            Exit Function
        End If
    End If
    If (Form.CB_ChangeNavy_When_Condition_20_30.Value = 1) Then 
        If (Ken_CmpColor(RGB_Ship_State_HuangLian, mStartX + 239, mStartY)) Then 
            ChangeNavyGetStateByColorRect = True
            Exit Function
        End If
    End If
    If (Form.CB_ChangeNavy_When_DaPo.Value = 1) Then 
        If (Ken_FindColorByRect(RGB_Ship_HP_DaPo, mStartX, mStartY, mEndX,mEndY)) Then 
            ChangeNavyGetStateByColorRect = True
            Exit Function
        End If
    End If
    If (Form.CB_ChangeNavy_When_ZhongPo.Value = 1) Then 
        If (Ken_FindColorByRect(RGB_Ship_HP_ZhongPo, mStartX, mStartY, mEndX,mEndY)) Then 
            ChangeNavyGetStateByColorRect = True
            Exit Function
        End If
    End If
    If (Form.CB_ChangeNavy_When_XiaoPo.Value = 1) Then 
        If (Ken_FindColorByRect(RGB_Ship_HP_XiaoPo, mStartX, mStartY, mEndX,mEndY)) Then 
            ChangeNavyGetStateByColorRect = True
            Exit Function
        End If
    End If
    If (Ken_FindColorByRectAndColorOffset(RGB_Ship_HP_Wusun, mStartX, mStartY, mEndX ,mEndY ,30)) Then //获取绿色血条。这个判断只为了判断是否获取到血条颜色，避免程序出现问题无法去色时出击
        ChangeNavyGetStateByColorRect = False
        Exit Function
    End If
End Function
//开始更换
Function ChangeNavyChangeInit()
    //通过船位，获得用户定义的下一艘可替换舰船
    Call Ken_Logcat_I("分析舰船文本框数据，即将开始更换")
    Call Ken_Logcat_D("ChangeNavyNeedChangePortIndex:" & ChangeNavyNeedChangePortIndex)
    
    Dim ChangeNavyIDs
    //获得当前（ChangeNavyNeedChangePortIndex）船位上的所有ID
    If (ChangeNavyNeedChangePortIndex = 0) Then 
        ChangeNavyPlaceIndex = Form.IB_ChangeNavy1.Text
        ChangeNavyIDs = Int(Form.Label_ChangeNavy_1.Caption)
    ElseIf (ChangeNavyNeedChangePortIndex = 1) Then
        ChangeNavyPlaceIndex = Form.IB_ChangeNavy2.Text
        ChangeNavyIDs = Int(Form.Label_ChangeNavy_2.Caption)
    ElseIf (ChangeNavyNeedChangePortIndex = 2) Then
        ChangeNavyPlaceIndex = Form.IB_ChangeNavy3.Text
        ChangeNavyIDs = Int(Form.Label_ChangeNavy_3.Caption)
    ElseIf (ChangeNavyNeedChangePortIndex = 3) Then
        ChangeNavyPlaceIndex = Form.IB_ChangeNavy4.Text
        ChangeNavyIDs = Int(Form.Label_ChangeNavy_4.Caption)
    ElseIf (ChangeNavyNeedChangePortIndex = 4) Then
        ChangeNavyPlaceIndex = Form.IB_ChangeNavy5.Text
        ChangeNavyIDs = Int(Form.Label_ChangeNavy_5.Caption)
    ElseIf (ChangeNavyNeedChangePortIndex = 5) Then 
        ChangeNavyPlaceIndex = Form.IB_ChangeNavy6.Text
        ChangeNavyIDs = Int(Form.Label_ChangeNavy_6.Caption)
    Else 
        ChangeNavyPlaceIndex = ""
        ChangeNavyIDs = ""
    End If
    Call Ken_Logcat_I("ChangeNavyIDs:" & ChangeNavyIDs &"ChangeNavyPlaceIndex:" & ChangeNavyPlaceIndex)
    If (ChangeNavyPlaceIndex = "") Then 
        Call Ken_Logcat_I("替换船位是第" & ChangeNavyNeedChangePortIndex + 1 & "号位置的舰船：没有填写可替换的舰船，跳出替换舰船模块")
        ChangeNavyChangeInit = False
        Exit Function
    Else 
        Call Ken_Logcat_I("替换船位是第" & ChangeNavyNeedChangePortIndex + 1 & "号位置的舰船：已获取数据成功")
        ChangeNavyChangeInitResult = 0
    End If
    
    //通过船位获得它的当前使用的舰船ID数组
    ChangeNavyIDArray = Split(ChangeNavyPlaceIndex, "|", - 1 , 1)
    //当前要更换的舰船ID
    ShipID = ChangeNavyIDArray(ChangeNavyIDs)//通过舰船ID数组和下标获得当前要更换的舰船ID
    
    If (IsNumeric(ShipID) = False) Then 
        Call Ken_Logcat_I("分析第" & ChangeNavyNeedChangePortIndex + 1 & "号位置的舰船数据：填写的" & ShipID & "不是数字，跳出替换舰船模块")
        ChangeNavyChangeInit = False
        Exit Function
    Else
        Call Ken_Logcat_I("分析第" & ChangeNavyNeedChangePortIndex + 1 & "号位置的舰船数据：成功解析，填写的" & ShipID & "")
    End If
    If (ChangeNavyChanging()) Then 
        ChangeNavyChangeInit = True
    Else 
        ChangeNavyChangeInit = False
        Exit Function
    End If
End Function
Function ChangeNavyChanging()
    Dim PageCount,LineIndex//舰船ID所在的页数和行数
    PageCount = Int(ShipID  / 10)
    LineIndex = Int(ShipID mod 10)
    
    Call Ken_Logcat_I("将更换第" & LineIndex &"页的第" & PageCount &"行船，ShipID:" & ShipID)
    //换船页数
    ChangeNavyPageCount = pageCount
    //换船行数
    ChangeNavyLineNumber = LineIndex
    
    Call Ken_Logcat_I("分析完毕，符合更换条件，开始更换")
    Dim ChangeNavyUpdateResult
    Call Ken_Logcat_I("点击更换按钮")
    Call Ken_PointAddAndClick(ChangeNavyChangeInitBtnPosition, ChangeNavyChangeInitBtnPositionOffsetX * (ChangeNavyNeedChangePortIndex mod 2), ChangeNavyChangeInitBtnPositionOffsetY * Int(ChangeNavyNeedChangePortIndex / 2))
    Delay 200//防卡
    
    If (Ken_FindPicUntilFound("编成_列表_顶部条") = False) Then 
        Call Ken_Logcat_I("没有找到列表的顶部条，可能没有点中更换按钮，更换失败，重新回到母港")
        Call GoToMuGang()
        ChangeNavyChanging = False
        Exit Function
    End If

    //选择可以替换的船
    Call Ken_Logcat_I("标准化列表类型")
    //列表类型
    Call Ken_ClickUntilChangeTo(TypePosition, "编成_列表_类型_船只")
    //初始化到最前页
    Call Ken_PointGetAndClick(ChangeNavyBackToFirstPagePosition)
    //直接选择第三页
    Call Ken_PointAddAndClick(ChangeNavyPagePosition, ChangeNavyPagePositionOffset * 2, 0)
    //按翻5页按钮
    For index = 0 To Int(ChangeNavyPageCount / 5) - 1
        Call Ken_PointGetAndClick(ChangeNavyJumpPageToNext5Position)
    Next
    //在（12345）中选按具体哪页按钮
    Call Ken_PointAddAndClick(ChangeNavyPagePosition, ChangeNavyPagePositionOffset * (ChangeNavyPageCount mod 5), 0)
    Delay 3000
    
    Call Ken_Logcat_I("选择第" & ChangeNavyLineNumber & "行的舰船")
    Call Ken_PointAddAndClick(ChangeNavyListPosition, 0, ChangeNavyListPositionOffset * (ChangeNavyLineNumber))
    Call ChangeNavySetNextShipIndex(ChangeNavyNeedChangePortIndex)//设置下一个要更换的INDEX
    Delay 1000
    If (Ken_FindPic("编成_列表_确定变更_disable")) Then
        Call Ken_Logcat_I("无法更改当前舰船。可能是在正在使用（入渠、已在舰队内），跳过至下一个定义的舰船ID再更换")
        //从舰船详情回到列表
        Call Ken_PointGetAndClick(ChangeNavyListNavyPosition)
        Delay 200//防卡
        Call Ken_PointGetAndClick(ChangeNavyListNavyPosition)
        Call ChangeNavyChangeInit()//无法更改当前舰船。可能是在正在使用（入渠、已在舰队内），跳过至下一个定义的舰船ID再更换
    End If
    Call Ken_Logcat_I("确定变更，开始")
    Call Ken_FindPicUntilFoundThenClick("编成_列表_确定变更")
    Call Ken_DeleyForNet()
    Call Ken_Logcat_I("确定变更，结束")
    ChangeNavyChanging = True
End Function
//更换后，设置下一个要更换的INDEX
Function ChangeNavySetNextShipIndex(ChangeNavyNeedChangePortIndex)
    //如果当前舰船下标已经获取到最后一个，则从头重新开始
    If (ChangeNavyIDs + 1 > UBound(ChangeNavyIDArray)) Then 
        ChangeNavyIDs = 0
    Else 
        ChangeNavyIDs = ChangeNavyIDs + 1
    End If
    If (ChangeNavyNeedChangePortIndex = 0) Then 
        Form.Label_ChangeNavy_1.Caption = ChangeNavyIDs
    ElseIf (ChangeNavyNeedChangePortIndex = 1) Then
        Form.Label_ChangeNavy_2.Caption = ChangeNavyIDs
    ElseIf (ChangeNavyNeedChangePortIndex = 2) Then
        Form.Label_ChangeNavy_3.Caption = ChangeNavyIDs
    ElseIf (ChangeNavyNeedChangePortIndex = 3) Then
        Form.Label_ChangeNavy_4.Caption = ChangeNavyIDs
    ElseIf (ChangeNavyNeedChangePortIndex = 4) Then
        Form.Label_ChangeNavy_5.Caption = ChangeNavyIDs
    ElseIf (ChangeNavyNeedChangePortIndex = 5) Then 
        Form.Label_ChangeNavy_6.Caption = ChangeNavyIDs
    End If
    Call Ken_Logcat_D("ChangeNavyIDs:" & ChangeNavyIDs & "ChangeNavyPageCount:" & ChangeNavyPageCount & "ChangeNavyLineNumber:" & ChangeNavyLineNumber & "UBound(ChangeNavyIDArray):" & UBound(ChangeNavyIDArray))
End Function

//工厂开发
Function FactoryNavy()
    Dim FactoryNumberArray
    Call Ken_Logcat_I("工厂模块是否打开:" & Form.CB_AutoFactory.Value)
    If (Form.CB_AutoFactory.Value = 0) Then 
        Exit Function
    End If
    Call GoToScene("工厂")
    Delay 1000
    Call FactoryDev()
    Call FactoryBuild()
End Function

Function FactoryDev()
    Call Ken_Logcat_D("Int(Form.IB_Dev_RepeatCount.Text):" & Int(Form.IB_Dev_RepeatCount.Text))
    Call Ken_Logcat_D("IsNumeric(Form.IB_Dev_RepeatCount.Text):" & IsNumeric(Form.IB_Dev_RepeatCount.Text))
    While (Int(Form.IB_Dev_RepeatCount.Text) > 0)
        If (IsNumeric(Form.IB_Dev_RepeatCount.Text) = False)
            Call Ken_Logcat_I("开发次数文本框内容为空，或者不是数字")
            Exit Function
        End If

        Call Ken_FindPicUntilFoundThenClick("工厂_主界面_开发")
        Delay 200 //防卡
        If (Ken_FindPicUntilFound("工厂_开发_开发界面") = False) Then 
            Call Ken_Logcat_E ("没有成功打开开发界面，退出开发，回到母港")
            Call GoToMuGang()
            Exit Function
        End If
   	
        FactoryNumberArray = Split(Int(Form.IB_Dev_Oil.Text) & "|" & Int(Form.IB_Dev_Steel.Text) & "|" & Int(Form.IB_Dev_Ammo.Text) & "|" & Int(Form.IB_Dev_Lv.Text), "|")
   	
        Dim mIndex
        For mIndex = 0 To 3 Step 1
            Call FactoryCountClick(FactoryNumberArray(mIndex),FactoryPositionArray(mIndex),True)
        Next
    
        Call Ken_FindPicUntilFoundThenClick("工厂_开发_开发开始")
        Call Ken_DeleyForNet()
        Delay 5000
        Call Ken_FindPicUntilFoundThenClick("出击_结束_评价_返回")
        
        Form.IB_Dev_RepeatCount.Text = Int(Form.IB_Dev_RepeatCount.Text) - 1
    Wend
    Call Ken_Logcat_I("开发次数小于等于0，开发结束")
End Function
Function FactoryBuild()
    Call Ken_Logcat_D("Int(Form.IB_Build_RepeatCount.Text):" & Int(Form.IB_Build_RepeatCount.Text))
    While (Int(Form.IB_Build_RepeatCount.Text) > 0)
        If (IsNumeric(Form.IB_Build_RepeatCount.Text) = False)
            Call Ken_Logcat_I("建造次数文本框内容为空，或者不是数字")
            Exit Function
        End If
        
        If (Ken_FindPicAndClick("工厂_建造_建造完毕")) Then 
            Call Ken_Logcat_I("发现建造完毕的舰船，正在获取")
            Call Ken_DeleyForNet()
            Delay 5000
            Call Ken_FindPicUntilFoundThenClick("出击_结束_评价_返回")
        End If
        
        Call Ken_FindPicUntilFoundThenClick("工厂_建造_选择空位")
        Delay 200 //防卡
        If (Ken_FindPicUntilFound("工厂_建造_建造界面") = False) Then 
            Call Ken_Logcat_E ("没有成功打开建造界面，退出建造，回到母港")
            Call GoToMuGang()
            Exit Function
        End If
   	
        FactoryNumberArray = Split(Int(Form.IB_Build_Oil.Text) & "|" & Int(Form.IB_Build_Steel.Text) & "|" & Int(Form.IB_Build_Ammo.Text) & "|" & Int(Form.IB_Build_Lv.Text), "|")
   	
        Dim mIndex
        For mIndex = 0 To 3 Step 1
            Call FactoryCountClick(FactoryNumberArray(mIndex),FactoryPositionArray(mIndex),False)
        Next
    
        Call Ken_FindPicUntilFoundThenClick("工厂_建造_建造开始")
        Call Ken_DeleyForNet()
        Form.IB_Build_RepeatCount.Text = Int(Form.IB_Build_RepeatCount.Text) - 1
    Wend
    Call Ken_Logcat_I("建造次数小于等于0，建造结束")
End Function

Function FactoryCountClick(Number,Position,isDev)
    Dim Ge, Shi, Bai
    Dim Decrease
    If (isDev) Then 
        Decrease = 10
    Else 
        Decrease = 30
    End If
    
    Number = Number - Decrease
    
    Bai = Int(Number / 100)
    Shi = Int(Number / 10 mod 10)
    Ge = Int(Number mod 10)
    Call Ken_Logcat_D("Bai" & Bai & " Shi" & Shi & " Ge" & Ge & " Number" & Number & " Position" & Position)
	
    Dim Ken_LeftClickOnXY_Delay_Temp
    Ken_LeftClickOnXY_Delay_Temp = Ken_LeftClickOnXY_Delay
    Ken_LeftClickOnXY_Delay = 100
    Dim indexForBai,indexForShi,indexForGe
    For indexForBai = 0 To Bai - 1 Step 1
        Call Ken_PointAddAndClick(Position, 0, 30)
    Next
    For indexForShi = 0 To Shi - 1 Step 1
        Call Ken_PointAddAndClick(Position, 0, 0)
    Next
    For indexForGe = 0 To Ge - 1 Step 1
        Call Ken_PointAddAndClick(Position, -127, 17)
    Next
    Ken_LeftClickOnXY_Delay = Ken_LeftClickOnXY_Delay_Temp
End Function


Function FacotryDissolve()
    Call GoToScene("工厂")
    Call Ken_FindPicUntilFoundThenClick("工厂_主界面_解体")
    If (Ken_ClickUntilChangeTo(FactoryDissolveType, "工厂_解体_列表类型_新入手")) Then 
        Dim DissolveIsFinish
        Do
            DissolveIsFinish = False
            Call Ken_PointGetAndClick(FactoryDissolveFirstShipPosition)
            If (Ken_FindPicAndClick("工厂_解体_确定解体")) Then 
                DissolveIsFinish =True
                Call Ken_DeleyForNet()
                Delay 3000
            End If
        Loop While(DissolveIsFinish)
    End If
    
End Function
























































/**********************************************************工具函数**********************************************************/
Function InitEnvironment()
    Dim fso
	
    ResourceFolder = Plugin.Sys.GetDir(0) & "\pic\"
    Call Ken_Logcat_I("资源路径为："&ResourceFolder)   	
    //    Set fso = CreateObject("Scripting.FileSystemObject")
    //    If (fso.FolderExists(ResourceFolder)) Then 
    //    Else 
    Call Ken_Logcat_I("释放资源开始")   	
    PutAttachment ResourceFolder, "*.bmp"
    Call Ken_Logcat_I("释放资源完毕") 
    Call Plugin.File.CreateFolder(Plugin.Sys.GetDir(0) & "\日志")
    //    End If
    DebugLogPath = ".\日志\"& "Debug_" & Ken_GetDateTimeStr() & ".txt"
    WarningLogPath = ".\日志\" & "Warning_" & Ken_GetDateTimeStr() & ".txt"
    
    Call Plugin.BGCP2_02.TransformWindow(HwndGame)
  	
End Function


/*获得游戏句柄*/
Function GetHwndForGame()
    Dim HwndEmbedding,HwndDocObject
    HwndTidu = Plugin.Window.Find(0, "提督業も忙しい！")
    HwndEmbedding = Plugin.Window.FIndex(HwndTidu, 0, "Shell Embedding", 0)
    HwndDocObject = Plugin.Window.FIndex(HwndEmbedding, 0, "Shell DocObject View", 0)
    HwndGame = Plugin.Window.FIndex(HwndDocObject, 0, "Internet Explorer_Server", 0)
    Call SetHwndByGame()
    If (Hwnd = 0) Then 
        MessageBox "找不到窗口句柄，程序结束"
        Call Ken_ErrorEndScript()
    End If
    Call Plugin.Window.SetClientSize(HwndTidu, 800, 1000)
    Call Ken_Logcat_D("HwndTidu:" & HwndTidu)
    Call Ken_Logcat_D("HwndGame:" & HwndGame)
    Call Ken_Logcat_D("Hwnd:" & Hwnd)
End Function
Function SetHwndByGame()
    Hwnd = HwndGame
    ScreenHeight = 480
    ScreenWidth = 800
    PicDefinition = 0.9
    Call Ken_Logcat_D("SetHwndByGame.Hwnd:" & Hwnd)
End Function
Function SetHwndByTidu()
    Hwnd = HwndTidu
    ScreenHeight = 1000
    ScreenWidth = 800
    PicDefinition = 1.0
    Call Ken_Logcat_D("SetHwndByTidu.Hwnd:" & Hwnd)
End Function

/**第三方库查找图片**/
Function Lib_FindPic(picName)
    Call Plugin.BGCP2_02.FindPicture(Hwnd, 0, 0, ScreenWidth, ScreenHeight, ResourceFolder & picName & ".bmp", 50, PicDefinition, X, Y)
End Function
Function Lib_FindPicByRect(picName,StartX,StartY,EndX,EndY)
    Call Plugin.BGCP2_02.FindPicture(Hwnd, StartX ,StartY ,EndX ,EndY ,ResourceFolder & picName & ".bmp", 50, PicDefinition, X, Y)
End Function
Function Lib_FindPicByRectAndDefinition(picName,StartX,StartY,EndX,EndY,mPicDefinition)
    Call Plugin.BGCP2_02.FindPicture(Hwnd, StartX ,StartY ,EndX ,EndY ,ResourceFolder & picName & ".bmp", 50, mPicDefinition, X, Y)
End Function

/**查找图片**/
Function Ken_FindPic(picName)
    Call Lib_FindPic(picName)
    If X > - 1  Then //找到了
        Call Ken_Logcat_D("Ken_FindPic:" & picName & " FoundPic = true")
        Ken_FindPic = True
    Else //没知道，可能是被选中的状态，更换选中状态的图片再找一次
        Call Lib_FindPic(picName & "_touched")
        If X > - 1  Then 
            Ken_FindPic = True//找到了	
        Else 
            Call Ken_Logcat_D("Ken_FindPic:" & picName & " FoundPic = false")
            Ken_FindPic = False//真没找到
        End If
    End If
End Function
Function Ken_FindPicByRect(picName,StartX,StartY,EndX,EndY)
    Call Lib_FindPicByRect(picName,StartX,StartY,EndX,EndY)
    If X > - 1  Then //找到了	
        Ken_FindPicByRect = True
        Call Ken_Logcat_D("Ken_FindPicByRect:" & picName & " Ken_FindPicByRect:"  & Ken_FindPicByRect &" StartX:" & StartX & " StartY:" & StartY & " EndX:" & EndX & " EndY:" & EndY)
    Else //没知道，可能是被选中的状态，更换选中状态的图片再找一次
        Call Lib_FindPicByRect(picName & "_touched",StartX,StartY,EndX,EndY)
        If X > - 1  Then 
            Ken_FindPicByRect = True//找到了	
        Else 
            Ken_FindPicByRect = False//真没找到
        End If
        Call Ken_Logcat_D("Ken_FindPicByRect:" & picName & " Ken_FindPicByRect:"  & Ken_FindPicByRect &" StartX:" & StartX & " StartY:" & StartY & " EndX:" & EndX & " EndY:" & EndY)
    End If
End Function

Function Ken_FindPicByRectAndClick(picName, StartX, StartY, EndX, EndY)
    Ken_FindPicByRectAndClick = False
    If (Ken_FindPicByRect(picName, StartX, StartY, EndX, EndY)) Then 
        Ken_FindPicByRectAndClick = Ken_LeftClickOnXY()
    End If
End Function


Function Ken_FindPicByRectAndDefinition(picName,StartX,StartY,EndX,EndY,mPicDefinition)
    Call Lib_FindPicByRectAndDefinition(picName,StartX,StartY,EndX,EndY,mPicDefinition)
    If X > - 1  Then //找到了	
        Ken_FindPicByRectAndDefinition = True
    Else //没知道，可能是被选中的状态，更换选中状态的图片再找一次
        Call Lib_FindPicByRectAndDefinition(picName & "_touched",StartX,StartY,EndX,EndY,mPicDefinition)
        If X > - 1  Then 
            Ken_FindPicByRectAndDefinition = True//找到了	
        Else 
            Ken_FindPicByRectAndDefinition = False//真没找到
        End If
    End If
End Function

/**查找图片，找到就点没找到就算了**/
Function Ken_FindPicAndClick(picName)
    Ken_FindPicAndClick = False
    If (Ken_FindPic(picName)) Then 
        Ken_FindPicAndClick = Ken_LeftClickOnXY()
    End If
End Function

/**查找图片，直到超时或者图片位置点击**/
Function Ken_FindPicUntilFoundThenClick(picName)
    Ken_FindPicUntilFoundThenClick = False
    If (Ken_FindPicUntilFound(picName)) Then 
        Ken_FindPicUntilFoundThenClick = Ken_LeftClickOnXY()
    End If
End Function

/**查找图片，直到超时**/
Function Ken_FindPicUntilFound(picName)
    Dim Timeout
    Timeout = 0
    Do
        Delay 100
        Timeout = Timeout + 100
        If (Timeout >= 5000) Then 
            Ken_FindPicUntilFound = False
            Exit Function
        End If
    Loop While (Ken_FindPic(picName) = False)
    Ken_FindPicUntilFound = True
End Function

/**点击XY的位置**/
Function Ken_LeftClickOnXY()
    If X <= - 1  Then 
        Ken_LeftClickOnXY = False
        Exit Function
    End If
    Call Ken_Logcat_D("Ken_LeftClickOnXY x:" & X & " Y :" & Y)
    If (Y < 800) Then     	
        Call Plugin.Bkgnd.LeftClick(Hwnd, X, Y)
        Ken_LeftClickOnXY = True
    Else 
        Call Plugin.Bkgnd.LeftClick(HwndTidu, X, Y)
        Ken_LeftClickOnXY = True
    End If
    X = -1 
    Y = - 1 
    Delay Ken_LeftClickOnXY_Delay
End Function

/**存储坐标给某个变量**/
Function Ken_PointSet(positionX, positionY)
    Ken_PointSet = positionX & "|" & positionY
End Function

/**获得坐标从某个变量**/
Function Ken_PointGet(XY)
    Dim ZuoBiao
    ZuoBiao = InStr(XY, "|")
    X = Clng(Left(XY, ZuoBiao - 1)) : Y = Clng(Right(XY, Len(XY) - ZuoBiao))
End Function

/**获得坐标从某个变量，然后单击**/
Function Ken_PointGetAndClick(XY)
    Ken_PointGet (XY)
    
    Call Ken_LeftClickOnXY()
End Function

/**某个变量与坐标相加**/
Function Ken_PointAdd(XY,positionX,positionY)
    Call Ken_PointGet(XY)
    X = X + positionX
    Y = Y + positionY
End Function
/**某个变量与坐标相加，然后单击**/
Function Ken_PointAddAndClick(XY,positionX,positionY)
    Call Ken_PointAdd(XY,positionX,positionY)
    Call Ken_LeftClickOnXY()
End Function

/**点击坐标，直到出现图片**/
Function Ken_ClickUntilChangeTo(Position,PicName)
    Dim Timeout
    Timeout = 0
    Do While (Ken_FindPic(PicName) = False)
        Call Ken_PointGetAndClick(Position)
        Delay 100
        Timeout = Timeout + 100
        If (Timeout >= 5000) Then 
            Ken_ClickUntilChangeTo = False
            Exit Function
        End If
    Loop
    Ken_ClickUntilChangeTo = True
End Function

Function Ken_DeleyForNet()
    Call Ken_Logcat_D("网络等待")
    Dim FindTime, nCount
    FindTime = Plugin.Sys.GetTime()
    Do
        If (Ken_FindPicByRectAndDefinition("全局_载入中", 770, 450, 800, 480, 0.7)) Then 
            FindTime = Plugin.Sys.GetTime()
        End If
    Loop While (FindTime  + 1500 > Plugin.Sys.GetTime())
    Call Ken_Logcat_D("获取网络数据完毕")
End Function

Function Ken_ErrorEndScript()
    Call Ken_Logcat_E("出现了严重错误，脚本即将中止。可尝试重启脚本、游戏和电脑。如问题继续请联系作者")
    EndScript
End Function

Function Ken_GetDateTimeStr()
    Ken_GetDateTimeStr = Year(now) & "_" & Month(now) & "_" & Day(now) & "_" & Hour(now) & "_" & Minute(now) & "_" & Second(now)
End Function

Function Ken_WriteLog(Log)
    Call Plugin.File.WriteFileEx(DebugLogPath, Log)
    TracePrint Log
End Function
Function Ken_WriteInputBox(Log)
    Dim FileLenSave,FileLenNow
    
    LogLine = LogLine + 1
    If (LogLine > 1000) Then 
        Call Ken_LogInputBoxClear()
    End If
    
    FileLenSave = Plugin.File.GetFileLength(DebugLogPath)
    Call Ken_WriteLog(Log)
    FileLenNow = Plugin.File.GetFileLength(DebugLogPath)
    
    HwndFile = Plugin.File.OpenFile(DebugLogPath)
    Call Plugin.File.SeekFile(HwndFile,FileLenSave)
        
    LogcatFileStr = Plugin.File.ReadFile(HwndFile, FileLenNow - FileLenSave)
    Form.IB_Logcat.Text = LogcatFileStr & Form.IB_Logcat.Text

    Plugin.File.CloseFile (HwndFile)
    FileLenSave = FileLenNow
End Function
Function Ken_LogInputBoxClear()
    Form.IB_Logcat.Text = ""
    LogcatFileStr = ""
    LogLine = 0
End Function

Function Ken_Logcat_D(Log)
    If (Form.OB_Logcat_Debug.Value = 1) Then 
        Call Ken_WriteInputBox(Log)
    Else 
        Call Ken_WriteLog(Log)
    End If
End Function
Function Ken_Logcat_I(Log)
    Call Ken_WriteInputBox(Log)
End Function

Function Ken_Logcat_W(Log)
    Call Ken_Logcat_I("*******************************"&Log&"*******************************")
End Function
Function Ken_Logcat_E(Log)
    Call Ken_Logcat_I(Log)
    
    If (Form.CB_Logcat_WhenWaringSavePicture.Value = 1) Then 
        Call Plugin.BGCP2_02.SavePicture(HwndTidu,0,0,800,1000, "./日志/" & Ken_GetDateTimeStr() &"_"& Log &".png")
    End If
End Function

Function Ken_CmpColor(mColor,PositionX,PositionY)
    Ken_CmpColor = Plugin.BGCP2_02.CmpColor(Hwnd, PositionX, PositionY, mColor, 0)
    Call Ken_Logcat_D("Ken_CmpColor Ken_CmpColor:" & Ken_CmpColor & "PositionX:" & PositionX & "     PositionY:" & PositionY & " mColor:" & mColor & " Hwnd:" & Hwnd)
End Function
Function Ken_GetColorByPosition(PositionX,PositionY)
    Ken_GetColorByPosition = Plugin.BGCP2_02.GetPixelColor(Hwnd, PositionX, PositionY)
    Call Ken_Logcat_D("Ken_GetColorByPosition Ken_GetColorByPosition:" & Ken_GetColorByPosition & "	    PositionX:" & PositionX & " PositionY:" & PositionY & " Hwnd:" & Hwnd)
End Function
Function Ken_FindColor(mColor)
    Ken_FindColor = Ken_FindColorByRect(mColor, 0, 0, 800, 480)
End Function
Function Ken_FindColorByRectAndColorOffset(mColor, mStartX, mStartY, mEndX, mEndY, ColorOffset)
    Ken_FindColorByRectAndColorOffset = Plugin.BGCP2_02.FindColor(Hwnd, mStartX, mStartY, mEndX, mEndY, mColor, ColorOffset, 0, ColorX, ColorY)
    Call Ken_Logcat_D("Ken_FindColorByRectAndColorOffset ColorX:" & ColorX & " ColorY:" & ColorY & "     mStartX:" & mStartX  & " mStartY:" & mStartY   & " mEndX:" & mEndX  & " mEndY:" & mEndY & " ColorOffset:" & ColorOffset & " Hwnd:" & Hwnd)
End Function
Function Ken_FindColorByRect(mColor, mStartX, mStartY, mEndX, mEndY)
    Call Ken_FindColorByRectAndColorOffset(mColor, mStartX, mStartY, mEndX, mEndY, 0)
    If (ColorX > - 1 ) Then 
        Ken_FindColorByRect = True
    Else 
        Ken_FindColorByRect = False
    End If
End Function
