[General]
SyntaxVersion=2
BeginHotkey=121
BeginHotkeyMod=0
PauseHotkey=19
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=7b0fd93b-ec20-46c4-87a5-4547b1cc55e9
Description=舰娘
Enable=1
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=1
QUI=Form
[Relative]
SetupOCXFile=
[Comment]

[UIPackage]
UEsDBBQAAgAIAGwUZ0a0Wlhkr3EAAAjKBgAJABEAVUlQYWNrYWdlVVQNAAfaY/pU2mP6VNpj+lTsXQl8VNXVP28Iq4DsIqLiUhdEzcxkQ9E6SQaIJJmYhc1lCBAkApkYAgJuuG+AuFRt3VDa6mdp3YCKqNjWIlSlfIrox1dbq59Vq/Wz2mq/zwo95703eW+SScl57yTHCNffkWF4b84999177v9/7n3ndgGrbP9t/7cfeHzYH6FZOR26wO49PaGb67vuKEbyL/0AAvhHf5Tde/bsSX69FKyLltKFeMFSuqgLwJ795RtZvkbJwEd0Ago96672c+6F0gOlJ8oBKH1QeqP0tR49HIgyxH7+A1AGogxCGYwyFOUglINRDkEZhjIc5TCUQ1EORzkSZQTKEShHoXwH5WiUY1COQzkW5XiUUSgjUU5EiaOcjHISSiZKCCWIEkbJQclCyUbJRRmNkodyCsoYlFNRTkP5rtm3Ac5AyUeJoBSgRFEKUcaiFKGMQxmPciZKMcoElBKUGEopShlKOcpZKBUoVSiVKBNRpqBMQpmMMhXlHJSzUc5FmYZyHko1ym0oM1Cmo8xEmYVSg3I+Si3KbJQLUOaizEGZh1KPUoeSQLkQZT5KA0ojykKUBSgXoSxGWYSyBOUSlItRLkW5HOUylCtQrjJtSOB/jfgsovi7jfhbi4FThmCPSfYlYy/XTrv07++EJ2830B3A84cHzO+qsLUzwXvpAYaR1A8Zregd+YmpN6nf/W8F+NSKfdSgl0t/V9iLfvtP979VYnvX41MvxR4xz3z6vDIAAqZ+Go97XH54byXZVOS7tSQ5/o+0fcDRth84xh7/x9k+YKTtn0bZfuAk2w9k2uM/ZPuA5PjPsX1Anu0HTrHH/xjbB5xu+4Ez7PGfb/uAQtsPjLXHv2bbdJSMTTTM8zH8wO/9Bvgrfu/3W9Y+9vJ7QUX9n376qa/7vfodx/8FUrBdW59Z0v/QrFONM+Bcj3Xoi/6P8El3hv8LuPRPxJl2PorXGvRD/b3BwbdtuaeLS385aq3G2T+G7TCXOfcm/X83sPBaW/VnuPRXov5FJnrw/PwN7vPvaguYfjeBdicQd3irySAP+ru57Hf05+NzmGHiLKZ+83n2ZLR/92bPf4bP9ids3oOhvwdYGN5dpuGgWKbtTD2UL9LbbFpSUjGiorpu/oiKmobaWe2kv7J6ekGirrEhMdfz/fGCRINnB+z3kU1Fz9OA/qfGZBH80teD/+/p6v/FOPb4oy61//e1f6+t+nu59I9F/XX+xh/bfpqvxtifI+h9apHx1ZmzcJ0X/8fW3zvF/xH/Cfqw3zBoPiXcPrCVa5K8p/6s9uE/hwFv/u1j9wEqGviH+msP+7ME/qE4y1BG/z8QZPHPMGb79wNZ/ENxp/4M+/uDKP5hP393vFQK/xzFsH+Ay/5OOOWnFL/8h+ynGOgMdGIrDG/3axa/+EcC/1LM93BG/xsIsviXYsyHMvQPAgf/auCfwSCLf4bbY7qt+oeALv6htYEk/ilC3TU4A8/3qL832k/2HMGwn+bKkfbnCtQ+1+6DNWYUnlcGeLD/YHDPPzT7J8eeMxrbWoah/dSeRzPsH+bS3wMydqx//cuMJ7/Y+GXGExue+kfGlo9e3J3x+NtPbs3Y8MMnH8rY8vrO5zK2frDzV+l/K8On//Lrv/3er10G+Lx/Ofmgovx4flVRcWG8ojIaLTaX8Ioj+dHicND5HMqhzyMK8uMVVWVlxVPik8ZHS+NRq//N99wDh3vo/4e4+k0FjrvFntGvOf7Z+oe3GH/zzVmg1mZg1Si1pl/cexnhQf+hafSPR93EA2czffEQD/oPg9T4l2VzLf5JHpDnkQ9D/zMCrDWctuonrHBMr6R+4p8hz/3fvf52XCvXJHlne/FP0p3NsH88OPxPg3/S+nYS/0wuixYWVRbFSuP50bGx8qi5pwOdRHm0LFJUHp86PlY6rixGEc6B+G2ksjJSMKG0aNz4yrH0P6PJvWQFqUcNzq8sjRfHxhVEKuOxsmjp2FhxYbS8m+OQQuSEDmz6JdMXTaFf6efonFwUiTVXGce6lUSoni6VmS7vlk3q+5B6yxNGCgtdfjDsujKLruxmfh5NSgY7SoqLSooq4wWxqlK3ZWG6oee48lhVWX5sch5Z0xM9rmWmY1t2ZvfUKpsOtjBSFjOaFOY5Pxsyf9ZWEaLPB+OtBeMjpeOipZGJtn+22sK5MjtISgaYn90X52Sk/To7/ddZ6b8Op/86lP7roKv+ph5qlMLoxHjxRFdrh6iJhzebdewGcnqcdXHQdAN9nZ5AjUf3D2nWqHavpMY8Mk2jFcRK7T4dzoxnZbrqaRrey65nrMg1VYZMcwY4igrGRwsm4CWG/bVd/+TX4NQ67HSoXLp6GF4ddcYV1Sscx+rlF9PisvnPzWtsG5SxV4NCmWiTy6Bc53MwM9BUD1oBN4dxpKoy5tTFqXQo03Bd4ehz/bTZpQ6gEUWNZY8n6+ezXdYH6Yf6xpLjIV6Eg9414PPorn7OuCyPlsQmRunLHsU2aqG/HNAEYaze09eu2dhIQWWsfEryErMmJSWxru4RGXbVxqx0r6bHFQyk/DWc+tdQ6l+znPbLAqfL2/2hqLQwOplsPeLfPqBMfESuRhztfA6PthrQtCLFgJBrCOQ6nSlM2g5Ko42GRUbqsIiMrYyW28PG5bryTK/Y1LbJphvU9A3eEY1Umh4vpUpB50eC5qA5PLVTlxRVVOCf0YnYQFQxc+Tu5ZpwG67JgvQDKOQaQFbrhKiGQ5uN16bn4Kp+ttOiLqvCWWRvb7tPNeHmdD7YatWM1KnC5Z1bGfNZriq7/EpJpKyYzDVSH6DdEE3/1PQkzA5xoDO+CqP5VeNcAyw75bnlJOdX24NOihZZLrSPPaCs71MnV3Mqxx8oLTTsNrE6h+0g+yZ9gDN2bd2mtgF2GzbrSrafGZ1SvWznX4JW37SrZVWE1A8uam067ut44YpYeSUNmqF4cUW0srKodFzctCIeq8K/lUS7O5XMddUmL6U2We6GsX45kApFrImOLutrOQP307PtGG3YFMzpN2aXS/0qp+VXWS2/Crf8Ktjyq5DLqbgxUG6Tr7X7SkFxNFLe7d9iwYLZNTPm5CcWecWf1FY19dW1DfHS6oWL4+yFpM6+/2fnxm1rtv9+3a5XNz774PrXOl6/3/iHxPoT7ccbyeA/tKdWcP2JzX8mgOz6E01+JzLsLwb5/TdZDP0lYK1BmuNXaP0pzNBfCrL7b2i/6CiG/hjIrj/QPtQTGPrLQHf94SyX/dRvfo7yIMorHvS/4NN/+fXf2vt/Ovv6qcT6E036xzL6fznorj/R+xpjmvzPbNMDzPG0+mPtf6C96Mcz7K+Elv6/3FP019v+nyrQjb9PdOnX2P80CZrvfwr76H+G0c/+zdGtXNMR8ecCRv+j95KS+2+Lq6fXzAXvxbw/XlJdX1yz0MsPdXb8v+7NV55Z/bSe/s64/5/ej0viTwn+Qe/ynMro/1NBdv/bGWC9N9RW/WeDLP+g95tOZ+g/B3T3/9N7kMmohBT/KGTYfx7I8g961+w0hv44yPIPeodtDEP/NHD4x8lg4TGaE6o96J/m0391dvyvXfzG7zT4ZzXI7n+j9zfzGP1/Oujyjxmgu/9/Jrj9fwM+jzqcA+vxzwZ2HYZ60F8Dbvy/APUlkIfUwhJv+JetfxY0x/9ZPp6/s/+kqJVrOgL/T2T0f8ovoLn/hPIa9LE/S+A/iudNYNhfC7rx5wtAFv9VgBVTbav+Oe7+nx+PLGhMRBobq2d48cKdnb+9sWP9o7T3VUu/X/5Ge3kp9k05PvI93C+F/6sY/W+uy/9I4f9Khv55IIv/KVdECUN/Hcjif4rnFzP0J0B3/aEeZPEf8ZfxDPsvBF38Ry0tGX+m9aQzGfbPd9kf8+m/9q/f6Ba//E9j/aERdNcfFoDu+sNCaM4/sn34H8OgfEWEqae2ck1H8I/zGf6H8pNp8g8aLJL8YxpYMdW26l8MuvxjCbTA/9YeLgX/+U3A//TGm5Z+bfwvwT8Jt8QZ/f9ikF9/mMXQfwnI848ahv5LQZZ/UOz+PIb+y0CWf1A89VyG/stBl38sBVn+QfHcKQz7rwBd/nElOPxjX8hxqC27PLbzBx7v+4Jx370+56/9/E+3FCTmTU/42b8vEH+g9byzGf7vKtDd/3Y16PLPa0CXf14Lzflnjo/5x1n/am0WTfLOpYvah38uBF7+qetAl39eD06uNAn+SfHMeYzxdwOk8j9z7Wds7fmzG8sTC+p4XqCz8z+/hZFyu1VfRPHYZ+x+wS1zfdZfYv9bA3P83Qiy65/UBvWM/n8TyPPPBQz97ZH/jdP+y0CWf9J6eoJh/3KQ5Z80fuoY+leALv+8GWT5J7XeBQz7V4Jc/j+/+B3xQ6YRNEJG2Mgyso0cI9fIM0ZDhxWB91+t+TM+aXZNXXxybXWiLMG4X3v+1Ig/3AKi+d/Y+m8FKwceFY38b7dBc/yd66P9DYPQO73Dt6SVa5K4u73wN9l9HcP/3A66+Pt7YOVgpCKBv5eCFVNuq/47QHf9506QxV+EYS9n2H8XyOOvaxn6vw9WDmxr/Mngr2sY+n8AsviLJq/LGPrvBv95G5Nl+wObN2/a+uoOrT10ftfPfoTecA31owDALz3cv9Bn/bXxlwT+pvWESxn97x7Qxd/3giz+pnjmYob994Hu+s/9ILv/jNazLmbYvwp0478PgG7890HQjf+uBjn/v6/vn6O8X4vqa2bWNtYm6swcSFnxaF319Llt7FDa/M/iH3k+/I8T/7+plWs6gn/cxfA/PwRd/vEjsPbtUJHgH8SnlzPs/zHo8o+HQJZ/EJ9bybD/YZDnH3cy9P8HyO8/uoOh/xGQ8//rdr30gk7mM6v4xf/0/jPhMeJv6z3cX+qz/tr4X4J/0nrizYz+9xOQjf9TPG0FQ/8a0OUfPwVZ/kHxtBsZ9v8MdPnHoyDLPyieu4xh/2Ogyz8eB13+8QTsx/9N/s/v/qmm9R9vOZC08b8G/3wSmq9/eF/wI/5B+yYI093TyjXtzT8eAt7+h7Wgyz/WgXPujAT/oHjGfdB2/7seZPMvrWa2/89Bln9QPPEBhv1PgTz/+DF423+iXfxWhd57oHdYiQN6wQ/n+qy/Nn7vDu7dExkbP1n/KEu/xv6jDSC7/kXraasY/f9pkOUfFE+6n6F/I+jyj2dAln9QPOtuhv3Pgi7/eA50959sAmf/r8b+k+dBDv8L4ufa+fNrE3VMDL1//7G/+TN5/nem5/7vxP9/0so1Sdy98v72wd/rgYf/fgG6+Jv2GST3n0ngb4on/BTa7n9/BbL4+wlm+78Asvib4nmPMez/Ncjj73XQefZ/bwZZ/EXrGY8y7H8RZPEXxRN+xtC/BXTx11aQxV8UT3iEYf9vXPrJFxJ/eg+88adq8Fe0+VNXF38ChSKAn1z7D2wMRRDK3Iuw93NVNfD3S6CLv18GZ/+nBv5+BZrHP4MQ9Gy/YdB+1tfB4rXpShJ3tRf++jXw5v9toIu/fgvWGcRUJPDX82Bx6rbq3w6y+OsXzPb/T5B7/2df508Uy6D8e30M8PT8xim3vwT+pnjWJkb/fxXk8fcL0Hnw92sgi79pPeE5hv07QBZ//9IeB23V/zro4u+dIIu/iU9vYNj/BujGP98EB3/5xc/HQsu3NwPBzEAwGAiGAsFwIJgVCGYHgjmBYG4gmBcIjg6EMgOhYCAUCoTCgVBWIJQdCOUEQrmBUF4gNDoQzgyEg4FwKBAOB8JZgXB2IJwTCOcGwnmBcDu8F9q++Hvv50ppz78a+Pu/wHpfm4oG/v5vaIm/Q57td+KfW1u5pr3x9w7g4b/fgS7+fgtk8Tfh+ZcY/vf3IIu/tzPb/w8gG/+keM42hv1vg9z6j98igb8pnyzh72Ue7q/3WX/t+JXf+VcKf78GnQd//xFk8TfFs19h2P8OyOJv4vMvM/S/C7r4+39AFn8Tn9zCsP890MXffwLd+Of74OCvbzf+3vu5Tvt6/EsDf38ILfG31xN4CX9vtn3Km61c0974+13g4b8/gy7+/ghk8Tfh6V3Qdv/7Mcji7z8w2/8vIIu/ic++xbD/E5CPf74DnQd//S/I4i+K5/2OYf+nIIu/3gYrptBW/X8FXfz1mct+Cf61Ciz+tc7D/fPBX+ns/Esbf0ngb+JTbzD6/+egi7//Brr4+++gG//8ElriryzP9jvxz/dbuSaJu1Ztbr/8D39j9L9/gC7++j+Qzf9AeOZDhv3/737+4vlPQp0q/4nfsm7X+t2dOf+BRv6Pr0AWfxOe+pjR//8J8vj7c4b+r0E+/8dnDP27QRZ/UzztI4b+PSCLv4lP/Jmhn5yGJv42DNn4J3mAPzHsD7j07z+fZ98Wyn9DOWwo/42XM3aKfc5f+88P0i0a/KuLIZv/heJpHzD8X4ahm/+lq6Gb/6WboZt/srvRkn9me7bfMGj9/yLD4nXpSpJ3tif/pDm1rfb3MOi9E6to8M+eqL+b/bm4enqNnzNkzPtD3u/v7Pxvw5ubHl79tJ5+v/xPIv5AfIJiCm3tf70M2fUfk08wxt8Bhiz/pHjO1wz7exvy/JMz/vu4xr8U/+zCaP++hiz/pPMu/8lo/wMNWf5JTugrhv5+yvyzv8t+yltaAdY6znQP+meCv9LZ8b928T1/C8QfKJ7xJaP/DzB0138GuviHBv4dlOL/G9Dv1eEcWI9/NrDrMNSD/sEp+H8B6kugD6iFJd7wL1v/kDT43+sJpO71px6tOJOOwP8DGPPfQcr4f2hz/B8GtaKN37e8v+GrbY9krl6z47OdG9d+tm7Xqxuf+uK5t9a9G+kY/X7xO71zQmfQXGhYMTxukcD/hOd6Mfr/wcL4n/DcIIb+YcL4n/h0H4b+Q5Tx/3DDWX+Wwv8DGfYfKoz/KZ7Vm6H/MGH8T3j+AIb+w5Xx/wiX/QnwV/bjd39FJP6W5eN+AfxPfLI7o/8foYz/j1TG/0cp4/+jlfH/d9Lgf68noBL+p/UU+s2hivj/SEb/P0YZ/x/rwv8S+I/m02EM+48Txn80nx7N0H+8MP4jPHsoQ/9IZfx3guHsP+rs6y9btm37a1Gh3gqMX/5G57ZQ/JXyR3mJv57ps/5S+P8oRv8fJYz/KZ40nKH/RGH8T3j6EIb+k5Tx/8nC+88Izx3EsD9TGf8FlfFfSBn/hQ25/G/7+ZsAf/ORedT/+T8dj/+z0uB/ryeQuuP/xyni/xDD/2Ur4/8cYfxP89lIhv25wvif5rMshv48YfxPfOJEhv7Ryvj/FEH877d8G/A7nT9F+P0JD/df6LP+/s9/lsH/YUb/P1UY/1M8ZRRD/xhh/E949gSG/tOU8f/pwvif8PSxDPu/q4z/z1DG/xFl/J/v0r8fvwvg9xzv9+uf/9nx+L8gDf73mtqA8D/tZ5poWLguXekI/J/P8H+Fyvg/Koz/aT45hWH/WGH8T/NJIUP/OGH8T3j+NIb+8cr4v8iF//2WbwN+vxgs/H6jh/sbfNZfO/4mhf8LGP3/TGH8T/GMMQz9E4TxP+HJUxn6i5Xxf4kw/ic8m8uwv1QZ/8eU8X+ZMv4/y/jm5H/2WwTy10QWNCacHDbM+zv7+vnX2GeuxD+vRrkWrD3E14E1F16PcgPKTSjLwcqvvQJlJcrNKLeg3I5yK1jnb1MeTnqf6A6Uu1DoXGY6m4rOBqYz0u8B65z4VWCdl0xnptPZyXR+PMXQ6Bzhh1DoLPOHwTrTjs4WpHNF6XxLOueRzvmjsx7pvEE695LO/qO4G52BR+eAUg46Ot+dzuOgc1EImNC7TXRGDc3xdE7K82CdV0PnJtHZHXR+CZ0fQ3mc6SwryiVM7/RRXnXaX0255Sm/M+VYpjzrlO+dcs5T3mXKvU/5hykBEJ1rQnnQKB8h5SKlnJiUG5JyA1J+SMpRSLky3wYrBzzlTaPcoZS7kfKXUg4PyqVCebQonxO90055TSi/E+VXoRw39K47IR7KeUJ5byjvDOV+ofxX9B4c5Rajd3HofUx6H5reS6PYNL2fSO/I0bua9L4OOQp6Z1mD/5W34H8hkfNnxyvyvyrG/Fdh6OYfq0T9/e3PEvyP5vMzGfZXyfI/tv0Thfkf9ecShv2T2oH/VTL0T3b1vzd2rH90x/rXv9Saf/zyN3qPYRTKDJR8D/ef5LP+nX3/hBT/q2D0vynC/I/iScUM/VOF+R/h+QkM/Wcr879zhPkf8YlxDPvPVeZ/5wnnHyI+WcSwP66cf2ia4P4v7SKyfpPr/f7Ozv808k9VK+efmp6Gf/g5f5nWU2YZ1ryWrnQE/5jB8D8zlNefZgqvP5E/PZthf43w+hP50xqG/lnC/IPwzHkM/ecrrz/Nbof3j2cy7K8Vxp/E585l6L9AGH+SPz2HoX+OC38++cXGL3/z+Oo1z3z8xIfPPrh2zebNL336xtqX13TUip5f/kevvlI8kGJumzzcf5HP+nd2/qfBP+YK8w+azycz+v88Zf5Rp7z+lFBef6pXfv/4wjT4T+L839q94L/H/tJ++G8ho/83CO7/8Fvkz58I72PnT2z52s/5Exr4f74he/4J+bM5jP7fqLz+sEAY/1N71jHsX9gO+H8BQ/9Fhvz5F40M/YuE8T/xqXkM/YuF8T/NZ3MZ+pe48L/f4he/0/kDlL+M9h2s8HB/ic/67+vnD2jg/4uF8T/hmdmM/n+JMv6/VHj9gfD0BQz7L1Nef7hc+fyDpcrx5yvS8A8/5x/T+8QbDcuvpytJ3pGOf+w/A2ffFlAuAvyvvKa+urYhXlhd7yGZYWfnf2s/37x5y0cv7vZ6v1T84TrG/HOl8v63qwzCLVaR4J80n1zCsP9qZf55jTD/JHsuZ9h/bTvwz2sZ+q9rB/55DUP/9cL8k/jsZQz9Nwju/5fgf5PB2kte5+H+533Wf1/nfxLxB/LnlzL6343K+99uEuafNJ8sZti/TJl/Lhfmn8RnLmbYv0KZf96szD9XKvPPW75B739JvL/V2Fg9Y0580uyauvjU2Ym688sYPKCz4/+d2zdv3rT11R20j8NT+9nxB68pxN3rnzd5iD9I8Y+7GP7nVmX+cRvqH2J/luAfNJ6XM+y/XZl/fE+Yf9DvrWTYf0c78I87Gfrp2t5N40+Gf9zB0H/XNwj/U+4Qeq9ztWG9h8ktC3zWf1/H/xL8k/jkzYz+933h9U/ypysY+n+gzD/uFuYf5M9vZNh/jzL/uFeYf9B8voxh/33K/ON+Zf6x6tuL/wury3iLAN+G+L8f/K/BPx9Is/7p5/x3iqc+Ylh+LV1J8o5/sXcd4E2VXbi5ARQUByAioiICgrNlV0BlW2QJKjgQGQUq0BZo2SDgANwTRRRIwigl0D3TUqClCzpIB0OQIYoKCsoogoX/fNxE8v+En5x7z+1paD6fFyP2nrcn+e6X973fOJvqHdfMf6xFjD9GZv8htFZd22sK/yHyWYbIfyWz/1hF7D9W6+Q+7Sr/ag38RxiCf40G/mMNgj+MeP5D6LkVCP61xPpT9OflCP5wZv25rhL5P3FejvB/nRT6vxCVv39V938U/kOMp0sR/d/M7D/WE/sP8X36HSL/Dcz+I4LZf0Qyz39EOdGfFPXH11/lZrTrTi31ZzKi/0VfX/t/bOu/hgQMDxqAXgHm7v6v0KBu/ReH/4hx0D8U/kPEi0D0/1hm/xFH7D8SdPI97Sp/vAb+IwnBn6DB+qtEBH8isf8QejoKwZ9E7D9Ef4pE8CdXov0/4oxLsf5LnB+oZP3XFpW/v2f/T8X7Twvx/IcYz8yI/p/C7D9Sif2H+D7bgMh/I7P/SGP2H5uY/cdmJ/5DTf1zMZ+6Tyd/rk7z/T/+g7vR6X/00i+S8bMyrP+qDPs/tiHGny3M8x/pxOcfZ+jkMcVV/gxm/7GV2H9k6+T31FX+TA38Ry6CP0sD/5GD4M8m9h9Cz2xB8OdUouf/oraA0P/ijHsl+n+zyt/fs/9Dvf8U9/NmRP/LZZ7/2kbsP8R4korIfzuz/8gj9h/i+yQNkX8+s/8oYPYfhcz+Y8f1uP6rX8CYsSE9xR8VOn5y6//0tNj8+JTUs9akklRF75/Nf3ZQ3P8vz38VMM5/7UWMP1Zm/1FEvP6qRCff067yFzP7jxJi/7FbJ+fkKn+pBv7jewT/Tg3WX+1B8O+qRPpf7Dt7XCfXCXtSwWAaoPL39+z/UO8/hZ4sQvS/3cTzX+J+siL49zD7j++J/Ye4n/MR+e9l9h/7iP2HGM8LEfn/wOw/9jP7jwOVSP+T1G/xUX799aD/U89aymLzc8uVnNnP4T8POpn/8lXc/3U68Tzld53cr521ivAfvyHGn0PM9Vd+JK6/8rNOzslV/sPE9VeOQLxjCP6fiP2H6M8/Ifh/Zq6/csTh/DMq/3EUkf8vxPMf4vv8MIL/V2L9KfL5EcH/G7P+PFrJzv8Se/hF/ekFCq7fqvL3d3f/p7ZR+A9xP+1H9P9jzP7jd+b6K38w1185zlx/5cQV+q81Sf3vE4z67xyi///JrP/+ctB/qscPCv/WwYutcfu3rKPZCdkFYvamqDBqlzW8ePcOQ/GfJnOS1XIuN6koXfyfgvPJGVHZqQWxJ+n5KfT/GZ3cp1ztfyeJ9X8ZxPsHwX+KWP+L+/k0gv80s/4Xn5e97jmV/j+PyL+MWP+L79NTCP6zxPpfxDuJ4P+bWf+fc8hfrX5f7CXP34g9PZ0UDKaZKsevqq7f1TYK/S/683FE/z/PrP//Ydb/5cz6/wKz/r/oRP+rqb99Gv5dQw9/SM5/xq77Cztqp/9rSa73f/F7cup/nXRZ/3tqoFRtkPg3Xy+2xu3fxNxbVmRyXurB3LPJJ+NTLAdTjkUfEjtytp9OuaA9v1r9RuH/asB4IiHGP/GzlP7vBoh3M4JfL9H6PzGeVkfwV5N4/Z/4Xe+1vabyfzch8q8h0fq/S3oGwX+DROv/bpTkPuUqv/h5Tv9X0yF/UYdX1E887CXXpcO2LJXjl8e/qWuqv78J/J/oTxcR/q+WxOv/xFjF6f9ulnj9X22J1//dIl3p/1op/Pwd539uu4r/s/s+Lf1fQ8T4fyuz/xPv0w2O44ePigV0Khu3ft9ptB4ymcUpyuIE5SjLDkNpYW6UyZyWk7HXcjAupXRLzOZYc4s+QZNDWmrBr1a/27+/O9hq8GEbhf6vD/2pDqL/306s/++EeI0Q/HWI9b/I5w4Ef11m/V8P+B+xvabS/3cj8r+DWP+L75N6CP76xPq/gSR/pq7y38ms/xs45J+jcvzy6Hd1jWb9eyvl1xPo/7skWdO42v/uYtb/DZn1/93M+r8Rs/6/x4n+b63w8xf6X/iZRwGNGfX/Q4j+fy+z/r/PQf9T6L/mEK8JIv/GxPrvQaFnEPz3E+s/Ea8Zgr8Js/57APhbeNE0/vVzSbE7DNYdaeGZp1KN8UUmc7qlqFD8V1yG+O9oizVc/IRW/FT+7WGdsuevDVV+AFT6/2FE/29KrP/FeNoUwd+MWP+3kOR7ylX+5sz6/0GJdv9xS0n+TnGVvwWz/mvJrP8eYtZ/Dzvwe/ybyvGTrH7doNDgYLz+UPv5cej/R5zof4r6096M+r8zYvwTXoXz/KHHhF+3vabQ/+0gXitE/o9LvOcPeRPr/ycgXltE/j4a6P9OCH7xWXkTjR9qm5h1yY3KSivNjE5KPBu3x2oRqr1F5qmidPEX1uKUSDElY/8f5HMwFOcXiTUQov56qYLr71b5AdCd/6NO/3dE9L/WxPpfjGdtEPxtiPV/B0nOyVX+tsz6vx2x/veV5DHdVf72zPq/g0R7/pDIxweRv6/Ee/7QEw787n5+GXej0P+hIUFC/I+fruB6te8fx/lTHSXe8287OfEfaupPi/mM1wFdruE/DozQzn/0Q4w/nZn9x5PAX9v2msJ/9IJ43RD5P8XsP54m9h/PQryeiPy7ED7/Udt2FsdHCKHPxU/x/F6spZkF6Krg+kbM+p/Kf/ZF9L+uEn39jT4I/m7E/kOMJz0Q/N2J/YefJMd0lb8Hs//oSew/ekvymOoqfy9m//EMsf8Q8boi8vfz6H+yRqD/Ze2v8AE41fhfkf6zt8R7/u2zzP6jjxP/QVF/fOBV/Ifdd2jpP4Yhxp++zP5DeKVattcU/mMIxHsekX9/Zv8xoBLp/7g92y6t0+HiV6v/hfZfA5gPSFNw/VPM+p/Cf74K/Wkwov8/p8H812sI/oEa+I+hCP5BxP5D3M8vIvifJ/YfL0O8FxD8LzD7jxeJ/ccrktynXeUfzOw/hjj4D4/+V9fI9L/CLRzq53/V+8+XJHlMc7X/vcQ8//Uys/94hdl/vOrEf6ipPy707ETASEb/EYzof0OZ/cdrxP4jAOL5I/Ifxuw/Xiee/5gA8cYi8h+ugf4MQvCP0EB/BiL4R1Yq/xd/wd39n6hBJ/zfPAXXd64067+U+w9xP41B9L9RxP5jHMQbjeD3Z/Yfo4n9x3hJHlNc5R/D7D/GEs9/vCHJfcpV/gBm/fkGs/4c55n/IWtk/k/hBmj1+z8q3n+Md+I/KOpPhzD6j3mI8WcCs/8IJPYfMyDeFET+Qcz+I5jYf8yBeNMR+U/UwH/MRfBPcuh//Po/u9zd9f9CL1n/r1Bw/ZPXyf6PNxH9bzLx/Ifoz9MQ/CHE/mMWxJuK4A9l9h9TiP3HbEn+TF3ln8rsP6YR+4+ZkvyZuso/ndl/zPDof7JGpv8VHsHpjvs/ZjLPf8xy4j/U1J8W+xm2At65hv84sUg7//EZYvyZzew/5hD7j/ch3gJE/m8y+4+5xP7jY4j3HiL/eQ78nhooVRv8/k/e2M/FT+H/envJ/m+Egus7XSf7fz5FjD/zNZj//ATB/xax/xTxFiH43yb2nx9CvIUI/neY/ee7xP7zI0l+T13lX8DsPxcS+88PJPk9dZV/kcf/kTWa85u92X5/jucP7zHPf77P7D8/uMJ/tvHyVpz/5fmvxVfxn3bfqaX/XIEYfz5kPv/4I+Lzj7+FeF8j8v+Y+Pzj7yCeEcH/iQN/OVxTDXqEHlAdcCOgBuAGQE3ATYBagJsBtwBqA24F3C5qWAPqAOoB6gLuANwJqA9ooJPPtrpLJ59RK/a53wu4B3Af4H5AY0ATQFPAA4BmgAcBzQEtAA8BWtrOxn0M8IhOrjX9OqAVwBvgA2gNaAtoA2hnq4XSHuAL6Ah4wlabWsy1iPVWYs9NF8DTgK6A7oBugB6AXoCegGcAvQF+gGcBfQF9AP0AzwH6AwYABgKeBwwCvAAYDHgRMATwMuAlwCuAoYBXAa8BhgOGAUYAvgT4A0YCRgFGA8YCxgACAOMAbwDGAwIBEwBBgImAYJ18dnAIYDIgFDAVMAUwDTATMB0wAzALMAcw21YnZr7tvGHu79/i+JKy5Dz5FDhRPTPGmFscGVtSYi3OKbh0frPGZ0NQnd9cBv+eq+DNHMf8AVA8f/oKxpOliPHnU+bzz8Wz0qa211T+04DI/3Ni//kFxPsGwf8Fsf9cBvGWIPi/ZPafi4n953JJzslV/q+Y/efXlWj/F3cjm78bNnisf6D9LOeu/qODJrkk59QO/+64/m8J8/nn3zDXv1nqxP8prcAo/J/4PokFrGb0fzGI8e9b5vlH4Zca2V5T+D8zxAtD5L+Mef5xOfH8YyTEW4fIf4UG+i8awW9wmH+m0n9RCH4jsf5bCfHCEfwmB361TTi3rEi+E/wozu8Wv3qEl/ycA9vGM8/fqdVvFPp/A/SntYj+t5JZ/68i1v8RkhzTVf7VzPp/DfH803pJjukqfxjz+se1zPMP4czzD+sIx3/P+s3/8n89pgX7jwoICQgKRHhAzvff7j+UVpB1nH9KYPQfGYjxx8zsP8R42dj2msJ/pEK8JET+G5j9RwSx/9gM8VIQ+Udq4D/SEfxRGviPLQj+aMLxX8zfuLv+F3OYQv83VTCYBrq5/qfwn3HQnyyI/hdDPP+QBvGSEfyxzP4jjth/bIJ48Yj845n9RwKx/9gI8RIR+Scy+48kZv+RTHj+j7vrf7/A4NAQFfrfr+uwbmOHB47x7zd8ipI9XFVx/sfiZP5D4fEXl/yHeJ75EyCb0X9YEeNPCrP/EH7hFttrCv+RD/FyEflvJF7/VgDxihD8acT+Iwfi5SH4NzGvf7ng4s9VRFP7q4iBOwZwDpCt4PqJbq7f1TYq/1mM6P+biee/MiHedgT/FmL/UQjxtiH405n9Rwax/9gB8bIQ+W9l9h+ZDv6DQ/9kOeQ/AHr9ZPhn6qV7AO+AlKw/ySZ8/qO20eyfaaP4enf3Pz7JW2PN+RZTssLr+3qFwh0QAvdAH0AgWoMp6f85TvS/0k/Qcf5h1zX0v1eUdvr/EGL8y2Xe/7KNeP/LDxBvDyL/7cT6fz/EO4zgzyPW/7sh3j4Efz6z/hd+qea/9x+N/vsRkX8hsf4rhXh7Efw7iPXfAYj3PYLfyqz/igi//9XOv3QGJACmArYquH5SFfdvahuF/j8I/Wknov8XM+v/Emb9X8q8/n0n8/r3XU70n5r66+LzPAP45Sr671/dp6H+O43o/7uZn/8KrXY70fhBsH6qS2hI0OU5FOT17u7fRP3zxH8sllRjqYWDn0L//wH96TdE//+eef3RXmL9/xfE+x2R/z4N9P8pBL/wazfb7z8i/X8Swb+fWP//DPGOIfgPEOv/ExDvKIL/ILP+P+SQP8X+d3EGWjigq4LrJ1dx/c79/UOh//+E/nQE0f9/ZNb/h4nXHx2HeL8i8v+Jef3Rz8zrj44w73/4xYn/oKi//jej/9DrXe9/vzo8f1Y9fpDM37T24mrc469f99zyjXm5WZE7Uo2x5m1/F++Jy7DG5JbvLMsPz92Qb8ktN9n+trAwtzw/PPGM+DuDiYqfw3/+Rjz/cBHinUeMv0eJ5x+84N6rjrj/jhH7j3MQ7wIi/9+Z5x+EX7TXe6LyH9UQ7/9xYv9RBvHKEe//CWL/oYPc/0Hw/+ngP9Tqf7FvTJzRVl2Sz13DthDP83vWxuE//yJefyRB/z+L6P8nmf3HKeb5h9PM8w9nmOcfypzofzX1z8V55guhD9bUX+WHKkD/10V8/5110P80+r2tF1fj1u9R2dlH4va0tcbEZcTtab3NGms2mf26b8wrjI3JadvKFLbT6GNaqyG/2u9vDv3/N7H+vxX6/k2I/n+OWP/fBtx3IPjPE+v/WsB9C4L/H2b9L7RyM9trKv1fD5H/BWL9fwNw10bwXyTW/7cD980IfuFX7fq/ImvNNNJ76g1VNgj/9pTt/O3nFHyZhnr8G2tTq984/J94XkHp/+pAvBsR45+k5/V/4lk9p/+rpuf1f9X1vP6vhv5K/0dRf/6ua/i/23Zp5/8eQPR/oVc49x+Ie5VS/98H8e5G5F9TT6v/G0O8Zgj+Wnpa/d8Q4t2L4L/Jcfy95N+Vzn6qb9z+vahUdvA+3rKF9/GWPbyYk/Px9tXcwFM8fx9iq4EyVsGbyeH/hFdpbntN5f+aIvp/bT2t/7sT4t2D4L9FT+v/7od4jRD8t+p515/dRqz/mkC8Boj8b2fWf3WY9V9dh/ynePwba6N5/t5e8fUc+r8es/6/w4n+V1P/vT7EawdoeRX9b9f9Wur/1ojxrz6z/r+TWP8/DvEeRuTfgFj/e0O8tgj+u4j1/0MQ7zEEf0P99XP+s5DnyWJpXGyRd1p4boopzNtg9DEYWxmMrQ3GNgZjW4OxncHY3mDsYDD6mtaK1XTWYrvOTzmdvconLrtojy/X70+h/0U9wPqSsvpzHPpfePVnbK+p9H8bRP+/h1j/PwjxHkXw30us/30g3iMI/vuY9X9jYv3fCuK1QOR/P7P+b8Ks/x9wyH+qR/+zNhr930Hx9Rz6vymz/m92hf5vS1J/25dR/3dDjH/NmfX/g8T6/ymI1xGRfwti/f80xOuB4G9JrP+fgHhPIvgf0l8/5z9nH0k6bw3f/kdhbPyBxDN+3U3movRZCaWJp0xh4sF+21k+3rNa+Wr3BJ9Cv9trpzdR8GZOU/kBcOh/4dVb2F5T6f/uiP7/CLH+bw/xOiP4HyXW/12EnkTwP8as/x8n1v9dIV4HRP7ezPrfh1n/tyIc/z31o9WffyPXjL4UqVtQoFw+zNXr1X5+HPq/NbP+b+NE/6upvyz09FiAH6P+fxEx/oln1ZznT4m5kga21xT6vz/EexaRf3s97/lDHYj1/yCI1w+Rvy/h+K+2RVtSjkUfyjRtyhNLbayHTGah6KMt6WXZCZu3pR4qOZR4Jml1xl6TOeto/onMU0XpJgOlmqeoHya0+4c6ZfXDpjM/f6PS/y8g+p/wq/YVZ1T6/3kEf0di/d8L4vVF8Hci1v/PQbw+CP7OzPr/SWL9P1DMJyHyf4pZ/z+tpz1/aADE643Iv4tD/lX9/Cu1jU7/9wmYEBAyrFtQaCCmN1KN/xV5/lRXPe/5U930vOdPdXfiPyjqL7/M6D/GIMafHsz+o6fYr2v/XQj8x+sQ71VE/r2Y/cczlUj/F/xQmrnZXHg29aylLDY/t7yi+Sn0vx+8ieu85HX42DaDWf9T+M9R0J+GIfq/n55+//loBH9vB/1L5T/8EfzPEvuPIRDvNQR/H2L/MQLiDUXw92X2H/2I/cdIiPcSIv/+zP5jgIP/8Oh/dY2gfjCr/qfwn8OhP72C6P/P6XnPvx3I7D8GMfuP5534DzX1lwdDvGmAcdfwH40vauc/QhH97wVm//Eisf+YCPEmIPIfTLz+aRLEm4LgH0I8/zEe4gUj+F/S855/JHy67t/7j0Z/TkXk/0ol8n/ezPwXVdafjhD3MLyJp8X7quDNnMns/yj8RwD0pyBE/3uV2H9MhniBCP6hzP7jNWL/EQLx3kDkP4zZf7zOvP5puJ63/vIIB36O+rsjK9H8D3ej2X+hfPsg9/pru/6nqL888yr63677tdT/7yDGv1HM+x/8ifc/zIN4sxH5jybW//Mh3gIE/xhi/T8L4s1F8I9l1v8BGjx/fheR/xuE+7/jorIid+6NOSPP3iguQ6+4qZ2/uQB4BkakkYDBCgbTWW6+f5JC/0+H/vQmov+NI9b/b0G8OQj+8cz6fwKx/n8b4s1A5B/IrP+DmPV/MPP5lxOZ179PIhz/uRuJfrdPwfgFjvJHzuS4+/5Ju/5XU39brKfJBrzPqP+/RIx/k5n1v3heU8f2mkL/fwrxPkTkH0qs/z+DeF8h+KcQ6/8PIN4nCP6pzPp/mgbP/xcj8p/ukD/383e1+n2oTtbvbyvU77Or+PknFPp/EfSnjxH9bwax/v8c4n2E4J/JrP9nEev/LyDee4j8ZzPr/znM+v9NZv0/l1n/z3Pg99RAqdrwYm7dgiaMCCLZP9MzaNKE4Zit85e/aFU0t9+/ZPN/FPXPlzL5v9W27z5Xx7/5zOu/xPPKurbXFP7PAPG+Q3z/v03s/4zI9/8dYv/3LcRbgcj/XQ383ypM/TmHn6Pyf5j3fwHx/oMlEG85Iv+FxPrfBPGWIfgXMev/94j1/0qI9w0i//cd+NVKAHHmQX8vee+TkvXjc5i/QNX67+pe1eJW7dxXLTG2uKjaltLC/Grb98EfcauSD1bI76/2+TeH//vAwf/5Abc/fANPVsivZP29eFZ6t+31IGAfbxuD/Cto/ddHTtbfq6k//TXESwCEX0N/eTc/odnz91jE+PMx8/P3T4jX30RCPDMi/0+J9VcUxItH8H/2v/W/Wil/Cuzu/qnkZGF+xa9audzUPv8WG6YHesn1W4cruJ5Cf6+D/hSB6H+fM8+/iOelNWyvqfR3HCL/L4n1dxjE24DgX0ysv6Mh3noE/1fM+vtrYv0dA/HWIvJfwvz8/RsH/fWmm+tvd28E5wcNCg0OHj9dPj+0fwDSDHDMvyxlnn/5lnn+5Tsn+p+i/nDyVfS/Xfdrqf+zEOPfMubnr8uJ199sgngpiPxXMJ//Y7iO6n+J00Kzo4rykvPiIqxrTebiv6ItxfElZQZTxfBTnB90HvALoLaCN3Ouyg+AQv9nQH9KQ/R/owb6PxPBL54XN7S9ptL/WxH8K4n1fyLE24jgX0Ws/7dAvFQE/2pm/b+GWP+nQ7wkRP5hzPp/rYP+516/VuXn32nrB6D1P8X5P5uhP1kQ/T+c+fyfdczn/5iZz/9Z78R/qKl/LMbTnwHbGP3HLkT/28DsPyKI/ccOiJeHyD/yOqv/9b/6X+xGdSf9L2aKhf5XEmmeyg+Aw39GEa//KYF4hYj+H62B/9iJ4I/RwH+UIvhjif1HDsQrQPDHEfuPIoiXj+CPZ/YfCcT+oxji5SLyT7yO6n+5u/7vNSkoNFiF/rdfr7R+FYf/TCKuf2GFeNsR/T+Z2X9YmP1HCrP/SL3Cf7Qjqb+8l8d/oPPfyOw/xLPamrbXFP7jEMT7AXH/bSJe//Qjcv35ZmL9uQ/iHUTkv4V5/Yt4Xmm/39zd/yXuT4nP+aU03RQm143LTogPE3XjLteMK/whMSPDnF2ww1DwB30daLX+T/iAJYB2kpfXaAVv5nyVHwCB/0CPPxm0/kO3B+IdQNx/W4n9x2GItx/Bn8nsP7KI/cdPEO97RP7ZzPMfOf+lP2X9oab+626IdxLwq5voj1wH/aG2qfV/VP5Haf2sqv79x6E/txHrz+MQ7yhi/NlOrD9PIPVnHrH+/A3i/YHIP9+BvxyueQs68Tu2M1TeBSwELAAsArwPeA/wAeBjW53bjwCfAD4DfAr4HLAY8AXgK0A2YAnga8A3gG8BSwHfAZYDlgFWAIwAA8AEWAVYCVgNWAtYAwgDhAPMor4WYD0gArABEAmIBkQBYgD/ae88AKMqnj9+gTR6rxY6AlJSqAoIhC5NuqiEAIFEIImQUBQQEewFRUXFAoROEAIJEELoNbSQhNCr9KL0Dv6/m9zB8+flH+a9OSYXbvVrDuHNMHd7+z4zu283GoqClkDLoKVQDBQLLYdWQKugOGgltBpaC62B1kEboPXQRmgLtAmKh+5C26Ct0HZoJ7QDUqN4IrQLSoJ2Q8lQCrQP2gPthfZDB6ED0CHoCHQYOgodh45Bf0InoRPQKegMdBo6C52HzkEXoL+hi9Bf0CXoCnQZuqr2n4euQTegW9BN6DZ0D7oD3YdqgDH/wc8HkBNeZ88mk3/s1OQfEvyZwMyfp2HvIuH7t4uZPy/D3gWC/0QNfxptHPnPPjWOoi8G6LiZfmjn69e5+Efv+T0S+UcSc/5xBfbOEPp/snD+sdtK/sFx/uuNDPKPRm0zR/6RIlz/3MPMn/dg7xah/+1l5s/7RP7cl4XWf2SF+t9+UxrH+ep4M8dlgvXfN9Gf7hL6/37h+vcBYf48yMyf12DvDuH9P8TMnw9g7zbB/2Hh+ucRZv74B/auE+I/KswfxzT8YbRlFv7Ve37N037/s/CnkfM/VW3hrovJlD2dh8os3JlZ+PO4MH/+ycyfOfC+uzg//vhzgpk/czrT+PMkc/3TGcbcCfGfEuaP08L8cYbx+U+j/Psc9JUprZ7aSsdgOt7O6z8s51d4eeq+noM/ndCZ3Ajfv7PM/JkLxlwJ/s8J8+d5Zv7MDWPZCPFfEObPi1bqXxznD+aX4Y9U/yUJ7/9fwvuf/c28/1lRxF6QEP8lZv4oBmPPEvxfZuaPAjBWhOD/ijB/qLUqz5t4WmZ4/ktlPQkbVNazbN2jvGfjtaR1tvdvlH/eNaWxYGO8kY10XP+R/Pq/1P73DKH/X2N+/igvjBUm+L/OzB/FYawQwf8NYf64ycwfJWAsHyH+W8L8cVv4/JE7wvtf3c1Cz39JN7792zoFD9bxNTD6+Unsf3bPyvM/Rs4fzANj1aHSgvxfjTD+3ReuP6r5mrzm1xz8XxGxlyXE/4/w/mfKOSf/V4GxCoT4nZz5+b8qwb+qFVS39AXHGUhPtaTzt6QNOzcvill2S+3ZtyRpx9nw2VsXJ1wJXx6VFL1/6/q4aUuSouOi9yfGqlf8qzd49u+oijcxCHpFx5v5sfD5k1z534uE8Se7M2/+9zyMlSf4d3bmzf8qwVg5gn81VyeZ/7k68+Z/lWGsFCF+N2fZ/E/NFXLuP/AC7JUhxJ/DWXb/gZwa/479OwyOn8bzv47+IX6Bg327+Qd2CH7i75/E/hO5nGX3n8jt/N/8k+P8Q88M8s8OobbLPxsSxh+VL0vmn6pem8/8miP/rAN73oT48znL5p/5mfPPl2GsNiH+As589T+jTc3fJO5aOT8pYff95P2bz296EL1e7eKXcHhZ1I5pGzdGr7etfw7+T4SqOKXt4UdtnwjzP1f9oQGh/6m54rLm11z5R32C/0LM+UcNGKtF8F+YOf+oB2M1Cf6LCOcfRZnzj5dgzIMQfzHh/KM4c/5RF/a8CPGXcPA/W+NZv+cl9veXyD9LOsvuf/eMcP7xrJX8w8j5n8/BWC+oSTr5hyXvsGX+0YYw/qi/r+T6N1Uv5Fz/1hL2mhLiL8Wbfzi1grF2BP+lMxH/75mWeDx8eUqs4n1LnV/lBDFRu6aqPODfv5OWEcRNi4rg8m+U/32h86a0vUZu67j+U+EPgCP/9EFnakHof2WcZdc/qrlqy3lrXPlHW0L85Zjzj0Yw1pzgvzxz/tEaxpoR/FcQzj8qMucfr8JYY0L8LwjnH5U0+Ydj/Zbh+r1PgF9Qf/92fkNH+HYL8A8y1/Mf83rp508l+Leys+z6xyrOsud/vmiF/znO/+woyP++hPGvqvD8g1qrV8L8moP/u8NeZ0L81YXnH2owzz+8CWPdCPF72ID/ehL8e1rlL2P89xbBvxcz/3WAsa4E/97OfM//qhkbk2Azmr+9DPWCPofe0XH9l8LzN0b5jYP/e6AzdSH0v5rC/F+Lmf/fgLHXCPHXFub/OszzD6/DXidC/HWF1z/VE64/vyRcf37ZOeuc/2202SD/8wkO6hsYGhgc5Ovh65XRuTbS+Z8l/zBy/md7dKZ3oD6C+UcIYfypL5x/qLUSZcyvOfKPQNjzJ8TfUDj/eIU5/xgEYwGE+BvZIP8IJvhXtcK8D79/PPlHEMF/E8bxf2P46u3LL6xZXMmjmpdHZdMTbxz8PxJaDH2p4/qv7Jz/OfJPP3Sm/oT+58M8/zAAxvoR/DcVzj+aMecfA2GsNyH+5sL5Rwvm/ONt2OtLiL+lcP7RSjj/aO3g/4eNZ/1WTd3XP43zP6/+Z/6jDsv5n6HpdOpek9PyDstP7e9x5R+jCeNPG+H1T22Z1z+9C3tDCfG3Y17/9B6MjSH4b8+cf4TB2AiC/w7C619UrbIw0/gZH5O0LjF551q1JivuVkLCsnuxsaYn2Izyv9o58zdoK/SHjusnZBn+N5Z/vk/o/x2Z578Gw9hwgv9OzPnHSBgbRvDfWTj/6MKcf4yCsSGE+LsK5x/dnGX3/+ouvP7ldUb+l25c5wfo3X/K3s8PkFj/1MMK/xs5f1fVk1dC42T4nxz/G8LzD2q9Duf5A5/B3keE8f8tZv7/nHj+QE9m/h8PY58S4vcV5v9eGv+r5i6dJjn+GOX3GiZVQzOZiqizV3VcP9HO+d1o/Uri/Ak/Xv53GgtjnxC+f72Z+f8LGPuY4L+PMP/3Zeb/L2HsQ0L8/sL838/5f88fqMNy/uY3gvXHyYT3v79w/TGAuf44CfYmEuIPZOaPH2HsV4L/t5n541sY+4Hgf4D2+586f6F39yP7z39S9i6LitoRfz98uYx/o/zjAwVBY0xp6xioTYI/1Xx1zod/f5764y+E/j+Iuf74NYx9T/AfxMwfP8HYdwT/wcL8EcLMHz/D2ARC/O8I88dg4frjEE3839l5/mPvrVVQSFiogfplqya+Tf2HqmdO/f1CfYLDgogdSKL+HCr8/GWYlfqjkfNPv4KxP6CpGfB/yFrb8f88wvg3VLj+qObKCppfc/D/LNgLJ8Q/nJn/Z8NYBMH/CGb+nwZjMwn+32Xc/0Wa3z2E/T/ukRPptbGQqt/NhUbruP57gx+ABP+r9TqWvzYX/88n9P+RzPz/O4zNIPgfxcz/c2BsOsH/aGH+f5+Z/+fC2BRC/GOE+f8DYf4fq4nfcQaK4/wXI81o/pbNZN+NZ/14Hd3XG/38OuCuNwT/DEu9B9KfwNCTf32oGX/aIv8biFEvEHeCQIx/VAbXM/6Ns5L/cZw/HZlO/mfJ+2yZ/8US7n/jhed/PmKe/1kKe4sJ8X/MnP8tg7E4gv9PmPO/RTC2hOD/08y0//+KNTul5l5UMzr/0hyaBA2CZui4/ocssv8/5fuv1ou5ml9z5X8rCP3/c+b8bwGMRRP8f8Gc/8XAWBTB/5fC+d9XzPnfchhbSIj/a+H8b4Jw/vdNJtr/X7oxzb+0D9SZBEjXXyXmf74Vnv+ZaIX/jZw//RuMHYbWCPL/VsL4953w/M/3mvUfHPy/CfbWEeL/gZn/N8PYNoL/Scz8vxbGNhL8/8j4/I+n8ASM0fmXENUfzZql4/pJdr5+QoL/1XolS92Pi/+3E/r/z8z8vwrGNhD8T2bm/y0wtp7g/xdh/v+Vmf/jYWw1If7fhPn/d2H+n6KJ31F/V/X3urqvt/f1ExL1/6nC9f9pVvif4/zfXRnw/5iztuP/A4TxL1y4/j+duf6/B/aSCPHPYOb/vTB2iOB/JjP/J8JYCsH/LOHnT2fboP57kBD/HGb+2wljuwn+5zLz3z4YSyb4n6fhv+gFiXPsff5liSlt/kXPUdE/PuXr3yX4P4KZ//fDWAKh/88X5v8/hPl/gfD+MwuF67+RVvjPyPmrO2DsL+hYOvxn4T5b8t95Qv9fpKn/Sjem+ZfGgwYF67re3vM3o/VXCf5Xa3VymV9z8P9p2PuT0P+jmPn/DIxdIPiPZub/4zB2iuB/iTD/L7VB/fciIf5lzPx/BMZOEvzHMPP/WRg7QfC/XMP/RhvH/EuUKW3+ZaOO63+yc36Xrr9K8H8sM/+fg7GjhP6/Qpj/44T5f6Umfon67yrh+u9qK/zPcf7qZUH+v0vo/2s09V+jjWf+pZ7u6+2d35elLFovWX+T4P+1zPX/m7B3ldD/1zHz/y0Yu0/wv56Z/6/A2A2C/w3C/L/RBvX/e4T4NzHz/98wdp3gfzMz/9+GsWsE/1s0/G+0/r7UlPb8w2GTvucffnbsPyPaJPg/npn/78DYJUL/3yrM/9uE+X+7cP1/h3D9f6cV/jdy/ql6nn8kgNopHai2cP+E/Jdtxv+5XB6//ydo6v9M9fdOof760oCnvf5utBmtv0nwv1onldv8moP/3dD3sxP6fyIz/7vDd26C/yRm/s8G364E/8nC/L/bBvX/PIT4U5j5/x9VTyH438PM/zng25ngf6+G/w+Z0mrv2Zz0Pf8w2VF/F21G628S/L+Pmf9zKu4i9P/9wvx/QJj/DwrX/w8J1/8P/4f/67KcP1ogHf63cL8t+f8ZQv8/Irz++yhz/bcYgilEiP8YM/8Vh+/nCP6PM/NfQfguSvD/5//u/++tP4mx9/xt7RrJ2Ree+qta/6zqr3rWP0vw/wmr/G2M/58l9P+TzPyfD76LEPyfYub/EvBdmOD/tPDzn2eY+a8kYs9PiP+sMP+dE+a/85r4f3HMv4g2pvprm6E6r5eo/18Qrv9ftML/Rs4fzYuxpzpUJgP+n1LHdvz/ImH8+0t4/5e/mc8ffQGxlyPEf4mZ/yvBd1WC/8vM/F8WvisS/F/JQvv/2/v8i6q/qvXPqv6qZ/3zr3a4//9VG9T/qxH6/zVm/i8F3xUI/q8z839l+C5P8H9DmP9vMvN/FcRemhD/LWH+vy3M/3cYx/+nff7FJ8C/zwAD/O7TxLdxWGhwc78+ocGD6bd/u9z//a5w/f+eFf7nOP/XMx3+t3D/wp624/+GhPHvvjD/P3BW9420xsH/dRC7NyH+f3j5nxy/mnzh5P+XYa82IX4nF8f5Lw7xnP9itO1JXrIgZvriWVL+jc6/lISqmtLOXm6i4/rfssj+/w0I449ar2a5/3Dlf/UJ/rO78OZ/NWCvFsG/swtv/lcP9moS/Ku1apL5n6sLb/73Eux5EOJ3c5HN/9R60foP+19Aag8YgP/21eFf1R/rwp4XIf4cLpln/3/p+4/R1mJwcFiIgfzPcr3e/SeNvn/38flnQxLuDLlCLpAblBNyh3JAuaA8UG4oL5QfygcVgApBBaHCUFGoCFQMKgEVh0pCz0LPQM9BpaHnoVJQGagcVBYqD1WEKkAvQJWhSlAVqCr0IlQN8oCqQ55Qb8gb8oJqQrWhWlAd6CWoLlQPehlqANWHGkKNoFegxpAP1ARqCjWHmkEtoFZQS6g11AZ6FWoLtYfaQR2gTtBrUEeoM9QV6gJ1g16HukM9oDehN6C3IF+oJ9QL6gP5QX2hH6B+kD/UHwqEAqC3oYHQAGgQFAIFQcHQO9AQaDAUCg2FwqBh0AhoOPQuNBJ6DxoFvQ+Nhj6APsz26P7fMbUKFfBE6k85NeNPJ3gcoTv7U/k33X8uF+3845Ovv+V2+W/9wcj548/D3ptQk3TqD5a6w+rxNqk/kOPP4yJbf1DztZzzjy1hrynh/pvPhXf+sZXZ9+P6z++Sec5/i5udfEHSv9H8z9NJjWFp97wUHdf/Lpz/cdSffNCfWhD6fwEX2eePCrqwrj8kjz+FePNPp0aw15zw/hdmzj9bw14zgv8iwvlnUeb881XYa0yIv5hw/llck38azf9Y9v/x9tR9vb2vX0nZuywqakf8falV6Bb+5Dj/uH06/GnhThvxZ6r/1wnfP7VeWvL5F7VemfP5ly6w9xoh/meY+bMr7L1B8P8s8/xXB9jrTPD/nDB/qHwt58PvH0/9uwch/lLM9e+2sNeJ4L80M390g72OBP9lhPmjLDN/dIe9doT4y2n8G81/mmE0D8LPsU5pc2DUNsXx/IFok+DP8i6y698quMjuf1TRRfb5hxes1B+NnH/bBvYGQr6C/BdIGP8qCdcf1Xrdwpbxk4H//GHPjxB/Fc3nz/D8UZOwwIF9fTv6h/j7hfoEhwWRvsL2nr8JP35g+PkDDv7vh/70NqH/vcjM/71gry/Bf1Vh/lfPKlj6LRf/DyDEX52Z/9+CvT4E/zWY+b8/7PUm+PcQ5n9PZv4PgL2ehPi9NP7HoSOq+l0Efo7W4X+qY/8n0Wa0/irB/97C/F/TRXb/o1ouss8/1LbC/xzn3wZnwP8JEbbj/xGE8a+OcP23LnP9Nwz23iHEX8/lf/f/8dIdv73z++YVa3ba8/mnLZ3S9l8PdtK3/zoH/w9Ff3qP0P9eYub/ENgLJfh/WZj/1Vp17vMP3iXE34CZ/wfB3hCC/4bM/D8M9gYT/L8izP+NmPl/OOwFEeJvrPE/zVF/F21s9bf2gbrSAAn+byLM/z7C9f+mwvX/Zlb438j5x2o8XQG9nw7/W7jflvz/KWH8ay5c/1drJTn3vx8Pex8Q4m/pknX2//G28/1/Bjul7b8+Sef+6+EGPwAO/v8I/ekzQv9rxcz/Y2BvHMF/a2H+V+tFufc/+pwQfxtm/h8Fex8S/Ldl5v+PYW8swX87Yf5vz8z/n8DeaEL8HVwc+/9wNZ71z966rzf6+Unw/2vC/N9RuP7fSbj+39kK/3Ocf/x1Bvx/NMl2/P8TYfzrIlz/78pc//8e9r4hxN+Nef33D7A3meC/OzP/TYC97wj+Xxfmvx42qP/+TIj/jUz0/Gf0gsQ59j7/os5fUPMves5fmC5cf+Xg/y/RnyYS+t+bzPw/Cfa+Jfh/S5j/ezLz/4+w9xUhfl/h5w97CfOfn3D9t7dw/bdPJtr/R7qxzb80HjQoWMf10vVXC/8bOf/4C/SnCOj3dPjfwv2X7tiO/+cQxr++wvV/tV4/j/k1B//PgL2phPj7MfP/TNibS/Dfn5n/p8DedIL/AGH+D7RB/XceIf63NfEbbVlh/kWdvzBJ5/kLM+x8/QQH//+K/hRO6H8DmPl/FuxNI/gfKMz/g5j5fzbs/UaIP0iY/4OF+T9EuP77jnD9d7DGv2P+Rc2/1NR9vb2vn0jj/3os5x8vSIf/LdxvS/6PIYx/Q4Tr/6HM9f9o2IskxB/GzP9LYC+W4H8oM/8vhL0ogv9hwvw/3Ab1/+WE+Edo4l+Wsmi9PdffY8zPPxzV+fzDzKd8/TMH/89Hf1pM6H/vMvP/UthbRPD/njD/j2Tm/2Ww9wch/lHC/D9amP/fF67/jxGu/3/wFJ7/E2teo56Z/44n8Pc7+YT/jibhxjb/0inUX08i+LSvf7fkf0bOv/4FffYgtCqD/M9U9orN8r8thPvfWOH5H7VWmvP8uw2wt4YQ/zjm/G8j7MUT/I9nzv9Ww956gv+PhPO/j20w/7OVEP8njPM/Rm8hR8zPv6jzZ/Q8/zLLsf+MocaR/8WhP60j9L9PmfO/TbC3luD/M+H873Pm/G8z7K0kxP+FcP73pXD+95Xw/M/XwvM/ExjHf575l1q6r7d3fl+7RrL6+oj/Oc6/3pkO/z/kfhvy/z7C+PeN8PzPt8zzP7thbxch/onM/J8CewcI/r9j5v8E2Esm+P9emP9/4D1/KNX/fkL8k5if/90Oe0kE/z8y898e2Esk+P9JmP9+Zua/vbC3gxD/ZMb9/2PMz78c1fn8y2zH/kOiTYL/fxHm/1+F539+E57/+f0/z//WM3T+6DbYuwAdyYD/8reyHf+dJYx/U4Trv2qtfi7zaw7+U3NGxwjxT7PF/v9thuq63rH/kLGWGfb/P4X+dI7Q/8KZ+f8o7J0g+J8uzP8zbFD/P0+IfyYz/x+CvT8J/mcx8/9p2DtO8D9bmP/nMPP/Gdg7TIh/rsb/EfPzL2r+Rc/zL3Mc8y+irU3gECO3bxH+nyfM/xHC9f/5wvX/P6zwP8f5r3+nw/8W7rcV/98xj32PG/8CTf1Vgv8XatZ/c/D/ddi7TBj/I7X3nya+Tf2H6g7f7vndaDPK3zXMb8I6/Gik482Ymwn2/7xB/P4tYub/S7B3jdD/F9uA/28T/GvXXXLxP+X9j2Lm/4uwd5UQfzQz/9+EvSsE/0uE+X8pM//fgr2/CPEvy0T7f+Y25fL0qFov9V9vj1xeHlW91Av1Gv+/lkdVT/VvLk/zC/xuHvXfWp6Q+h+58cdrp/2mp0eetMvV70D4g+ZL1I986ldp16Uql8Ue/s1tNu+VajHtF96pVz3O+G/oBtAkLDQ0OMjA9aFB6gbu27hvX13XS/B/jIb/W8G3PwhsiE7/uXX4V8/K/W5+3QneB5rHIP8nxP9xVvjbyPm7D2DsbwDlAxn+Jse/UsO/Evy9irn+7qyCcX38sWA17/oLcvxrstD+/9surkiKjpPzb3T+fJ/5TSwCldDxZs4z+AFw8LcL+n52Qv9fK1x/X8f7/DX5+7eel7+d7qn5BML7v4GZv13h24ngfyMvfzu5K98E/t3EzN9u8H+f4H+z8PrrLRr+svf1M1z83NF/UPBQHTdge79/dgB7DE9lYH0Erif/jbfCvxznz+Z2tf5nLNxbOiRz8O9WYf7dxvz8YUEEk5cw/m8X5t8dzPXHQoi9ACH+ncL8k6Dxn7hx8X3J8YeDnyuY+bmhjsE0wrH/yxPn313M/JsT3738hO9fIjP/FobvfAT/Scz8WxS+8xD8JzPzbxH4zkXwv1uYf1M0/CvBP3us8I+R8zdz4L2vCJVMh38s3GMj/nGq4Eqb/9srPP++T7P+l4N/SiP+Zwn9fz/z81dliO//Ae333+D6oTbm9b96r3esHzC2fsDTKe1N2OCkb/0AB/8+g/5XitD/D9qAf8u72s/8+yHm+ffiiP15QvyHmfmnLHw/R/B/RHj+/Sgz/5RD7CUI8R8T5p/jGv6Zb+f5T25TLm/zggH8m0dN/XunTfl7e+T1qpP2/yFP8y891R+oo1YW/PvP5qmZ+qNq7bQra6bO/j/8pXfab6b9mYe/VL+J/5VP/W9lpRZUR/12rUd/uhbc1kp1b3b03/FfdP2AxPy7elYg0vxaYv79lBX+5jj/srIMf5PjPy1cfzzDfP5NDQTzImH8PStcfzzHXH/0QOzVCfGf1/hX8x/mA6x0rSByrB8w1ozWPw+Y+b9YNn3rByTqzxeE598vMtcfX0Aw1Qjfv7+Y+dsTvqsS/P/NXH/0hu8qBP+XmPnbC74rEfxfFubvK8L1x6ua+P94yuc/ONYPpN0/9a0gyBznP9YzdP5jMXz3OkJ1MuBfj0mZg3+vCfPvdc34y8G/DRBMPcL4d0OYf28y829DxF6fEP8t4fn327z7f5Hf/zuM+z/a+/oBxc8VzPysZ/3AAsf5j0618N17mfD9u8vMv6/A90sE//eY+bcxfNcl+L/PzL+N4Ls2Zf5DmH//EeZfdfP/d/3P0+Sh8wS8vJr6X7N0+MfCPTbin1T/7Qmfv1qrbXlU6Gk5/yUj+bg+ne+FwdsP0/7PtXVfb+/1x1Vzl06LmRcfF75884o1O6tGL0icU1WdyVd17Zon4l8i/1HPqnDuf/wq7LUgjH/ZXXnX37SBvdcI/p1defOf5rDXmuDfxVU2/1HPCz1jfs21/qIDIX43V971F+re0Yrg392Vl3/bwl5Lgn+1XtDCv0bzJ7V/yRmoMgbSmzquX+jY/1e0Say/yenKm/+0g72mhP6fy1U2/1HPKUnuf5bHVXb/47yusvsf57Oa/+k7AU/lf01grzfUJYP8r9FK2+V/voT+n1+T//Hwex3d19s7v8fNTr6Qxu8y/o3evyX4vwAz/78Be90I/b8gM/+/CXt+BP+FmPm/K+z1IPgvLMz/6nmhnObXXPzfixB/UWb+7wR7rxP8F2Pm/7dgrzvBf3EN/6vnBxS/v6+T3yMd/C7ajN6/Jfi/BDP/94S9zoT+X1KY/58R5v9nhfn/OWH+f94q/+s7AU87/+OfDv9buN+W/B9M6P+lXGXPvyvNzH8DYK8/If4yzPw3EPbeIfgvy8x//WDvbYL/ctrxNzV/0/v0g/3nb1vnxd5ckxB5cdWV9fs3HwqPSImMS4qPSVqncrr4+ysP2dq/0fxNVS1a4E08j59d7GT9t3pWs7T5NRf/hxD6fwVm/u8De4EE/xWZ+X8Q7AUQ/L/gKvv8ZSVm/guCvb6E+CsL818VYf57URP/Ikf+Jtp46q/1dF8vwf9Vhfm/mlX+13cCouL/mrC3AAoT5P/3CeNfdWH+r8HM/+/B3jBC/B7M/D8S9j4g+Pdk5v+hsPcuwb+XK9/6b2l+375xxY11qzbv3rxjx+X4SEXuU8OfpH+j/F4S6ok38Vv8HKTjzVxs8AOQ4H/1vGBh82su/h9D6P81mfl/COyNIPivxcz/o2BvOMF/bWH+r8PM/6NhL5QQf11h/q8nzP8vuWae81/svbHwe025Q4Ql+P9lYf6vb5X/9Z2AqK3/j8+A/zuctB3/f00Y/xoI839DZv7/HPY+JsT/CjP/fwF73xD8N2Lm/49g7zOC/8aM47/RtuJW0v49yUsWxExfPCtm5vqDi2IXhyetC49YtypqR9yGyJUpexPWJm9NSIiPDI+IPZb6J/dG7g6PiDy47viOq1Ezlk6zXC3z9+fg/8H4EPJnM5nG6PgwouyQ/9V6ydbm11z8P4HQ/5sy8/+HsPcpwX8zZv7/EvY+IfhvLsz/LZj5/yvYG0eIv6Uw/7cS5v/WDv5nay0GB4eFGNhA2XK93hXURj+/+/j8xuLeMw76CBoPfQx9Bn0CfQp9Dn0JfQF9BU2Avoa+gSZC30LfQZOg76EfoXhoMvQT9DP0C/Qb9Cv0OzQVmgJNg6ZD4dAMaBY0E5oNzYPmQHOhCOgPaD60AIqEFkKLoChoMRQNLYWWQMugWCgGWg6tgFZCcdAqaA20GloLrYfWQRugTdBGaDO0FdoCbYPuQzug7dBOKBFKgHZBSdBuKBlKgfZCe6B90AFoP3QQOgwdgo5Ax6Cj0HHoBPQndBI6DZ2CzkDnobPQOegC9Bd0Efobugxdgq5A16Cr0HXoJnQDugXdgW5Dd6EH0D3oH8gru8mUHXLKLpP/vSqc/7Wxmv/pO4FT5X9jYe936Pt08j9L3mej/I8cv3pe0LL/vUT+p57XymF+zZH/TYa9SYT7f3vm/O8X4v77HZjzvx9g72dC/K9lovwvOjIxeefaPVHbIpZO23JHZXnL7sXGxk2Lingy/o3mb9VT+3Da/kGT9cQvvP5CIv9Te8WVNL+W2P+qE2/+5zQR9n4ifP86M+d/v8LejwT/XYTzv67M+d9vsPcdIf5uwvlfd03+94g/9O2Boq0/T9PBH0bzt1ZBIWFGDpBp1cTXJ8AvqL9/O7+hI3QswXGcH2NsCx+u+YcIwvfvdWH+VM9Kcp5/ORv2phPif4OZP+fA3nyC/zeZ+TMc9mYR/L8l/PypLc7/+YMQf0/m+vMU2JtJ8O/LzB9zYW8GwX8vYf7wY+aPebA3lRB/b2H+6KPhD3XjToTuQKd1+F/qWD8u2oyuP5GYf+ir6f8dMOoNwT/DUsfAJ3P+j7/Gf1tTGN6BULwHbaAg8j1YT/z9rNYf9c0AKP7/FvZ2Qotk6o+p978VhPGvv/D6kwDm9SfLYC+KEH8gM//FwN5Kgv+3//f5Ty99zz48HGgNNOn8y3v5hqiIHbFS2/cYrj82gFKgYdAJHddz8P9i9KelhP43QJj/B2rmH7j4P44Q/yBm/l8Ie0sI/oOY+X857EUT/AcL838IM//Hwl4kIf53hPl/sIb/lzn4XbSx1k91TGFL8P8Q4f1nQoXXH4RZ5X99e3Bo6/9rM+D/Xrmv2oz/txHGv6HC9d9hzPXfzbC3nhD/cGb+3wJ72wn+RzDO/z/t8ydq4L5sSqufuep4M2KE778c/L8O/WkTof+9mwXr/zsI8b/HzP+rYW8jwf9IZv6Ph70NBP+jhPl/NDP/b4W9NYT43xfm/zEa/nec/fN0yzF/wvD8rlct3ddL85dE/veB8PzPWOH5nw+t5n/69nBS+d8q2DsCJaaT/1nyPlvmfwcJ979xwvM/45nnf/bCXjIh/o+Y8799sHeY4P9j5vU/SbC3h+D/E2H+/9QG9f9DhPg/Y+b/BNhLIfj/nHH/p1pZYP7suilt/iy7jpvpcjuvn3Pkf/vRn3YT+t8Xwvnfl8z53wHY20WI/yvh/O9r4eePJwjX/78Rrv9/a4X/PBnOHz6eAf+FeP+X/+y9sc6f6TgCwN7r51z8f4Ew/k0Unv/5jnn+5wzsnSDE/z0z/5+FvYsE/z8w8/+fsHea4H9SFqz//0WI/0dm/j8Ke6cI/n9i5H+j82fq3KlF+Pms2ntBx/WxjvUrhhoH/59DfzpJ6H8/C/P/ZGb+Pw97xwjx/yLM/78K8/9vwvXf34Xrv1Os8r/+82fVer7BbibTlXT438L9tuB/nv1PPXVfb+/87SVcP+Pi/3uE8W+qcP1/GnP9/xbsXSPEH87M/7dh7wHB/3Rm/r8KezcJ/mcI8/9MG9T/7xPin8XM/5dg7wbB/2yNf6P186YYQJfg52j8XK/j+hUOfhdtHPx/B/3pOqH/zRHm/7nM/H8X9i4T4p8nzP8Rwvw/X7j+/4dw/X+BVf43fv5sNjfrf+b/438u/svt9vj9f6Fw/TeSuf7rjtidCfEvYua/HPCdh+B/scY/6/yJjiMUHM8fGK+fqv07VP1Uz/4dHPyfHX3PjdD/orJg/T8vIf5oZv5Xyawrwf8S5vX/OeHbheB/qTD/LWPmv1yI3YkQf4ww/y3X8F+cI/8SbTz1Uy/d10vwf6xw/X+FcP0/zir/6z9/9h/YK4Xxp2A6/D+mRxr3W35qf4+L/58ljH8rheu/q5jrv8VhrDAh/tXM/F8Cvp8n+F+ThZ7/rWnn649V/VTt36Pqp3r271lp8APg4P9C6HvFCP1vrTD/r7NB/f85Qvzrmfk/P3wXJfjfwMz/JeG7CMH/RmH+38TM/88g9gKE+DcL8/8WDf87+N1YY62f6dgC3h6f/4wXrv9vFa7/b7PK/8bPny0ryP9VCePfduH6/w7m+n8lxF6eEP9OZv6vDN/VCP4TMtH5P0YbR/1c7d+j6ud69u9ZlQWe/zPK/+XQ914g9L9dWbD+X50QfyIz/5eG74oE/0nM/F8FvisQ/CcL8/9uZv5/EbGXIcSfIsz/e4TXf+wVrv/uE67/7rfKf/rPn8yHvtcB8sqA/yZ8kPWe/+SZP3l69z/n4v/6hPHvgHD9/yBz/b8ujNUkxH+Imf/rwXdDgv/DzOu/veG7DsH/EWH+O2qD+m8DQvzHmPnPA75rE/wf1/ivnQXmT9T+LWr+RM/+Lauf8vUPHPz/EvpeLUL/+1OY/08w8//LiN2TEP9JYf4/Jcz/p4Xrv2eE679nrfK/8fNfm6TD/xbunzI78/G/T4B/nwEG5k98tPMnvt0C/IN8m/p1CH7s6+2d36Oubtxo5Hou/m9PGP/OCdf/1fP6xcyvOfi/JWJvSoj/Ai//k+O/yMz/bRB7C0L8f9mA/9sR/P9tlb+N8X9bgv9LzPzfCL6bE/xfZtz/xSi/x0B+UA4MpHoIcM1Tzu8c5z8Y5f/W6HvNCP3vijD/X2Xm/1cRe2NC/NeE+f+6hv99TAGpPWAA/ttXh39Vf2qF2H0I8d+wMv53TM1CAp5I/nFT478TPI7Qffc3mXLr8H/rX/nHk8+/bjOO/0abDfi/R0BwUP/HTQHsnf9TEozx/6P8U//5w6/gu+8HdUon/7TkndbyT678oxdh/LkjnH+o/QJKml9z5B+vI/YuhPjvCecf95nzj7cQe3dC/A9skH/4Evz/Y4P8oyfBv5r8svh3nIHzdMvo/cdo/lfHKS3/+1hn/rfWkf8Zahz1h9cwnnQjjD9Obrzrz96Ava4E/2qfFMn8M7sbb/75Jux1JMTv7Cabf6q9Ajjzzx6w15kQv6ubbP7p5iabf7q7Zen8r3ugX/BjzwDZe/6XMNVY/idRf8jhZm3+0/j5130F8893COOP2i9FMv9U+5WUML/myD/fhr1+hPhzu8nmn3ncePPPINgLJMSf140//wwh+M/nxp9/BhP853fjnf/qDXsBBP8FmPlzIOz1J/gvKMyfhdwyz/xfNEbj3vjpks2EcYDe1jnyP0ONI/8YhP7Uh9D/CwvnH0WY848BsOdPiL+ocP5RTDj/KO4mO/9Vwip/6j9/twbsXYPCMuDPhTttx59jCf2vpIY/pZsN8j+f4KC+gaGBwUG+Xh6+3h62HT+l87+N4au3L968ZnElL49q3h6VyddL5B9qv5Sy5tcc+cd7sDeM0P+fFc4/nmPOP96HvXcJ8T9vg/zjA4J/tVddPsv3lyn/GEPwX5o5/xgCeyMI/ssw5x+jYG84wX9ZTf5htHGs/3sP8sRA+oWO69c7+N9Qk8g/yzHPf4yGvVBC/y8vnH9UYM4/RsLeUEL8FYXzjxeE849KwvlHZSv5hxfD+c8fpZN/WPIOa/mHdLMp/3t7+NbM4vwfuxHs7+1RraYO9k/7/vPknxMJ408V4fmPF5nzjy9g7xNC/FWF849qzPnHBNj7nBB/dRvkH98S/Kt6TS7L+MGUf3xD8O/BnH+Mg73PCP49M1H9X63/Uvz/uU7+3+Dgf0ONI//8Cv3pU0L/8xKe//Jmzj++hr3xhPhrCucftZjzjy9h72NC/LWF8486wvlHXeH8o14mWv/Fs39XTd3X2zv/R0duWmhk855H+af+88c/RH+aDk3KIP9cfcN2819TCeOP2q9Gcv8xtV8M5/5jv8LYT4T46/PmH06/wV44wX8D5vzjR9j7heC/oZvs/mPqeTnXh98/nvxjGiH+RpmI/++rMQwqr/P86I2O88sMNY7883v0p8mE/teYef7rd9j7meC/iXD+4cOcf0yBvR8I8TcVzj+aucnuP9bcTXb/sRZusvuPtWQc/3n4vZbu6592fjfaHvG/8fPHZ6XD/xbutyX/RxLGv1bC/N+amf/nw9gcQvyvMvP/H7C3mOC/DTP/z4a9CIL/tsL8384G/L+IEH975vmHGbA3j+C/AzP/LYC9uQT/rwnzX0dm/lsIezMJ8XfS+OfI33ab0vI3PedXbnLkb6JNgv87C/N/F2H+7yrM/92srj/Sf/70d7CXDC0V5L81hPGvuzD/vc7Mf3EwFkOIv4f2/sOSv9XWfb0jfzPWjN6/Ofh/JfrTOkL/e4OZ/5fB3gqC/zeF+f8tG/D/WkL8PZn5Pxr2Ygn+fZn5fxXsLSf47yXM/37M/L8a9pYQ4u+t8a/4/Zopjd/1nJ+y2cHvos3o/VuC//sI839fYf73F+b/flb53/j505sy4P+E567ZjP93Eca//sL8H8DM/9thbAsh/sD/5f+adXTH7+B3Y80ov5fOlrZ+okU2fesnOPh/B/pTEqH/vc3M/5thbxvB/wBh/h9oA/5PJMQ/iJn/N8DeVoL/IGb+3wl78QT/wcL8H8LM/wmwt5EQ/zsa/1sc/C7aeOpvdXVfL8H/g4X5f4gw/4cK83+YVf7Xf/74etg7Ae1Jh/8t3G9L/j9GGP+GCvP/MGb+PwRj+wjxD9d8/g5+N9Y4+F3Nnyt+1zN/Hm/wA+Dg/8PoT38S+t8IZv7fC3sHCf7fFeb/92zA/8cJ8Y9k5v/dsHeA4H8UM/8fgb39BP+jhfn/fWb+Pwp7KYT4xzjOf3HILEf+Zqzx5G/1dF9v9POTyP8+EM7/xgrnfx8K53/jtPO/uCZbdvwacoVcIDcoB+QO5YRyQ7mgPFA+KC+UHyoIFYAKQUWgwlBRqDhUDCoBPQuVhJ6BnoNKQc9DpaGyUBmoHFQBKg9VhCpBL0CVoRehKlBVqDpUDaoBeUMekCdUM3vafaw2ftaC6kD1oLrQS1B96GWoAfQK1BBqBDWBGkM+UHOoKdQMagG1glpCraE20KtQW6g91A7qAHWEXoM6QV2gzlBXqDvUDXodehPqAb0BvQX5Qj2hXlBvyA/qk/3RffhJt0f5v741XNr5v9MZ5P9Hm9ou/79M4J/xwvn/R8z5/0UYO0uI/2Pm5z/+gr2rBP+fMOd/Z2DvAsH/p8L532c2yP+uEOL/nLH+Y7RlhfqNWj+l6jd61k9tFZ5/4cj/T6I/nSf0vy+Y8/+/Ye8cwf+Xwvn/V8z5/yXYO0WI/2vh578nCPP/N8L8/60w/0/U+Hfk7wz5u3YLWuI2StLzL4/4X/f576Yo9Kea7ibTzXT438L9tuR/J/fHH/++E+Z/tV9KQfNrDv6/D3u3CeP/D8z8/wD2shPe/0nM/H8L9u4R4v9RmP/VXl1OD79/PPyfjfD+/8y4/4eHSbYZ5fdS+CCWmNLOn1ir4/ptdr5+ioP/r6M/3SV8/yYz8/8/sHeH4P8XYf7/lZn/1WbqNwjx/ybM/78L8/8UYf6fKsz/0zLR/q9GGzu/Ex+Dt/f1U4/43/j5227pHCpo4f5LA2zH/wUI/BMuzP/Tmfk/D2LPQYh/BjP/54XvQgT/M5n53x2+cxP8zxLm/9k24P+ChPjnaOLPCvyeYkrj9+M6rt/+lD//wMH/Luh7uQj9by4z/+eD75wE//OE+T+Cmf/zI3ZXQvzzhfn/D2H+XyDM/wuF+T8yq53/oOV34mMs9s7vRu/fj/hf//nnzhh7ykPF0uF/C/fbkv/LEMa/RcL8v5iZ/59D7CUI8Ucx8//z8F2O4D+amf+Lw/ezBP9LhPl/qQ34vywh/mWZ6PwHxe/XTWn87qRjMN3heH7ZUOPg/yLoe88Q+l8MM/+Xgu+SBP/Lhfk/lpn/SyP2ooT4Vwjzf5ww/68U5v9Vwvy/OrOd/6Dld+IxBE87vxttFv73Zjh//AVB/vckjH9rhPl/LTP/V0PslQnxr2Pm/+rw7U3wv56Z/yvBd1WC/w3C/L/RBvzvRYh/E/Pz3xXg+0WC/83M/FcDvqsQ/G8R5r94Zv7zQOwVCfFvZTz/4ZVsaeunXsumb/3UTkf+Jtok+H+bMP9vF+b/HcL8v9PK/k/eBs7/LYyxJwyqkwH/mSbajv8aE8a/BGH+28XMfw0Qez1C/Inc5z9o8zfiNsKO/M1YywznPzRE3/Mh9L8kZv6vC9/1Cf6Thfl/tw34vwkh/hRm/q8F3y8T/O9h5v9X4Pslgv+9wvy/j5n/GyH22oT492v8K35X66cUv+tZP5Xg4HfRZo/nPxwQ5v+Dwvx/SJj/D1vlf+Pn/7ZIh/8fcr8N+f81wvh3RJj/jzLzf1vE3ooQ/7H/5X8tvxO3AXLwu7HGUX9T6yfU/VvP+gkO/m+HvteJ0P+OM/N/S/huQ/D/pzD/n7AB/3ckxH+Smf+bwferBP+nmPm/PXy3Jvg/Lcz/Z5j5vwNib06I/6zG/y4Hv4s2nwD/PgOaBA/XfX0T38ahoX59Bvg27hfqP9i3o3+IXyChK0vw/zlh/j8vzP8XhPn/olX+13/+c1OMPf5Qtwz4P/9y2/F/X8L4p/YrtPxVJfhf7VdW1Pyag//fQjCvE+K/lIXOf4g7Fn9r+dU101ZEbT6/6cGKC4uOh89eFJsYu2R24tyYqC07wyMSF8UeS96/8cTWu/GRy6+oPxF/cOulPVHbIsLnGPdvlN/VdMldNSbgjcyt481MlD//gdz/LzPzvx/6/puE/n/FBvzfh+Bf7ZXa0Pyai/97E/xfY+b/LvD9BsH/dWb+94XvHgT/N4T5/yYz//dC7F0J8d9iHP+l+V36/mO0scy/19JfxZLg/9sa/vcxBaSOAAPw3746/Kv6U0/0/e6E/n/HyvjfMTULCXgi+cddjf9O8DhCN/2BGXT4v/ev/OPJ51/3reYfxs+fDkgn/7DkHaWP2S7/GEzofw+E5x/+Yd5/Pgixv02IXyVfnOvPg2EvlODfyZ2XPwNhbxDBfzZ32fqz2quzoqUvOs5AemqVum+uyVgTz/9vbT6/O27J0vjIFSc2n465uzgi5n54RPKVxdPik2P3RsetX7bsgC3PFzCa/5eD1JSrm5O6F9JbksEPgCv/HEIY/5zdefPPfrA3kODfxZ03/wyBvQEE/2qvHsn8082dN/98B/b6E+J3d5d9/ljtlSc5/5DTXXb+IZd71sn/jTaj8bcKCgkLNTB/16qJbyf/0NDAoP6+zQP7B4T6tg8L7Rw4yP9J/f0l5p9yu1vL/3SfP27qDHvfQ8PTyf8seZ8t87+xhPFP7dcpOf+k9ussbn7Nkf+Nhr13CfHnY87/3oe9Dwn+8zPnfyNgbxTBfwHh/E/tFZqNafww2jyFF+A9bskivVYEb6CaOa/tpL5L9Jacac7/Msb/4wj9vxAz/w+FvZEE/4WZ+X8M7L1H8F9EmP+LMvP/B7A3jBB/MWH+Ly7M/yU08XdArx+Cf4alfgfoMyB6+KukO9/5X9lM9t145t88dV8vXX9rC/4fiF4fiJEgEP2fymB6+v8zVvnf+PnDnwjy/7eE8U/tVSk5/6P2C+Wc//kK9j4jxP88M/9/DXvfEfyXYub/T2HvS4L/0sL8X8adb/+3pSkpSSbBZrT+3hSjgao8vImfTXRcvzvLnP9ljP8nEvp/WWb+/wj2viD4L8fM/xNg73OC//LC/F+Bmf+/gb2PCfFXFOb/F4T5v5Jw/b+ye+bZ/z8T1N/bBPfv4xcq9PeXrr9J1P+rWOV/3ecPO42HvcXQjxnwv4f7dZvx/zTC+PeicP1f7ZWZw/yag/9/g72fCfFXY+b/32EvnOC/OjP//wR7vxL81xDm/weaP8fFf9MJ8Xsw898PsPcLwb8nM/9Ngb3JBP9ewvznzXj/Nzp/UlKNR9BZjMpjddwMUxzPLxtqHPw/Ff1pEqH/1xTm/1rC/F9buP5fR+Nfov5b1yr/GT9/dnY6/GfhPhvxHzl+tVenq/m1BP+9pLn/GB3/moSFhgYHGbg+NMicgPn6DPT3I98E7T3/2nRy1e7oyE0LdybHr1y/f/OhJ+2fg///QH+aSxj/X+blf3L/r8/M/wtgbz4h/gbC/N9Q8/1n4H/y+/8KL/87zYS9CML734iZ/xfC3jyC/8a8/O+0CPbmEPw3cefb//+Sef1Tz2wm06s6rt/zlPM74/2zfYh/UPPggX39KT2Jg/8j0Z9mEfqfjzD/N9Xwfwfce4bj2zcQdyGd3z+y/2ZW+Vf3+aumGbCXCC3JgH8b1cgc/NtcmH/VPqVFLJ8FA/+sgL1lhP7fUph/Wrlnnf1/oq6smrt5d8rKHetXPFiR8OT9c9w/u5jS7p+DdFy/1+AHwMG/cehPsYT+31qYf9VelXnNryX4tw0z/0bB3nLC+9+WmX9Xwl4MwX87Zv5dDXtLCf7bM69/WAV70QT/HYT55zUN/9g7P7cPCQ0MDtK/AKC9Zf7ft6l/77D+5Ovt/f4pwb8drfBvTf3njz70vz4d/rVwb4eutpv/30X4/nfSzL9L8K96XjKf+TUH/8bD3kZC/F2E+bcrc/1vB+xtIcTfzQb8k0Dw313jP/pmfLLk+GOUn53AzafwsyZ+PtBx/YGnvP7Etf5jJ6H/vc68/mMt7G0m+O/BzL/bYG8Twf8bwus/3mTm3+2wt44Q/1vC/NvTnXf/wa2wt4EQv6+77P6DvRjrP9KtxeDgsBAD638t19fVeb2987/E/pN+7rL7T/a2mn/oP/92DewdgXank39Y8g4b5R/k+PsIrz/uy7z++ADs7SGMv/7M648Pmn0/rv9+zPlHCuztJ8TfX7j+qvZpzf3w+/fk66+BzPXXJNjbR3j/32bmz0Owt5fgf4CGP9W6IzV/svpownaTQOOYP1HHOKj5k1w6bqYH7Tz/M1r/lMg/BjLnH4dhL5nQ/wcJ5x9B/8o/LPyh+/zNh/6PZ8AfvUbZrv75N+H9Dxauf4Zo5v84+OMM7J0gxP+OcP1zsMb/o/mPVkH9gp/8+Ced/0Se27NC0j9H/XO1Ka3+uVfH9Rz8eQH96TSh/w+xAX/+RfAfapX/jNU/LxL8hzHXP4/C3imC/6HM/HkO9k4S/A8Trn8OZ+aP87B3jBD/CGH+eFfDH4fsnH/t/f4j3Tjq32fRn/4k9P/3hOvfI91lz98ZJVz/HK3x/39QSwECFwsUAAIACABsFGdGtFpYZK9xAAAIygYACQAJAAAAAAAAAAAAAIAAAAAAVUlQYWNrYWdlVVQFAAfaY/pUUEsFBgAAAAABAAEAQAAAAOdxAAAAAA==


[Script]
/**********************************************************初始化变量**********************************************************/
Dim X,Y
X = -1 
Y = - 1 

Dim Ken_LeftClickOnXY_Delay
Ken_LeftClickOnXY_Delay = 100

//资源文件夹路径
Dim ResourceFolder

DimEnv ChangeNavyArray1Index,ChangeNavyArray2Index,ChangeNavyArray3Index,ChangeNavyArray4Index,ChangeNavyArray5Index,ChangeNavyArray6Index
ChangeNavyArray1Index = 0
ChangeNavyArray2Index = 0
ChangeNavyArray3Index = 0
ChangeNavyArray4Index = 0
ChangeNavyArray5Index = 0
ChangeNavyArray6Index = 0

Dim DebugLogPath, WarningLogPath

Dim LogcatFileStr





















































/**********************************************************窗体函数**********************************************************/
//开关
Dimenv AutoSupply,AutoRepair,AutoExpedition,AutoAttack,AutoChangeNavy,AutoFactory

Dimenv SupplyNavyArray
Dimenv ExpeditionNavyArray 
Dimenv AutoAttackNavyArray

//远征舰队
Dimenv Expedition_Navy2_Enable, Expedition_Navy3_Enable, Expedition_Navy4_Enable
//远征舰队对应任务ID
DimEnv ExpeditionMissionID_Navy2, ExpeditionMissionID_Navy3, ExpeditionMissionID_Navy4

//出击状态
DimEnv AttackNightFight,AttackFightRound

//换船
Dimenv ChangeNavyPageCount, ChangeNavyLineNumber

//窗体载入时
Event Form.LoadOver
    LB_Dev_Setting = Plugin.File.ReadINI("Factory", "DevList", ".\Config.ini")
    LB_Dev_SettingArray = Split(LB_Dev_Setting, "|")
    If (UBound(LB_Dev_SettingArray) = -1) Then 
        Form.LB_Dev.AddItem "10,10,10,10"
    End If
    For i = 0 To UBound(LB_Dev_SettingArray)
        Item = LB_Dev_SettingArray(i) 
        Form.LB_Dev.AddItem Item
    Next
    LB_Build_Setting = Plugin.File.ReadINI("Factory", "BuildList", ".\Config.ini")
    LB_Build_SettingArray = Split(LB_Build_Setting, "|")
    If (UBound(LB_Build_SettingArray) = -1) Then 
        Form.LB_Build.AddItem "30,30,30,30"
    End If
    For i = 0 To UBound(LB_Build_SettingArray)
        Item = LB_Build_SettingArray(i)
        Form.LB_Build.AddItem Item
    Next
    Form.IB_Dev_RepeatCount.Text = 0
    Form.IB_Build_RepeatCount.Text = 0
    Form.CB_AutoFactory.Value = 0
End Event
//脚本启动时
Sub OnScriptLoad()
End Sub
//脚本退出时
Sub OnScriptExit()
    Call Ken_Logcat_I("*******************************肯的舰队脚本，停止*******************************")
End Sub

//自动补给开关
Event Form.CB_AutoSupply.Click
    If (Form.CB_AutoSupply.Value = 1) Then 
        Form.CB_Supply_When_Attack_Before.Value = 1
        Form.CB_Supply_When_Expedition_Before.Value = 1
        Form.CB_Supply_Sort.Value = 1
        Form.CB_Repair_WeiPo.Value = 1
    End If
End Event
//自动入渠开关
Event Form.CB_AutoRepair.Click
    If (Form.CB_AutoRepair.Value = 1) Then 
        Form.CB_Repair_Dapo.Value = 1
        Form.CB_Repair_ZhongPo.Value = 1
        Form.CB_Repair_XiaoPo.Value = 0
        Form.CB_Repair_Navy_1.Value = 0
        Form.CB_Repair_WeiPo.Value = 0
    End If
End Event
//自动远征开关
Event Form.CB_AutoExpedition.Click
    If (Form.CB_AutoExpedition.Value = 1) Then 
        Form.CB_Supply_CheckOil.Value = 1
    End If
End Event
//自动攻击开关
Event Form.CB_AutoAttack.Click
    If (Form.CB_AutoAttack.Value = 1) Then 
        Form.CB_Attack_When_DaPo.Value = 0
        Form.CB_Attack_When_ZhongPo.Value = 1
        Form.CB_Attack_When_XiaoPo.Value = 1
        Form.CB_Attack_Suppy.Value = 1
        Form.CB_Attack_CheckOil.Value = 1
        Form.CB_Attack_After_Repair.Value = 0
        Form.CB_Attack_CheckCondition.Value = 0
        Form.CB_Attack_Limit_Count.Value = 0
        Form.CB_AttackNightFight.Value = 0
    End If
End Event
//自动换船开关
Event Form.CB_AutoChangeNavy.Click
    If (Form.CB_AutoChangeNavy.Value = 1) Then 
        Form.CB_ChangeNavy_When_Repair.Value = 1
        Form.CB_ChangeNavy_When_DaPo.Value = 1
        Form.CB_ChangeNavy_When_ZhongPo.Value = 0
        Form.Label_ChangeNavy_1.Caption = 0
        Form.Label_ChangeNavy_2.Caption = 0
        Form.Label_ChangeNavy_3.Caption = 0
        Form.Label_ChangeNavy_4.Caption = 0
        Form.Label_ChangeNavy_5.Caption = 0
        Form.Label_ChangeNavy_6.Caption = 0
    End If
End Event
//自动工厂开关
Event Form.CB_AutoFactory.Click
End Event


//大破出击开关
Event Form.CB_Attack_When_DaPo.Click
    If (Form.CB_Attack_When_DaPo.Value = 1) Then 
        MessageBox "警告，这极有可能导致舰船沉没！请确认了解该情况会导致的后果！"
    End If
End Event

//是否进击回合次数
Event Form.CB_AttackNightFight.Click
    AttackNightFight = Form.CB_AttackNightFight.Value
End Event
//是否夜战
Event Form.CB_AttackFightRound.SelectChange
    AttackFightRound = Form.CB_AttackFightRound.ListIndex
End Event

//设置第几舰队远征
Event Form.CB_Expedition_Navy2_Enable.Click
    Expedition_Navy2_Enable = Form.CB_Expedition_Navy2_Enable.Value
    Form.CB_Supply2.Value = Form.CB_Expedition_Navy2_Enable.Value
    Form.CB_AutoSupply.Value =1
End Event
Event Form.CB_Expedition_Navy3_Enable.Click
    Expedition_Navy3_Enable = Form.CB_Expedition_Navy3_Enable.Value
    Form.CB_Supply3.Value = Form.CB_Expedition_Navy3_Enable.Value
    Form.CB_AutoSupply.Value = 1
End Event
Event Form.CB_Expedition_Navy4_Enable.Click
    Expedition_Navy4_Enable = Form.CB_Expedition_Navy4_Enable.Value
    Form.CB_Supply4.Value = Form.CB_Expedition_Navy4_Enable.Value
    Form.CB_AutoSupply.Value = 1
End Event
//设置远征地图
Event Form.CB_Expedition_Missionevel_Navy2.SelectChange
    ExpeditionMissionID_Navy2 = Form.CB_Expedition_Missionevel_Navy2.ListIndex
End Event
Event Form.CB_Expedition_Missionevel_Navy3.SelectChange
    ExpeditionMissionID_Navy3 = Form.CB_Expedition_Missionevel_Navy3.ListIndex
End Event
Event Form.CB_Expedition_Missionevel_Navy4.SelectChange
    ExpeditionMissionID_Navy4 = Form.CB_Expedition_Missionevel_Navy4.ListIndex
End Event

//出击后强制补给
Event Form.CB_Attack_Suppy.Click
    Form.CB_Supply1.Value = Form.CB_Attack_Suppy.Value
    Form.CB_AutoSupply.Value = 1
End Event

//工厂开发公式列表
Event Form.LB_Dev.DblClick
    Dim SelectOfArray,ItemArray
    SelectOfArray = split(Form.LB_Dev.List, "|")
    ItemArray = split(SelectOfArray(Form.LB_Dev.ListIndex), ",")
    Form.IB_Dev_Oil.Text = ItemArray(0)
    Form.IB_Dev_Ammo.Text = ItemArray(1)
    Form.IB_Dev_Steel.Text = ItemArray(2)
    Form.IB_Dev_Lv.Text = ItemArray(3)
End Event
Event Form.Btn_Dev_Add.Click 
    Form.LB_Dev.AddItem (Form.IB_Dev_Oil.Text & "," & Form.IB_Dev_Ammo.Text & "," & Form.IB_Dev_Steel.Text & "," & Form.IB_Dev_Lv.Text)
    Call Plugin.File.WriteINI("Factory", "DevList", Form.LB_Dev.List, ".\Config.ini")
End Event
Event Form.Btn_Dev_Remove.Click
    Form.LB_Dev.RemoveItem (Form.LB_Dev.ListIndex)
    Call Plugin.File.WriteINI("Factory", "DevList", Form.LB_Dev.List, ".\Config.ini")
End Event
//工厂建造公式列表
Event Form.LB_Build.DblClick
    Dim SelectOfArray,ItemArray
    SelectOfArray = split(Form.LB_Build.List, "|")
    ItemArray = split(SelectOfArray(Form.LB_Build.ListIndex), ",")
    Form.IB_Build_Oil.Text = ItemArray(0)
    Form.IB_Build_Ammo.Text = ItemArray(1)
    Form.IB_Build_Steel.Text = ItemArray(2)
    Form.IB_Build_Lv.Text = ItemArray(3)
End Event
//开发公式保存
Event Form.Btn_Build_Add.Click 
    Form.LB_Build.AddItem (Form.IB_Build_Oil.Text & "," & Form.IB_Build_Ammo.Text & "," & Form.IB_Build_Steel.Text & "," & Form.IB_Build_Lv.Text)
    Call Plugin.File.WriteINI("Factory", "BuildList", Form.LB_Build.List, ".\Config.ini")
End Event
//建造公式保存
Event Form.Btn_Build_Remove.Click
    Form.LB_Build.RemoveItem (Form.LB_Build.ListIndex)
    Call Plugin.File.WriteINI("Factory", "BuildList", Form.LB_Build.List, ".\Config.ini")
End Event

Event Form.IB_Setting_Fight_OutTime.Change
    Dim a
    a = lib.算法.提取字串符中所有数字(Form.IB_Setting_Fight_OutTime.Text)
    Form.IB_Setting_Fight_OutTime.Text = right(a, 2)
End Event


Event Form.Btn_Logcat_Clear.Click
    Form.IB_Logcat.Text = ""
    LogcatFileStr = ""
End Event
Event Form.Btn_Logcat_OpenFolder.Click
    Runapp ResourceFolder & "\日志\"
End Event

























































/*****************************设置常量*****************************/
//远征舰队坐标
Const ExpeditionNavyPosition = "356|120"
Const ExpeditionNavyPositionOffset = 30
//远征地图坐标
Const ExpeditionMapPosition = "135|450"
Const ExpeditionMapPositionOffset = 55
//远征关卡坐标
Const ExpeditionMissionPosition = "160|170"
Const ExpeditionMissionPositionOffset = 30

//补给全选框坐标
Const SupplyCheckBoxAllPosition = "120|120"
//补给舰队坐标
Const SupplyNavyPosition = "150|120"
Const SupplyNavyPositionOffset = 30
//补给舰队确定
Const SupplyNavyConfirmPosition = "700|450"

//入渠空位坐标
Const RepairEmptyPosition = "250|170"
Const RepairEmptyPositionOffset = 80
//列表类型坐标
Const TypePosition = "780|110"
//入渠舰队坐标
Const RepairNavyPosition = "480|141"
Const RepairNavyPositionOffset = 30

//出击地图坐标
Const AttackMapPosition = "160|450"
Const AttackMapPositionOffset = 75
//出击任务坐标
Const AttackMissionPosition = "280|200"
Const AttackMissionPositionOffsetX = 350
Const AttackMissionPositionOffsetY = 150
//出击的BOSS地图坐标
Const AttackMissionPositionOfBossMap = "710|260"
//出击的BOSS地图任务2坐标
Const AttackMissionPositionOfBossMission1 = "710|260"
//出击的BOSS地图任务3坐标
Const AttackMissionPositionOfBossMission2 = "710|300"

//出击的活动地图坐标
Const AttackMissionPositionOfSpecialMap = "720|450"
//出击的活动地图任务1坐标
Const AttackMissionPositionOfSpecialMission = "720|200"
Const AttackMissionPositionOfSpecialMissionOffset = 100

//攻击阵形坐标数组
AttackFormationPositionArray = Array("450|185","480|185","710|185","510|345","640|345")//数组无法声明成const


//换船接触除了旗舰以外的船坐标
Const ChangeNavyWithOutFlagPosition = "420|120"
Const ChangeNavyPagePosition = "520|450"
Const ChangeNavyPagePositionOffset = 30
Const ChangeNavyListPosition = "470|170"
Const ChangeNavyListPositionOffset = 29
Const ChangeNavyBackToFirstPagePosition = "440|450"
Const ChangeNavyJumpPageToNext5Position = "680|450"
Const ChangeNavyListNavyPosition = "130|120"
Const ChangeNavyChangeInitBtnPosition = "420|220"
Const ChangeNavyChangeInitBtnPositionOffsetX = 350
Const ChangeNavyChangeInitBtnPositionOffsetY = 114

//工厂坐标
Const OilPosition = "490|140"
Const SteelPosition = "720|140"
Const AmmoPosition = "490|270"
Const LvPosition = "720|270"
FactoryPositionArray = Array(OilPosition,SteelPosition,AmmoPosition,LvPosition)

























































//**********************************************************逻辑**********************************************************/
Do
/****************************初始化****************************/
    Call InitEnvironment()
    Call GetHwndForGame()
    Call GoToMuGang()
    //    Call RepairNavy()
    Call ChangeNavy()
    Call FactoryNavy()
    Call TD_CheckTiDu()
    Delay 5000
Loop While(1=1)





















































/**********************************************************提督很忙**********************************************************/
/*****************************远征*****************************/
Function TD_Expedition()
    Call SetHwndByGame()
    Call GoToMuGang()
    If (Form.CB_Supply_When_Expedition_Before.Value = 1) Then 
        Call SupplyNavy()
    End If
    Call ExpeditionNavy()
End Function

/****************************出击****************************/
Function TD_Attack()
    Call SetHwndByGame()
    Call GoToMuGang()
    If (Form.CB_Supply_When_Attack_Before.Value = 1) Then 
        Call SupplyNavy()
    End If
    Call AttackNavy()
    Call GoToMuGang()
    If (Form.CB_Attack_After_Repair.Value = 1) Then 
        Call RepairNavy()
    End If
End Function


/****************************检查远征是否就绪****************************/
Function TD_CheckTiDu()
    Do
        Call SetHwndByTidu()
        
        Rem 远征判断
        If (Form.CB_AutoExpedition.Value = 1) Then 
            If (Form.CB_Expedition_Navy2_Enable.Value = 1 and Ken_FindPic("提督_综合_远征_第二舰队_准备就绪1")) Then 
                Call TD_Expedition()
                Exit Function
            End If
            If (Form.CB_Expedition_Navy2_Enable.Value = 1 and Ken_FindPic("提督_综合_远征_第二舰队_准备就绪2")) Then 
                Call TD_Expedition()
                Exit Function
            End If
            If (Form.CB_Expedition_Navy3_Enable.Value = 1 and Ken_FindPic("提督_综合_远征_第三舰队_准备就绪1")) Then 
                Call TD_Expedition()
                Exit Function
            End If
            If (Form.CB_Expedition_Navy3_Enable.Value = 1 and Ken_FindPic("提督_综合_远征_第三舰队_准备就绪2")) Then 
                Call TD_Expedition()
                Exit Function
            End If
            If (Form.CB_Expedition_Navy4_Enable.Value = 1 and Ken_FindPic("提督_综合_远征_第四舰队_准备就绪1")) Then 
                Call TD_Expedition()
                Exit Function
            End If
            If (Form.CB_Expedition_Navy4_Enable.Value = 1 and Ken_FindPic("提督_综合_远征_第四舰队_准备就绪2")) Then 
                Call TD_Expedition()
                Exit Function
            End If
        Else 
            Call Ken_Logcat_I("远征没有开启")
        End If
        Rem 远征结束
        
        Rem 入渠开始判断	
        If (Form.CB_Repair_Dapo.Value = 1) Then 
            Call Ken_Logcat_I("按照入渠设置，检测是否大破")
            If (Ken_FindPic("提督_综合_舰队列表_HP_大破")) Then 
                Call Ken_Logcat_I("大破了吗？是")
                Call RepairNavy()
                Call ChangeNavy()
                Goto 入渠结束判断
            Else 
                Call Ken_Logcat_I("大破了吗？否")
            End If
        Else 
            Call Ken_Logcat_I("按照入渠设置，不检测是否大破")
        End If
        If (Form.CB_Repair_ZhongPo.Value = 1) Then 
            Call Ken_Logcat_I("按照入渠设置，检测是否中破")
            If (Ken_FindPic("提督_综合_舰队列表_HP_中破")) Then 
                Call Ken_Logcat_I("中破了吗？是")
                Call RepairNavy()
                Call ChangeNavy()
                Goto 入渠结束判断
            Else 
                Call Ken_Logcat_I("中破了吗？否")
            End If
        Else 
            Call Ken_Logcat_I("按照入渠设置，不检测是否中破")
        End If
            
        If (Form.CB_Repair_XiaoPo.Value = 1) Then 
            Call Ken_Logcat_I("按照入渠设置，检测是否小破")
            If (Ken_FindPic("提督_综合_舰队列表_HP_小破")) Then 
                Call Ken_Logcat_I("小破了吗？是！")
                Call RepairNavy()
                Call ChangeNavy()
                Goto 入渠结束判断
            Else 
                Call Ken_Logcat_I("小破了吗？否")
            End If
        Else
            Call Ken_Logcat_I("按照入渠设置，不检测是否小破")
        End If
        Rem 入渠结束判断
        
        Rem 进击判断
        If (Form.CB_AutoAttack.Value = 1) Then 
            If (Form.CB_Attack_When_DaPo.Value = 1) Then 
                Call Ken_Logcat_I("按照出击设置，不检测是否大破")
            Else 
                If (Ken_FindPic("提督_综合_舰队列表_HP_大破")) Then 
                    Call Ken_Logcat_I("大破了吗？是 取消出击！")
                    Goto 进击结束
                Else 
                    Call Ken_Logcat_I("大破了吗？否")
                End If
            End If
            If (Form.CB_Attack_When_ZhongPo.Value = 1) Then 
                Call Ken_Logcat_I("按照出击设置，不检测是否中破")
            Else 
                If (Ken_FindPic("提督_综合_舰队列表_HP_中破")) Then 
                    Call Ken_Logcat_I("中破了吗？是 取消出击！")
                    Goto 进击结束
                Else 
                    Call Ken_Logcat_I("中破了吗？否")
                End If
            End If
            If (Form.CB_Attack_When_XiaoPo.Value = 1) Then 
                Call Ken_Logcat_I("按照出击设置，不检测是否小破")
            Else
                If (Ken_FindPic("提督_综合_舰队列表_HP_小破")) Then 
                    Call Ken_Logcat_I("小破了吗？是 取消出击！")
                    Goto 进击结束
                Else 
                    Call Ken_Logcat_I("小破了吗？否")
                End If
            End If
            If (Ken_FindPicByRect("提督_综合_入渠_入渠结束", 650, 620, 650+120, 620+105)) Then 
                Call Ken_Logcat_I("已有船只入渠结束，直接进入入渠界面刷新舰船状态")
                Call GoToScene("入渠")
            End If
            If (Ken_FindPic("提督_综合_舰队列表_入渠中")) Then 
                Call Ken_Logcat_I("当前舰队有船只正在入渠")
                If (Form.CB_AutoChangeNavy.Value = 1) Then //如果有开启自动更换的话
                    Call Ken_Logcat_I("自动更换已经打开，更换船只")
                    Call ChangeNavy()
                    Exit Function
                Else 
                    Call Ken_Logcat_I("自动更换没有打开，在入渠界面等待入渠结束")
                    Call GoToScene("入渠")
                End If
                Goto 进击结束
            End If
            Call Ken_Logcat_I("Form.CB_AutoAttack.Value:" & Form.CB_AutoAttack.Value)
            If (Form.CB_AutoAttack.Value = 1) Then 
                If (Form.CB_Attack_CheckCondition.Value = 1) Then 
                    Call TD_Attack()
                    Exit Function
                End If
                If (Ken_FindPic("提督_综合_舰队列表_可以出击")) Then 
                    Call TD_Attack()
                    Exit Function
                End If
                If (Ken_FindPic("提督_综合_舰队列表_疲劳回复好了")) Then 
                    Call TD_Attack()
                    Exit Function
                End If
                If (Ken_FindPic("提督_综合_舰队列表_疲劳回复时间到了")) Then 
                    Call TD_Attack()
                    Exit Function
                End If
                If (Ken_FindPic("提督_综合_舰队列表_6只疲劳49")) Then 
                    Call TD_Attack()
                    Exit Function
                End If
                If (Ken_FindPic("提督_综合_舰队列表_6只疲劳40以上")) Then 
                    Call TD_Attack()
                    Exit Function
                End If
                If (Ken_FindPicByRect("提督_综合_舰队列表_舰队状态_可以出击",103,572,130,604)) Then 
                    Call TD_Attack()
                    Exit Function
                End If
                Call ChangeNavy()
            End If
            If (Ken_FindPic("提督_综合_舰队列表_入渠中")) Then 
                Call GoToMuGang()
            End If
        End If
        Rem 进击结束
        Call Ken_Logcat_I("进击结束")
        Delay 5000
    loop While (True)
End Function

Function TD_RefreshGame()
    Call SetHwndByTidu()
    Call Ken_PointGetAndClick("30|840")
    Call Ken_PointGetAndClick("130|590")
    Call Ken_PointGetAndClick("770|590")
    Call Ken_FindPicAndClick("提督_设置")
    Call SetHwndByGame()
End Function





















































/**********************************************************函数**********************************************************/
Function GoToMuGang()
    Dim WayFromExpeditionFinish
    Call SetHwndByGame()
    //回到母港
    If (Ken_FindPic("母港_出击") = False)
        If (Ken_FindPicAndClick("左侧UI_母港")) Then 
            Call Ken_DeleyForNet()
        Else 
            Call Ken_Logcat_W("无法回到母港")
        End If
    End If
    
    Do While(Ken_FindPicAndClick("远征_结束_开始"))
        Call Ken_Logcat_I("发现远征结束舰队")
        Call Ken_DeleyForNet()
        Delay 8000
        Call Ken_FindPicUntilFoundThenClick("远征_结束_评价")
        Delay 2000
        Call Ken_FindPicUntilFoundThenClick("远征_结束_评价_继续")
        Delay 2000
        Call Ken_DeleyForNet()
        WayFromExpeditionFinish = True
    Loop
    If (WayFromExpeditionFinish) Then 
        WayFromExpeditionFinish = False
        Call SupplyNavy()
    End If
End Function
Function GoToScene(SceneName)
    Call SetHwndByGame()
    If (Ken_FindPicAndClick("左侧UI_" & SceneName)) Then 
    Else 
        Call GoToMuGang()
        If (Ken_FindPicUntilFoundThenClick("母港_" & SceneName)) Then 
        	Call Ken_Logcat_W("进入" & SceneName & "界面失败")
        End If
    End If
    Call Ken_Logcat_I("*******************************进入" & SceneName & "界面*******************************")
    Call Ken_DeleyForNet()
End Function

/*远征主逻辑*/
Function ExpeditionNavy()
    Call Ken_Logcat_I("远征模块是否打开:" & Form.CB_AutoExpedition.Value)
    Call SetHwndByGame()
    If (Form.CB_AutoExpedition.Value = 0) Then 
        Exit Function
    End If
    
    Call GoToMuGang()
    If (Ken_FindPicUntilFoundThenClick("母港_出击") = False) Then
        Call Ken_Logcat_W("远征失败，没有找到出击按钮，返回母港")
        Call GoToMuGang()
        Exit Function
    End If
    Call Ken_DeleyForNet()
    Call Ken_FindPicUntilFoundThenClick("出击_主界面_远征")
    Call Ken_DeleyForNet()
    
    If (Expedition_Navy2_Enable = 1) Then 
        Call ExpeditionSelectMapByMissionID(ExpeditionMissionID_Navy2,1)	
    End If
    If (Expedition_Navy3_Enable = 1) Then 
        Call ExpeditionSelectMapByMissionID(ExpeditionMissionID_Navy3,2)	
    End If
    If (Expedition_Navy4_Enable = 1) Then 
        Call ExpeditionSelectMapByMissionID(ExpeditionMissionID_Navy4,3)	
    End If

    Call Ken_DeleyForNet()
End Function

/*选择远征地图*/
Function ExpeditionSelectMapByMissionID(ExpeditionMissionID,NavyNumber)
    //远征地图下标
    ExpeditionMapIndex = Int(ExpeditionMissionID / 8)
    Call Ken_Logcat_D("ExpeditionMapIndex:" & ExpeditionMapIndex)
    //远征任务下标
    ExpeditionMissionIndex = Int(ExpeditionMissionID mod 8)
    Call Ken_Logcat_D("ExpeditionMissionIndex:" & ExpeditionMissionIndex)
    
    /*选择远征地图*/
    Call Ken_PointAddAndClick(ExpeditionMapPosition,ExpeditionMapIndex * ExpeditionMapPositionOffset,0)
	/*选择远征关卡*/
    Call Ken_PointAddAndClick(ExpeditionMissionPosition,0,ExpeditionMissionIndex * ExpeditionMissionPositionOffset)

    If (Ken_FindPic("出击_远征_远征中止")) Then //如果远征正在执行，则退出
        Call Ken_Logcat_I("第" & NavyNumber + 1 & "舰队已经在执行远征任务")
        Exit Function
    End If
    Delay 1000
    Call Ken_FindPicUntilFoundThenClick("出击_确定任务")
    Delay 1000
    Call Ken_PointAddAndClick(ExpeditionNavyPosition, NavyNumber * ExpeditionNavyPositionOffset, 0)
    
    If (Form.CB_Attack_CheckOil.Value = 1) Then 
        If (CheckOilAndAmmoIsFull() = false) Then 
            Call Ken_Logcat_I(NavyNumber & "舰队在执行任务" & ExpeditionMissionID + 1  & "时缺油或弹药")
            Call SupplyNavy()
            Exit Function
        End If
    End If
    Call Ken_FindPicUntilFoundThenClick("出击_远征_远征开始")
    Call Ken_DeleyForNet()
    Delay 5000
End Function

Function CheckOilAndAmmoIsFull()
    If (Ken_FindPic("远征_结束_舰队_缺油")) Then 
        CheckOilAndAmmoIsFull = False
        Exit Function
    End If
    
    If (Ken_FindPic("远征_结束_舰队_极度缺油")) Then 
        CheckOilAndAmmoIsFull = False
        Exit Function
    End If
    
    If (Ken_FindPic("远征_结束_舰队_缺弹药")) Then 
        CheckOilAndAmmoIsFull = False
        Exit Function
    End If
    CheckOilAndAmmoIsFull = True
End Function

/*补给主逻辑*/
Function SupplyNavy()
    Call Ken_Logcat_I("补给模块是否打开:" & Form.CB_AutoSupply.Value)
    Call SetHwndByGame()
    If (Form.CB_AutoSupply.Value = 0) Then 
        Exit Function
    End If
    Call GoToMuGang()
    Call GoToScene("补给")
    Call Ken_DeleyForNet()
    ForForm = 0
    ForTo = 3
    ForStep = 1
    If (Form.CB_Supply_Sort.Value = 1) Then 
        ForForm = 3
        ForTo = 0
        ForStep = -1
    End If
    For index = ForForm To ForTo Step ForStep
        If (index = 0) Then 
            If (Form.CB_Supply1.Value = 0) Then 
                Goto 下一个补给舰队
            End If
        End If
        If (index = 1) Then 
            If (Form.CB_Supply2.Value = 0) Then 
                Goto 下一个补给舰队
            End If
        End If
        If (index = 2) Then 
            If (Form.CB_Supply3.Value = 0) Then 
                Goto 下一个补给舰队
            End If
        End If
        If (index = 3) Then 
            If (Form.CB_Supply4.Value = 0) Then 
                Goto 下一个补给舰队
            End If
        End If
        Call Ken_PointAddAndClick(SupplyNavyPosition, index * SupplyNavyPositionOffset, 0)
        Delay 200//防卡
        If (Ken_FindPic("补给_补给列表_全选框")) Then 
            Call Ken_Logcat_I("补给第" & index+1 &"舰队")
            Call Ken_PointGetAndClick(SupplyCheckBoxAllPosition)
            If (Ken_FindPicAndClick("补给_补给列表_确定补给") = False) Then 
                Call Ken_Logcat_I("第" & index+1 &"舰队不需要补给")
            End If
            Call Ken_DeleyForNet()
        End If
        Rem 下一个补给舰队
    Next
    Call GoToMuGang()
End Function

/*入渠主逻辑*/
Function RepairNavy()
    Call Ken_Logcat_I("入渠模块是否打开:" & Form.CB_AutoRepair.Value)
    Call SetHwndByGame()
    If (Form.CB_AutoRepair.Value = 0) Then 
        Exit Function
    End If
    Call GoToScene("入渠")
    Call Ken_DeleyForNet()
    
    Dim FlagShipIsRepayed //旗舰是否修复
    FlagShipIsRepayed = 0
    Dim RepairedX, RepairedY //扫描这行的起始坐标
    RepairedX = 360
    RepairedY = 125
    Dim HaveSomeoneOnRapired //整个扫描的页里面是否有一艘被修复的
    HaveSomeoneOnRapired = False
    Dim TheLineIsRepaired //这行是否被修复
    TheLineIsRepaired = 0
    
    For index = 0 To 3
        If (Ken_FindPicAndClick("入渠_维修列表_空位")) Then 
            Call Ken_Logcat_I("找到空位，准备入渠")
        Else 
            Call Ken_Logcat_I ("没找到空位，停止入渠，查看是否打开自动更换")
            Call ChangeNavy()
            //            If (Form.CB_AutoChangeNavy.Value = 1) Then //如果有开启自动更换的话
            //                Call Ken_Logcat_I("自动更换已经打开，更换船只")
            //                Call ChangeNavy()
            //                Exit Function
            //            Else 
            //                Call Ken_Logcat_I("自动更换没有打开，在入渠界面等待入渠结束")
            //                Call GoToScene("入渠")
            //            End If
            Exit Function
        End If
        Delay 1000//右边弹出 防卡
        //确定船只
        For index = 0 To 9
            Call Ken_Logcat_I("正在判断第" & index+1 &"艘舰")
                
            TheLineIsRepaired = RepairFindShip(RepairedX, RepairedY)
            
            If (TheLineIsRepaired = False) Then 
                If (Ken_FindPicAndClick("入渠_维修列表_入渠开始")) Then 
                    Delay 500
                    Call Ken_FindPicAndClick("入渠_维修列表_维修开始_确定维修")
                    Call Ken_DeleyForNet()
                    Call Ken_FindPicAndClick("入渠_维修列表_空位_详情返回")
                    Delay 500
                    Call Ken_FindPicAndClick("入渠_维修列表_空位_列表返回")
                    Delay 500
                End If
            End If
            RepairedY = RepairedY + 30//查找下一行
        Next
    Next
    //    Call GoToMuGang()
End Function
Function RepairFindShip(mRepairedX, mRepairedY)
    Dim IsFirstNavy//这艘舰，这是第一舰队的

    RepairedYEnd = mRepairedY + 30
    
    If (Form.CB_Repair_Navy_1.Value = 1) Then 
        If (Ken_FindPicByRect("入渠_维修列表_第一舰队", mRepairedX, mRepairedY, 800, RepairedYEnd)) Then 
            Call Ken_Logcat_I("找到第一舰队 x:" & X & " Y:" &Y)
            IsFirstNavy = True
        Else 
            Call Ken_Logcat_I("没有找到第一舰队，如果没有找到当页最后，尝试继续查找")
            IsFirstNavy = False
            //RepairFindShip = False//当成已修复处理，跳过该舰入渠
            Exit Function
        End If
    End If
    
    If (Form.CB_Repair_XiaoPo.Value = 1) Then 
        Call Ken_Logcat_I("小破入渠被选中 检查中")
        Call Ken_FindPicByRect("入渠_战斗状态_小破", mRepairedX, mRepairedY, 800, RepairedYEnd)
        Call Ken_LeftClickOnXY()
    End If
    If (Form.CB_Repair_ZhongPo.Value = 1) Then 
        Call Ken_Logcat_I("中破入渠被选中 检查中")
        Call Ken_FindPicByRect("入渠_战斗状态_中破", mRepairedX, mRepairedY, 800, RepairedYEnd)
        Call Ken_LeftClickOnXY()
    End If
    If (Form.CB_Repair_DaPo.Value = 1) Then 
        Call Ken_Logcat_I("大破入渠被选中 检查中")
        Call Ken_FindPicByRect("入渠_战斗状态_大破", mRepairedX, mRepairedY, 800, RepairedYEnd)
        Call Ken_LeftClickOnXY()
    End If
    If (Form.CB_Repair_WeiPo.Value = 1 and HaveSomeoneOnRapired = True) Then 
        Call Ken_Logcat_I("微破入渠被选中，并且已经有其他正在入渠的舰只 检查中")
        If (Ken_FindPicByRect("入渠_战斗状态_满血", mRepairedX, mRepairedY, 800, RepairedYEnd) = False) Then 
            X = mRepairedX + 150
            Y = mRepairedY + 20
            Call Ken_LeftClickOnXY()
        End If
    End If
    If (Ken_FindPicByRect("入渠_战斗状态_修复", mRepairedX, mRepairedY, 800, RepairedYEnd)) Then 
        RepairFindShip = True//用作判断本行
        HaveSomeoneOnRapired = True//用来判断全部
    End If
    
End Function

/**战斗**/
Function AttackNavy()
    Call SetHwndByGame()
    Call Ken_Logcat_I("出击模块是否打开:" & Form.CB_AutoAttack.Value)
    If (Form.CB_AutoAttack.Value = 0) Then 
        Exit Function
    End If
    If (Int(Form.CB_Attack_Limit_Count.Value) = 1 and Int(Form.Label_Attack_Index.Caption) > Int(Form.IB_Attack_Limit_Count.Text)) Then 
        Call Ken_Logcat_I("当前出击次数超过用户设置的最大次数，停止出击" & Form.Label_Attack_Index.Caption &" "& Int(Form.IB_Attack_Limit_Count.Text))
        Exit Function
    End If
    Form.Label_Attack_Index.Caption = Int(Form.Label_Attack_Index.Caption) + 1
        
    Call GoToMuGang()
    If (Ken_FindPicUntilFoundThenClick("母港_出击") = False) Then
        Call Ken_Logcat_W("出击失败，没有找到出击按钮，返回母港")
        Call GoToMuGang()
        Exit Function
    End If
    Call Ken_FindPicUntilFoundThenClick("出击_主界面_出击")
    Call Ken_DeleyForNet()
    
    //出击地图
    AttackMapIndex = Form.CB_Attack_MapLevel.ListIndex
    //出击关卡
    AttackMissionXIndex = Form.CB_Attack_MissionLevel.ListIndex mod 2
    AttackMissionYIndex = Int(Form.CB_Attack_MissionLevel.ListIndex / 2)
	
	/*选择出击地图*/
    If (AttackMapIndex < 6) Then //正常地图
        Call Ken_PointAddAndClick(AttackMapPosition, AttackMapIndex * AttackMapPositionOffset, 0)
		/*选择出击关卡*/
        If (Form.CB_Attack_MissionLevel.ListIndex < 4) Then //如果是正常地图，就用正常关卡
            Call Ken_PointAddAndClick(AttackMissionPosition,AttackMissionXIndex * AttackMissionPositionOffsetX,AttackMissionYIndex * AttackMissionPositionOffsetY)
        Else// If(AttackMapIndex = 5)//如果是BOSS地图，就是第五地图
            Call Ken_PointGetAndClick(AttackMissionPositionOfBossMap)
            Delay 2000
            Call Ken_PointGetAndClick(AttackMissionPositionOfBossMission1)//只实现了X-5，没有实现X-6
        End If
    Else// If(AttackMapIndex = 6)//活动地图
        Call Ken_PointGetAndClick(AttackMissionPositionOfSpecialMap)
        Call Ken_PointAddAndClick(AttackMissionPositionOfSpecialMission, 0, Form.CB_Attack_MissionLevel.ListIndex * AttackMissionPositionOfSpecialMissionOffset)
        Call Ken_PointAddAndClick(AttackMissionPositionOfSpecialMission, 0, Form.CB_Attack_MissionLevel.ListIndex * AttackMissionPositionOfSpecialMissionOffset)
        Call Ken_PointAddAndClick(AttackMissionPositionOfSpecialMission, 0, Form.CB_Attack_MissionLevel.ListIndex * AttackMissionPositionOfSpecialMissionOffset)
    End If
	

    Delay 1000
	
    
    Call Ken_FindPicUntilFoundThenClick("出击_确定任务")
    Delay 500
    
    If (Form.CB_Supply_CheckOil.Value = 1) Then 
        If (CheckOilAndAmmoIsFull() = false) Then 
            Call Ken_Logcat_I(NavyNumber & "舰队在执行任务" & ExpeditionMissionID + 1  & "时缺油或弹药")
            Call SupplyNavy()
            Exit Function
        End If
    End If
    
    If (Ken_FindPic("出击_出击_出击开始_disable") = False) Then 
        Call Ken_FindPicUntilFoundThenClick("出击_出击_出击开始")
        Call Fighting()
        Call Ken_DeleyForNet()
    End If
End Function
//战斗中
Function Fighting()
    FightingRound = 0
    Timeout = 0
    Do
        Call Ken_FindPicAndClick("战斗_战斗中_指南针")
        
        Call Ken_PointGetAndClick(AttackFormationPositionArray(Form.CB_Attack_Formation.ListIndex))
        
        If (AttackNightFight = 1) Then 
            Call Ken_FindPicAndClick("战斗_战斗中_脱离判定_夜战")
        Else 
            Call Ken_FindPicAndClick("战斗_战斗中_脱离判定_追击")
        End If
        If (FightingRound < AttackFightRound) Then 
            If (Ken_FindPicAndClick("战斗_战斗中_回合结束_进击")) Then 
                FightingRound = FightingRound + 1
                Call Ken_Logcat_I("当前战斗回合数：" & FightingRound & " 总攻击回合数：" & AttackFightRound)
                Delay 1000
            End If
        Else 
            Call Ken_FindPicAndClick("战斗_战斗中_回合结束_撤退")
        End If
        If (Ken_FindPicAndClick("战斗_结束_评价_战果报告")) Then 
            Call Ken_Logcat_I("战斗结束，判断舰船是否大破")
            If (Ken_FindPicByRect("战斗_战斗中_战斗状态_大破", 0, 0, 400, 480)) Then 
                Call Ken_Logcat_I("检测到舰船大破，不再继续进击")
                ShipWasDestroyed = 1
                FightingRound = 999//不在继续战斗
            End If
        End If
        Call Ken_FindPicAndClick("进击_结束_评价_继续")
        Call Ken_FindPicAndClick("出击_结束_评价_返回")
        Delay 1000
        Timeout = Timeout + 1000
        
        FightOutTime = Int(Form.IB_Setting_Fight_OutTime.Text)
        If (FightOutTime <= 0) Then 
            FightOutTime = 10
        End If
        
        If (Timeout >= FightOutTime * 60 * 1000) Then 
            Exit Function
        End If
    Loop While (Ken_FindPic("母港_出击") = False)
    //Call Ken_FindPicUntilFoundThenClick("出击_结束_评价_继续")
End Function

//换船
Function ChangeNavy()
    Dim ChangeNavyNeedChangePortIndex,ChangeNavyIDArray,ShipID
    Call Ken_Logcat_I("编成模块是否打开" & Form.CB_AutoChangeNavy.Value)
    If (Form.CB_AutoChangeNavy.Value = 0) Then 
        Exit Function
    End If
    Call GoToScene("编成")
    
    //获取哪个船位需要更换
    Call ChangeNavyChoiceWhatShipNeedToChange()
    Call Ken_DeleyForNet()
    Rem 结束换船逻辑
End Function
//通过条件判断哪艘船需要被替换
Function ChangeNavyChoiceWhatShipNeedToChange()
    Call Ken_Logcat_I("通过条件判断哪艘船需要被替换")
    Dim ScanningX, ScanningY//扫描这行的起始坐标
    Dim ChangeNavyChangeInitResult
    ChangeNavyChangeInitResult = 0
    ScanningX = 110
    ScanningY = 634
    For ChangeNavyNeedChangePortIndex = 0 To 5
        Call Ken_Logcat_I("开始检测第" & ChangeNavyNeedChangePortIndex+1 & "船位的舰船状态")
        Dim ScanningEndX,ScanningEndY
        ScanningEndX = ScanningX + 240
        ScanningEndY = ScanningY + 40 * (ChangeNavyNeedChangePortIndex + 1)
        ScanningY = ScanningY + 40 * (ChangeNavyNeedChangePortIndex)
        If (ChangeNavyChangeInitResult = 0 and Form.CB_ChangeNavy_When_Repair.Value) Then 
            Call SetHwndByTidu()
            If (Ken_FindPicByRect("提督_综合_舰队列表_入渠中", ScanningX, ScanningY, ScanningEndX, ScanningEndY)) Then 
                Call ChangeNavyController()
            End If
        End If
        If (ChangeNavyChangeInitResult = 0 and Form.CB_ChangeNavy_When_DaPo.Value) Then 
            Call SetHwndByTidu()
            If (Ken_FindPicByRect("提督_综合_舰队列表_HP_大破", ScanningX, ScanningY, ScanningEndX, ScanningEndY)) Then 
                Call ChangeNavyController()
            End If
        End If
        If (ChangeNavyChangeInitResult = 0 and Form.CB_ChangeNavy_When_ZhongPo.Value) Then 
            Call SetHwndByTidu()
            If (Ken_FindPicByRect("提督_综合_舰队列表_HP_中破", ScanningX, ScanningY, ScanningEndX, ScanningEndY)) Then 
                Call ChangeNavyController()
            End If
        End If
        If (ChangeNavyChangeInitResult = 0 and Form.CB_ChangeNavy_When_XiaoPo.Value) Then 
            Call SetHwndByTidu()
            If (Ken_FindPicByRect("提督_综合_舰队列表_HP_小破", ScanningX, ScanningY, ScanningEndX, ScanningEndY)) Then 
                Call ChangeNavyController()
            End If
        End If
        If (ChangeNavyChangeInitResult = 0 and Form.CB_ChangeNavy_When_Condition_0_20.Value) Then 
            Call SetHwndByTidu()
            If (Ken_FindPicByRect("提督_综合_舰队列表_红脸", ScanningX, ScanningY, ScanningEndX, ScanningEndY)) Then 
                Call ChangeNavyController()
            End If
        End If
        If (ChangeNavyChangeInitResult = 0 and Form.CB_ChangeNavy_When_Condition_20_30.Value) Then 
            Call SetHwndByTidu()
            If (Ken_FindPicByRect("提督_综合_舰队列表_橙脸", ScanningX, ScanningY, ScanningEndX, ScanningEndY)) Then 
                Call ChangeNavyController()
            End If
        End If
        If (ChangeNavyChangeInitResult = 0 and Form.CB_ChangeNavy_When_Condition_30_40.Value) Then 
            Call SetHwndByTidu()
            If (Ken_FindPicByRect("提督_综合_舰队列表_黄脸", ScanningX, ScanningY, ScanningEndX, ScanningEndY)) Then 
                Call ChangeNavyController()
            End If
        End If
        Rem ChangeNavyChoiceWhatShipNeedToChangeFor
    Next
End Function
Function ChangeNavyController()
    If (Ken_FindPicByRect("提督_综合_入渠_入渠结束", 662, 572, 790, 707)) Then 
        Call Ken_Logcat_I("更换舰船前检测到有船只入渠完毕，回到母港以刷新全体舰船状态")
        Call GoToMuGang()
    End If
    Call SetHwndByGame()
    Call ChangeNavyChangeInit()
        /*在ChangeNavyChangeInit()函数后面添加代码，会被其内部Exit Function的（比如ID文本框内数字检验失败）情况调用到，请注意使用*/
End Function
//开始更换
Function ChangeNavyChangeInit()
    //通过船位，获得用户定义的下一艘可替换舰船
    Call Ken_Logcat_I("分析舰船文本框数据，即将开始更换")
    Call Ken_Logcat_D("ChangeNavyNeedChangePortIndex:" & ChangeNavyNeedChangePortIndex)
    
    Dim ChangeNavyIDs
    //获得当前（ChangeNavyNeedChangePortIndex）船位上的所有ID
    If (ChangeNavyNeedChangePortIndex = 0) Then 
        ChangeNavyPlaceIndex = Form.IB_ChangeNavy1.Text
        ChangeNavyIDs = Int(Form.Label_ChangeNavy_1.Caption)
    ElseIf (ChangeNavyNeedChangePortIndex = 1) Then
        ChangeNavyPlaceIndex = Form.IB_ChangeNavy2.Text
        ChangeNavyIDs = Int(Form.Label_ChangeNavy_2.Caption)
    ElseIf (ChangeNavyNeedChangePortIndex = 2) Then
        ChangeNavyPlaceIndex = Form.IB_ChangeNavy3.Text
        ChangeNavyIDs = Int(Form.Label_ChangeNavy_3.Caption)
    ElseIf (ChangeNavyNeedChangePortIndex = 3) Then
        ChangeNavyPlaceIndex = Form.IB_ChangeNavy4.Text
        ChangeNavyIDs = Int(Form.Label_ChangeNavy_4.Caption)
    ElseIf (ChangeNavyNeedChangePortIndex = 4) Then
        ChangeNavyPlaceIndex = Form.IB_ChangeNavy5.Text
        ChangeNavyIDs = Int(Form.Label_ChangeNavy_5.Caption)
    ElseIf (ChangeNavyNeedChangePortIndex = 5) Then 
        ChangeNavyPlaceIndex = Form.IB_ChangeNavy6.Text
        ChangeNavyIDs = Int(Form.Label_ChangeNavy_6.Caption)
    Else 
        ChangeNavyPlaceIndex = ""
        ChangeNavyIDs = ""
    End If
    Call Ken_Logcat_I("ChangeNavyIDs:" & ChangeNavyIDs &"ChangeNavyPlaceIndex:" & ChangeNavyPlaceIndex)
    If (ChangeNavyPlaceIndex = "") Then 
        Call Ken_Logcat_I("替换船位是第" & ChangeNavyNeedChangePortIndex + 1 & "号位置的舰船：没有填写可替换的舰船，跳出替换舰船模块")
        ChangeNavyChangeInitResult = 1
        Exit Function
    Else 
        Call Ken_Logcat_I("替换船位是第" & ChangeNavyNeedChangePortIndex + 1 & "号位置的舰船：已获取数据成功")
        ChangeNavyChangeInitResult = 0
    End If
    
    //通过船位获得它的当前使用的舰船ID数组
    ChangeNavyIDArray = Split(ChangeNavyPlaceIndex, "|", - 1 , 1)
    //当前要更换的舰船ID
    ShipID = ChangeNavyIDArray(ChangeNavyIDs)//通过舰船ID数组和下标获得当前要更换的舰船ID
    
    If (IsNumeric(ShipID) = False) Then 
        Call Ken_Logcat_I("分析第" & ChangeNavyNeedChangePortIndex + 1 & "号位置的舰船数据：填写的" & ShipID & "不是数字，跳出替换舰船模块")
        ChangeNavyChangeInitResult = 1
        Exit Function
    Else
        Call Ken_Logcat_I("分析第" & ChangeNavyNeedChangePortIndex + 1 & "号位置的舰船数据：成功解析，填写的" & ShipID & "")
        ChangeNavyChangeInitResult = 0
    End If
    Call ChangeNavyChanging()
End Function
Function ChangeNavyChanging()
    Dim PageCount,LineIndex//舰船ID所在的页数和行数
    PageCount = Int(ShipID  / 10)
    LineIndex = Int(ShipID mod 10)
    
    Call Ken_Logcat_I("将更换第" & LineIndex &"页的第" & PageCount &"行船，ShipID:" & ShipID)
    //换船页数
    ChangeNavyPageCount = pageCount
    //换船行数
    ChangeNavyLineNumber = LineIndex
    
    Call Ken_Logcat_I("分析完毕，符合更换条件，开始更换")
    Dim ChangeNavyUpdateResult
    Call Ken_Logcat_I("点击更换按钮")
    Call Ken_PointAddAndClick(ChangeNavyChangeInitBtnPosition, ChangeNavyChangeInitBtnPositionOffsetX * (ChangeNavyNeedChangePortIndex mod 2), ChangeNavyChangeInitBtnPositionOffsetY * Int(ChangeNavyNeedChangePortIndex / 2))
    Delay 200//防卡
    
    If (Ken_FindPicUntilFound("编成_列表_顶部条") = False) Then 
        Call Ken_Logcat_I("没有找到列表的顶部条，可能没有选中更换按钮，更换失败，重新回到母港")
        Call GoToMuGang()
        Exit Function
    End If

    //选择可以替换的船
    Call Ken_Logcat_I("标准化列表类型")
    //列表类型
    Call Ken_ClickUntilChangeTo(TypePosition, "编成_列表_类型_船只")
    //初始化到最前页
    Call Ken_PointGetAndClick(ChangeNavyBackToFirstPagePosition)
    //直接选择第三页
    Call Ken_PointAddAndClick(ChangeNavyPagePosition, ChangeNavyPagePositionOffset * 2, 0)
    //按翻5页按钮
    For index = 0 To Int(ChangeNavyPageCount / 5) - 1
        Call Ken_PointGetAndClick(ChangeNavyJumpPageToNext5Position)
    Next
    //在（12345）中选按具体哪页按钮
    Call Ken_PointAddAndClick(ChangeNavyPagePosition, ChangeNavyPagePositionOffset * (ChangeNavyPageCount mod 5), 0)
    Delay 3000
    
    Call Ken_Logcat_I("选择第" & ChangeNavyLineNumber & "行的舰船")
    Call Ken_PointAddAndClick(ChangeNavyListPosition, 0, ChangeNavyListPositionOffset * (ChangeNavyLineNumber))
    Call ChangeNavySetNextShipIndex(ChangeNavyNeedChangePortIndex)//设置下一个要更换的INDEX
    Delay 1000
    If (Ken_FindPic("编成_列表_确定变更_disable")) Then
        Call Ken_Logcat_I("无法更改当前舰船。可能是在正在使用（入渠、已在舰队内），跳过至下一个定义的舰船ID再更换")
        //从舰船详情回到列表
        Call Ken_PointGetAndClick(ChangeNavyListNavyPosition)
        Delay 200//防卡
        Call Ken_PointGetAndClick(ChangeNavyListNavyPosition)
        Call ChangeNavyChangeInit()
    End If
    Call Ken_Logcat_I("确定变更，开始")
    Call Ken_FindPicUntilFoundThenClick("编成_列表_确定变更")
    Call Ken_DeleyForNet()
    Call Ken_Logcat_I("确定变更，结束")
End Function
//更换后，设置下一个要更换的INDEX
Function ChangeNavySetNextShipIndex(ChangeNavyNeedChangePortIndex)
    //如果当前舰船下标已经获取到最后一个，则从头重新开始
    If (ChangeNavyIDs + 1 > UBound(ChangeNavyIDArray)) Then 
        ChangeNavyIDs = 0
    Else 
        ChangeNavyIDs = ChangeNavyIDs + 1
    End If
    If (ChangeNavyNeedChangePortIndex = 0) Then 
        Form.Label_ChangeNavy_1.Caption = ChangeNavyIDs
    ElseIf (ChangeNavyNeedChangePortIndex = 1) Then
        Form.Label_ChangeNavy_2.Caption = ChangeNavyIDs
    ElseIf (ChangeNavyNeedChangePortIndex = 2) Then
        Form.Label_ChangeNavy_3.Caption = ChangeNavyIDs
    ElseIf (ChangeNavyNeedChangePortIndex = 3) Then
        Form.Label_ChangeNavy_4.Caption = ChangeNavyIDs
    ElseIf (ChangeNavyNeedChangePortIndex = 4) Then
        Form.Label_ChangeNavy_5.Caption = ChangeNavyIDs
    ElseIf (ChangeNavyNeedChangePortIndex = 5) Then 
        Form.Label_ChangeNavy_6.Caption = ChangeNavyIDs
    End If
    Call Ken_Logcat_D("ChangeNavyIDs:" & ChangeNavyIDs & "ChangeNavyPageCount:" & ChangeNavyPageCount & "ChangeNavyLineNumber:" & ChangeNavyLineNumber & "UBound(ChangeNavyIDArray):" & UBound(ChangeNavyIDArray))
End Function

//工厂开发
Function FactoryNavy()
    Dim FactoryNumberArray
    Call Ken_Logcat_I("工厂模块是否打开:" & Form.CB_AutoFactory.Value)
    If (Form.CB_AutoFactory.Value = 0) Then 
        Exit Function
    End If
    Call GoToScene("工厂")
    Delay 1000
    Call FactoryDev()
    Call FactoryBuild()
End Function

Function FactoryDev()
    Call Ken_Logcat_D("Int(Form.IB_Dev_RepeatCount.Text):" & Int(Form.IB_Dev_RepeatCount.Text))
    Call Ken_Logcat_D("IsNumeric(Form.IB_Dev_RepeatCount.Text):" & IsNumeric(Form.IB_Dev_RepeatCount.Text))
    While (Int(Form.IB_Dev_RepeatCount.Text) > 0)
        If (IsNumeric(Form.IB_Dev_RepeatCount.Text) = False)
            Call Ken_Logcat_I("开发次数文本框内容为空，或者不是数字")
            Exit Function
        End If

        Call Ken_FindPicUntilFoundThenClick("工厂_主界面_开发")
        Delay 200 //防卡
        If (Ken_FindPicUntilFound("工厂_开发_开发界面") = False) Then 
            Call Ken_Logcat_W ("没有成功打开开发界面，退出开发，回到母港")
            Call GoToMuGang()
            Exit Function
        End If
   	
        FactoryNumberArray = Split(Int(Form.IB_Dev_Oil.Text) & "|" & Int(Form.IB_Dev_Steel.Text) & "|" & Int(Form.IB_Dev_Ammo.Text) & "|" & Int(Form.IB_Dev_Lv.Text), "|")
   	
        Dim mIndex
        For mIndex = 0 To 3 Step 1
            Call FactoryCountClick(FactoryNumberArray(mIndex),FactoryPositionArray(mIndex),True)
        Next
    
        Call Ken_FindPicUntilFoundThenClick("工厂_开发_开发开始")
        Call Ken_DeleyForNet()
        Delay 5000
        Call Ken_FindPicUntilFoundThenClick("出击_结束_评价_返回")
        
        Form.IB_Dev_RepeatCount.Text = Int(Form.IB_Dev_RepeatCount.Text) - 1
    Wend
    Call Ken_Logcat_I("开发次数小于等于0，开发结束")
End Function
Function FactoryBuild()
    Call Ken_Logcat_D("Int(Form.IB_Build_RepeatCount.Text):" & Int(Form.IB_Build_RepeatCount.Text))
    While (Int(Form.IB_Build_RepeatCount.Text) > 0)
        If (IsNumeric(Form.IB_Build_RepeatCount.Text) = False)
            Call Ken_Logcat_I("建造次数文本框内容为空，或者不是数字")
            Exit Function
        End If
        
        If (Ken_FindPicAndClick("工厂_建造_建造完毕")) Then 
            Call Ken_Logcat_I("发现建造完毕的舰船，正在获取")
            Call Ken_DeleyForNet()
            Delay 5000
            Call Ken_FindPicUntilFoundThenClick("出击_结束_评价_返回")
        End If
        
        Call Ken_FindPicUntilFoundThenClick("工厂_建造_选择空位")
        Delay 200 //防卡
        If (Ken_FindPicUntilFound("工厂_建造_建造界面") = False) Then 
            Call Ken_Logcat_W ("没有成功打开建造界面，退出建造，回到母港")
            Call GoToMuGang()
            Exit Function
        End If
   	
        FactoryNumberArray = Split(Int(Form.IB_Build_Oil.Text) & "|" & Int(Form.IB_Build_Steel.Text) & "|" & Int(Form.IB_Build_Ammo.Text) & "|" & Int(Form.IB_Build_Lv.Text), "|")
   	
        Dim mIndex
        For mIndex = 0 To 3 Step 1
            Call FactoryCountClick(FactoryNumberArray(mIndex),FactoryPositionArray(mIndex),False)
        Next
    
        Call Ken_FindPicUntilFoundThenClick("工厂_建造_建造开始")
        Call Ken_DeleyForNet()
        Form.IB_Build_RepeatCount.Text = Int(Form.IB_Build_RepeatCount.Text) - 1
    Wend
    Call Ken_Logcat_I("建造次数小于等于0，建造结束")
End Function

Function FactoryCountClick(Number,Position,isDev)
    Dim Ge, Shi, Bai
    Dim Decrease
    If (isDev) Then 
        Decrease = 10
    Else 
        Decrease = 30
    End If
    
    Number = Number - Decrease
    
    Bai = Int(Number / 100)
    Shi = Int(Number / 10 mod 10)
    Ge = Int(Number mod 10)
    Call Ken_Logcat_D("Bai" & Bai & " Shi" & Shi & " Ge" & Ge & " Number" & Number & " Position" & Position)
	
    Dim Ken_LeftClickOnXY_Delay_Temp
    Ken_LeftClickOnXY_Delay_Temp = Ken_LeftClickOnXY_Delay
    Ken_LeftClickOnXY_Delay = 100
    Dim indexForBai,indexForShi,indexForGe
    For indexForBai = 0 To Bai - 1 Step 1
        Call Ken_PointAddAndClick(Position, 0, 30)
    Next
    For indexForShi = 0 To Shi - 1 Step 1
        Call Ken_PointAddAndClick(Position, 0, 0)
    Next
    For indexForGe = 0 To Ge - 1 Step 1
        Call Ken_PointAddAndClick(Position, -127, 17)
    Next
    Ken_LeftClickOnXY_Delay = Ken_LeftClickOnXY_Delay_Temp
End Function






















































/**********************************************************工具函数**********************************************************/
Function InitEnvironment()
    Dim fso
	
    ResourceFolder = Plugin.Sys.GetDir(0) & "\pic\"
    Call Ken_Logcat_I("资源路径为："&ResourceFolder)   	
    Set fso = CreateObject("Scripting.FileSystemObject")
    If (fso.FolderExists(ResourceFolder)) Then 
    Else 
        Call Ken_Logcat_I("释放资源开始")   	
        PutAttachment ResourceFolder, "*.bmp"
        Call Ken_Logcat_I("释放资源完毕") 
        Call Plugin.File.CreateFolder(Plugin.Sys.GetDir(0) & "\日志")
    End If
    DebugLogPath = ".\日志\"& "Debug_" & Ken_GetDateTimeStr() & ".txt"
    WarningLogPath = ".\日志\" & "Warning_" & Ken_GetDateTimeStr() & ".txt"
  	
End Function


/*获得游戏句柄*/
Function GetHwndForGame()
    Dim HwndEmbedding,HwndDocObject
    HwndTidu = Plugin.Window.Find(0, "提督業も忙しい！")
    HwndEmbedding = Plugin.Window.FIndex(HwndTidu, 0, "Shell Embedding", 0)
    HwndDocObject = Plugin.Window.FIndex(HwndEmbedding, 0, "Shell DocObject View", 0)
    HwndGame = Plugin.Window.FIndex(HwndDocObject, 0, "Internet Explorer_Server", 0)
    Call SetHwndByGame()
    If (Hwnd = 0) Then 
        MessageBox "找不到窗口句柄，程序结束"
        EndScript
    End If
    Call Plugin.Window.SetClientSize(HwndTidu, 800, 1000)
    Call Ken_Logcat_D("HwndTidu:" & HwndTidu)
    Call Ken_Logcat_D("HwndGame:" & HwndGame)
    Call Ken_Logcat_D("Hwnd:" & Hwnd)
End Function
Function SetHwndByGame()
    Hwnd = HwndGame
    ScreenHeight = 480
    ScreenWidth = 800
    PicDefinition = 0.9
    Call Ken_Logcat_D("SetHwndByGame.Hwnd:" & Hwnd)
End Function
Function SetHwndByTidu()
    Hwnd = HwndTidu
    ScreenHeight = 1000
    ScreenWidth = 800
    PicDefinition = 1.0
    Call Ken_Logcat_D("SetHwndByTidu.Hwnd:" & Hwnd)
End Function

/**第三方库查找图片**/
Function Lib_FindPic(picName)
    Call Plugin.BGCP2_02.FindPicture(Hwnd, 0, 0, ScreenWidth, ScreenHeight, ResourceFolder & picName & ".bmp", 50, PicDefinition, X, Y)
End Function
Function Lib_FindPicByRect(picName,StartX,StartY,EndX,EndY)
    Call Plugin.BGCP2_02.FindPicture(Hwnd, StartX ,StartY ,EndX ,EndY ,ResourceFolder & picName & ".bmp", 50, PicDefinition, X, Y)
End Function

Function Lib_FindPicByRectAndDefinition(picName,StartX,StartY,EndX,EndY,mPicDefinition)
    Call Plugin.BGCP2_02.FindPicture(Hwnd, StartX ,StartY ,EndX ,EndY ,ResourceFolder & picName & ".bmp", 50, mPicDefinition, X, Y)
End Function

/**查找图片**/
Function Ken_FindPic(picName)
    Call Lib_FindPic(picName)
    If X > - 1  Then //找到了
        Call Ken_Logcat_D("Ken_FindPic:" & picName & " FoundPic = true")
        Ken_FindPic = True
    Else //没知道，可能是被选中的状态，更换选中状态的图片再找一次
        Call Lib_FindPic(picName & "_touched")
        If X > - 1  Then 
            Ken_FindPic = True//找到了	
        Else 
            Call Ken_Logcat_D("Ken_FindPic:" & picName & " FoundPic = false")
            Ken_FindPic = False//真没找到
        End If
    End If
End Function
Function Ken_FindPicByRect(picName,StartX,StartY,EndX,EndY)
    Call Lib_FindPicByRect(picName,StartX,StartY,EndX,EndY)
    If X > - 1  Then //找到了	
        Ken_FindPicByRect = True
    Else //没知道，可能是被选中的状态，更换选中状态的图片再找一次
        Call Lib_FindPicByRect(picName & "_touched",StartX,StartY,EndX,EndY)
        If X > - 1  Then 
            Ken_FindPicByRect = True//找到了	
        Else 
            Ken_FindPicByRect = False//真没找到
        End If
        Call Ken_Logcat_D("Ken_FindPicByRect:" & picName & " Ken_FindPicByRect:"  & Ken_FindPicByRect &" StartX:" & StartX & " StartY:" & StartY & " EndX:" & EndX & " EndY:" & EndY)
    End If
End Function

Function Ken_FindPicByRectAndDefinition(picName,StartX,StartY,EndX,EndY,mPicDefinition)
    Call Lib_FindPicByRectAndDefinition(picName,StartX,StartY,EndX,EndY,mPicDefinition)
    If X > - 1  Then //找到了	
        Ken_FindPicByRectAndDefinition = True
    Else //没知道，可能是被选中的状态，更换选中状态的图片再找一次
        Call Lib_FindPicByRectAndDefinition(picName & "_touched",StartX,StartY,EndX,EndY,mPicDefinition)
        If X > - 1  Then 
            Ken_FindPicByRectAndDefinition = True//找到了	
        Else 
            Ken_FindPicByRectAndDefinition = False//真没找到
        End If
    End If
End Function

/**查找图片，找到就点没找到就算了**/
Function Ken_FindPicAndClick(picName)
    Ken_FindPicAndClick = False
    If (Ken_FindPic(picName)) Then 
        Ken_FindPicAndClick = Ken_LeftClickOnXY()
    End If
End Function

/**查找图片，直到超时或者图片位置点击**/
Function Ken_FindPicUntilFoundThenClick(picName)
    Call Ken_FindPicUntilFound(picName)
    Ken_FindPicUntilFoundThenClick = Ken_LeftClickOnXY()
End Function

/**查找图片，直到超时**/
Function Ken_FindPicUntilFound(picName)
    Dim Timeout
    Timeout = 0
    Do
        Delay 100
        Timeout = Timeout + 100
        If (Timeout >= 5000) Then 
            Ken_FindPicUntilFound = False
            Exit Function
        End If
    Loop While (Ken_FindPic(picName) = False)
    Ken_FindPicUntilFound = True
End Function

/**点击XY的位置**/
Function Ken_LeftClickOnXY()
    If X <= - 1  Then 
        Ken_LeftClickOnXY = False
        Exit Function
    End If
    Call Ken_Logcat_D("Ken_LeftClickOnXY x:" & X & " Y :" & Y)
    If (Y < 800) Then     	
        Call Plugin.Bkgnd.LeftClick(Hwnd, X, Y)
        Ken_LeftClickOnXY = True
    Else 
        Call Plugin.Bkgnd.LeftClick(HwndTidu, X, Y)
        Ken_LeftClickOnXY = True
    End If
    X = -1 
    Y = - 1 
    Delay Ken_LeftClickOnXY_Delay
End Function

/**存储坐标给某个变量**/
Function Ken_PointSet(positionX, positionY)
    Ken_PointSet = positionX & "|" & positionY
End Function

/**获得坐标从某个变量**/
Function Ken_PointGet(XY)
    Dim ZuoBiao
    ZuoBiao = InStr(XY, "|")
    X = Clng(Left(XY, ZuoBiao - 1)) : Y = Clng(Right(XY, Len(XY) - ZuoBiao))
End Function

/**获得坐标从某个变量，然后单击**/
Function Ken_PointGetAndClick(XY)
    Ken_PointGet (XY)
    
    Call Ken_LeftClickOnXY()
End Function

/**某个变量与坐标相加**/
Function Ken_PointAdd(XY,positionX,positionY)
    Call Ken_PointGet(XY)
    X = X + positionX
    Y = Y + positionY
End Function
/**某个变量与坐标相加，然后单击**/
Function Ken_PointAddAndClick(XY,positionX,positionY)
    Call Ken_PointAdd(XY,positionX,positionY)
    Call Ken_LeftClickOnXY()
End Function

/**点击坐标，直到出现图片**/
Function Ken_ClickUntilChangeTo(Position,PicName)
    Dim Timeout
    Timeout = 0
    Do While (Ken_FindPic(PicName) = False)
        Call Ken_PointGetAndClick(Position)
        Delay 100
        Timeout = Timeout + 100
        If (Timeout >= 5000) Then 
            Exit Function
        End If
    Loop
End Function

Function Ken_DeleyForNet()
    Call Ken_Logcat_D("网络等待")
    Dim FindTime, nCount
    FindTime = Plugin.Sys.GetTime()
    Do
        If (Ken_FindPicByRectAndDefinition("全局_载入中", 770, 450, 800, 480, 0.7)) Then 
            FindTime = Plugin.Sys.GetTime()
        End If
    Loop While (FindTime  + 1500 > Plugin.Sys.GetTime())
    Call Ken_Logcat_D("获取网络数据完毕")
End Function

Function Ken_Logcat_D(Log)
    If (Form.OB_Logcat_Debug.Value = 1) Then 
        Dim FileLenSave,FileLenNow
    
        FileLenSave = Plugin.File.GetFileLength(DebugLogPath)
        Call Plugin.File.WriteFileEx(DebugLogPath, Log)
        TracePrint Log
        FileLenNow = Plugin.File.GetFileLength(DebugLogPath)
    
        HwndFile = Plugin.File.OpenFile(DebugLogPath)
        Call Plugin.File.SeekFile(HwndFile,FileLenSave)
        
        LogcatFileStr = Plugin.File.ReadFile(HwndFile, FileLenNow - FileLenSave)
        Form.IB_Logcat.Text = LogcatFileStr & Form.IB_Logcat.Text

        Plugin.File.CloseFile (HwndFile)
        FileLenSave = FileLenNow
    Else 
        Call Plugin.File.WriteFileEx(DebugLogPath, Log)
        TracePrint Log
    End If
    
End Function

Function Ken_Logcat_I(Log)
    Dim FileLenSave,FileLenNow
    
    FileLenSave = Plugin.File.GetFileLength(DebugLogPath)
    Call Ken_Logcat_D(Log)
    FileLenNow = Plugin.File.GetFileLength(DebugLogPath)
    
    HwndFile = Plugin.File.OpenFile(DebugLogPath)
    Call Plugin.File.SeekFile(HwndFile,FileLenSave)
        
    LogcatFileStr = Plugin.File.ReadFile(HwndFile, FileLenNow - FileLenSave)
    Form.IB_Logcat.Text = LogcatFileStr & Form.IB_Logcat.Text

    Call Plugin.File.CloseFile (HwndFile)
    FileLenSave = FileLenNow
    
End Function

Function Ken_Logcat_W(Log)
    Call Ken_Logcat_I(Log)
    
    Call Plugin.BGCP2_02.SavePicture(HwndTidu,0,0,800,1000, "./日志/" & Ken_GetDateTimeStr() &"_"& Log &".png")
End Function

Function Ken_GetDateTimeStr()
    Ken_GetDateTimeStr = Year(now) & "_" & Month(now) & "_" & Day(now) & "_" & Hour(now) & "_" & Minute(now) & "_" & Second(now)
End Function
