[General]
SyntaxVersion=2
BeginHotkey=121
BeginHotkeyMod=0
PauseHotkey=19
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=7b0fd93b-ec20-46c4-87a5-4547b1cc55e9
Description=舰娘
Enable=1
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=1
QUI=Form
[Relative]
SetupOCXFile=
[Comment]

[UIPackage]
UEsDBBQAAgAIAGoRZ0aKKrjs2nEAAAjKBgAJABEAVUlQYWNrYWdlVVQNAAc5XvpUOV76VDle+lTsXQl8VNXVP28I+yK7iCi41AVRMzPZULROkgEik0zMwuYyBAwSlkwMAUVccMUFcK3auktbraV1AyqiYluLWJXyKaIfX21trVWrXz+XVtrPCj3nvTd5L8mk5Lx3kmOE6+/IMLw355777j33/z/3vnO7gFW2/WbAOw88PvwP0KycCl1g956e0M31XXcUI/WX/gAB/GMAyu49e/akvl4G1kXL6EK8YBld1AVgz/7ytSxfoWTgIzoOhZ51V/s590LpgdITpTdKX5Q+KP2sRw8HoAy1n/9AlEEog1GGoAxDORDlIJSDUYajjEA5FOUQlJEoh6OMQjkM5QiUb6EciXIUyjEoR6McizIGZTTK8SgJlBNRTkDJRAmhBFHCKDkoWSjZKLkoY1HyUE5CGYdyMsopKN82+zbAaSj5KBGUApQoSiHKeJQilAkoE1FOR4mhTEIpRomjlKCUopShnIFSjlKJUoEyGWUayhSUqSjTUc5CORPlbJQZKOegVKHcijILZSbKuSizUapRzkOpQZmDMhdlPso8lAUodSi1KEmU81EWotSjNKAsRlmEcgHKEpQLUS5CuRhlKcolKJehXIpyOcqVpg1J/K8Bn0UUf7cBf2sJcMpQ7DGpvmTs5dplf/rn8syp2wx0B/D8yID5XSW2diZ4Lz3AMFL6ISP9Naf9/VNTb0q/+98K8KnFfNSgl0t/V/jP+lN/uv+tAtu7Dp96CfaIBebT55WBEDD103jc4/LDeyuppiLfrSWp8X+47QOOtP3AUfb4P8b2AaNt/zTG9gMn2H4g0x7/IdsHpMZ/ju0D8mw/cJI9/sfZPuBU2w+cZo//fNsHFNp+YLw9/jXbpqNkfLJ+gY/hB37vN8Bf8Xu/37L2sVfeCyrq/+STT3zd79XvOP4v0ATbtfWZpfwPzTpVOAPO91iHfuj/CJ90Z/i/gEv/ZJxpF6J4rUF/1N8HHHzblnu6uPSXodYqnP3j2A7zmXNvyv93AwuvtVV/hkt/Beq/0EQPnp+/wX3+XW0B0+8m0e4k4g5vNRnsQX83l/2O/nx8DrNMnMXUbz7Pnoz2797s+c/y2f6EzXsw9PcAC8O7ywwcFCu0namH8kV6m01ListHlVfVLhxVXl1fM7ud9FdUzSxI1jbUJ+d7vj9RkKz37ID9PrLp6Hnq0f9UmyyCX/p58P89Xf0/hmOPP+qa9v9+9u+1VX8vl/7xqL/W3/hj20/z1Tj7cwS9Tw0yvlpzFq714v/Y+vs08X/Ef4I+7DcMmk8Jtw9q5ZoU7ykd8Vm78J9DgTf/9rX7ABUN/EP9tYf9WQL/UJxlGKP/HwCy+Gc4s/37gyz+objTAIb9A0AU/7CfvzteKoV/jmDYP9Blfyec8psUv/yH7KcY6Cx0YqsMb/drFr/4RwL/Usx3JKP/DQJZ/Esx5kMY+geDg3818M8QkMU/I+wx3Vb9Q0EX/9DaQAr/FKHuapyBF3rU3wftJ3sOY9hPc+Vo+3M5ap9v98FqMwrPKwM92H8QuOcfmv1TY88ZjW0tw9F+as8jGfYPd+nvARnb17+xK+PJLzbuynhiw1P/yNjy0Yu7Mx5/58mXMjZ8/8mHMra8seO5jJc+2PHL9L+V4dN/+fXffu/XLgN93r+SfFBRfiK/sihWmCiviEZj5hJeLJIfjYWDzudQDn0eVZCfKK8sLY1NS0yZGC1JRK3+t9BzDxzhof8f7Oo35TjulnhGv+b4Z+sf0WL8LTRngRqbgVWh1Jh+ce9llAf9h6TRPxF1Ew+cw/TFQz3oPxSaxr8sm2vwT/KAPI98KPqfUWCt4bRVP2GF3r1S+ol/hjz3f/f62zGtXJPine3FP0l3NsP+ieDwPw3+SevbKfwztTRaWFRRFC9J5EfHx8ui5p4OdBJl0dJIUVli+sR4yYTSOEU4B+G3kYqKSMGkkqIJEyvG0/+MRveSFaQeNSS/oiQRi08oiFQk4qXRkvHxWGG0rJvjkELkhA5o/CXTF02jX+nv6JxaFIk3V5nAuhVHqJ4ulZku75ZN6vuSessTRgoLXX4w7Loyi67sZn4eS0qGOEpiRcVFFYmCeGWJ27Iw3dBzQlm8sjQ/PjWPrOmJHtcy07EtO7N70yqbDrYwUho3GhXmOT8bMn/WVhGizwfhrQUTIyUToiWRybZ/ttrCuTI7SEoGmp/dF+dkpP06O/3XWem/Dqf/OpT+66Cr/qYeapTC6OREbLKrtUPUxCOazTp2Azk9zro4aLqBfk5PoMaj+4c2a1S7V7qekWlRL7sC8SLXHBgy6znQ+YWCidGCSXiJYX9tVyz1NTjVCTs9JZeuHo5XR50BQ60QTmBj5Mdo1dj85+bPz66pq6lync/BzECjAlqzNgdepLIi7ihxahPKpCocnkZHQbzEurgYb6osznD9kHOpqwZmX+lNQ4Uayx4oVi2yXdYHSV+/eKqjJ4pwNLtGch7d1d8ZcGXR4vjkKH3ZI2bDEfpL70ZsYnWLfnbNxkcKKuJl01KXmDUpLo53dQ+1sKs2ZqV7NT6uYKDJX8NN/xpq+tcsp5mzwOnLdn8oKimMTiVbe5pdAPW6e/ZY53N4rNVQZm2bVDTk6sO5TqcJ068emOaJUb/OaNqvI+MromV2v3f16zzTrTW2YaqJBjd+g3dEIxWmy6J/GPmf+kcsPqWJKws6ioLmABrZtIMXF5WX45/RydhY9HPm8NzLNeE2XJMF6QdTyDWYrBYMUQ2HNRu7jfa4qp/ttLrLqnAWtUkfu381guN0jtZq+Yym84HLBbcy/rNcVXb5mOJIaYzMNZo+ZLshGv+p8UmYneYAZ6wVRvMrJ7gGW3aT7paTmkRtNzklWmT5yb724LK+bzqDmvM1/kBJoWG3idWBbGfZL+UPnHFs6za1DbTbsFl3s13T2CbVy3b+JWj1X7taVkVI/ZCi1ubcfo5HLo+XVdDAGoYXl0crKopKJiRMKxLxSvxbcbS7U8lcV23ymtQmy90w1i8HmuINazajy/pZjsH99Gw7xho2z3L6jdnlmn6V0/KrrJZfhVt+FWz5VcjleNxAJ7fR79p9pSAWjZR184ofC+ZUz5qXn7zQ8/3YjNV1VTX1iZKqxUsS7IWkzr7/Z8fGrWu2/W7dztc2Pvvg+tc7Xr/f+IfE+hPtxxvN4D+0p1Zw/YnNfyaB7PoTzYvHM+yPgfz+myyG/mKw1iDN8Su0/hRm6C8B2f03tF90DEN/HGTXH2gf6nEM/aWgu/5whst+6jc/Q3kQ5VUP+l/w6b/8+m/t/T+dff1UYv2JJv2jGf2/DHTXn+h9jXGN/meO6QHmeVr9sfY/0F70Yxn2V0BL/1/mKfrrbf9PJejG3ye79Gvsf5oCzfc/hX30P8Pob//m2Fau6Yj4cwGj/9F7San9t7GqmdXzwXsx708UV9XFqhd7+aHOjv/XvfXqM6uf1tPfGff/0/txKfwpwT/oXZ6TGf1/OsjufzsNrPeG2qr/TJDlH/R+06kM/WeB7v5/eg8yFbCQ4h+FDPvPAVn+Qe+ancLQnwBZ/kHvsI1j6J8BDv84ESw8RnNClQf9M3z6r86O/7WL3/idBv+sAtn9b/T+Zh6j/88EXf4xC3T3/58Lbv9fj8+jFufAOvyznl2HYR70V4Mb/y9CfUnkITVwkTf8y9Y/G5rj/ywfz9/Zf1LUyjUdgf8nM/o/5RfQ3H9CeQ362p8l8B/F8yYx7K8B3fjzXJDFf+VgxVTbqn+eu//nJyKLGpKRhoaqWV68cGfnb29uX/8o7X3V0u+Xv9FeXop9U46PfA/3S+H/Skb/m+/yP1L4v4KhfwHI4n/KFVHM0F8Lsvif4vkxhv4k6K4/1IEs/iP+MpFh//mgi/+opSXjz7SedDrD/oUu++M+/df+9Rvd4pf/aaw/NIDu+sMi0F1/WAzN+Ue2D/9jGJSviDD19Fau6Qj+cR7D/1B+Mk3+QYNFkn/MACum2lb9S0CXf1wELfC/tYdLwX9+HfA/vfGmpV8b/0vwT8ItCUb/Xwry6w+zGfovBnn+Uc3QfwnI8g+K3Z/D0H8pyPIPiqeezdB/Gejyj2Ugyz8onjuNYf/loMs/rgCHf+wLOQ61ZafHdv7A431fMO67x+f8tZ//6ZaC5IKZST/79wXiD7SedybD/10JuvvfrgJd/nk16PLPa6A5/8zxMf8461+tzaLtzT8XAy//1HLQ5Z/XgpMrTYJ/UjxzAWP8XQdN+Z+59jO+5rw5DWXJRbU8L9DZ+Z/fwki53aovonjsM3a/4Jb5Pusvsf+tnjn+rgfZ9U9qgzpG/78B5PnnIob+9sj/xmn/FSDLP2k9PcmwfyXI8k8aP7UM/atAl3/eCLL8k1pvLsP+m0Au/59f/I74IdMIGiEjbGQZ2UaOkWvkGWOhw4rA+6/W/JmYMqe6NjG1pipZmmTcrz1/asQfbgbR/G9s/beAlQOPikb+t1uhOf7O9dH+hkHond7hu6iVazpi/Wc5w//cBrr4+ztg5WCkIoG/l4EVU26r/ttBd/3nDpDFX4RhL2PYfyfI469rGPq/C1YObGv8yeCvqxn6vwey+Ismr0sZ+u8C/3kbU2XbA5s3b3rpte1ae+j8rp/9AL3hGupHAYBfeLh/sc/6a+MvCfxN6wmXMPrf3aCLv+8BWfxN8cwlDPvvBd31n/tAdv8ZrWctZdh/P+jGfx8A3fjvg6Ab/10Ncv5/X98/RynBLqyrPremoSZZa+ZAykpEa6tmzm9jh9Lmfxb/yPPhf5z4/w2tXNMR/ONOhv/5Pujyjx+AtW+HigT/ID69kmH/D0GXfzwEsvyD+NxNDPsfBnn+cQdD/49Afv/R7Qz9j4Cc/1+38+UXdDKfWcUv/qf3nwmPEX9b7+H+Ep/118b/EvyT1hNvZPS/H4Ns/J/iaasY+teALv/4CcjyD4qnXc+w/6egyz8eBVn+QfHcFQz7HwNd/vE46PKPJ2A//m/0f373TzWu/3jLgaSN/zX455PQfP3D+4If8Q/aN0GY7u5WrknxjhkF7cM/HgLe/oe1oMs/1oFz7owE/6B4xr3Qdv+7HmTzL61mtv/PQJZ/UDzxAYb9T4E8//gheNt/ol38VoXee6B3WIkDesEPZ/usvzZ+7w7u3RMZG/+6/lGWfo39RxtAdv2L1tPuZ/T/p0GWf1A86T6G/o2gyz+eAVn+QfGsuxj2Pwu6/OM50N1/sgmc/b8a+0+eBzn8L4ifaxYurEnWMjH0/v3H/ubP1PnfmZ77vxP//3Er16Rwd3vh7/XAw38/B138TfsMUvvPJPA3xRN+Am33v78EWfz9BLP9XwBZ/E3xvMcY9v8K5PH3Oug8+783gyz+ovWMRxn2vwiy+IviCT9l6N8CuvjrJZDFXxRPeIRh/69d+skXEn96D7zxpyrwV7T5U1cXfwKFIoCfXPsPbAxFEMrci7D3c1U18PfLoIu/XwFn/6cG/n4Vmsc/gxD0bL9h0H7WN8DitelKe+OvXwFv/t8KuvjrN2CdQUxFAn89Dxanbqv+bSCLv37ObP//Arn3f/Z1/kSxDMq/19cAT89vgnL7S+BvimdtYvT/10Aef78AnQd/vw6y+JvWE55j2L8dZPH3L+xx0Fb9b4Au/t4Bsvib+PQGhv1vgm788y1w8Jdf/Hw0tHx7MxDMDASDgWAoEAwHglmBYHYgmBMI5gaCeYHg2EAoMxAKBkKhQCgcCGUFQtmBUE4glBsI5QVCYwPhzEA4GAiHAuFwIJwVCGcHwjmBcG4gnBcIt8N7oe2Lv/d+rpT2/KuBv/8brPe1qWjg7/+Blvg75Nl+J/75UivXtDf+3g48/Pdb0MXfb4Ms/iY8/zLD//4OZPH3Nmb7/x5k458Uz9nKsP8dkFv/8Vsk8DflkyX8vcLD/XU+668dv/I7/0rh79eh8+DvP4As/qZ49qsM+/8Isvib+PwrDP3vgi7+/hPI4m/ik1sY9r8Huvj7z6Ab/3wfHPz1zcbfez/XaV+Pf2ng7w+hJf72egIv4e/Ntk95q5Vr2ht/vws8/PcX0MXfH4Es/iY8vRPa7n8/Bln8/Xtm+/8vyOJv4rNvM+z/K8jHP/8InQd//R/I4i+K5/2WYf8nIIu/3gErptBW/Z+CLv76zGW/BP+6Hyz+tc7D/QvBX+ns/Esbf0ngb+JTbzL6/+egi7//Brr4+++gG//cBS3xV5Zn+5345/utXNPe+It0/43R//4BuvjrnyCb/4HwzIcM+//f/fzF85+EOlX+E79l3c71uztz/gON/B9fgiz+Jjz1MaP//wvk8ffnDP1fgXz+j88Y+neDLP6meNpHDP17QBZ/E5/4C0M/OQ1N/G0YsvFP8gB/ZtgfcOnffz7Pvi2U/4Zy2FD+Gy9n7MR8zl/7zw/SLRr8q4shm/+F4mkfMPxfhqGb/6WroZv/pZuhm3+yu9GSf2Z7tt8waP3/AsPidelKR/BPmlPban8Pg947sYoG/+yJ+rvZn2NVM6v9nCFj3h/yfn9n538b3tr08Oqn9fT75X8S8QfiExRTaGv/62XIrv+YfIIx/nobsvyT4jlfMezvY8jzT8747+sa/1L8swuj/fsZsvyTzrv8F6P9DzBk+Sc5oS8Z+vsr888BLvspb2k5WOs4Mz3oPxf8lc6O/7WL7/lbIP5A8YxdjP4/0NBd/xnk4h8a+HdwE/9fj36vFufAOvyznl2HYR70D2mC/xehviT6gBq4yBv+Zesfmgb/ez2B1L3+1KMVZ9IR+H8gY/47UBn/D2uO/8OgVrTx+5b3N3y59ZHM1Wu2f7Zj49rP1u18beNTXzz39rp3Ix2j3y9+p3dO6Aya8w0rhsctEvif8FwvRv8/SBj/E54bzNA/XBj/E5/uy9B/sDL+H2E4689S+H8Qw/5DhPE/xbP6MPQfKoz/Cc/3ZugfqYz/R7nsT4K/sh+/+ysi8bcsH/cL4H/ik90Z/f8wZfx/uDL+P0IZ/x+pjP+/lQb/ez0BlfA/rafQbw5TxP+HM/r/Ucr4/2gX/pfAfzSfDmfYf4ww/qP59EiG/mOF8R/h2UMY+kcr47/jDGf/UWdff9mydeunRYV6KzB++Rud20LxV8of5SX+errP+kvh/yMY/X+MMP6neNIIhv7jhfE/4emDGfpPUMb/JwrvPyM8dyDD/kxl/BdUxn8hZfwXNuTyv+3nbwL8zUfmUf/n/3Q8/s9Kg/+9nkDqjv8fsxf8Xze3/fB/iOH/spXxf44w/qf5bDTD/lxh/E/zWRZDf54w/ic+cTxD/1hl/H+SIP73W74J+J3OnyL8/oSH+8/3WX//5z/L4P8wo/+fLIz/KZ4yhqF/nDD+Jzx7HEP/Kcr4/1Rh/E94+miG/d9Wxv+nKeP/iDL+z3fp34/fBfB7jvf79c//7Hj8X5AG/3tNbUD4n/YzTTYsXJeupHB/e+L/fIb/K1TG/1Fh/E/zyUkM+8cL43+aTwoZ+icI43/C86cw9E9Uxv9FLvzvt3wT8PtSsPD79R7ur/dZf+34mxT+L2D0/9OF8T/FM8Yx9E8Sxv+EJ09m6I8p4/9iYfxPeDaXYX+JMv6PK+P/UmX8f4bx9cn/7LcI5K+JLGpIOjlsmPd39vXzr7DPXIF/XoVyDVh7iJeDNRdei3Idyg0oK8HKr70K5SaUG1FuRrkN5Rawzt+mPJz0PtHtKHei0LnMdDYVnQ1MZ6TfDdY58feDdV4ynZlOZyfT+fEUQ6NzhB9CobPMHwbrTDs6W5DOFaXzLemcRzrnj856pPMG6dxLOvuP4m50Bh6dA0o56Oh8dzqPg85FIWBC7zbRGTU0x9M5Kc+DdV4NnZtEZ3fQ+SV0fgzlcaazrCiXML3TR3nVaX815Zan/M6UY5nyrFO+d8o5T3mXKfc+5R+mBEB0rgnlQaN8hJSLlHJiUm5Iyg1I+SEpRyHlynwHrBzwlDeNcodS7kbKX0o5PCiXCuXRonxO9E475TWh/E6UX4Vy3NC77oR4KOcJ5b2hvDOU+4XyX9F7cJRbjN7Fofcx6X1oei+NYtP0fiK9I0fvatL7OuQo6J1lDf5X1oL/hUTOn52oyP8qGfNfuaGbf6wC9Q+wP0vwP5rPT2fYXynL/9j2Txbmf9Sfixn2T2kH/lfB0D/V1f/e3L7+0e3r39ilNf/45W/0HsMYlFko+R7uP8Fn/Tv7/gkp/lfO6H/ThPkfxZNiDP3Thfkf4flJDP1nKvO/s4T5H/GJCQz7z1bmf+cI5x8iPlnEsD+hnH9ohuD+L+0isn6T6/3+zs7/NPJPVSnnn5qZhn/4OX+Z1lNmG9a8lq50BP+YxfA/s5TXn84VXn8if3omw/5q4fUn8qfVDP2zhfkH4ZlzGPrPU15/mtMO7x+fy7C/Rhh/Ep87m6F/rjD+JH96FkP/PBf+fPKLjbt+/fjqNc98/MSHzz64ds3mzS9/8ubaV9Z01IqeX/5Hr75SPJBibps83H+Bz/p3dv6nwT/mC/MPms+nMvr/AmX+Uau8/pRUXn+qU37/+Pw0+E/i/N8aRfy3mNH/6wX3f/gt8udPhPex8ye2fOXn/AkN/L/QkD3/hPzZPEb/b1Bef1gkjP+pPWsZ9i9uB/y/iKH/AkP+/IsGhv4LhfE/8akFDP1LhPE/zWfzGfovcuF/v8UvfqfzByh/Ge07WOXh/mKf9d/Xzx/QwP9LhfE/4Zk5jP5/sTL+v0R4/YHw9FyG/Zcqrz9cpnz+wTLl+PPlafiHn/OP6X3ijYbl19OVFO9YdnNL/rH/DJx9W0C5CPC/suq6qpr6RGFVnYdkhp2d/639fPPmLR+9uNvr/VLxh+WM+ecK5f1vVxqEW6wiwT9pPrmYYf9VyvzzamH+SfZcxrD/mnbgn9cw9C9vB/55NUP/tcL8k/jspQz91wnu/5fgf1PB2kte6+H+533Wf1/nfxLxB/LnlzD63/XK+99uEOafNJ8sYdi/Qpl/rhTmn8RnljLsX6XMP29U5p83KfPPm79G739JvL/V0FA1a15iypzq2sT0Ocna80oZPKCz4/8d2zZv3vTSa9tpH4en9rPjD15TiLvXP29opTFScYd08Qcp/nEnw//cosw/bkX9Q+3PEvyDxvNKhv23KfOP7wjzD/q9mxj2394O/OMOhn66tk/j+JPhH7cz9N/5NcL/lDuE3utcbVjvYXLLIp/139fxvwT/JD55I6P/fVd4/ZP86SqG/u8p84+7hPkH+fPrGfbfrcw/7hHmHzSfr2DYf68y/7hPmX/c/83F/4VVpbxFgG9C/N8P/tfgnw+kWf/0c/47xVMfMSy/lq50BP/4EcP//Ju96wCPqlrC2V3AB4oFFBFREUHBmtBRUOkGaQIKFkRKgAgkARI6CFjAjg1FFMguJYRAek8IkJAGKaQhCFJEUUFFKUEw+Ga4u7LvsXzs3Ds3kyV7/H5cMXf+zO65Z///njJmYf+BWqu+9TWH/8B8lhPyXyXsP1Yz+481BqVPO8u/Rgf/EULgX6uD/1hL4A9hnv9APbeSwL+OWX9if15B4A8V1p/rq5D/w/Ny0P91Uun/AjX+/tXd/3H4DxxPlxH6f5iw/9jA7D/w+/RrQv4bhf1HuLD/iBCe/4h0oD856o9vuIL+XJygn/5MIvS/qKtr/491/ddQ3xH+A8grwFzd/xUGa1v/JeE/ou30D4f/wHjhhP4fI+w/Ypn9R7xBuaed5Y/TwX8kEvjjdVh/lUDgT2D2H6inIwn8icz+A/tTBIE/qQrt/8EzLnH9F54fqGb911aNv797/0/l+89k5vkPHM/CCP0/Rdh/pDL7D/w+20jIf5Ow/0gT9h+bhf3HFgf+Q0v9c5xP3WdQPldHzeY7HPkP6can/8lLv1jGz6qw/qsq7P/YThh/tgrPf6Qzn3+cYVDGFGf5M4T9xzZm/5FtUN5TZ/kzdfAfuQT+LB38Rw6BP5vZf6Ce2Urgz6lCz/+xtgDqfzzjXo3+36Lx93fv/9DuP/F+3kLof7nC81/bmf0HjiephPx3CPuPPGb/gd8naYT884X9R4Gw/ygU9h87r8b1X/18x44L7Il/VOr4Ka3/09Ni8uNSUs8UJZamqnr/rP6zg+r+f3H+q0CF/+TyH3sJ40+RsP8oZl5/VWpQ7mln+UuE/Ucps//YbVBycpa/TAf/8S2Bf5cO66/2EPi/qUL6H/edPWJQ6oQ9rmIw9dX4+7v3f2j3n6gniwn9bzfz/BfeT0UE/j3C/uNbZv+B93M+If+9wv5jH7P/wPG8kJD/d8L+Y7+w/zhQhfQ/S/0WL/XXXw36P/VMcnlMfm6FmjP7JfznQQfzXx1V93+DAZ+n/GpQ+rWjVhn+4xfC+HNIuP7K98z1V340KDk5y3+Yuf7KEYh3jMD/A7P/wP78A4H/R+H6K0fszj/j8h9HCfn/xDz/gd/nhwn8PzPrT8znewL/L8L682gVO/8L9/Bj/emFKq7fpvH3d3X/p7Vx+A+8n/YT+v8xYf/xq3D9ld+E66/8Llx/5fgl+q81S/3v44L67yyh//8hrP/+tNN/mscPDv/WwUOsSfu3rKPZ8dkFOHtTXBj5TVFoye6dwSV/WMISi5LP5iYWp+P/KTiXlBGZnVoQc4Kfn0P/nzYofcrZ/neCWf+XQ7y/CfwnmfU/3s+nCPynhPU/fl62uudc+v8cIf9yZv2P36cnCfxnmPU/xjtB4P9LWP+ftctfq35f4qHM3+Cenk4qBtNMjeNXddfvWhuH/sf+/Duh/58T1v9/C+v/CmH9f15Y///jQP9rqb99Cv5dywR/GB3/jE33r9yvn/6vY3S+/+PvKan/DcaL+t9dA6V6g8W/dfQQa9L+DefesiKS8lIP5p5JOhGXknww5VjUIdyRs+NUynn9+bXqNw7/VwvGEyNh/MOf5fR/10C86wj8JiOv/8PxtCaBv4ZR1v/h73qn9TWX/7uWkH8tI6//u6BnCPzXGHn933+MSp9ylh9/XtL/1bbLH+vwYv3Ewx5KXTpqy9I4frn9m7am+fubwf9hf/qH4P/qGGX9H45Vkv7vOqOs/6trlPV/1xsv9X+tVH7+9vM/N17G/9l8n57+rxFh/L9B2P/h+3SN/fjhpWEBncYmrd93mYsOWcLwFGU8QTkyeWdwWWFupCUsLSdjb/LB2JSyrdFbYsJa9PGfEthSD36t+t32/d3BWoOP2jj0fwPoT/UI/f8mZv1/K8RrTOCvx6z/MZ9bCPz1hfX/zcD/oPU1l/6/nZD/Lcz6H79PbibwN2DW/w2NymfqLP+twvq/oV3+ORrHL7d+19Z41r+3Un89g/6/zahoGmf7323C+r+RsP6/XVj/NxbW/3c40P+tVX7+qP/RzzwEaCKo/+8n9P87hfX/XXb6n0P/3QvxmhLyb8Ks/+5DPUPgv5tZ/2G85gT+psL67x7gb+HB0+TXzyXG7Awu2pkWmnky1RxXbAlLTy4uxP+KzcD/jkouCsWf0Iufy789YFD3/LWRxg+AS/8/QOj/zZj1P46nzQj8zZn1fwujck85y3+vsP6/z8i7/7ilUflOcZa/hbD+ayms/+4X1n8P2PG7/ZvG8ZOtft2goIAAuv7Q+vlJ6P8HHeh/jvrTnoL6vzNh/EOvInn+0MPo162vOfR/O4jXipD/I0bZ84c8mfX/oxCvLSF/Lx30fycCP35Wnkzjh9aGsy65kVlpZZlRiQlnYvcUJaNqb5F5sjgd/6KoJCUCp2Rs/4N9Dobj/CJcA4H118tUXH+7xg+A7/wfbfr/MUL/a82s/3E8a0Pgb8Os/zsYlZyc5W8rrP/bMev/jkZlTHeWv72w/u9g5D1/CPPxIuTf0Sh7/tCjdvyufn6ZdOPQ/0GB/ij+J8xQcb3W90/i/KnHjLLn33Zy4D+01J/G+YxXAF2u4D8iap3QzX/0I4w/nYX9x+PAX9f6msN/9IJ43Qj5PyHsP55k9h9PQ7yehPy7MD7/0dp2lcSFo9CX4ud4fo9raWYDuqq4vrGw/ufyn30J/a+rkb/+Rh8Cfzdm/4HjSQ8Cf3dm/+FtVGI6y99D2H/0ZPYfvY3KmOosfy9h//EUs//AeF0J+Xu79T9bY9D/ivZX+QCca/yvTP/Z2yh7/u3Twv6jjwP/wVF/fOBl/IfNd+jpP4YTxp++wv4DvVId62sO/zEU4g0m5N9f2H8MqEL6P3bP9gvrdKT4tep/1P5rAQsAaSquf0JY/3P4z5egPw0h9P9ndJj/epnAP1AH/zGMwD+I2X/g/fwcgX8ws/94AeI9S+B/Vth/PMfsP140Kn3aWf4hwv5jqJ3/cOt/bY1N/6vcwqF9/le7/3zeqIxpzva/54Xnv14Q9h8vCvuPlxz4Dy31x1HPTgKMEvQfAYT+N0zYf7zM7D98IZ4PIf/hwv7jFeb5j4kQbxwh/xE66E9/Av9IHfSnH4F/VJXyf3HnXd3/YQ069H/zVVzfucqs/1LvP/B+Gkvof6OZ/cd4iDeGwO8j7D/GMPuPCUZlTHGWf6yw/xjHPP/xqlHpU87y+wrrz1eF9ed49/wPW2Pzfyo3QGvf/1H5/mOCA//BUX86UNB/zCeMPxOF/Ycfs/+YCfGmEvL3F/YfAcz+Yy7Em0HIf5IO/mMegX+yXf+T1//ZFa6u/xd5KPp/pYrrH79K9n+8Ruh/U5jnP7A/TyfwBzL7j9kQbxqBP0jYf0xl9h9zjMpn6iz/NGH/MZ3Zf8wyKp+ps/wzhP3HTLf+Z2ts+l/lEZyuuP9jlvD8x2wH/kNL/Wncz7AN8OYV/Mfmh/TzHx8Txp85wv5jLrP/eBfiLSTk/5qw/5jH7D8+hHjvEPKfb8fvroFSvSHv/5SN/VL8HP6vt4fi/0aquL7TVbL/5yPC+LNAh/nPxQT+15n9J8Z7m8D/BrP/fB/iLSLwvynsP99i9p8fGJX31Fn+hcL+cxGz/3zPqLynzvK/7fZ/bI3n/GZPsd9f4vnDO8Lzn+8K+8/3LvGfbTw8Ved/cf5ryWX8p8136uk/VxLGn/eFzz/+gPn8468g3heE/D9kPv/4a4hnJvAvtuOvgGtqQI8wAWoC/gOoBbgGUBtwLaAO4DrA9YC6gBsAN2ENa0A9wM2A+oBbALcCGgAaGpSzrW4zKGfU4j73OwF3AO4C3A1oAmgKaAa4B9AccB/gXkALwP2AltazcR8GPGhQak2/AmgF8AR4AVoD2gLaANpZa6G0B3QEPAZ41FqbGudacL0V7rnpAngS0BXQHdAN0APQC9AT8BSgN8Ab8DSgL6APoB/gGUB/wADAQMBgwCDAs4AhgOcAQwEvAJ4HvAgYBngJ8DJgBGA4YCTgM4APYBRgNGAMYBxgLMAXMB7wKmACwA8wEeAPmAQIMChnBwcCpgCCANMAUwHTAbMAMwAzAbMBcwFzrHViFljPG5b+/i2JKy1PylNOgcPqmdHm3JKImNLSopKcggvnN+t8NgTX+c3l8O95Kt7M8cIfAMfzp89hPFlGGH8+Ej7/HJ+VNrO+5vKfwYT8P2H2n59CvC8J/J8y+8/lEG8pgf8zYf+5hNl/rjAqOTnL/7mw//yiCu3/km5s83fDh4zz8bOd5dzVZ4z/ZKfknNbh3xXX/y0VPv/8S+H6N8sc+D+1FRjR/+H3SQxgjaD/iyaMf18Jzz+iX2psfc3h/8IgXggh/+XC848rmOcfIyDeekL+K3XQf1EE/mC7+Wcu/RdJ4Dcz679VEC+UwG+x49fa0LllRcid4Mdxfjf+6uEeynMOapsgPH+nVb9x6P+N0J/WEfrfKmH9v5pZ/4cblZjO8q8R1v9rmeefNhiVmM7yhwivf1wnPP8QKjz/sJ5x/Hev3/wf/9djeoDPaN9AX38/ggeUfP9t/kNtBVn7+ad4Qf+RQRh/woT9B46XTayvOfxHKsRLJOS/Udh/hDP7jy0QL4WQf4QO/iOdwB+pg//YSuCPYhz/cf7G1fU/zmGi/m+mYjD1c3H9z+E/Y6E/JRP6XzTz/EMaxEsi8McI+49YZv+xGeLFEfKPE/Yf8cz+YxPESyDknyDsPxKF/UcS4/k/rq7/vf0CggI16H/vrsO7jRvhN9an34ipavZwVcf5n2QH8x8qj7+44D/weeYPgOwr+I/Cwfr5jyLC+JMi7D/QL1xvfc3hP/IhXi4h/03M698KIF4xgT+N2X/kQLw8Av9m4fUv5538ucpoWn8VHLijAWcB2Squn+Ti+l1r4/KfJYT+v4V5/isT4u0g8G9l9h+FEG87gT9d2H9kMPuPnRAvi5D/NmH/kWnnPyT0T5Zd/gOg10+Bf6ZduAfoDkjN+pNsxuc/WhvP/pk2qq93df/jlbQtJiw/2ZKk8vq+HkFwBwTCPdAH4EfWYGr6f44D/a/2E7Sff/jmMvrfpvv11P+HCONfrvD+l+3M+1++g3h7CPnvYNb/+yHeYQJ/HrP+3w3x9hH484X1P/ql2v/efzz673tC/oXM+q8M4u0l8O9k1n8HIN63BP4iYf1XzPj9r3X+pTMgHjANsE3F9ZOruX/T2jj0/0HoT7sI/b9EWP+XCuv/MuH177uE179/40D/aam/jp/nacBPgvrvFKH/7xZ+/ota7Sam8YNh/VSXoED/i3MoxOtd3b9h/fOEv5OTU81lyRL8HPr/N+hPvxD6/7fC64/2Muv/PyHer4T89+mg/08S+NGvXWe7/5j0/wkC/35m/f8jxDtG4D/ArP+PQ7yjBP6Dwvr/kF3+HPvf8Qy0UEBXFddPqeb6Xfr7h0P//wH96Qih/38vrP8PM68/+h3i/UzI/wfh9Uc/Cq8/OiK8/+EnB/6Do/76X4L+w2Ryvv/9bPf8WfP4wTJ/09pDqkmPv97dcys25eVmRexMNceEbf+rZE9sRlF0bsWu8vzQ3I35ybkVFuvfFhbmVuSHJpzGvwu2cPFL+M9fmOcf/oF45wjj71Hm+QcPuPdqEu6/Y8z+4yzEO0/I/1fh+Qf0i7Z6T1z+owbh/f+d2X+UQ7wKwvt/nNl/GCD3vwn8f9j5D636H/eN4RltNY3KuWvUFuh+fi/aJPznn8zrj4zQ/88Q+v8JYf9xUnj+4ZTw/MNp4fmHcgf6X0v9czzPfBH0wdomxz9j0/0HZumn/+sTvv/O2Ol/Hv3e1kOqSev3yOzsI7F72hZFx2bE7mm9vSgmzBLm3X1TXmFMdE7bVpaQXWYvyzod+bV+f0vo/7+Y9f8N0PevJfT/s8z6/0bgvoXAf45Z/9cB7usJ/H8L63/Uys2tr7n0/82E/M8z6/9rgLsugf8fZv1/E3BfR+BHv2rT/5VZa6axyV1vqKoB/dsT1vO3n1HxZRrk9m+iTat+k/B/+LyC0//Vg3j/IYx/RpOs/8Nn9ZL+r4ZJ1v/VNMn6v1qmS/0fR/352y7j/2y+T0//dw+h/6Nekdx/gPcqp/6/C+LdTsi/tolX/zeBeM0J/HVMvPq/EcS7k8B/rf34e8G/q5391N6k/XtxmeLgvTwVC+/lqXh4nJPz8uyou4HneP4+1FoDZZyKN1PC/6FXudf6msv/NSP0/7omXv93K8S7g8B/vYnX/90N8RoT+G8wya4/u5FZ/zWFeA0J+d8krP/qCeu/+nb5T3X7N9HG8/y9verrJfT/zcL6/xYH+l9L/fcGEK8doKWg/m9NGP8aCOv/W5n1/yMQ7wFC/g2Z9b8nxGtL4L+NWf/fD/EeJvA3Ml095z+jPE/CpXExxZ5pobkplhDPYLNXsLlVsLl1sLlNsLltsLldsLl9sLlDsLmjZR2upisqsen8lFPZq71is4v3dJT6/Tn0P9YDbGBUV39OQv+jV3/K+ppL/7ch9P87mPX/fRDvIQL/ncz63wviPUjgv0tY/zdh1v+tIF4LQv53C+v/psL6/x67/Ke59b9o49H/HVRfL6H/mwnr/+aX6P+2LPW3Owrq/26E8e9eYf1/H7P+fwLiPUbIvwWz/n8S4vUg8Ldk1v+PQrzHCfz3m66e85+zjySeKwrd8VthTNyBhNPe3S1hxemz48sSTlpC8MF+29lenrNbddTvCT6HfrfVTm+q4s2crvEDkND/6NVbWF9z6f/uhP7/ILP+bw/xOhP4H2LW/11QTxL4HxbW/48w6/+uEK8DIX9PYf3vJaz/WzGO/+760drPv1FqRl+I1M3fTykf5uz1Wj8/Cf3fWlj/t3Gg/7XUX0Y9PQ7gfQX9f9ysn/5/jjD+4bNqyfOncK6kofU1h/7vD/GeJuTf3iR7/lAHZv0/COL1I+TfkXH819qiklOORR3KtGzOw6U2RYcsYajoo5LTy7Pjt2xPPVR6KOF04pqMvZawrKP5xzNPFqdbgjnVPEf9MNTu7xvU1Q+bIfz8jUv/P0vof+hXbSvOuPT/YAL/Y8z6vxfE60vg78Ss/5+BeH0I/J2F9f/jzPp/IM4nEfJ/Qlj/P2niPX9oAMTrTci/i13+1f38K62NT//38Z3oGzi8m3+QH6U3co3/lXn+VFeT7PlT3Uyy5091d+A/OOovv3AZ/2HzHXr6j7GE8aeHsP/oift1bb8Lg/94BeK9RMi/l7D/eKoK6f+C78oyt4QVnkk9k1wek59bUdn8HPrfG97E9R7KOnxqmyms/zn852joT8MJ/d/bxL//fAyBv7ed/uXyHz4E/qeZ/cdQiPcygb8Ps/8YCfGGEfj7CvuPfsz+YxTEe56Qf39h/zHAzn+49b+2xlA/WFT/c/jPEdCfXiT0/2dMsuffDhT2H4OE/cdgB/5DS/3lIRBvOmC8oP8IIvS/Z4X9x3PM/mMSxJtIyH8I8/qnyRBvKoF/KPP8xwSIF0Dgf94ke/4R+nTDv/cfj/6cRsj/xSrk/zyF+f/RWH86HO9heBNP4fuq4s2cJez/OPyHL/Qnf0L/e4nZf0yBeH4E/mHC/uNlZv8RCPFeJeQ/XNh/vCK8/mmESbb+8kg7fon6u6Oq0PyPdOPZf6F++6D0+mub/ueovzxLUP+/SRj/Rgvvf/Bh3v8wH+LNIeQ/hln/L4B4Cwn8Y5n1/2yIN4/AP05Y//vq8Pz5LUL+rzLu/46NzIrYtTf6tDJ7o7oMveqmdf7mPOApGJFGAYaoGExnu/j+SQ79PwP602uE/jeeWf+/DvHmEvgnCOv/icz6/w2IN5OQv5+w/vcX1v8BwudfThJe/z6ZcfyXbiz63TYF4+032oc4k+Pq+ydt+l9L/W1cT5MNePcK+t8jVz/9/xlh/JsirP/xeU0962sO/f8RxHufkH8Qs/7/GOJ9TuCfyqz/34N4iwn804T1/3Qdnv8vIeQ/wy5/6efvWvX7MIOi399Qqd/nVPPzTzj0/9vQnz4k9L+ZzPr/E4j3AYF/lrD+n82s/z+FeO8Q8p8jrP/nCuv/14T1/zxh/T/fjt9dA6V6w0O4dfOfONKfZf9MT//JE0dQts5f/KLV0Fx+/5LV/3HUP192Gf/3r+/Tyf+tsX73OTv+LRBe/4XPK+tbX3P4v2CI9zXh+/8NZv9nJr7/bzL7v68g3kpC/m/p4P9WU+rP2f0cl/+jvP8LmfcfLIV4Kwj5L2LW/xaIt5zA/7aw/n+HWf+vgnhfEvJ/145fqwTAMw/6eyh7n9SsH58r/AWq1X/X9KgRu3rXvhoJMSXFNbaWFebX2LEP/ohdnXSwUn5/rc+/Jfzfe3b+zxu4feAbeIpKfjXr7/FZ6e3W14OAfYJ1DPKppPVfHzhYf6+l/vQXEC8eECqkvzDvGML486Hw8/fFzOtvIiBeGCH/j5j1VyTEiyPwf/z/9b9aqX8K7Or+qfREYX7lr1q52LQ+/8YN0wM9lPqtI1Rcz6G/10N/Cif0v0+E51/weWkt62su/R1LyP8zZv0dAvE2EviXMOvvKIi3gcD/ubD+/oJZf0dDvHWE/JcKP3//0k5/vebi+tvVG8P5QYOCAgImzFDOD+3vSzQDEvMvy4TnX74Snn/52oH+56g/nCSo/7MI499y4eevK5jX32yGeCmE/FcKn/8TfBXV/8LTQrMji/OS8mLDi9ZZwkr+jEouiSstD7ZUDj/H+UHnAD8B6qp4M+dp/AA49H8G9Kc0Qv8366D/Mwn8+Ly4kfU1l/7fRuBfxaz/EyDeJgL/amb9vxXipRL41wjr/7XM+j8d4iUS8g8R1v/r7PS/9Pq1aj//zls/gKz/Oc7/2QL9KZnQ/0OFz/9ZL3z+T5jw+T8bHPgPLfWPcTz9EbD9Cv7jxj/08x/fEPrfRmH/Ec7sP3ZCvDxC/hFXWf2v/9f/uBvVlfQ/zhSj/lcTab7GD0DCf0Yyr/8phXiFhP4fpYP/2EXgj9bBf5QR+GOY/UcOxCsg8Mcy+49iiJdP4I8T9h/xzP6jBOLlEvJPuIrqf7m6/u812T8oQIP+t12vtn6VhP9MZK5/UQTxdhD6f5Kw/0gW9h8pwv4j9RL/0Y6l/vLey/gPm+/QyX+Q898k7D/wWW1t62sO/3EI4n1HuP82M69/+p64/nwLs/7cB/EOEvLfKrz+BZ9X2u43V/d/CftT4nJ+Kku3hCh147Lj40KwbtzFmnGF3yVkZIRlF+wMLviNvw60Vv+HPmApoJ3Rw2OMijdzgcYPgMF/kMefDF7/YdgD8Q4Q7r9tzP7jMMTbT+DPFPYfWcz+4weI9y0h/2zh+Y+c/9Gfiv7QUv91N8Q7AfjZRfRHrp3+0Nq0+j8u/6O2flZ1//6T0J/bmfXn7xDvKGH82cGsP48T9Wces/78BeL9Rsg/346/Aq55HTrxm9YzVN4CLAIsBLwNeBfwDuA9wIfWOrcfABYDPgZ8BPgEsATwKeBzQDZgKeALwJeArwDLAF8DVgCWA1YCzIBggAWwGrAKsAawDrAWEAIIBYRhfS3ABkA4YCMgAhAFiPxve+cBH1XxxPELpNFROhaaICAlhSpKC12aIIIFQoBAIpBESCgWRMQuihUrAgFpUQgkQAih19BCEkKvIh0FpDf/v83dwdP/5RPmvXlMLtzqzxzCm2Hu9vZ9Z3bfLjQfiofioAXQImghlAAlQouhJdAyKAlaCi2HVkIroFXQGmg1tBbaAK2DkqHr0CZoI7QZ2gptgdQongptg9Kg7VA6lAHtgnZAO6Hd0F5oD7QPOgDthw5Ch6FD0O/QH9AR6Ch0HDoGnYBOQSeh09Bf0BnoT+gsdB46B/2t9p+HLkCXoCvQZegqdAO6Bt2EaoMx/8HPW5AbXufNI5N/bNXkHxL8mcLMn8dg7wzh+7eNmT/Pwd5pgv9UDX8abRz5zy41jqIvhui4mb7j5OvXufhH7/k9EvlHGnP+cR72jhP6f7pw/rHdQf7Bcf7rJSfJPzKE6587mPnzBuxdIfS/ncz8eZPIn7ty0fqP3FD/222xclygjjdzbA5Y/30Z/ek6of/vFq5/7xHmz73M/HkB9q4R3v99zPx5C/auEvzvF65/HmDmj39g7yIh/oPC/HFIwx9GW07hX73n19zv9z87fxo5/1PVFq57WCx5s3ioLKfx52Fh/vydmT/z4X33cL/78ecIM3/md6fx5x/M9U93GPMmxH9UmD+OCfPHccbnP43y7yPQpxZrPbWtjsH0XSev/7CcX+Hnq/t6Dv50Q2fyInz/TjDzZwEY8yT4PynMn6eY+bMgjOUhxH9amD/POKh/cZw/WDQb/ihf+oJpzx+VJbz/fwrvf/YX8/5nJRH7g4T4zzLzRykYe5jg/xwzfzwAYyUI/s8L84daq/KohaflhOe/VNaTskZlPYtW3cl71l5IW2W+f6P885rFyoLN8EY21XH9e/Lr/zL730OE/n+B+fmjwjBWnOD/IjN/lIaxYgT/l4T54zIzf5SBsSKE+K8I88dV4fNHrgnvf3U9Fz3/Jd349m/rGj5Ex9fA6Ocnsf/ZDQfP/xg5f7AQjNWCymfB/3buN5P/axLGv5vC9Uc1X1PY9pqD/6sg9oqE+P8R3v9MOefk/+owVpkQv5s7P//XIPhXtYJa9r7gOgPpvpZ0/pa2Zuv6eQmLrqg9+xakbTkRPWPj/JTz0Yvj0uJ3b1ydNGVBWnxS/O7URPWKf/UGz/4dNfAmhkFNdLyZ7wufP8mV/z1BGH/yuvPmf4/C2GME/+7uvPlfVRirRPCv5uok8z9Pd978rxqMlSPE7+Uum/+puULO/Qceh70KhPjzucvuP5Bf49+1f4fB8dN4/tclOCIodEhg9+DQzuH3/P2T2H+igLvs/hMF3f8//+Q4/9A3m/zTp4l5+Wdjwvij8mXJ/FPVa4vYXnPkn/Vhz58QfxF32fyzKHP+2QjG6hHif8Cdr/5ntKn5m9RtS39NS9l+M333+lPrbsWvVrv4pexfFLdlytq18avN9c/B/6lQdTfrHn7U9oEw/3PVH54m9D81V1zR9por/3iK4L8Yc/5RG8bqEvwXZ84/GsJYHYL/EsL5R0nm/ONJGPMhxF9KOP8ozZx/NIA9P0L8ZVz8z9Z41u/5if39JfLPsu6y+989JJx/POwg/zBy/ucjMNYbap5F/mHPO8zMP9oTxh/195Vc/6bqhZzr39rAXgtC/OV48w+3tjDWkeC/fA7i/x1TUg9HL85IVLxvr/OrnCAhbttklQf8+3esGUHSlLgYLv9G+T8QOmWx7jVyVcf1Hwp/ABz5ZwA6U2tC/6vgLrv+Uc1V289b48o/OhDir8ScfzSFsVYE/48x5x/tYKwlwX9l4fyjCnP+8QyMNSPE/7hw/lFVk3+41m8Zrt8HhASFDQjuGDRsZGD3kOAwWz3/Lq+Xfv5Ugn+rucuuf6zuLnv+5xMO+J/j/M8ugvwfSBj/agjPP6i1emVsrzn4vwfsPUeIv5bw/ENt5vmHl2GsOyF+HxP4rxfBv69D/jLGfz0J/v2Y+a8zjD1P8O/vzvf8r5qxsQg2o/lbI6g39DH0qo7rxwnP3xjlNw7+fxGdqRuh/9UR5v+6zPz/Eow9S4i/njD/12eef3gB9roS4m8gvP6poXD9+Unh+nMj99xz/rfRZkL+FxAe1i80MjQ8rH34cNPfP+Prf635h5HzPzuhM70K9c0m/2ja37z8I4Iw/jwlnH+otRLlbK858o9Q2AsmxN9YOP9owpx/DIaxEEL8TU3IP8IJ/lWtsPDt7x9P/hFG8N+ccfxfG7188+LTK+ZX9anp51PNcs8bB/+/Ac2Hxum4/lMn53+O/DMInWkAof8FMM8/DISx/gT/LYTzj5bM+ccgGOtDiL+VcP7Rmjn/eAX2+hHibyOcf7QVzj/aufj/duNZv1VH9/X34/zPM/83/1Gf5fzPyCw6tT3vMDP/GEUYf9oLr3/qwLz+6TXYG0aIvyPz+qfXYWw0wX8n5vwjCsZGEvx3Fl7/omqVxZnGz+SEtFWp6VtXqjVZSVdSUhbdSEy03MNmlP/VzpkToY3QbzquH59r+N9Y/vkWof93YZ7/GgJjIwj+uzLnH2/A2HCC/+eE849uzPnHmzA2lBD/88L5R3d32f2/egivf3mBkf+lG9f5AXr3n3L28wMk1j+96ID/jZy/q+rJS6GxMvxPjv8l4fkHtV6H8/yBj2DvPcL435OZ/z8mnj/Qi5n/34WxDwnxBwrzf2+N/2WzFk6RHH+M8ntti6qhWSwl1NmrOq7/0sn53Wj9SuL8iSBe/ncbA2MfEL5/fZj5/xMYe5/gv68w//dj5v9xMPYOIf5gYf7v7/7f8wfqs5y/+Xk2/NF5nHn1xx8I7/8A4fpjCHP9cQLsfUmIP5SZP76FsZ8I/l9h5o8vYOwbgv+B2u9/5vyF3t2PnD//ydi5KC5uS/LN6MUy/o3yTwAUBo22WNcxUJsEf6r56vy3//489ccfCf1/MHP98TMY+5rgP4yZP76Dsa8I/sOF+SOCmT++h7HxhPhfFeaPIcL1x6Ga+L9y8vzH2VvbsIioSAP1y7bNA1sED1PPnAYHRQaER4URO5BE/TlS+PnLKAf1RyPnn34KY79Bk7Pgfzv3m8n/swnj3zDh+qOaK3vQ9pqD/6fDXjQh/hHM/D8DxmII/kcy8/8UGPuF4P81xv1fpPndR9j/3R45kVUbA6n63SxolI7rvzb4AUjwv1qvY/9rc/H/r4T+/wYz//8MY9MI/t9k5v+ZMDaV4H+UMP+/xcz/s2BsEiH+0cL8/7Yw/4/RxO86A8V1/ouRZjR/y2Nx7sazfry+7uuNfn6dcdcbin+GZ94D6U9g6Mm/3tGMPx2Q/w3CqBeKO0Eoxj8qg+sZ/8Y6yP84zp+OFcz/Egn3v3eF53/eY57/WQh78wnxv8+c/y2CsSSC/w+Y8795MLaA4P/DnLT//5IVW6XmXlQzOv/SCpoADYam6bj+m1yy/z/l+6/Wi3naXnPlf0sI/f9j5vxvDozFE/x/wpz/JcBYHMH/OOH871Pm/G8xjM0lxP+ZcP43Xjj/+zwH7f8v3ZjmXzqF6kwCpOuvEvM/XwjP/3zpgP+NnD89Ecb2Qyuy4P/ecVbut//89/vPw/8bCePfV8LzP19r1n9w8P862FtFiP8bZv5fD2ObCP4nMPP/ShhbS/D/LePzP77CEzBG518iVH+0abqO6yc4+foJCf5X65XsdT8u/t9M6P/fM/P/MhhbQ/D/AzP/b4Cx1QT/Pwrz/0/M/J8MY8sJ8U8U5v+fhfl/kiZ+V/1d1d8b6L7e2ddPSNT/JwvX/6c44H+O83+3CfL/HsL4Fy1c/5/KXP/fAXtphPinMfP/ThjbR/D/CzP/p8JYBsH/dOHnT2eYUP/dS4h/JjP/bYWx7QT/s5j5bxeMpRP8z9bwX/yc1JnOPv+ywGKdf9FzVPS39/n6dwn+j2Hm/90wlkLo/78K8/9vwvw/R3j/mbnC9d9YB/xn5PzVLTD2J3RIkP9OEfr/PE39V7oxzb80Gzw4XNf1zp6/Ga2/SvC/WqtTwPaag/+Pwd7vhP4fx8z/x2HsNMF/PDP/H4axowT/C4T5f6EJ9d8zhPgXMfP/ARj7g+A/gZn/T8DYEYL/xRr+N9o45l/iLNb5l7U6rv/Oyflduv4qwf+JzPx/EsYOEvr/EmH+TxLm/6Wa+CXqv8uE67/LHfA/x/mr57Lh/4g95vH/dUL/X6Gp/xptPPMvDXVf7+z8vihj3mrJ+psE/69krv9fhr2/Cf1/FTP/X4GxmwT/q5n5/zyMXSL4XyPM/2tNqP/fIMS/jpn//4KxiwT/65n5/yqMXSD436Dhf6P194UW6/MP+y36nn/43rX/jGiT4P9kZv6/BmNnCf1/ozD/bxLm/83C9f8twvX/rQ7438j5p+p5/jcA1G5ZQLWd+83k/wIed9//UzT1f6b6e9fIYH1pwP1efzfajNbfJPhfrZMqaHvNwf9e6Pt5Cf0/lZn/veG7IMF/GjP/54FvT4L/dGH+325C/b8QIf4MZv7/R9VTCP53MPN/Pvh2J/jfqeH/fRZr7T2Pm77nH35w1d9Fm9H6mwT/72Lm//yKuwj9f7cw/+8R5v+9wvX/fcL1//3/x/8NWM4ffUCQ/x8i9P8Dwuu/DzLXf0shmGKE+A8x819p+H6E4P8wM/89CN8lCf5//+/+//76kxhnz99WrpCcfeGpv6r1z6r+qmf9swT/H3HI38b4/2FC//+Dmf+LwHcJgv+jzPxfBr6LE/wfE37+8zgz/5VF7EUJ8Z8Q5r+Twvx3ShP/j675F9HGVH9tP0zn9RL1/9PC9f8zDvjfyPmjhTH21IIqZMP/o/NcNI3/nyCMf38K7//yF/P5o48j9kqE+M8y839V+K5B8H+Omf8rwncVgv/zuWj/f2eff1H1V7X+WdVf9ax//skJ9///24T6f01C/7/AzP/l4Lsywf9FZv6vBt+PEfxfEub/y8z8Xx2xlyfEf0WY/68K8/81xvH/fp9/CQgJ7jvQAL8HNA9sFhUZ3iqob2T4EPrt3yn3f78uXP+/4YD/Oc7/9c2C/+3cbyb/NyaMfzeF+f+Wu7pvWBsH/9dH7P6E+P/h5X9y/GryhZP/G8FePUL8bh6u819c4jn/xWjbkb5gTsLU+dOl/BudfykL1bBYz15uruP6iblk//+nCeOPWq9mv/9w5X9PEfzn9eDN/2rDXl2Cf3cP3vyvIezVIfhXa9Uk8z9PD97870nY8yHE7+Uhm/+p9aJP3e5/IZk9YCD+20+Hf1V/bAB7foT483nknP3/pe8/RlvrIeFREQbyP/v1evefNPr+3cTnnwdJuDvkCXlAXlB+yBvKBxWACkEFocJQUagI9ABUDHoQKg6VhEpApaAyUGmoLPQw9BD0CFQeehQqB1WAKkEVocegKlBl6HGoGlQVqg7VgJ6AakI+UC3IF+oD+UN+UB2oHlQXqg89CTWAGkKNoKehp6DGUFOoCdQMCoCaQy2gVlBLqDXUFmoDtYPaQ89AHaBOUEeoM9QVehbqAj0HPQ91g7pDL0A9oBehl6GXoJ5QINQL6g31hYKgftA3UH8oGBoAhUIh0CvQIGggNBiKgMKgcOhVaCg0BIqEhkFR0HBoJDQCeg16A3odehN6CxoFvQ29k+fO/b9LZhUq5J7Un/Jrxp+u8DhSd/an8m+6/wIe2vnHe19/K+jx//UHI+ePPwp7L0PNs6k/jK9mSv2BHH8hD9n6g5qv5Zx/bAN7LQj33yIevPOPbW2+79Z/UY+cc/5b0oz005L+jeZ/vm5qDLPe8zJ0XP+zcP7HUX8KQH9qTej/D3jIPn/0oAfr+kPy+FOMN/90awp7rQjvf3Hm/LMd7LUk+C8hnH+WZM4/n4G9ZoT4Swnnn6U1+afR/I9l/x9/X93XO/v6lYydi+LitiTflFqFbudPjvOPO2XBn3buNIk/M/2/QPj+qfXSks+/qPXKnM+/dIO9ZwnxP8TMn8/D3ksE/w8zz391hr3nCP4fEeYPla/lv/3946l/v0iIvxxz/bsD7HUl+C/PzB/dYa8LwX8FYf6oyMwfPWCvIyH+Shr/RvOflhjNw/BzjJt1DozaJrmePxBtEvz5mIfs+rfKHrL7H1XxkH3+4XEH9Ucj59+2h71BUGA2/Deps3n8F0oY/6oK1x/Vet3i9vGTgf+CYS+IEH91zefP8PxR86jQQf0CuwRHBAdFBoRHhZG+ws6evwk/fmD4+QMO/u+P/vQKof89wcz/vWGvH8F/DWH+V88q2PstF/8PJMRfi5n/e8JeX4L/2sz8PwD2+hD8+wjzvy8z/4fAXi9C/H4a/2PREVX9LgY/R+nwP9m1/5NoM1p/leB/f2H+r+Mhu/9RXQ/Z5x/qOeB/jvNvw7Pgfzv3m8n/IwnjX33h+m8D5vpvFOy9Soi/ocd/9//x0x2/s/P7+iUrtjrz+adt3Kz7r4e76dt/nYP/h6E/vU7of08y838E7EUS/DcS5n+1Vp37/IPXCPE/zcz/g2FvKMF/Y2b+Hw57Qwj+mwjzf1Nm/h8Be2GE+Jtp/E9x1d9FG1v9rVOorjRAgv+bC/N/gHD9v4Vw/b+lA/43cv6xGk+XQG8J8v+HhPGvlXD9X62V5Nz//l3Ye5sQfxuP3LP/j7+T7/8zxM26//oEnfuvRxv8ADj4/z30p48I/a8tM/+Phr2xBP/thPlfrRfl3v/oY0L87Zn5/03Ye4fgvwMz/78Pe2MI/jsK838nZv7/APZGEeLv7OHa/4er8ax/9td9vdHPT4L/nxXm/y7C9f+uwvX/5xzwP8f5x59lw/9zh5vH/98Rxr9uwvX/55nr/1/D3ueE+Lszr//+BvZ+IPjvwcx/42HvK4L/F4T570UT6r/fE+J/KQc9/xk/J3Wms8+/qPMX1PyLnvMXpgrXXzn4fxz605eE/vcyM/9PgL0vCP57CvN/L2b+/xb2PiXEHyj8/GFvYf4LEq7/9hGu//bNQfv/SDe2+ZdmgweH67heuv5q538j5x9/gv4UA/2cBf/bud9M/p9JGP/6Cdf/1Xr9QrbXHPw/DfYmE+Lvz8z/v8DeLIL/Acz8Pwn2phL8hwjzf6gJ9d/ZhPhf0cRvtOWG+Rd1/sIEnecvTHPy9RMc/P8T+lM0of8NZOb/6bA3heB/kDD/D2bm/xmwN5EQf5gw/4cL83+EcP33VeH67xCNf9f8i5p/qaP7emdfP2Hl/4Ys5x/PyYb/l080j/8TCOPfUOH6fyRz/T8e9mIJ8Ucx8/8C2Esk+B/GzP9zYS+O4H+4MP+PMKH+v5gQ/0hN/Isy5q125vp7gu35h4M6n3/45T5f/8zB/7+iP80n9L/XmPl/IezNI/h/XZj/32Dm/0Ww9xsh/jeF+X+UMP+/JVz/Hy1c/3/7Pjz/J9G2Rj0n/x2P4O/3xz3+O1qEG9v8S9fIYD2J4P2+/t2e/xk5//pH9Nm90LIs8j973mdm/reBcP8bIzz/o9ZKc55/twb2VhDiH8uc/62FvWSC/3eZ87/lsLea4P894fzvfRPmfzYS4v+Acf7H6C3kgO35F3X+jJ7nX6a79p8x1DjyvyT0p1WE/vchc/63DvZWEvx/JJz/fcyc/62HvaWE+D8Rzv/GCed/nwrP/3wmPP8znnH855l/qav7emfn95UrJKuvd/if4/zrrYL8v4sw/n0uPP/zBfP8z3bY20aI/0tm/s+AvT0E/18x838K7KUT/H8tzP/f8J4/lOl/NyH+CczP/26GvTSC/2+Z+W8H7KUS/H8nzH/fM/PfTtjbQoj/B8b9/xNsz78c1Pn8ywzX/kOiTYL/fxTm/5+E538mCs///Px/z/82NHT+6CbYOw0dyIL/UtZYuc/+U/t7XPx3gjD+TRKu/6q1+gVsrzn4T80ZHSLEP8WM/f/bD9N1vWv/IWMtJ+z/fxT96SSh/0Uz8/9B2DtC8D9VmP+nmVD/P0WI/xdm/t8He78T/E9n5v9jsHeY4H+GMP/PZOb/47C3nxD/LI3/A7bnX9T8i57nX2a65l9EW/vQoUZu3yL8P1uY/2OE6/+/Ctf/f3PA/xznv/6VDf8fPG0O/1+zjX13G/8cTf1Vgv/natZ/c/D/Rdg7Rxj/Y7X3n+aBLYKH6Q7f6fndaDPK37Vtb8Iq/Giq482YlQP2/7xE/P7NY+b/s7B3gdD/55vA/1cJ/rXrLrn4n/L+xzHz/xnY+5sQfzwz/1+GvfME/wuE+X8hM/9fgb0/CfEvykH7fxa0FPD1qdEw819/nwJ+PjX81Av1Gv+/rk8NX/VvAV/bC/xuIfXfur6Q+h8F8cfrWX/T16eQ9XL1OxD+oO0S9aOI+pX1ukwVsNvDvwVt5v0yLVp/4Z951d2M/4ZuAM2jIiPDwwxcHxmmbuCBzfr103W9BP8naPi/LXwHg8CG6vRfUId/9azcz7bXXeF9kG0MCr5H/J/kgL+NnL97C8b+AlDeyoK/7dxtEn+T41+q4V8J/l7GXH93V8F43v1YsJx3/QU5/hW5aP//TWeWpMUnyfk3On++y/YmloDK6HgzZxv8ADj42wN9Py+h/68Urr+v4n3+mvz9W83L32431HwC4f1fw8zfnvDtRvC/lpe/3byVbwL/rmPmby/4v0nwv154/fUGDX85+/oZLn7uEjw4fJiOG7Cz3z87gz1GZDKwPgLXk/8mO+BfjvNnC3o6/jM5jX83CvPvJubnDx9EMIUJ4/9mYf7dwlx/LIbYHyDEv1WYf1I0/lPXzr8pOf5w8HNlGz831jGYxrj2f7nn/LuNmX/z47tXlPD9S2Xm3+LwXYTgP42Zf0vCdyGC/3Rm/i0B3wUI/rcL82+Ghn8l+GeHA/4xcv5mPrz3VaCy2fDP2WKXTJl/r+xJm//bKTz/vkuz/peDf8oj/ocJ/X838/NXFYjv/x7t99/g+qH2tvW/eq93rR8wtn7A1836Jqxx07d+gIN/H0L/K0fo/3tN4N/HPJ1n/n0f8/x7acT+KCH+/cz8UxG+HyH4PyA8/36QmX8qIfYyhPgPCfPPYQ3//Ork+U9BSwF/24IB/FtITf37W6f8/X0K+9W3/n/I1/ZLX/UH6quVBf/+s4XqZP6oUc96ZZ3M2f/bv/S3/qb1z9z+pfpN/K8i6n8rK3Wh+uq3697503Xhtm6me5uj/x//RdcPSMy/q2cFYm2vJebfjzrgb47zL6tlwd927jaJv8nxHxOuPx5nPv+mNoJ5gjD+nhCuP55krj/6IPZahPhPafyr+Q/bAVa6VhC51g8Ya0brn3ts/F8qj771AxL159PC8+9nmOuPjyOYmoTv35/M/O0L3zUI/v9irj/6w3d1gv+zzPztB99VCf7PCfP3eeH649+a+H+7z+c/ONYPWO+f+lYQ5IzzHxsaOv+xFL57XaD6TsK/F4T596Jm/OXg36cRTEPC+HdJmH8vM/NvY8T+FCH+K8Lz71d59/8iv//XGPd/dPb1A4qfK9v4Wc/6gTmu8x/d6uK714jw/bvOzL9N4PtJgv8bzPzbDL4bEPzfZObfpvBdjzL/Icy//wjzr7r5/7v+52vx0XkCXmFN/a9lNvxjaXTJtP2vOhE+f7VW2/6o0P1y/kt2CvC8P98Lg7cfpv2f6+m+3tnrj8tmLZySMDs5KXrx+iUrttaIn5M6s4Y6k6/GyhX3xL9E/qOeVeHc//gZ2GtNGP/yevKuv2kPe88S/Lt78uY/rWCvHcG/h6ds/qOeF3rI9ppr/UVnQvxenrzrL9S9oy3Bv7cnL/92gL02BP9qvaCdf43mT2r/kuNQNQykl3VcP9e1/69ok1h/k9+TN//pCHstCP2/gKds/qOeU5Lc/6yQp+z+x4U9Zfc/LuIw/9N3Ap7K/5rDXh+oWxb53+28z8T8L5DQ/4tq8j8efq+v+3pn5/ekGemnrfwu49/o/VuC/x9g5v+XYK87of8/yMz/L8NeEMF/MWb+fx72XiT4Ly7M/+p5ofy211z835sQf0lm/u8Key8Q/Jdi5v+esNeD4L+0hv/V8wOK39/Sye+xLn4XbUbv3xL8X4aZ/3vB3nOE/l9WmP8fEub/h4X5/xFh/n/UIf/rOwFPO/8TnA3/F+1jHv+HE/p/OU/Z8+/KM/PfQNgbQIi/AjP/DYK9Vwn+KzLzX3/Ye4Xgv5J2/M3M3/Q+/eD8+dvG2YmXV6TEnll2fvXu9fuiYzJik9KSE9JWqZwu+ebSfWb7N5q/qapFa7yJp/Czm5Os/1bPapa3vebi/whC/6/MzP99YS+U4L8KM/8Phr0Qgv/HPWWfv6zKzH9hsNePEH81Yf6rLsx/T2jin+fK30QbT/21oe7rJfi/hjD/13TI//pOQFT8Xwf25kBRWfC/nfvN5P+3CONfLWH+r83M/6/D3nBC/D7M/P8G7L1N8O/LzP/DYO81gn8/T77139L8vnntkkurlq3fvn7LlnPJsYrcJ0ffS/9G+b0s1Atv4hf4OVjHmznf4Acgwf/qecHittdc/D+a0P/rMPP/UNgbSfBfl5n/34S9EQT/9YT5vz4z/4+CvUhC/A2E+b+hMP8/6Zlzzn9x9sbC73XkDhGW4P9Gwvz/lEP+13cCorb+/242/F/+Q/P4/zPC+Pe0MP83Zub/j2HvfUL8TZj5/xPY+5zgvykz/78Hex8R/DdjHP+NtiVX0nbvSF8wJ2Hq/OkJv6zeOy9xfnTaquiYVcvitiStiV2asTNlZfrGlJTk2OiYxEOZf3Jn7PbomNi9qw5v+Ttu2sIp9qtl/v4c/D8EH0LRPBbLaB0fRpwT8r9aL9nO9pqL/8cT+n8LZv5/B/Y+JPhvycz/42DvA4L/VsL835qZ/z+FvbGE+NsI839bYf5v5+J/ttZ6SHhUhIENlO3X611BbfTzu4nPbwzuPWOh96B3ofehj6APoA+hj6Fx0CfQp9B46DPoc+hL6AvoK2gC9DX0LZQM/QB9B30P/QhNhH6CfoYmQ5OgKdBUKBqaBk2HfoFmQLOhmdAsKAb6DfoVmgPFQnOheVAcNB+KhxZCC6BFUCKUAC2GlkBLoSRoGbQCWg6thFZDq6A10DpoLbQe2ghtgDZBN6Et0GZoK5QKpUDboDRoO5QOZUA7oR3QLmgPtBvaC+2H9kEHoEPQQegwdAT6HfoDOgYdhY5Dp6AT0EnoNPQndAb6CzoHnYXOQxegv6GL0GXoEnQFugZdha5Dt6Ab0D+QX16LJS/kllcm/3tGOP9r7zD/03cCp8r/xsDez9DXWeR/9rzPZ27O2P9IPS9o3/9eIv9Tz2vls73myP9+gL0JhPt/J+b870fi/vudmfO/b2Dve0L8z+ag/C8+NjV968odcZtiFk7ZcE1leYtuJCYmTYmLuTf+jeZvtTL7sHX/oB/0xC+8/kIi/1N7xZW1vZbY/6orb/7n9iXsfUf4/j3HnP/9BHvfEvx3E87/nmfO/ybC3leE+LsL5389NPnfHf7QtweKtv48JQv+sHOHI/4wmr+1DYuIMnKATNvmgQEhQWEDgjsGDRupYwmO6/wYY1v4cM0/xBC+fy8I86d6VpLz/MsZsDeVEP9LzPw5E/Z+Jfh/mZk/o2FvOsF/T+HnT804/+c3Qvy9mOvPk2DvF4L/QGb+mAV70wj+ewvzRxAzf8yGvcmE+PsI80dfDX+oG3cqdA06psP/Qtf6cdFmdP2JxPxDP03/74xRbyj+GZ45Bt6b83+CNf47WKLwDkTiPWgPhZHvwXri7++w/qhvBkDx/xewtxWalw3/N91h3vqTJYTxb4Dw+pMQ5vUni2AvjhB/KDP/JcDeUoL/V/77/Kefvmcfbg+0Bpp0/uW/eE1czJZEqe17DNcfn4YyoOHQER3Xc/D/fPSnhYT+N1CY/wdp5h+4+D+JEP9gZv6fC3sLCP7DmPl/MezFE/yHC/N/BDP/J8JeLCH+V4X5f4iG/xe5+F20sdZPdUxhS/D/UOH9ZyKF1x9EOeR/fXtwaOv/K7Pgfzv3m8n/mwjj3zDh+u9w5vrvethbTYh/BDP/b4C9zQT/Ixnn/+/3+RM1cJ+zWOtnnjrejATh+y8H/69Cf1pH6H+v5cL6/xZC/K8z8/9y2FtL8P8GM/8nw94agv83hfl/FDP/b4S9FYT43xLm/9Ea/ned/XN/yzV/wvD8rl9d3ddL85dE/ve28PzPGOH5n3cc5n/69nBS+d8y2DsApWaT/3W+ZV7+t5dw/xsrPP/zLvP8z07YSyfE/x5z/rcL9vYT/L/PvP4nDfZ2EPx/IMz/H5pQ/99HiP8jZv5Pgb0Mgv+PGfd/qpsL5s8uWqzzZ3l13EwXO3n9nCP/243+tJ3Q/z4Rzv/GMed/e2BvGyH+T4Xzv8+Enz8eL1z//1y4/v+FA/7zZTh/+HAW/GfnPkf85+yNdf5MxxEAzl4/5+L/04Tx70vh+Z+vmOd/jsPeEUL8XzPz/wnYO0Pw/w0z//8Oe8cI/ifkwvr/n4T4v2Xm/4Owd5Tg/ztG/jc6f6bOnZqHnw+rvRd0XJ/oWr9iqHHw/0n0pz8I/e97Yf7/gZn/T8HeIUL8Pwrz/0/C/D9RuP77s3D9d5JD/td//qxazzfEy2I5nw3/9658mZ3/efY/9dV9vbPzt59w/YyL/28Qxr/JwvX/Kcz1/yuwd4EQfzQz/1+FvVsE/1OZ+f9v2LtM8D9NmP9/MaH+f5MQ/3Rm/j8Le5cI/mdo/Butn7fAALoAP0fh52od1y9x8bto4+D/a+hPFwn9b6Yw/89i5v/rsHeOEP9sYf6PEeb/X4Xr/78J1//nOOR/4+fP5vFy/Gfs3O+I/7n4r6DX3ff/ucL131jm+q83YncnxD+Pmf/ywXchgv/5Gv+s8yc6jlBwPX9gvH6q9u9Q9VM9+3dw8H9e9D0vQv+Ly4X1/8KE+OOZ+V8ls54E/wuY1//nh28Pgv+Fwvy3iJn/CiB2N0L8CcL8t1jDf0mu/Eu08dRP/XRfL8H/icL1/yXC9f8kh/yv//zZf2CvHMafBwX5/2HC+LdUuP67jLn+WxrGihPiX87M/2Xg+1GC/xW56PnfOk6+/ljVT9X+Pap+qmf/nqUGPwAO/i+GvleK0P9WCvP/KhPq/48Q4l/NzP9F4bskwf8aZv4vC98lCP7XCvP/Omb+fwixP0CIf70w/2/Q8L+L34011vqZji3gnfH5z2Th+v9G4fr/Jof8b/z82YrZ8H9Ee/P4vwZh/NssXP/fwlz/r4rYHyPEv5WZ/6vBd02C/5QcdP6P0cZRP1f796j6uZ79e5blguf/jPJ/JfS9xwn9b1surP/XIsSfysz/5eG7CsF/GjP/V4fvygT/6cL8v52Z/59A7BUI8WcI8/8O4fUfO4Xrv7uE67+7HfKf/vMni6DvdYb8suA/O/eNHno51z3/yTN/cv/uf87F/08Rxr89wvX/vcz1/wYwVocQ/z5m/m8I340J/vczr//2h+/6BP8HhPnvoAn136cJ8R9i5j8f+K5H8H9Y479eLpg/Ufu3qPkTPfu3LL/P1z9w8P+T6Ht1Cf3vd2H+P8LM/40Quy8h/j+E+f+oMP8fE67/Hheu/55wyP/Gz39tngX/27l//Pc5j/8DQoL7DjQwfxKgnT8J7B4SHBbYIqhz+F1f7+z8Hvf32rVGrufi/06E8e+kcP1fPa9fyvaag//bIPYWhPhP8/I/Of4zzPzfHrG3JsT/pwn835Hg/y+H/G2M/zsQ/J9l5v+m8N2K4P8c4/4vRvk9AQqC8mEg1UOAK+5zfuc4/8Eo/7dD32tJ6H/nhfn/b2b+fwaxNyPEf0GY/y9q+D/AEpLZAwbiv/10+Ff1p7aIPYAQ/yUH43+XzCwk5J7kH5c1/rvC40jdd3+LpaAO/1f+lX/c+/zrKuP4b7SZwP8vhoSHDbjbFMDZ+T8jxRj/38k/9Z8/3ATf/SCoaxb5pz3vdJR/cuUfvQnjzzXh/EPtF1DW9poj/3gBsXcjxH9DOP+4yZx/9ETsPQjx3zIh/wgk+P/HhPyjF8G/mvyy+3edgXN/y+j9x2j+V9/Nmv+9rzP/W+nK/ww1jvrDsxhPuhPGHzcv3vVnL8He8wT/ap8Uyfwzrxdv/vky7HUhxO/uJZt/qr0COPPPF2HvOUL8nl6y+aeXl2z+6e2Vq/O/HqFB4Xc9A+Ts+V/KZGP5n0T9IZ+Xo/lP4+df98sm/5y0wrz881XC+KP2S5HMP9V+JWVsrznyz1dgrz8h/oJesvlnIS/e/DMM9kIJ8Rf24s8/Iwj+i3jx55/hBP9FvXjnv/rAXgjB/wPM/DkI9gYQ/D8ozJ/FvHLO/F88RuM++OmRx4JxgN5WufI/Q40j/xiM/tSX0P+LC+cfJZjzj4GwF0yIv6Rw/lFKOP8o7SU7/1XGIX/qP3+3NuxdgKKy4E87d5rJn2MI/a+shj+lmwn5X0B4WL/QyNDwsA7B/UKjBps7fkrnf2ujl2+ev37F/Kp+PjX9faqRr5fIP9R+KRVtrznyj9dhbzih/z8snH88wpx/vAV7rxHif9SE/ONtgn+1V10R+/eXKf8YTfBfnjn/GAp7Iwn+KzDnH2/C3giC/4qa/MNo41j/9zrki4H0Ex3Xr3bxv6EmkX9WYp7/GAV7kYT+/5hw/lGZOf94A/aGEeKvIpx/PC6cf1QVzj+qOcg//BjOf34vm/xj7vFc+PyP7Xq9J8g5O/8nrgX7+/vUrKOD/a3ff57880vC+FNdeP5D7ddif/6bI//4BPY+IMRfQzj/qMmcf4yHvY8J8dcyIf/4guBf1WsK2McPpvzjc4J/H+b8YyzsfUTw75uD6v9q/Zfi/4918v8aF/8bahz556foTx8S+p+f8PyXP3P+8RnsvUuIv45w/lGXOf8YB3vvE+KvJ5x/1BfOPxoI5x8Nc9D6L579u+rovt7Z+T8+dt1cI5v33Mk/9Z8//g7601RoQhb5pz3vXF7kimnzX5MJ44/ar0Zy/zG1Xwzn/mM/wdh3hPif4s0/3CbCXjTB/9PM+ce3sPcjwX9jL9n9x9Tzcp63v388+ccUQvxNcxD/31RjGPSYzvOj17rOLzPUOPLPr9GffiD0v2bM818/w973BP/NhfOPAOb8YxLsfUOIv4Vw/tHSS3b/sVZesvuPtfaS3X+sDeP4z8PvdXVff7/zu9F2h/+Nnz8+PQv+t3O/mfwfSxj/2grzfztm/v8VxmYS4n+Gmf9/g735BP/tmfl/BuzFEPx3EOb/jibw/zxC/J2Y5x+mwd5sgv/OzPw3B/ZmEfw/K8x/XZj5by7s/UKIv6vGP0f+tt1izd/0nF+5zpW/iTYJ/n9OmP+7CfP/88L8393h+iP9509/BXvp0MJs+C+lnnn8t4Iw/vUQ5r8XmPkvCcYSCPG/qL3/sORv9XRf78rfjDWj928O/l+K/rSK0P9eYub/RbC3hOD/ZWH+72kC/68kxN+Lmf/jYS+R4D+Qmf+Xwd5igv/ewvwfxMz/y2FvASH+Phr/it8vWKz8ruf8lPUufhdtRu/fEvzfV5j/+wnzf7Aw//d3yP/Gz59elwX/27n/YE/z+H8bYfwbIMz/Icz8vxnGNhDiD/0v/9eprzt+F78ba0b5vXwe6/qJ1nn0rZ/g4P8t6E9phP73CjP/r4e9TQT/A4X5f5AJ/J9KiH8wM/+vgb2NBP9hzPy/FfaSCf7Dhfk/gpn/U2BvLSH+VzX+N7j4XbTx1N8a6L5egv+HCPP/UGH+jxTm/yiH/K///PHVsHcE2pEF/9u530z+P0QY/4YJ8/9wZv7fB2O7CPGP0Hz+Ln431jj4Xc2fK37XM3+ebPAD4OD//ehPvxP630hm/t8Je3sJ/l8T5v/XTeD/w4T432Dm/+2wt4fg/01m/j8Ae7sJ/kcJ8/9bzPx/EPYyCPGPdp3/4pJNrvzNWOPJ3xrqvt7o5yeR/70tnP+NEc7/3hHO/8Zq539xTZ68+DXkCXlAXlA+yBvKDxWECkCFoCJQYago9CD0AFQMKgEVh0pCpaFSUBnoYags9BD0CFQOehQqD1WEKkCVoMrQY1AVqCr0OFQNegKqDtWAakE1odqQP+QD+UJ18lrvY/Xwsy5UH2oINYCehJ6CGkFPQ02gxlBTqDnUDAqAWkEtoJZQa6gt1AZqB7WHnoE6QJ2gjlBnqAv0LNQV6gY9Bz0P9YC6Qy9AL0MvQi9BPaFAqBfUG+oDBUF98965D9/rdif/17eGSzv/dyyL/P/sWGveb/+p/T2u/P8cgX/eFc7/32PO/8/A2AlC/O8zP//xJ+z9TfD/AXP+dxz2ThP8fyic/31kQv53nhD/x4z1H6MtN9Rv1PopVb/Rs35qo/D8C0f+/wf60ylC//uEOf//C/ZOEvyPE87/P2XO/8/C3lFC/J8JP/89Xpj/Pxfm/y+E+f9LjX9X/s6Qv2uPoCBuoyQ9/3KH/3Wf/26JQ3+q422xXBbkfzfvux//vhLmf7VfyoO21xz8fxP2rhLG/2+Y+f8W7OUlvP8TmPn/CuzdIMT/rTD/q7263G5//3j4Pw/h/f+ecf8PH4tsM8rv5fBBLLBYz59YqeP6TU6+foqD/y+iP10nfP9+YOb/f2DvGsH/j8L8/xMz/6vN1C8R4p8ozP8/C/P/JGH+nyzM/1Ny0P6vRhs7vxMfg3f29VN3+N/4+dteWRwqeJv7Y8zj/wcI/BMtzP9Tmfm/EGLPR4h/GjP/F4bvYgT/vzDzvzd8FyT4ny7M/zNM4P8HCfHP1MSfG/g9w2Ll98M6rt98nz//wMH/Huh7BQj9bxYz/xeB7/wE/7OF+T+Gmf+LInZPQvy/CvP/b8L8P0eY/+cK839sbjv/QcvvxMdYnJ3fjd6/7/C//vPP3TH2PAaVyupQ8Rjz+b8CYfybJ8z/85n5/xHEXoYQfxwz/z8K35UI/uOZ+b80fD9M8L9AmP8XmsD/FQnxL8pB5z8ofr9osfK7m47BdIvr+WVDjYP/S6DvPUTofwnM/F8OvssS/C8W5v9EZv4vj9hLEuJfIsz/ScL8v1SY/5cJ8//ynHb+g5bficcQ3O/8brTZ+d+f4fzxx7Pg/6JpVu63/9T+Hhf/+xLGvxXC/L+Smf9rIvZqhPhXMfN/Lfj2J/hfzcz/VeG7BsH/GmH+X2sC//sR4l/H/Px3Zfh+guB/PTP/1Ybv6gT/G4T5L5mZ/3wQexVC/BsZz39okse6furZPPrWT2115W+iTYL/Nwnz/2Zh/t8izP9bHez/5G/g/N/iGHuioPqC/NeMMP6lCPPfNmb+exqxNyTEn8p9/oM2fyNuI+zK34y1nHD+Q2P0vQBC/0tj5v8G8P0UwX+6MP9vN4H/mxPiz2Dm/7rw3Yjgfwcz/zeB7ycJ/ncK8/8uZv5vitjrEeLfrfGv+F2tn1L8rmf9VIqL30WbM57/sEeY//cK8/8+Yf7f75D/jZ//2zob/i9/zTz+f5Yw/h0Q5v+DzPzfAbG3JcR/6L/8r+V34jZALn431jjqb2r9hLp/61k/wcH/HdH3uhL632Fm/m8D3+0J/n8X5v8jJvB/F0L8fzDzf0v4fobg/ygz/3eC73YE/8eE+f84M/93RuytCPGf0Pjf5uJ30RYQEtx3YPPwEbqvbx7YLDIyqO/AwGb9I4OHBHYJjggKJXRlCf4/Kcz/p4T5/7Qw/59xyP/6z39ugbEnGOqeBf/bud9M/u9HGP/UfoX2v6oE/6v9ykraXnPwf08E8wIh/rO56PyHpEPJVxb/vWLKkrj1p9bdWnJ63uHoGfMSUxMXzEidlRC3YWt0TOq8xEPpu9ce2Xg9OXbxefUnkvduPLsjblNM9Ezj/o3yu5ouua7GBLyRBXW8many5z+Q+/85Zv4PQt9/mdD/z5vA/30J/tVeqY1tr7n4vw/B/wVm/u8G3y8R/F9k5v9A+H6R4P+SMP9fZub/3oj9eUL8VxjHf2l+l77/GG0s8+919VexJPj/qob/AywhmSPAQPy3nw7/qv7UC32/B6H/X3Mw/nfJzEJC7kn+cV3jvys8jtRNf2AGHf5v/Cv/uPf5102H+Yfx86dDssk/fCpcNS3/GELof7eE5x/+Yd5/Pgyxv0KIXyVfnOvPw2EvkuDfzZuXP0NhbzDBfx5v2fqz2quzir0vus5Aum+VuW+uxVgTz/+vrD+1PWnBwuTYJUfWH0u4Pj8m4WZ0TPr5+VOS0xN3xietXrRoj5nnCxjN/ytBasrVy03dC+ktzeAHwJV/DiWMf+7evPlnf9gbRPDv4c2bf0bA3kCCf7VXj2T+6eXNm3++CnsDCPF7e8s+f6z2ypOcf8jvLTv/UMA79+T/RpvR+NuGRURFGpi/a9s8sGtwZGRo2IDAVqEDQiIDO0VFPhc6OPhe/f0l5p8KejvK/3SfP255Dva+hkZkkf/Z8z4z878xhPFP7dcpOf+k9ussbXvNkf+Ngr3XCPEXYc7/3oK9dwj+izLnfyNh702C/weE8z+1V2gepvHDaPMVXoB3tyWLrFoJvIFq5ryem/ou0Vt6jjn/yxj/jyX0/2LM/D8M9t4g+C/OzP+jYe91gv8Swvxfkpn/34a94YT4Swnzf2lh/i+jib8zev1Q/DM88ztAnwHRw19lvfnO/8pjce7GM//mq/t66fpbB/D/IPT6UIwEoej/VAbT0/8fcsj/xs8f/iAb/m/axjz+/4Iw/qm9KiXnf9R+oZzzP5/C3keE+B9l5v/PYO8rgv9yzPz/IeyNI/gvL8z/Fbz59n9bmJGRZhFsRuvvLTAaqMrDy/jZXMf123PN+V/G+P9LQv+vyMz/78HeJwT/lZj5fzzsfUzw/5gw/1dm5v/PYe99QvxVhPn/cWH+rypc/6/mnXP2/88B9ff24QP6BkUK/f2l628S9f/qDvlf9/nDbu/C3nzo2yz43879ncPN4/8phPHvCeH6v9orM5/tNQf/T4S97wnx12Tm/59hL5rgvxYz/38Hez8R/NcW5v9bmj/HxX9TCfH7MPPfN7D3I8G/LzP/TYK9Hwj+/YT5z5/x/m90/qSsGo+gExiVx+i4GWa4nl821Dj4fzL60wRC/68jzP91hfm/nnD9v77Gv0T9t4FD/jN+/uyMLPjPzn0m8R85frVXp6fttQT/Pam5/xgd/5pHRUaGhxm4PjLMloAFBgwKDiLfBJ09/1r3x7Lt8bHr5m5NT166evf6fffaPwf//4b+NIsw/jfi5X9y/3+Kmf/nwN6vhPifFub/xprvPwP/k9//Jrz87/YL7MUQ3v+mzPw/F/ZmE/w34+V/t3mwN5Pgv7k33/7/Z23rn3rlsVie0XH9jvuc3xnvn50igsNahQ/qF0zpSRz8H4v+NJ3Q/wKE+b+Fhv87494zAt++QbgL6fz+kf23dMi/us9ftUyDvVRoQTb82/ubnMG/rYT5V+1TWsL+WTDwzxLYW0To/22E+aetd+7Z/yfu/LJZ67dnLN2yesmtJSn33j/H/bObxXr/HKzj+p0GPwAO/k1Cf0ok9P92wvyr9qosbHstwb/tmfk3DvYWE97/Dsz8uxT2Egj+OzLz73LYW0jw34l5/cMy2Isn+O8szD/PavjH2fm5U0RkaHiY/gUAnezz/4EtgvtEDSBf7+z3Twn+7eKAf+voP3/0tv/VWfCvnXsjksyb/99G+P531cy/S/Cvel6yiO01B/8mw95aQvzdhPn3eeb63xbY20CIv7sJ/JNC8N9D4z/+cnK65PhjlJ/dwM1H8bMOft7Scf2e+7z+xLX+Yyuh/73AvP5jJeytJ/h/kZl/N8HeOoL/l4TXf7zMzL+bYW8VIf6ewvzby5t3/8GNsLeGEH+gt+z+g70Z6z/SrfWQ8KgIA+t/7dc30Hm9s/O/xP6TQd6y+0/2cZh/6D//dgXsHYC2Z5F/2PMOk/IPcvx9hdcf92Nef7wH9nYQxt9g5vXHe22+79Z/f+b8IwP2dhPiHyBcf1X7tBa8/f279/XXUOb6axrs7SK8/68w8+c+2NtJ8D9Qw59q3ZGaP1l+MGWzRaBxzJ+oYxzU/EkBHTfTvU6e/xmtf0rkH4OY84/9sJdO6P+DhfOPsH/lH3b+0H3+5m3/h7Phj9FHzKt//kV4/8OF658Rmvk/Dv44DntHCPG/Klz/HKLxf2f+o21Y//B7P/5J5z+xJ3cskfTPUf9cbrHWP3fquJ6DP0+jPx0j9P+hJvDnnwT/kQ75z1j98wzBfxRz/fMg7B0l+B/GzJ8nYe8Pgv/hwvXPEcz8cQr2DhHiHynMH69p+GOfk/Ovs99/pBtH/fsE+tPvhP7/unD9+w1v2fN33hSuf47S+P8fUEsBAhcLFAACAAgAahFnRooquOzacQAACMoGAAkACQAAAAAAAAAAAACAAAAAAFVJUGFja2FnZVVUBQAHOV76VFBLBQYAAAAAAQABAEAAAAAScgAAAAA=


[Script]
/**********************************************************初始化变量**********************************************************/
Dim X,Y
X = -1 
Y = - 1 

Dim Ken_LeftClickOnXY_Delay
Ken_LeftClickOnXY_Delay = 100

//资源文件夹路径
Dim ResourceFolder

DimEnv ChangeNavyArray1Index,ChangeNavyArray2Index,ChangeNavyArray3Index,ChangeNavyArray4Index,ChangeNavyArray5Index,ChangeNavyArray6Index
ChangeNavyArray1Index = 0
ChangeNavyArray2Index = 0
ChangeNavyArray3Index = 0
ChangeNavyArray4Index = 0
ChangeNavyArray5Index = 0
ChangeNavyArray6Index = 0

Dim DebugLogPath, WarningLogPath

Dim LogcatFileStr





















































/**********************************************************窗体函数**********************************************************/
//开关
Dimenv AutoSupply,AutoRepair,AutoExpedition,AutoAttack,AutoChangeNavy,AutoFactory

Dimenv SupplyNavyArray
Dimenv ExpeditionNavyArray 
Dimenv AutoAttackNavyArray

//远征舰队
Dimenv Expedition_Navy2_Enable, Expedition_Navy3_Enable, Expedition_Navy4_Enable
//远征舰队对应任务ID
DimEnv ExpeditionMissionID_Navy2, ExpeditionMissionID_Navy3, ExpeditionMissionID_Navy4

//出击状态
DimEnv AttackNightFight,AttackFightRound

//换船
Dimenv ChangeNavyPageCount, ChangeNavyLineNumber

//窗体载入时
Event Form.LoadOver
    LB_Dev_Setting = Plugin.File.ReadINI("Factory", "DevList", ".\Config.ini")
    LB_Dev_SettingArray = Split(LB_Dev_Setting, "|")
    If (UBound(LB_Dev_SettingArray) = -1) Then 
        Form.LB_Dev.AddItem "10,10,10,10"
    End If
    For i = 0 To UBound(LB_Dev_SettingArray)
        Item = LB_Dev_SettingArray(i) 
        Form.LB_Dev.AddItem Item
    Next
    LB_Build_Setting = Plugin.File.ReadINI("Factory", "BuildList", ".\Config.ini")
    LB_Build_SettingArray = Split(LB_Build_Setting, "|")
    If (UBound(LB_Build_SettingArray) = -1) Then 
        Form.LB_Build.AddItem "30,30,30,30"
    End If
    For i = 0 To UBound(LB_Build_SettingArray)
        Item = LB_Build_SettingArray(i)
        Form.LB_Build.AddItem Item
    Next
    Form.IB_Dev_RepeatCount.Text = 0
    Form.IB_Build_RepeatCount.Text = 0
    Form.CB_AutoFactory.Value = 0
End Event
//脚本启动时
Sub OnScriptLoad()
End Sub
//脚本退出时
Sub OnScriptExit()
    Call Ken_Logcat_I("*******************************肯的舰队脚本，停止*******************************")
End Sub

//自动补给开关
Event Form.CB_AutoSupply.Click
    If (Form.CB_AutoSupply.Value = 1) Then 
        Form.CB_Supply_When_Attack_Before.Value = 1
        Form.CB_Supply_When_Expedition_Before.Value = 1
        Form.CB_Supply_Sort.Value = 1
        Form.CB_Repair_WeiPo.Value = 1
    End If
End Event
//自动入渠开关
Event Form.CB_AutoRepair.Click
    If (Form.CB_AutoRepair.Value = 1) Then 
        Form.CB_Repair_Dapo.Value = 1
        Form.CB_Repair_ZhongPo.Value = 1
        Form.CB_Repair_XiaoPo.Value = 0
        Form.CB_Repair_Navy_1.Value = 0
        Form.CB_Repair_WeiPo.Value = 0
    End If
End Event
//自动远征开关
Event Form.CB_AutoExpedition.Click
    If (Form.CB_AutoExpedition.Value = 1) Then 
        Form.CB_Supply_CheckOil.Value = 1
    End If
End Event
//自动攻击开关
Event Form.CB_AutoAttack.Click
    If (Form.CB_AutoAttack.Value = 1) Then 
        Form.CB_Attack_When_DaPo.Value = 0
        Form.CB_Attack_When_ZhongPo.Value = 1
        Form.CB_Attack_When_XiaoPo.Value = 1
        Form.CB_Attack_Suppy.Value = 1
        Form.CB_Attack_CheckOil.Value = 1
        Form.CB_Attack_After_Repair.Value = 0
        Form.CB_Attack_CheckCondition.Value = 0
        Form.CB_Attack_Limit_Count.Value = 0
        Form.CB_AttackNightFight.Value = 0
    End If
End Event
//自动换船开关
Event Form.CB_AutoChangeNavy.Click
    If (Form.CB_AutoChangeNavy.Value = 1) Then 
        Form.CB_ChangeNavy_When_Repair.Value = 1
        Form.CB_ChangeNavy_When_DaPo.Value = 1
        Form.CB_ChangeNavy_When_ZhongPo.Value = 0
        Form.Label_ChangeNavy_1.Caption = 0
        Form.Label_ChangeNavy_2.Caption = 0
        Form.Label_ChangeNavy_3.Caption = 0
        Form.Label_ChangeNavy_4.Caption = 0
        Form.Label_ChangeNavy_5.Caption = 0
        Form.Label_ChangeNavy_6.Caption = 0
    End If
End Event
//自动工厂开关
Event Form.CB_AutoFactory.Click
End Event


//大破出击开关
Event Form.CB_Attack_When_DaPo.Click
    If (Form.CB_Attack_When_DaPo.Value = 1) Then 
        MessageBox "警告，这极有可能导致舰船沉没！请确认了解该情况会导致的后果！"
    End If
End Event

//是否进击回合次数
Event Form.CB_AttackNightFight.Click
    AttackNightFight = Form.CB_AttackNightFight.Value
End Event
//是否夜战
Event Form.CB_AttackFightRound.SelectChange
    AttackFightRound = Form.CB_AttackFightRound.ListIndex
End Event

//设置第几舰队远征
Event Form.CB_Expedition_Navy2_Enable.Click
    Expedition_Navy2_Enable = Form.CB_Expedition_Navy2_Enable.Value
    Form.CB_Supply2.Value = Form.CB_Expedition_Navy2_Enable.Value
    Form.CB_AutoSupply.Value =1
End Event
Event Form.CB_Expedition_Navy3_Enable.Click
    Expedition_Navy3_Enable = Form.CB_Expedition_Navy3_Enable.Value
    Form.CB_Supply3.Value = Form.CB_Expedition_Navy3_Enable.Value
    Form.CB_AutoSupply.Value = 1
End Event
Event Form.CB_Expedition_Navy4_Enable.Click
    Expedition_Navy4_Enable = Form.CB_Expedition_Navy4_Enable.Value
    Form.CB_Supply4.Value = Form.CB_Expedition_Navy4_Enable.Value
    Form.CB_AutoSupply.Value = 1
End Event
//设置远征地图
Event Form.CB_Expedition_Missionevel_Navy2.SelectChange
    ExpeditionMissionID_Navy2 = Form.CB_Expedition_Missionevel_Navy2.ListIndex
End Event
Event Form.CB_Expedition_Missionevel_Navy3.SelectChange
    ExpeditionMissionID_Navy3 = Form.CB_Expedition_Missionevel_Navy3.ListIndex
End Event
Event Form.CB_Expedition_Missionevel_Navy4.SelectChange
    ExpeditionMissionID_Navy4 = Form.CB_Expedition_Missionevel_Navy4.ListIndex
End Event

//出击后强制补给
Event Form.CB_Attack_Suppy.Click
    Form.CB_Supply1.Value = Form.CB_Attack_Suppy.Value
    Form.CB_AutoSupply.Value = 1
End Event

//工厂开发公式列表
Event Form.LB_Dev.DblClick
    Dim SelectOfArray,ItemArray
    SelectOfArray = split(Form.LB_Dev.List, "|")
    ItemArray = split(SelectOfArray(Form.LB_Dev.ListIndex), ",")
    Form.IB_Dev_Oil.Text = ItemArray(0)
    Form.IB_Dev_Ammo.Text = ItemArray(1)
    Form.IB_Dev_Steel.Text = ItemArray(2)
    Form.IB_Dev_Lv.Text = ItemArray(3)
End Event
Event Form.Btn_Dev_Add.Click 
    Form.LB_Dev.AddItem (Form.IB_Dev_Oil.Text & "," & Form.IB_Dev_Ammo.Text & "," & Form.IB_Dev_Steel.Text & "," & Form.IB_Dev_Lv.Text)
    Call Plugin.File.WriteINI("Factory", "DevList", Form.LB_Dev.List, ".\Config.ini")
End Event
Event Form.Btn_Dev_Remove.Click
    Form.LB_Dev.RemoveItem (Form.LB_Dev.ListIndex)
    Call Plugin.File.WriteINI("Factory", "DevList", Form.LB_Dev.List, ".\Config.ini")
End Event
//工厂建造公式列表
Event Form.LB_Build.DblClick
    Dim SelectOfArray,ItemArray
    SelectOfArray = split(Form.LB_Build.List, "|")
    ItemArray = split(SelectOfArray(Form.LB_Build.ListIndex), ",")
    Form.IB_Build_Oil.Text = ItemArray(0)
    Form.IB_Build_Ammo.Text = ItemArray(1)
    Form.IB_Build_Steel.Text = ItemArray(2)
    Form.IB_Build_Lv.Text = ItemArray(3)
End Event
//开发公式保存
Event Form.Btn_Build_Add.Click 
    Form.LB_Build.AddItem (Form.IB_Build_Oil.Text & "," & Form.IB_Build_Ammo.Text & "," & Form.IB_Build_Steel.Text & "," & Form.IB_Build_Lv.Text)
    Call Plugin.File.WriteINI("Factory", "BuildList", Form.LB_Build.List, ".\Config.ini")
End Event
//建造公式保存
Event Form.Btn_Build_Remove.Click
    Form.LB_Build.RemoveItem (Form.LB_Build.ListIndex)
    Call Plugin.File.WriteINI("Factory", "BuildList", Form.LB_Build.List, ".\Config.ini")
End Event

Event Form.IB_Setting_Fight_OutTime.Change
    Dim a
    a = lib.算法.提取字串符中所有数字(Form.IB_Setting_Fight_OutTime.Text)
    Form.IB_Setting_Fight_OutTime.Text = right(a, 2)
End Event


Event Form.Btn_Logcat_Clear.Click
    Form.IB_Logcat.Text = ""
    LogcatFileStr = ""
End Event
Event Form.Btn_Logcat_OpenFolder.Click
    Runapp ResourceFolder & "\日志\"
End Event

























































/*****************************设置常量*****************************/
//远征舰队坐标
Const ExpeditionNavyPosition = "356|120"
Const ExpeditionNavyPositionOffset = 30
//远征地图坐标
Const ExpeditionMapPosition = "135|450"
Const ExpeditionMapPositionOffset = 55
//远征关卡坐标
Const ExpeditionMissionPosition = "160|170"
Const ExpeditionMissionPositionOffset = 30

//补给全选框坐标
Const SupplyCheckBoxAllPosition = "120|120"
//补给舰队坐标
Const SupplyNavyPosition = "150|120"
Const SupplyNavyPositionOffset = 30
//补给舰队确定
Const SupplyNavyConfirmPosition = "700|450"

//入渠空位坐标
Const RepairEmptyPosition = "250|170"
Const RepairEmptyPositionOffset = 80
//列表类型坐标
Const TypePosition = "780|110"
//入渠舰队坐标
Const RepairNavyPosition = "480|141"
Const RepairNavyPositionOffset = 30

//出击地图坐标
Const AttackMapPosition = "160|450"
Const AttackMapPositionOffset = 75
//出击任务坐标
Const AttackMissionPosition = "280|200"
Const AttackMissionPositionOffsetX = 350
Const AttackMissionPositionOffsetY = 150
//出击的BOSS地图坐标
Const AttackMissionPositionOfBossMap = "710|260"
//出击的BOSS地图任务2坐标
Const AttackMissionPositionOfBossMission1 = "710|260"
//出击的BOSS地图任务3坐标
Const AttackMissionPositionOfBossMission2 = "710|300"

//出击的活动地图坐标
Const AttackMissionPositionOfSpecialMap = "720|450"
//出击的活动地图任务1坐标
Const AttackMissionPositionOfSpecialMission = "720|200"
Const AttackMissionPositionOfSpecialMissionOffset = 100

//攻击阵形坐标数组
AttackFormationPositionArray = Array("450|185","480|185","710|185","510|345","640|345")//数组无法声明成const


//换船接触除了旗舰以外的船坐标
Const ChangeNavyWithOutFlagPosition = "420|120"
Const ChangeNavyPagePosition = "520|450"
Const ChangeNavyPagePositionOffset = 30
Const ChangeNavyListPosition = "470|170"
Const ChangeNavyListPositionOffset = 29
Const ChangeNavyBackToFirstPagePosition = "440|450"
Const ChangeNavyJumpPageToNext5Position = "680|450"
Const ChangeNavyListNavyPosition = "130|120"
Const ChangeNavyChangeInitBtnPosition = "420|220"
Const ChangeNavyChangeInitBtnPositionOffsetX = 350
Const ChangeNavyChangeInitBtnPositionOffsetY = 114

//工厂坐标
Const OilPosition = "490|140"
Const SteelPosition = "720|140"
Const AmmoPosition = "490|270"
Const LvPosition = "720|270"
FactoryPositionArray = Array(OilPosition,SteelPosition,AmmoPosition,LvPosition)

























































//**********************************************************逻辑**********************************************************/
Do
/****************************初始化****************************/
    Call InitEnvironment()
    Call GetHwndForGame()
    Call GoToMuGang()
    //    Call RepairNavy()
    Call ChangeNavy()
    Call FactoryNavy()
    Call TD_CheckTiDu()
    Delay 5000
Loop While(1=1)





















































/**********************************************************提督很忙**********************************************************/
/*****************************远征*****************************/
Function TD_Expedition()
    Call SetHwndByGame()
    Call GoToMuGang()
    If (Form.CB_Supply_When_Expedition_Before.Value = 1) Then 
        Call SupplyNavy()
    End If
    Call ExpeditionNavy()
End Function

/****************************出击****************************/
Function TD_Attack()
    Call SetHwndByGame()
    Call GoToMuGang()
    If (Form.CB_Supply_When_Attack_Before.Value = 1) Then 
        Call SupplyNavy()
    End If
    Call AttackNavy()
    Call GoToMuGang()
    If (Form.CB_Attack_After_Repair.Value = 1) Then 
        Call RepairNavy()
    End If
End Function


/****************************检查远征是否就绪****************************/
Function TD_CheckTiDu()
    Do
        Call SetHwndByTidu()
        
        Rem 远征判断
        If (Form.CB_AutoExpedition.Value = 1) Then 
            If (Form.CB_Expedition_Navy2_Enable.Value = 1 and Ken_FindPic("提督_综合_远征_第二舰队_准备就绪1")) Then 
                Call TD_Expedition()
                Exit Function
            End If
            If (Form.CB_Expedition_Navy2_Enable.Value = 1 and Ken_FindPic("提督_综合_远征_第二舰队_准备就绪2")) Then 
                Call TD_Expedition()
                Exit Function
            End If
            If (Form.CB_Expedition_Navy3_Enable.Value = 1 and Ken_FindPic("提督_综合_远征_第三舰队_准备就绪1")) Then 
                Call TD_Expedition()
                Exit Function
            End If
            If (Form.CB_Expedition_Navy3_Enable.Value = 1 and Ken_FindPic("提督_综合_远征_第三舰队_准备就绪2")) Then 
                Call TD_Expedition()
                Exit Function
            End If
            If (Form.CB_Expedition_Navy4_Enable.Value = 1 and Ken_FindPic("提督_综合_远征_第四舰队_准备就绪1")) Then 
                Call TD_Expedition()
                Exit Function
            End If
            If (Form.CB_Expedition_Navy4_Enable.Value = 1 and Ken_FindPic("提督_综合_远征_第四舰队_准备就绪2")) Then 
                Call TD_Expedition()
                Exit Function
            End If
        Else 
            Call Ken_Logcat_I("远征没有开启")
        End If
        Rem 远征结束
        
        Rem 入渠开始判断	
        If (Form.CB_Repair_Dapo.Value = 1) Then 
            Call Ken_Logcat_I("按照入渠设置，检测是否大破")
            If (Ken_FindPic("提督_综合_舰队列表_HP_大破")) Then 
                Call Ken_Logcat_I("大破了吗？是")
                Call RepairNavy()
                Call ChangeNavy()
                Goto 入渠结束判断
            Else 
                Call Ken_Logcat_I("大破了吗？否")
            End If
        Else 
            Call Ken_Logcat_I("按照入渠设置，不检测是否大破")
        End If
        If (Form.CB_Repair_ZhongPo.Value = 1) Then 
            Call Ken_Logcat_I("按照入渠设置，检测是否中破")
            If (Ken_FindPic("提督_综合_舰队列表_HP_中破")) Then 
                Call Ken_Logcat_I("中破了吗？是")
                Call RepairNavy()
                Call ChangeNavy()
                Goto 入渠结束判断
            Else 
                Call Ken_Logcat_I("中破了吗？否")
            End If
        Else 
            Call Ken_Logcat_I("按照入渠设置，不检测是否中破")
        End If
            
        If (Form.CB_Repair_XiaoPo.Value = 1) Then 
            Call Ken_Logcat_I("按照入渠设置，检测是否小破")
            If (Ken_FindPic("提督_综合_舰队列表_HP_小破")) Then 
                Call Ken_Logcat_I("小破了吗？是！")
                Call RepairNavy()
                Call ChangeNavy()
                Goto 入渠结束判断
            Else 
                Call Ken_Logcat_I("小破了吗？否")
            End If
        Else
            Call Ken_Logcat_I("按照入渠设置，不检测是否小破")
        End If
        Rem 入渠结束判断
        
        Rem 进击判断
        If (Form.CB_AutoAttack.Value = 1) Then 
            If (Form.CB_Attack_When_DaPo.Value = 1) Then 
                Call Ken_Logcat_I("按照出击设置，不检测是否大破")
            Else 
                If (Ken_FindPic("提督_综合_舰队列表_HP_大破")) Then 
                    Call Ken_Logcat_I("大破了吗？是 取消出击！")
                    Goto 进击结束
                Else 
                    Call Ken_Logcat_I("大破了吗？否")
                End If
            End If
            If (Form.CB_Attack_When_ZhongPo.Value = 1) Then 
                Call Ken_Logcat_I("按照出击设置，不检测是否中破")
            Else 
                If (Ken_FindPic("提督_综合_舰队列表_HP_中破")) Then 
                    Call Ken_Logcat_I("中破了吗？是 取消出击！")
                    Goto 进击结束
                Else 
                    Call Ken_Logcat_I("中破了吗？否")
                End If
            End If
            If (Form.CB_Attack_When_XiaoPo.Value = 1) Then 
                Call Ken_Logcat_I("按照出击设置，不检测是否小破")
            Else
                If (Ken_FindPic("提督_综合_舰队列表_HP_小破")) Then 
                    Call Ken_Logcat_I("小破了吗？是 取消出击！")
                    Goto 进击结束
                Else 
                    Call Ken_Logcat_I("小破了吗？否")
                End If
            End If
            If (Ken_FindPicByRect("提督_综合_入渠_入渠结束", 650, 620, 650+120, 620+105)) Then 
                Call Ken_Logcat_I("已有船只入渠结束，直接进入入渠界面刷新舰船状态")
                Call GoToScene("入渠")
            End If
            If (Ken_FindPic("提督_综合_舰队列表_入渠中")) Then 
                Call Ken_Logcat_I("当前舰队有船只正在入渠")
                If (Form.CB_AutoChangeNavy.Value = 1) Then //如果有开启自动更换的话
                    Call Ken_Logcat_I("自动更换已经打开，更换船只")
                    Call ChangeNavy()
                    Exit Function
                Else 
                    Call Ken_Logcat_I("自动更换没有打开，在入渠界面等待入渠结束")
                    Call GoToScene("入渠")
                End If
                Goto 进击结束
            End If
            Call Ken_Logcat_I("Form.CB_AutoAttack.Value:" & Form.CB_AutoAttack.Value)
            If (Form.CB_AutoAttack.Value = 1) Then 
                If (Form.CB_Attack_CheckCondition.Value = 1) Then 
                    Call TD_Attack()
                    Exit Function
                End If
                If (Ken_FindPic("提督_综合_舰队列表_可以出击")) Then 
                    Call TD_Attack()
                    Exit Function
                End If
                If (Ken_FindPic("提督_综合_舰队列表_疲劳回复好了")) Then 
                    Call TD_Attack()
                    Exit Function
                End If
                If (Ken_FindPic("提督_综合_舰队列表_疲劳回复时间到了")) Then 
                    Call TD_Attack()
                    Exit Function
                End If
                If (Ken_FindPic("提督_综合_舰队列表_6只疲劳49")) Then 
                    Call TD_Attack()
                    Exit Function
                End If
                If (Ken_FindPic("提督_综合_舰队列表_6只疲劳40以上")) Then 
                    Call TD_Attack()
                    Exit Function
                End If
                If (Ken_FindPicByRect("提督_综合_舰队列表_舰队状态_可以出击",103,572,130,604)) Then 
                    Call TD_Attack()
                    Exit Function
                End If
                Call ChangeNavy()
            End If
            If (Ken_FindPic("提督_综合_舰队列表_入渠中")) Then 
                Call GoToMuGang()
            End If
        End If
        Rem 进击结束
        Call Ken_Logcat_I("进击结束")
        Delay 5000
    loop While (True)
End Function

Function TD_RefreshGame()
    Call SetHwndByTidu()
    Call Ken_PointGetAndClick("30|840")
    Call Ken_PointGetAndClick("130|590")
    Call Ken_PointGetAndClick("770|590")
    Call Ken_FindPicAndClick("提督_设置")
    Call SetHwndByGame()
End Function





















































/**********************************************************函数**********************************************************/
Function GoToMuGang()
    Dim WayFromExpeditionFinish
    Call SetHwndByGame()
    //回到母港
    If (Ken_FindPic("母港_出击") = False)
        If (Ken_FindPicAndClick("左侧UI_母港")) Then 
            Call Ken_DeleyForNet()
        Else 
            Call Ken_Logcat_W("无法回到母港")
        End If
    End If
    
    Do While(Ken_FindPicAndClick("远征_结束_开始"))
        Call Ken_Logcat_I("发现远征结束舰队")
        Call Ken_DeleyForNet()
        Delay 8000
        Call Ken_FindPicUntilFoundThenClick("远征_结束_评价")
        Delay 2000
        Call Ken_FindPicUntilFoundThenClick("远征_结束_评价_继续")
        Delay 2000
        Call Ken_DeleyForNet()
        WayFromExpeditionFinish = True
    Loop
    If (WayFromExpeditionFinish) Then 
        WayFromExpeditionFinish = False
        Call SupplyNavy()
    End If
End Function
Function GoToScene(SceneName)
    Call SetHwndByGame()
    If (Ken_FindPicAndClick("左侧UI_" & SceneName)) Then 
    Else 
        Call GoToMuGang()
        Call Ken_FindPicUntilFoundThenClick("母港_" & SceneName)
    End If
    Call Ken_DeleyForNet()
End Function

/*远征主逻辑*/
Function ExpeditionNavy()
    Call Ken_Logcat_D("Form.CB_AutoExpedition.Value:" & Form.CB_AutoExpedition.Value)
    Call SetHwndByGame()
    If (Form.CB_AutoExpedition.Value = 0) Then 
        Exit Function
    End If
    
    Call GoToMuGang()
    If (Ken_FindPicUntilFoundThenClick("母港_出击") = False) Then
        Call Ken_Logcat_W("远征失败，没有找到出击按钮，返回母港")
        Call GoToMuGang()
        Exit Function
    End If
    Call Ken_DeleyForNet()
    Call Ken_FindPicUntilFoundThenClick("出击_主界面_远征")
    Call Ken_DeleyForNet()
    
    If (Expedition_Navy2_Enable = 1) Then 
        Call ExpeditionSelectMapByMissionID(ExpeditionMissionID_Navy2,1)	
    End If
    If (Expedition_Navy3_Enable = 1) Then 
        Call ExpeditionSelectMapByMissionID(ExpeditionMissionID_Navy3,2)	
    End If
    If (Expedition_Navy4_Enable = 1) Then 
        Call ExpeditionSelectMapByMissionID(ExpeditionMissionID_Navy4,3)	
    End If

    Call Ken_DeleyForNet()
End Function

/*选择远征地图*/
Function ExpeditionSelectMapByMissionID(ExpeditionMissionID,NavyNumber)
    //远征地图下标
    ExpeditionMapIndex = Int(ExpeditionMissionID / 8)
    Call Ken_Logcat_D("ExpeditionMapIndex:" & ExpeditionMapIndex)
    //远征任务下标
    ExpeditionMissionIndex = Int(ExpeditionMissionID mod 8)
    Call Ken_Logcat_D("ExpeditionMissionIndex:" & ExpeditionMissionIndex)
    
    /*选择远征地图*/
    Call Ken_PointAddAndClick(ExpeditionMapPosition,ExpeditionMapIndex * ExpeditionMapPositionOffset,0)
	/*选择远征关卡*/
    Call Ken_PointAddAndClick(ExpeditionMissionPosition,0,ExpeditionMissionIndex * ExpeditionMissionPositionOffset)

    If (Ken_FindPic("出击_远征_远征中止")) Then //如果远征正在执行，则退出
        Call Ken_Logcat_I("第" & NavyNumber + 1 & "舰队已经在执行远征任务")
        Exit Function
    End If
    Delay 1000
    Call Ken_FindPicUntilFoundThenClick("出击_确定任务")
    Delay 1000
    Call Ken_PointAddAndClick(ExpeditionNavyPosition, NavyNumber * ExpeditionNavyPositionOffset, 0)
    
    If (Form.CB_Attack_CheckOil.Value = 1) Then 
        If (CheckOilAndAmmoIsFull() = false) Then 
            Call Ken_Logcat_I(NavyNumber & "舰队在执行任务" & ExpeditionMissionID + 1  & "时缺油或弹药")
            Call SupplyNavy()
            Exit Function
        End If
    End If
    Call Ken_FindPicUntilFoundThenClick("出击_远征_远征开始")
    Call Ken_DeleyForNet()
    Delay 5000
End Function

Function CheckOilAndAmmoIsFull()
    If (Ken_FindPic("远征_结束_舰队_缺油")) Then 
        CheckOilAndAmmoIsFull = False
        Exit Function
    End If
    
    If (Ken_FindPic("远征_结束_舰队_极度缺油")) Then 
        CheckOilAndAmmoIsFull = False
        Exit Function
    End If
    
    If (Ken_FindPic("远征_结束_舰队_缺弹药")) Then 
        CheckOilAndAmmoIsFull = False
        Exit Function
    End If
    CheckOilAndAmmoIsFull = True
End Function

/*补给主逻辑*/
Function SupplyNavy()
    Call Ken_Logcat_D("Form.CB_AutoSupply.Value:" & Form.CB_AutoSupply.Value)
    Call SetHwndByGame()
    If (Form.CB_AutoSupply.Value = 0) Then 
        Exit Function
    End If
    Call GoToMuGang()
    Call GoToScene("补给")
    Call Ken_DeleyForNet()
    ForForm = 0
    ForTo = 3
    ForStep = 1
    If (Form.CB_Supply_Sort.Value = 1) Then 
        ForForm = 3
        ForTo = 0
        ForStep = -1
    End If
    For index = ForForm To ForTo Step ForStep
        If (index = 0) Then 
            If (Form.CB_Supply1.Value = 0) Then 
                Goto 下一个补给舰队
            End If
        End If
        If (index = 1) Then 
            If (Form.CB_Supply2.Value = 0) Then 
                Goto 下一个补给舰队
            End If
        End If
        If (index = 2) Then 
            If (Form.CB_Supply3.Value = 0) Then 
                Goto 下一个补给舰队
            End If
        End If
        If (index = 3) Then 
            If (Form.CB_Supply4.Value = 0) Then 
                Goto 下一个补给舰队
            End If
        End If
        Call Ken_PointAddAndClick(SupplyNavyPosition, index * SupplyNavyPositionOffset, 0)
        Delay 200//防卡
        If (Ken_FindPic("补给_补给列表_全选框")) Then 
            Call Ken_Logcat_I("补给第" & index+1 &"舰队")
            Call Ken_PointGetAndClick(SupplyCheckBoxAllPosition)
            If (Ken_FindPicAndClick("补给_补给列表_确定补给") = False) Then 
                Call Ken_Logcat_I("第" & index+1 &"舰队不需要补给")
            End If
            Call Ken_DeleyForNet()
        End If
        Rem 下一个补给舰队
    Next
    Call GoToMuGang()
End Function

/*入渠主逻辑*/
Function RepairNavy()
    Call Ken_Logcat_D("Form.CB_AutoRepair.Value:" & Form.CB_AutoRepair.Value)
    Call SetHwndByGame()
    If (Form.CB_AutoRepair.Value = 0) Then 
        Exit Function
    End If
    Call GoToScene("入渠")
    Call Ken_DeleyForNet()
    
    Dim FlagShipIsRepayed //旗舰是否修复
    FlagShipIsRepayed = 0
    Dim RepairedX, RepairedY //扫描这行的起始坐标
    RepairedX = 360
    RepairedY = 125
    Dim HaveSomeoneOnRapired //整个扫描的页里面是否有一艘被修复的
    HaveSomeoneOnRapired = False
    Dim TheLineIsRepaired //这行是否被修复
    TheLineIsRepaired = 0
    
    For index = 0 To 3
        If (Ken_FindPicAndClick("入渠_维修列表_空位")) Then 
            Call Ken_Logcat_I("找到空位，准备入渠")
        Else 
            Call Ken_Logcat_I ("没找到空位，停止入渠，查看是否打开自动更换")
            Call ChangeNavy()
            //            If (Form.CB_AutoChangeNavy.Value = 1) Then //如果有开启自动更换的话
            //                Call Ken_Logcat_I("自动更换已经打开，更换船只")
            //                Call ChangeNavy()
            //                Exit Function
            //            Else 
            //                Call Ken_Logcat_I("自动更换没有打开，在入渠界面等待入渠结束")
            //                Call GoToScene("入渠")
            //            End If
            Exit Function
        End If
        Delay 1000//右边弹出 防卡
        //确定船只
        For index = 0 To 9
            Call Ken_Logcat_I("正在判断第" & index+1 &"艘舰")
                
            TheLineIsRepaired = RepairFindShip(RepairedX, RepairedY)
            
            If (TheLineIsRepaired = False) Then 
                If (Ken_FindPicAndClick("入渠_维修列表_入渠开始")) Then 
                    Delay 500
                    Call Ken_FindPicAndClick("入渠_维修列表_维修开始_确定维修")
                    Call Ken_DeleyForNet()
                    Call Ken_FindPicAndClick("入渠_维修列表_空位_详情返回")
                    Delay 500
                    Call Ken_FindPicAndClick("入渠_维修列表_空位_列表返回")
                    Delay 500
                End If
            End If
            RepairedY = RepairedY + 30//查找下一行
        Next
    Next
    //    Call GoToMuGang()
End Function
Function RepairFindShip(mRepairedX, mRepairedY)
    Dim IsFirstNavy//这艘舰，这是第一舰队的

    RepairedYEnd = mRepairedY + 30
    
    If (Form.CB_Repair_Navy_1.Value = 1) Then 
        If (Ken_FindPicByRect("入渠_维修列表_第一舰队", mRepairedX, mRepairedY, 800, RepairedYEnd)) Then 
            Call Ken_Logcat_I("找到第一舰队 x:" & X & " Y:" &Y)
            IsFirstNavy = True
        Else 
            Call Ken_Logcat_I("没有找到第一舰队，如果没有找到当页最后，尝试继续查找")
            IsFirstNavy = False
            //RepairFindShip = False//当成已修复处理，跳过该舰入渠
            Exit Function
        End If
    End If
    
    If (Form.CB_Repair_XiaoPo.Value = 1) Then 
        Call Ken_Logcat_I("小破入渠被选中 检查中")
        Call Ken_FindPicByRect("入渠_战斗状态_小破", mRepairedX, mRepairedY, 800, RepairedYEnd)
        Call Ken_LeftClickOnXY()
    End If
    If (Form.CB_Repair_ZhongPo.Value = 1) Then 
        Call Ken_Logcat_I("中破入渠被选中 检查中")
        Call Ken_FindPicByRect("入渠_战斗状态_中破", mRepairedX, mRepairedY, 800, RepairedYEnd)
        Call Ken_LeftClickOnXY()
    End If
    If (Form.CB_Repair_DaPo.Value = 1) Then 
        Call Ken_Logcat_I("大破入渠被选中 检查中")
        Call Ken_FindPicByRect("入渠_战斗状态_大破", mRepairedX, mRepairedY, 800, RepairedYEnd)
        Call Ken_LeftClickOnXY()
    End If
    If (Form.CB_Repair_WeiPo.Value = 1 and HaveSomeoneOnRapired = True) Then 
        Call Ken_Logcat_I("微破入渠被选中，并且已经有其他正在入渠的舰只 检查中")
        If (Ken_FindPicByRect("入渠_战斗状态_满血", mRepairedX, mRepairedY, 800, RepairedYEnd) = False) Then 
            X = mRepairedX + 150
            Y = mRepairedY + 20
            Call Ken_LeftClickOnXY()
        End If
    End If
    If (Ken_FindPicByRect("入渠_战斗状态_修复", mRepairedX, mRepairedY, 800, RepairedYEnd)) Then 
        RepairFindShip = True//用作判断本行
        HaveSomeoneOnRapired = True//用来判断全部
    End If
    
End Function

/**战斗**/
Function AttackNavy()
    Call SetHwndByGame()
    Call Ken_Logcat_D("Form.CB_AutoAttack.Value:" & Form.CB_AutoAttack.Value)
    If (Form.CB_AutoAttack.Value = 0) Then 
        Exit Function
    End If
    If (Int(Form.CB_Attack_Limit_Count.Value) = 1 and Int(Form.Label_Attack_Index.Caption) > Int(Form.IB_Attack_Limit_Count.Text)) Then 
        Call Ken_Logcat_I("当前出击次数超过用户设置的最大次数，停止出击" & Form.Label_Attack_Index.Caption &" "& Int(Form.IB_Attack_Limit_Count.Text))
        Exit Function
    End If
    Form.Label_Attack_Index.Caption = Int(Form.Label_Attack_Index.Caption) + 1
        
    Call GoToMuGang()
    If (Ken_FindPicUntilFoundThenClick("母港_出击") = False) Then
        Call Ken_Logcat_W("出击失败，没有找到出击按钮，返回母港")
        Call GoToMuGang()
        Exit Function
    End If
    Call Ken_FindPicUntilFoundThenClick("出击_主界面_出击")
    Call Ken_DeleyForNet()
    
    //出击地图
    AttackMapIndex = Form.CB_Attack_MapLevel.ListIndex
    //出击关卡
    AttackMissionXIndex = Form.CB_Attack_MissionLevel.ListIndex mod 2
    AttackMissionYIndex = Int(Form.CB_Attack_MissionLevel.ListIndex / 2)
	
	/*选择出击地图*/
    If (AttackMapIndex < 6) Then //正常地图
        Call Ken_PointAddAndClick(AttackMapPosition, AttackMapIndex * AttackMapPositionOffset, 0)
		/*选择出击关卡*/
        If (Form.CB_Attack_MissionLevel.ListIndex < 4) Then //如果是正常地图，就用正常关卡
            Call Ken_PointAddAndClick(AttackMissionPosition,AttackMissionXIndex * AttackMissionPositionOffsetX,AttackMissionYIndex * AttackMissionPositionOffsetY)
        Else// If(AttackMapIndex = 5)//如果是BOSS地图，就是第五地图
            Call Ken_PointGetAndClick(AttackMissionPositionOfBossMap)
            Delay 2000
            Call Ken_PointGetAndClick(AttackMissionPositionOfBossMission1)//只实现了X-5，没有实现X-6
        End If
    Else// If(AttackMapIndex = 6)//活动地图
        Call Ken_PointGetAndClick(AttackMissionPositionOfSpecialMap)
        Call Ken_PointAddAndClick(AttackMissionPositionOfSpecialMission, 0, Form.CB_Attack_MissionLevel.ListIndex * AttackMissionPositionOfSpecialMissionOffset)
        Call Ken_PointAddAndClick(AttackMissionPositionOfSpecialMission, 0, Form.CB_Attack_MissionLevel.ListIndex * AttackMissionPositionOfSpecialMissionOffset)
        Call Ken_PointAddAndClick(AttackMissionPositionOfSpecialMission, 0, Form.CB_Attack_MissionLevel.ListIndex * AttackMissionPositionOfSpecialMissionOffset)
    End If
	

    Delay 1000
	
    
    Call Ken_FindPicUntilFoundThenClick("出击_确定任务")
    Delay 500
    
    If (Form.CB_Supply_CheckOil.Value = 1) Then 
        If (CheckOilAndAmmoIsFull() = false) Then 
            Call Ken_Logcat_I(NavyNumber & "舰队在执行任务" & ExpeditionMissionID + 1  & "时缺油或弹药")
            Call SupplyNavy()
            Exit Function
        End If
    End If
    
    If (Ken_FindPic("出击_出击_出击开始_disable") = False) Then 
        Call Ken_FindPicUntilFoundThenClick("出击_出击_出击开始")
        Call Fighting()
        Call Ken_DeleyForNet()
    End If
End Function
//战斗中
Function Fighting()
    FightingRound = 0
    Timeout = 0
    Do
        Call Ken_FindPicAndClick("战斗_战斗中_指南针")
        
        Call Ken_PointGetAndClick(AttackFormationPositionArray(Form.CB_Attack_Formation.ListIndex))
        
        If (AttackNightFight = 1) Then 
            Call Ken_FindPicAndClick("战斗_战斗中_脱离判定_夜战")
        Else 
            Call Ken_FindPicAndClick("战斗_战斗中_脱离判定_追击")
        End If
        If (FightingRound < AttackFightRound) Then 
            If (Ken_FindPicAndClick("战斗_战斗中_回合结束_进击")) Then 
                FightingRound = FightingRound + 1
                Call Ken_Logcat_I("当前战斗回合数：" & FightingRound & " 总攻击回合数：" & AttackFightRound)
                Delay 1000
            End If
        Else 
            Call Ken_FindPicAndClick("战斗_战斗中_回合结束_撤退")
        End If
        If (Ken_FindPicAndClick("战斗_结束_评价_战果报告")) Then 
            Call Ken_Logcat_I("战斗结束，判断舰船是否大破")
            If (Ken_FindPicByRect("战斗_战斗中_战斗状态_大破", 0, 0, 400, 480)) Then 
                Call Ken_Logcat_I("检测到舰船大破，不再继续进击")
                ShipWasDestroyed = 1
                FightingRound = 999//不在继续战斗
            End If
        End If
        Call Ken_FindPicAndClick("进击_结束_评价_继续")
        Call Ken_FindPicAndClick("出击_结束_评价_返回")
        Delay 1000
        Timeout = Timeout + 1000
        
        FightOutTime = Int(Form.IB_Setting_Fight_OutTime.Text)
        If (FightOutTime <= 0) Then 
            FightOutTime = 10
        End If
        
        If (Timeout >= FightOutTime * 60 * 1000) Then 
            Exit Function
        End If
    Loop While (Ken_FindPic("母港_出击") = False)
    //Call Ken_FindPicUntilFoundThenClick("出击_结束_评价_继续")
End Function

//换船
Function ChangeNavy()
    Dim ChangeNavyNeedChangePortIndex,ChangeNavyIDArray,ShipID
    Call Ken_Logcat_D("Form.CB_AutoChangeNavy.Value:" & Form.CB_AutoChangeNavy.Value)
    If (Form.CB_AutoChangeNavy.Value = 0) Then 
        Exit Function
    End If
    Call GoToScene("编成")
    
    //获取哪个船位需要更换
    Call ChangeNavyChoiceWhatShipNeedToChange()
    Call Ken_DeleyForNet()
    Rem 结束换船逻辑
End Function
//通过条件判断哪艘船需要被替换
Function ChangeNavyChoiceWhatShipNeedToChange()
    Call Ken_Logcat_I("通过条件判断哪艘船需要被替换")
    Dim ScanningX, ScanningY//扫描这行的起始坐标
    Dim ChangeNavyChangeInitResult
    ChangeNavyChangeInitResult = 0
    ScanningX = 110
    ScanningY = 634
    For ChangeNavyNeedChangePortIndex = 0 To 5
        Call Ken_Logcat_I("开始检测第" & ChangeNavyNeedChangePortIndex+1 & "船位的舰船状态")
        Dim ScanningEndX,ScanningEndY
        ScanningEndX = ScanningX + 240
        ScanningEndY = ScanningY + 40 * (ChangeNavyNeedChangePortIndex + 1)
        ScanningY = ScanningY + 40 * (ChangeNavyNeedChangePortIndex)
        If (ChangeNavyChangeInitResult = 0 and Form.CB_ChangeNavy_When_Repair.Value) Then 
            Call SetHwndByTidu()
            If (Ken_FindPicByRect("提督_综合_舰队列表_入渠中", ScanningX, ScanningY, ScanningEndX, ScanningEndY)) Then 
                Call ChangeNavyController()
            End If
        End If
        If (ChangeNavyChangeInitResult = 0 and Form.CB_ChangeNavy_When_DaPo.Value) Then 
            Call SetHwndByTidu()
            If (Ken_FindPicByRect("提督_综合_舰队列表_HP_大破", ScanningX, ScanningY, ScanningEndX, ScanningEndY)) Then 
                Call ChangeNavyController()
            End If
        End If
        If (ChangeNavyChangeInitResult = 0 and Form.CB_ChangeNavy_When_ZhongPo.Value) Then 
            Call SetHwndByTidu()
            If (Ken_FindPicByRect("提督_综合_舰队列表_HP_中破", ScanningX, ScanningY, ScanningEndX, ScanningEndY)) Then 
                Call ChangeNavyController()
            End If
        End If
        If (ChangeNavyChangeInitResult = 0 and Form.CB_ChangeNavy_When_XiaoPo.Value) Then 
            Call SetHwndByTidu()
            If (Ken_FindPicByRect("提督_综合_舰队列表_HP_小破", ScanningX, ScanningY, ScanningEndX, ScanningEndY)) Then 
                Call ChangeNavyController()
            End If
        End If
        If (ChangeNavyChangeInitResult = 0 and Form.CB_ChangeNavy_When_Repair.Value) Then 
            Call SetHwndByTidu()
            If (Ken_FindPicByRect("提督_综合_舰队列表_红脸", ScanningX, ScanningY, ScanningEndX, ScanningEndY)) Then 
                Call ChangeNavyController()
            End If
        End If
        If (ChangeNavyChangeInitResult = 0 and Form.CB_ChangeNavy_When_Repair.Value) Then 
            Call SetHwndByTidu()
            If (Ken_FindPicByRect("提督_综合_舰队列表_橙脸", ScanningX, ScanningY, ScanningEndX, ScanningEndY)) Then 
                Call ChangeNavyController()
            End If
        End If
        If (ChangeNavyChangeInitResult = 0 and Form.CB_ChangeNavy_When_Repair.Value) Then 
            Call SetHwndByTidu()
            If (Ken_FindPicByRect("提督_综合_舰队列表_黄脸", ScanningX, ScanningY, ScanningEndX, ScanningEndY)) Then 
                Call ChangeNavyController()
            End If
        End If
        Rem ChangeNavyChoiceWhatShipNeedToChangeFor
    Next
End Function
Function ChangeNavyController()
    If (Ken_FindPicByRect("提督_综合_入渠_入渠结束", 662, 572, 790, 707)) Then 
        Call Ken_Logcat_I("更换舰船前检测到有船只入渠完毕，回到母港以刷新全体舰船状态")
        Call GoToMuGang()
    End If
    Call SetHwndByGame()
    Call ChangeNavyChangeInit()
        /*在ChangeNavyChangeInit()函数后面添加代码，会被其内部Exit Function的（比如ID文本框内数字检验失败）情况调用到，请注意使用*/
End Function
//开始更换
Function ChangeNavyChangeInit()
    //通过船位，获得用户定义的下一艘可替换舰船
    Call Ken_Logcat_I("分析用户更换数据，即将开始更换")
    Call Ken_Logcat_D("ChangeNavyNeedChangePortIndex:" & ChangeNavyNeedChangePortIndex)
    
    Dim ChangeNavyIDs
    //获得当前（ChangeNavyNeedChangePortIndex）船位上的所有ID
    If (ChangeNavyNeedChangePortIndex = 0) Then 
        ChangeNavyPlaceIndex = Form.IB_ChangeNavy1.Text
        ChangeNavyIDs = Int(Form.Label_ChangeNavy_1.Caption)
    ElseIf (ChangeNavyNeedChangePortIndex = 1) Then
        ChangeNavyPlaceIndex = Form.IB_ChangeNavy2.Text
        ChangeNavyIDs = Int(Form.Label_ChangeNavy_2.Caption)
    ElseIf (ChangeNavyNeedChangePortIndex = 2) Then
        ChangeNavyPlaceIndex = Form.IB_ChangeNavy3.Text
        ChangeNavyIDs = Int(Form.Label_ChangeNavy_3.Caption)
    ElseIf (ChangeNavyNeedChangePortIndex = 3) Then
        ChangeNavyPlaceIndex = Form.IB_ChangeNavy4.Text
        ChangeNavyIDs = Int(Form.Label_ChangeNavy_4.Caption)
    ElseIf (ChangeNavyNeedChangePortIndex = 4) Then
        ChangeNavyPlaceIndex = Form.IB_ChangeNavy5.Text
        ChangeNavyIDs = Int(Form.Label_ChangeNavy_5.Caption)
    ElseIf (ChangeNavyNeedChangePortIndex = 5) Then 
        ChangeNavyPlaceIndex = Form.IB_ChangeNavy6.Text
        ChangeNavyIDs = Int(Form.Label_ChangeNavy_6.Caption)
    Else 
        ChangeNavyPlaceIndex = ""
        ChangeNavyIDs = ""
    End If
    Call Ken_Logcat_I("ChangeNavyIDs:" & ChangeNavyIDs &"ChangeNavyPlaceIndex:" & ChangeNavyPlaceIndex)
    If (ChangeNavyPlaceIndex = "") Then 
        Call Ken_Logcat_I("替换船位是第" & ChangeNavyNeedChangePortIndex + 1 & "号位置的舰船：没有填写可替换的舰船，跳出替换舰船模块")
        ChangeNavyChangeInitResult = 1
        Exit Function
    Else 
        Call Ken_Logcat_I("替换船位是第" & ChangeNavyNeedChangePortIndex + 1 & "号位置的舰船：已获取数据成功")
        ChangeNavyChangeInitResult = 0
    End If
    
    //通过船位获得它的当前使用的舰船ID数组
    ChangeNavyIDArray = Split(ChangeNavyPlaceIndex, "|", - 1 , 1)
    //当前要更换的舰船ID
    ShipID = ChangeNavyIDArray(ChangeNavyIDs)//通过舰船ID数组和下标获得当前要更换的舰船ID
    
    If (IsNumeric(ShipID) = False) Then 
        Call Ken_Logcat_I("分析第" & ChangeNavyNeedChangePortIndex + 1 & "号位置的舰船数据：填写的" & ShipID & "不是数字，跳出替换舰船模块")
        ChangeNavyChangeInitResult = 1
        Exit Function
    Else
        Call Ken_Logcat_I("分析第" & ChangeNavyNeedChangePortIndex + 1 & "号位置的舰船数据：成功解析，填写的" & ShipID & "")
        ChangeNavyChangeInitResult = 0
    End If
    Call ChangeNavyChanging()
End Function
Function ChangeNavyChanging()
    Dim PageCount,LineIndex//舰船ID所在的页数和行数
    PageCount = Int(ShipID  / 10)
    LineIndex = Int(ShipID mod 10)
    
    Call Ken_Logcat_I("将更换第" & LineIndex &"页的第" & PageCount &"行船，ShipID:" & ShipID)
    //换船页数
    ChangeNavyPageCount = pageCount
    //换船行数
    ChangeNavyLineNumber = LineIndex
    
    Call Ken_Logcat_I("分析完毕，符合更换条件，开始更换")
    Dim ChangeNavyUpdateResult
    Call Ken_Logcat_I("点击更换按钮")
    Call Ken_PointAddAndClick(ChangeNavyChangeInitBtnPosition, ChangeNavyChangeInitBtnPositionOffsetX * (ChangeNavyNeedChangePortIndex mod 2), ChangeNavyChangeInitBtnPositionOffsetY * Int(ChangeNavyNeedChangePortIndex / 2))
    Delay 200//防卡
    
    If (Ken_FindPicUntilFound("编成_列表_顶部条") = False) Then 
        Call Ken_Logcat_I("没有找到列表的顶部条，可能没有选中更换按钮，更换失败，重新回到母港")
        Call GoToMuGang()
        Exit Function
    End If

    //选择可以替换的船
    Call Ken_Logcat_I("标准化列表类型")
    //列表类型
    Call Ken_ClickUntilChangeTo(TypePosition, "编成_列表_类型_船只")
    //初始化到最前页
    Call Ken_PointGetAndClick(ChangeNavyBackToFirstPagePosition)
    //直接选择第三页
    Call Ken_PointAddAndClick(ChangeNavyPagePosition, ChangeNavyPagePositionOffset * 2, 0)
    //按翻5页按钮
    For index = 0 To Int(ChangeNavyPageCount / 5) - 1
        Call Ken_PointGetAndClick(ChangeNavyJumpPageToNext5Position)
    Next
    //在（12345）中选按具体哪页按钮
    Call Ken_PointAddAndClick(ChangeNavyPagePosition, ChangeNavyPagePositionOffset * (ChangeNavyPageCount mod 5), 0)
    Delay 3000
    
    Call Ken_Logcat_I("选择第" & ChangeNavyLineNumber & "行的舰船")
    Call Ken_PointAddAndClick(ChangeNavyListPosition, 0, ChangeNavyListPositionOffset * (ChangeNavyLineNumber))
    Call ChangeNavySetNextShipIndex(ChangeNavyNeedChangePortIndex)//设置下一个要更换的INDEX
    Delay 1000
    If (Ken_FindPic("编成_列表_确定变更_disable")) Then
        Call Ken_Logcat_I("无法更改当前舰船。可能是在正在使用（入渠、已在舰队内），跳过至下一个定义的舰船ID再更换")
        //从舰船详情回到列表
        Call Ken_PointGetAndClick(ChangeNavyListNavyPosition)
        Delay 200//防卡
        Call Ken_PointGetAndClick(ChangeNavyListNavyPosition)
        Call ChangeNavyChangeInit()
    End If
    Call Ken_Logcat_I("确定变更，开始")
    Call Ken_FindPicUntilFoundThenClick("编成_列表_确定变更")
    Call Ken_DeleyForNet()
    Call Ken_Logcat_I("确定变更，结束")
End Function
//更换后，设置下一个要更换的INDEX
Function ChangeNavySetNextShipIndex(ChangeNavyNeedChangePortIndex)
    //如果当前舰船下标已经获取到最后一个，则从头重新开始
    If (ChangeNavyIDs + 1 > UBound(ChangeNavyIDArray)) Then 
        ChangeNavyIDs = 0
    Else 
        ChangeNavyIDs = ChangeNavyIDs + 1
    End If
    If (ChangeNavyNeedChangePortIndex = 0) Then 
        Form.Label_ChangeNavy_1.Caption = ChangeNavyIDs
    ElseIf (ChangeNavyNeedChangePortIndex = 1) Then
        Form.Label_ChangeNavy_2.Caption = ChangeNavyIDs
    ElseIf (ChangeNavyNeedChangePortIndex = 2) Then
        Form.Label_ChangeNavy_3.Caption = ChangeNavyIDs
    ElseIf (ChangeNavyNeedChangePortIndex = 3) Then
        Form.Label_ChangeNavy_4.Caption = ChangeNavyIDs
    ElseIf (ChangeNavyNeedChangePortIndex = 4) Then
        Form.Label_ChangeNavy_5.Caption = ChangeNavyIDs
    ElseIf (ChangeNavyNeedChangePortIndex = 5) Then 
        Form.Label_ChangeNavy_6.Caption = ChangeNavyIDs
    End If
    Call Ken_Logcat_D("ChangeNavyIDs:" & ChangeNavyIDs & "ChangeNavyPageCount:" & ChangeNavyPageCount & "ChangeNavyLineNumber:" & ChangeNavyLineNumber & "UBound(ChangeNavyIDArray):" & UBound(ChangeNavyIDArray))
End Function

//工厂开发
Function FactoryNavy()
    Dim FactoryNumberArray
    Call Ken_Logcat_D("CB_AutoFactory:" & Form.CB_AutoFactory.Value)
    If (Form.CB_AutoFactory.Value = 0) Then 
        Exit Function
    End If
    Call GoToScene("工厂")
    Delay 1000
    Call FactoryDev()
    Call FactoryBuild()
End Function

Function FactoryDev()
    Call Ken_Logcat_D("Int(Form.IB_Dev_RepeatCount.Text):" & Int(Form.IB_Dev_RepeatCount.Text))
    Call Ken_Logcat_D("IsNumeric(Form.IB_Dev_RepeatCount.Text):" & IsNumeric(Form.IB_Dev_RepeatCount.Text))
    While (Int(Form.IB_Dev_RepeatCount.Text) > 0)
        If (IsNumeric(Form.IB_Dev_RepeatCount.Text) = False)
            Call Ken_Logcat_I("开发次数文本框内容为空，或者不是数字")
            Exit Function
        End If

        Call Ken_FindPicUntilFoundThenClick("工厂_主界面_开发")
        Delay 200 //防卡
        If (Ken_FindPicUntilFound("工厂_开发_开发界面") = False) Then 
            Call Ken_Logcat_W ("没有成功打开开发界面，退出开发，回到母港")
            Call GoToMuGang()
            Exit Function
        End If
   	
        FactoryNumberArray = Split(Int(Form.IB_Dev_Oil.Text) & "|" & Int(Form.IB_Dev_Steel.Text) & "|" & Int(Form.IB_Dev_Ammo.Text) & "|" & Int(Form.IB_Dev_Lv.Text), "|")
   	
        Dim mIndex
        For mIndex = 0 To 3 Step 1
            Call FactoryCountClick(FactoryNumberArray(mIndex),FactoryPositionArray(mIndex),True)
        Next
    
        Call Ken_FindPicUntilFoundThenClick("工厂_开发_开发开始")
        Call Ken_DeleyForNet()
        Delay 5000
        Call Ken_FindPicUntilFoundThenClick("出击_结束_评价_返回")
        
        Form.IB_Dev_RepeatCount.Text = Int(Form.IB_Dev_RepeatCount.Text) - 1
    Wend
    Call Ken_Logcat_I("开发次数小于等于0，开发结束")
End Function
Function FactoryBuild()
    Call Ken_Logcat_D("Int(Form.IB_Build_RepeatCount.Text):" & Int(Form.IB_Build_RepeatCount.Text))
    While (Int(Form.IB_Build_RepeatCount.Text) > 0)
        If (IsNumeric(Form.IB_Build_RepeatCount.Text) = False)
            Call Ken_Logcat_I("建造次数文本框内容为空，或者不是数字")
            Exit Function
        End If
        
        If (Ken_FindPicAndClick("工厂_建造_建造完毕")) Then 
            Call Ken_Logcat_I("发现建造完毕的舰船，正在获取")
            Call Ken_DeleyForNet()
            Delay 5000
            Call Ken_FindPicUntilFoundThenClick("出击_结束_评价_返回")
        End If
        
        Call Ken_FindPicUntilFoundThenClick("工厂_建造_选择空位")
        Delay 200 //防卡
        If (Ken_FindPicUntilFound("工厂_建造_建造界面") = False) Then 
            Call Ken_Logcat_W ("没有成功打开建造界面，退出建造，回到母港")
            Call GoToMuGang()
            Exit Function
        End If
   	
        FactoryNumberArray = Split(Int(Form.IB_Build_Oil.Text) & "|" & Int(Form.IB_Build_Steel.Text) & "|" & Int(Form.IB_Build_Ammo.Text) & "|" & Int(Form.IB_Build_Lv.Text), "|")
   	
        Dim mIndex
        For mIndex = 0 To 3 Step 1
            Call FactoryCountClick(FactoryNumberArray(mIndex),FactoryPositionArray(mIndex),False)
        Next
    
        Call Ken_FindPicUntilFoundThenClick("工厂_建造_建造开始")
        Call Ken_DeleyForNet()
        Form.IB_Build_RepeatCount.Text = Int(Form.IB_Build_RepeatCount.Text) - 1
    Wend
    Call Ken_Logcat_I("建造次数小于等于0，建造结束")
End Function

Function FactoryCountClick(Number,Position,isDev)
    Dim Ge, Shi, Bai
    Dim Decrease
    If (isDev) Then 
        Decrease = 10
    Else 
        Decrease = 30
    End If
    
    Number = Number - Decrease
    
    Bai = Int(Number / 100)
    Shi = Int(Number / 10 mod 10)
    Ge = Int(Number mod 10)
    Call Ken_Logcat_D("Bai" & Bai & " Shi" & Shi & " Ge" & Ge & " Number" & Number & " Position" & Position)
	
    Dim Ken_LeftClickOnXY_Delay_Temp
    Ken_LeftClickOnXY_Delay_Temp = Ken_LeftClickOnXY_Delay
    Ken_LeftClickOnXY_Delay = 100
    Dim indexForBai,indexForShi,indexForGe
    For indexForBai = 0 To Bai - 1 Step 1
        Call Ken_PointAddAndClick(Position, 0, 30)
    Next
    For indexForShi = 0 To Shi - 1 Step 1
        Call Ken_PointAddAndClick(Position, 0, 0)
    Next
    For indexForGe = 0 To Ge - 1 Step 1
        Call Ken_PointAddAndClick(Position, -127, 17)
    Next
    Ken_LeftClickOnXY_Delay = Ken_LeftClickOnXY_Delay_Temp
End Function






















































/**********************************************************工具函数**********************************************************/
Function InitEnvironment()
    Dim fso
	
    ResourceFolder = Plugin.Sys.GetDir(0) & "\pic\"
    Call Ken_Logcat_I("资源路径为："&ResourceFolder)   	
    Set fso = CreateObject("Scripting.FileSystemObject")
    If (fso.FolderExists(ResourceFolder)) Then 
    Else 
        Call Ken_Logcat_I("释放资源开始")   	
        PutAttachment ResourceFolder, "*.bmp"
        Call Ken_Logcat_I("释放资源完毕") 
        Call Plugin.File.CreateFolder(Plugin.Sys.GetDir(0) & "\日志")
    End If
    DebugLogPath = ".\日志\"& "Debug_" & Ken_GetDateTimeStr() & ".txt"
    WarningLogPath = ".\日志\" & "Warning_" & Ken_GetDateTimeStr() & ".txt"
  	
End Function


/*获得游戏句柄*/
Function GetHwndForGame()
    Dim HwndEmbedding,HwndDocObject
    HwndTidu = Plugin.Window.Find(0, "提督業も忙しい！")
    HwndEmbedding = Plugin.Window.FIndex(HwndTidu, 0, "Shell Embedding", 0)
    HwndDocObject = Plugin.Window.FIndex(HwndEmbedding, 0, "Shell DocObject View", 0)
    HwndGame = Plugin.Window.FIndex(HwndDocObject, 0, "Internet Explorer_Server", 0)
    Call SetHwndByGame()
    If (Hwnd = 0) Then 
        MessageBox "找不到窗口句柄，程序结束"
        EndScript
    End If
    Call Plugin.Window.SetClientSize(HwndTidu, 800, 1000)
    Call Ken_Logcat_D("HwndTidu:" & HwndTidu)
    Call Ken_Logcat_D("HwndGame:" & HwndGame)
    Call Ken_Logcat_D("Hwnd:" & Hwnd)
End Function
Function SetHwndByGame()
    Hwnd = HwndGame
    ScreenHeight = 480
    ScreenWidth = 800
    PicDefinition = 0.9
    Call Ken_Logcat_D("SetHwndByGame.Hwnd:" & Hwnd)
End Function
Function SetHwndByTidu()
    Hwnd = HwndTidu
    ScreenHeight = 1000
    ScreenWidth = 800
    PicDefinition = 1.0
    Call Ken_Logcat_D("SetHwndByTidu.Hwnd:" & Hwnd)
End Function

/**第三方库查找图片**/
Function Lib_FindPic(picName)
    Call Plugin.BGCP2_02.FindPicture(Hwnd, 0, 0, ScreenWidth, ScreenHeight, ResourceFolder & picName & ".bmp", 50, PicDefinition, X, Y)
End Function
Function Lib_FindPicByRect(picName,StartX,StartY,EndX,EndY)
    Call Plugin.BGCP2_02.FindPicture(Hwnd, StartX ,StartY ,EndX ,EndY ,ResourceFolder & picName & ".bmp", 50, PicDefinition, X, Y)
End Function

Function Lib_FindPicByRectAndDefinition(picName,StartX,StartY,EndX,EndY,mPicDefinition)
    Call Plugin.BGCP2_02.FindPicture(Hwnd, StartX ,StartY ,EndX ,EndY ,ResourceFolder & picName & ".bmp", 50, mPicDefinition, X, Y)
End Function

/**查找图片**/
Function Ken_FindPic(picName)
    Call Lib_FindPic(picName)
    If X > - 1  Then //找到了
        Call Ken_Logcat_D("Ken_FindPic:" & picName & " FoundPic = true")
        Ken_FindPic = True
    Else //没知道，可能是被选中的状态，更换选中状态的图片再找一次
        Call Lib_FindPic(picName & "_touched")
        If X > - 1  Then 
            Ken_FindPic = True//找到了	
        Else 
            Call Ken_Logcat_D("Ken_FindPic:" & picName & " FoundPic = false")
            Ken_FindPic = False//真没找到
        End If
    End If
End Function
Function Ken_FindPicByRect(picName,StartX,StartY,EndX,EndY)
    Call Lib_FindPicByRect(picName,StartX,StartY,EndX,EndY)
    If X > - 1  Then //找到了	
        Ken_FindPicByRect = True
    Else //没知道，可能是被选中的状态，更换选中状态的图片再找一次
        Call Lib_FindPicByRect(picName & "_touched",StartX,StartY,EndX,EndY)
        If X > - 1  Then 
            Ken_FindPicByRect = True//找到了	
        Else 
            Ken_FindPicByRect = False//真没找到
        End If
        Call Ken_Logcat_D("Ken_FindPicByRect:" & picName & " Ken_FindPicByRect:"  & Ken_FindPicByRect &" StartX:" & StartX & " StartY:" & StartY & " EndX:" & EndX & " EndY:" & EndY)
    End If
End Function

Function Ken_FindPicByRectAndDefinition(picName,StartX,StartY,EndX,EndY,mPicDefinition)
    Call Lib_FindPicByRectAndDefinition(picName,StartX,StartY,EndX,EndY,mPicDefinition)
    If X > - 1  Then //找到了	
        Ken_FindPicByRectAndDefinition = True
    Else //没知道，可能是被选中的状态，更换选中状态的图片再找一次
        Call Lib_FindPicByRectAndDefinition(picName & "_touched",StartX,StartY,EndX,EndY,mPicDefinition)
        If X > - 1  Then 
            Ken_FindPicByRectAndDefinition = True//找到了	
        Else 
            Ken_FindPicByRectAndDefinition = False//真没找到
        End If
    End If
End Function

/**查找图片，找到就点没找到就算了**/
Function Ken_FindPicAndClick(picName)
    Ken_FindPicAndClick = False
    If (Ken_FindPic(picName)) Then 
        Ken_FindPicAndClick = Ken_LeftClickOnXY()
    End If
End Function

/**查找图片，直到超时或者图片位置点击**/
Function Ken_FindPicUntilFoundThenClick(picName)
    Call Ken_FindPicUntilFound(picName)
    Ken_FindPicUntilFoundThenClick = Ken_LeftClickOnXY()
End Function

/**查找图片，直到超时**/
Function Ken_FindPicUntilFound(picName)
    Dim Timeout
    Timeout = 0
    Do
        Delay 100
        Timeout = Timeout + 100
        If (Timeout >= 5000) Then 
            Ken_FindPicUntilFound = False
            Exit Function
        End If
    Loop While (Ken_FindPic(picName) = False)
    Ken_FindPicUntilFound = True
End Function

/**点击XY的位置**/
Function Ken_LeftClickOnXY()
    If X <= - 1  Then 
        Ken_LeftClickOnXY = False
        Exit Function
    End If
    Call Ken_Logcat_D("Ken_LeftClickOnXY x:" & X & " Y :" & Y)
    If (Y < 800) Then     	
        Call Plugin.Bkgnd.LeftClick(Hwnd, X, Y)
        Ken_LeftClickOnXY = True
    Else 
        Call Plugin.Bkgnd.LeftClick(HwndTidu, X, Y)
        Ken_LeftClickOnXY = True
    End If
    X = -1 
    Y = - 1 
    Delay Ken_LeftClickOnXY_Delay
End Function

/**存储坐标给某个变量**/
Function Ken_PointSet(positionX, positionY)
    Ken_PointSet = positionX & "|" & positionY
End Function

/**获得坐标从某个变量**/
Function Ken_PointGet(XY)
    Dim ZuoBiao
    ZuoBiao = InStr(XY, "|")
    X = Clng(Left(XY, ZuoBiao - 1)) : Y = Clng(Right(XY, Len(XY) - ZuoBiao))
End Function

/**获得坐标从某个变量，然后单击**/
Function Ken_PointGetAndClick(XY)
    Ken_PointGet (XY)
    
    Call Ken_LeftClickOnXY()
End Function

/**某个变量与坐标相加**/
Function Ken_PointAdd(XY,positionX,positionY)
    Call Ken_PointGet(XY)
    X = X + positionX
    Y = Y + positionY
End Function
/**某个变量与坐标相加，然后单击**/
Function Ken_PointAddAndClick(XY,positionX,positionY)
    Call Ken_PointAdd(XY,positionX,positionY)
    Call Ken_LeftClickOnXY()
End Function

/**点击坐标，直到出现图片**/
Function Ken_ClickUntilChangeTo(Position,PicName)
    Dim Timeout
    Timeout = 0
    Do While (Ken_FindPic(PicName) = False)
        Call Ken_PointGetAndClick(Position)
        Delay 100
        Timeout = Timeout + 100
        If (Timeout >= 5000) Then 
            Exit Function
        End If
    Loop
End Function

Function Ken_DeleyForNet()
    Call Ken_Logcat_D("网络等待")
    Dim FindTime, nCount
    FindTime = Plugin.Sys.GetTime()
    Do
        If (Ken_FindPicByRectAndDefinition("全局_载入中", 770, 450, 800, 480, 0.7)) Then 
            FindTime = Plugin.Sys.GetTime()
        End If
    Loop While (FindTime  + 1500 > Plugin.Sys.GetTime())
    Call Ken_Logcat_D("获取网络数据完毕")
End Function

Function Ken_Logcat_D(Log)
    If (Form.OB_Logcat_Debug.Value = 1) Then 
        Dim FileLenSave,FileLenNow
    
        FileLenSave = Plugin.File.GetFileLength(DebugLogPath)
        Call Plugin.File.WriteFileEx(DebugLogPath, Log)
        TracePrint Log
        FileLenNow = Plugin.File.GetFileLength(DebugLogPath)
    
        HwndFile = Plugin.File.OpenFile(DebugLogPath)
        Call Plugin.File.SeekFile(HwndFile,FileLenSave)
        
        LogcatFileStr = Plugin.File.ReadFile(HwndFile, FileLenNow - FileLenSave)
        Form.IB_Logcat.Text = LogcatFileStr & Form.IB_Logcat.Text

        Plugin.File.CloseFile (HwndFile)
        FileLenSave = FileLenNow
    Else 
        Call Plugin.File.WriteFileEx(DebugLogPath, Log)
        TracePrint Log
    End If
    
End Function

Function Ken_Logcat_I(Log)
    Dim FileLenSave,FileLenNow
    
    FileLenSave = Plugin.File.GetFileLength(DebugLogPath)
    Call Ken_Logcat_D(Log)
    FileLenNow = Plugin.File.GetFileLength(DebugLogPath)
    
    HwndFile = Plugin.File.OpenFile(DebugLogPath)
    Call Plugin.File.SeekFile(HwndFile,FileLenSave)
        
    LogcatFileStr = Plugin.File.ReadFile(HwndFile, FileLenNow - FileLenSave)
    Form.IB_Logcat.Text = LogcatFileStr & Form.IB_Logcat.Text

    Call Plugin.File.CloseFile (HwndFile)
    FileLenSave = FileLenNow
    
End Function

Function Ken_Logcat_W(Log)
    Call Ken_Logcat_I(Log)
    
    Call Plugin.BGCP2_02.SavePicture(HwndTidu,0,0,800,1000, "./日志/" & Ken_GetDateTimeStr() &"_"& Log &".png")
End Function

Function Ken_GetDateTimeStr()
    Ken_GetDateTimeStr = Year(now) & "_" & Month(now) & "_" & Day(now) & "_" & Hour(now) & "_" & Minute(now) & "_" & Second(now)
End Function